<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-15 15:22:08
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.41 C
-------------------
Today PnL: 3.56 L (2.59%)
Current PnL: -36.01 L (-22.16%)
CY Booked + Current PnL: -20.12 L (-12.38%)
-------------------
Total profit:  1.91 L
Total loss:  -37.92 L
-------------------
Total Booked + Current PnL: 6.86 L (5.07%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.26%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.07 C (75.65%)
===================
Deployed:  1.36 C
Current:  1.41 C
CAGR/XIRR %: 1.96%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,6.10,21.96,1.82,24.18,6770.0,66975.0,371975.0,303.00,-82.34,76.0,X-SC,2.16,97.0,9.89,2.64,42.31,X40N,NTT,FINANCE
50,MASFIN,2.35,-3.93,26.55,21.57,24990.0,-3855.0,94125.0,397.04,-17.34,56.0,H-SC,4.52,167.0,-0.15,0.67,21.63,XR,ATH,FINANCE
77,TTKPRESTIG,2.08,-37.39,59.87,0.09,37776.0,-37681.0,63096.0,770.00,46.42,50.0,M-SC,22.98,250.0,-1.00,0.45,12.35,OX40N,NTT,DURABLES
67,SONACOMS,2.99,1.43,37.13,39.09,38096.0,1443.0,102602.0,804.02,-19.66,70.0,M-MC,8.63,193.0,0.04,0.73,45.15,AR,ATH,AUTO
37,ICICIGI,4.31,-1.53,21.19,19.34,41756.0,-3055.0,197054.0,2252.93,-17.14,61.0,X-MC,7.59,66.0,-0.07,1.40,10.06,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COFFEEDAY,8.51,-52.37,183.99,35.27,99513.0,-59463.0,54086.0,80.00,-63.78,59.0,L-SC,32.75,266.0,-0.60,0.38,33.38,XR,NTT,HOTELS
65,SIEMENS,7.19,-3.71,30.35,25.51,54384.0,-6905.0,179190.0,4671.50,50.45,69.0,H-LC,1.41,51.0,-0.13,1.27,27.54,AR,ATH,ELECTRICAL
70,SYMPHONY,6.65,-39.36,64.85,-0.03,67305.0,-67356.0,103785.0,1306.00,-51.40,55.0,M-SC,17.87,205.0,-1.00,0.74,15.10,OX40N,NTT,DURABLES
5,ANGELONE,6.10,21.96,1.82,24.18,6770.0,66975.0,371975.0,303.00,-82.34,76.0,X-SC,2.16,97.0,9.89,2.64,42.31,X40N,NTT,FINANCE
23,DIXON,5.53,-19.25,70.80,37.92,149102.0,-50202.0,210596.0,18931.72,-65.70,58.0,X-MC,26.75,54.0,-0.34,1.49,14.59,X40N,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
7,ATULAUTO,-2.98,-18.83,79.35,45.57,126963.0,-37128.0,160004.0,844.00,3462.16,60.0,M-SC,8.19,248.0,-0.29,1.13,23.13,XY24,NTT,AUTO
62,SATIN,-0.90,-11.28,71.14,51.83,174373.0,-31171.0,245113.0,274.00,-21.16,65.0,H-SC,2.38,159.0,-0.18,1.74,19.41,XY24,NTT,FINANCE
22,DEN,-0.31,-45.05,158.53,42.07,73583.0,-38048.0,46416.0,75.00,65.80,65.0,M-SC,18.49,235.0,-0.52,0.33,26.24,AR,NTT,ENTERTAINMENT
28,GLAXO,-0.23,-3.31,43.91,39.15,84609.0,-6596.0,192688.0,3466.20,-26.09,52.0,X-MC,11.55,56.0,-0.08,1.37,6.60,X40,ATH,PHARMA
24,DMART,0.40,7.35,20.72,29.60,55520.0,18354.0,267954.0,5391.45,-9.43,69.0,X-LC,4.01,14.0,0.33,1.90,22.48,X40N,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,4.26,11.81,85.95,107.91,141890.0,17440.0,165084.0,1641.55,0.46,59.0,M-SC,1.50,220.0,0.12,1.17,24.20,OX40N,ATH,CABLES
66,SIS,4.22,-27.08,66.30,21.26,53678.0,-30070.0,80962.0,528.00,1906.22,67.0,H-SC,13.41,168.0,-0.56,0.57,20.38,OX40N,NTT,MISC
18,CERA,1.73,-30.60,78.51,23.89,95847.0,-53821.0,122082.0,9475.00,-32.94,68.0,H-SC,16.11,153.0,-0.56,0.87,17.32,OX40N,NTT,CERAMICS
48,KANSAINER,4.02,-34.51,73.27,13.47,129400.0,-93060.0,176607.0,340.00,-43.73,60.0,H-SC,22.76,162.0,-0.72,1.25,23.36,XY24,NTT,PAINTS
72,TATAELXSI,2.98,-34.53,101.65,32.03,87741.0,-45518.0,86317.0,9161.00,-18.18,58.0,H-SC,20.30,158.0,-0.52,0.61,14.24,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.69,26.15,15.40,45.57,50824.0,68405.0,330024.0,7934.0,-18.93,70.0,H-MC,16.06,125.0,1.35,2.34,46.55,AR,NTT,ELECTRICAL
5,ANGELONE,6.10,21.96,1.82,24.18,6770.0,66975.0,371975.0,303.0,-82.34,76.0,X-SC,2.16,97.0,9.89,2.64,42.31,X40N,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,4.26,11.81,85.95,107.91,141890.0,17440.0,165084.0,1641.55,0.46,59.0,M-SC,1.50,220.0,0.12,1.17,24.20,OX40N,ATH,CABLES
1,ABB,0.69,26.15,15.40,45.57,50824.0,68405.0,330024.0,7934.00,-18.93,70.0,H-MC,16.06,125.0,1.35,2.34,46.55,AR,NTT,ELECTRICAL
67,SONACOMS,2.99,1.43,37.13,39.09,38096.0,1443.0,102602.0,804.02,-19.66,70.0,M-MC,8.63,193.0,0.04,0.73,45.15,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.69,26.15,15.40,45.57,50824.0,68405.0,330024.0,7934.00,-18.93,70.0,H-MC,16.06,125.0,1.35,2.34,46.55,AR,NTT,ELECTRICAL
26,FINCABLES,4.26,11.81,85.95,107.91,141890.0,17440.0,165084.0,1641.55,0.46,59.0,M-SC,1.50,220.0,0.12,1.17,24.20,OX40N,ATH,CABLES
67,SONACOMS,2.99,1.43,37.13,39.09,38096.0,1443.0,102602.0,804.02,-19.66,70.0,M-MC,8.63,193.0,0.04,0.73,45.15,AR,ATH,AUTO
85,ZYDUSLIFE,1.52,-1.26,37.35,35.63,77294.0,-2630.0,206944.0,1286.17,-13.96,63.0,H-MC,5.91,120.0,-0.03,1.47,15.21,AR,ATH,PHARMA
40,INDIAMART,0.64,-8.89,126.88,106.72,142583.0,-10960.0,112376.0,4810.62,-58.98,56.0,H-SC,12.90,140.0,-0.08,0.80,7.96,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,1.03,-25.85,78.03,32.01,123543.0,-55192.0,158328.0,17616.87,-49.81,44.0,X-MC,21.46,57.0,-0.45,1.12,8.29,X40,ATH,FMCG
78,UNITDSPR,1.58,-8.10,31.41,20.77,67586.0,-18972.0,215172.0,1644.00,-18.49,44.0,X-MC,6.18,64.0,-0.28,1.52,2.64,X40N,NTT,BREWERIES
21,DABUR,2.02,-15.28,69.61,43.70,146303.0,-37893.0,210175.0,735.00,-23.16,45.0,X-MC,14.29,70.0,-0.26,1.49,5.58,XY24,BTT,FMCG
59,RELIANCE,2.22,-13.71,45.21,25.30,78401.0,-27548.0,173415.0,1952.00,-15.80,46.0,X-LC,5.26,21.0,-0.35,1.23,8.91,XY25,BTT,REFINERIES
2,ABBOTINDIA,1.19,-12.68,35.21,18.07,54991.0,-22675.0,156180.0,35195.00,-25.68,47.0,X-MC,11.55,58.0,-0.41,1.11,2.14,X40,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,7.19,-3.71,30.35,25.51,54384.0,-6905.0,179190.0,4671.50,50.45,69.0,H-LC,1.41,51.0,-0.13,1.27,27.54,AR,ATH,ELECTRICAL
5,ANGELONE,6.10,21.96,1.82,24.18,6770.0,66975.0,371975.0,303.00,-82.34,76.0,X-SC,2.16,97.0,9.89,2.64,42.31,X40N,NTT,FINANCE
24,DMART,0.40,7.35,20.72,29.60,55520.0,18354.0,267954.0,5391.45,-9.43,69.0,X-LC,4.01,14.0,0.33,1.90,22.48,X40N,ATH,FMCG
59,RELIANCE,2.22,-13.71,45.21,25.30,78401.0,-27548.0,173415.0,1952.00,-15.80,46.0,X-LC,5.26,21.0,-0.35,1.23,8.91,XY25,BTT,REFINERIES
78,UNITDSPR,1.58,-8.10,31.41,20.77,67586.0,-18972.0,215172.0,1644.00,-18.49,44.0,X-MC,6.18,64.0,-0.28,1.52,2.64,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,1.19,-12.68,35.21,18.07,54991.0,-22675.0,156180.0,35195.0,-25.68,47.0,X-MC,11.55,58.0,-0.41,1.11,2.14,X40,ATH,PHARMA
78,UNITDSPR,1.58,-8.10,31.41,20.77,67586.0,-18972.0,215172.0,1644.0,-18.49,44.0,X-MC,6.18,64.0,-0.28,1.52,2.64,X40N,NTT,BREWERIES
45,ITC,1.17,-20.41,49.59,19.06,134253.0,-69440.0,270726.0,452.0,-56.33,49.0,X-LC,19.61,1.0,-0.52,1.92,5.02,X40,NTT,FMCG
35,HINDUNILVR,1.54,-15.97,35.28,13.67,76205.0,-41063.0,216000.0,2922.0,-37.59,51.0,X-LC,11.86,9.0,-0.54,1.53,5.25,XY25,NTT,FMCG
21,DABUR,2.02,-15.28,69.61,43.70,146303.0,-37893.0,210175.0,735.0,-23.16,45.0,X-MC,14.29,70.0,-0.26,1.49,5.58,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,3.46,-60.49,285.50,52.31,163737.0,-87809.0,57351.0,1176.00,-57.89,57.0,X-SC,33.03,92.0,-0.54,0.41,28.23,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.50,-51.98,181.55,35.20,112178.0,-66881.0,61789.0,2096.00,-18.99,59.0,X-SC,33.64,91.0,-0.60,0.44,22.54,X40,NTT,FOOTWEAR
54,QUESS,2.36,-19.97,117.29,73.90,100244.0,-21326.0,85467.0,424.00,-57.02,60.0,X-SC,21.53,80.0,-0.21,0.61,14.97,XY24,NTT,MISC
36,HONAUT,4.16,-20.87,91.21,51.31,139186.0,-40238.0,152600.0,58357.33,-34.22,61.0,X-SC,19.15,90.0,-0.29,1.08,15.94,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,1.19,-12.68,35.21,18.07,54991.0,-22675.0,156180.0,35195.00,-25.68,47.0,X-MC,11.55,58.0,-0.41,1.11,2.14,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.17,-20.41,49.59,19.06,134253.0,-69440.0,270726.0,452.00,-56.33,49.0,X-LC,19.61,1.0,-0.52,1.92,5.02,X40,NTT,FMCG
73,TCS,3.43,-24.93,68.60,26.57,238586.0,-115480.0,347793.0,4311.59,-36.41,54.0,X-LC,17.71,2.0,-0.48,2.46,8.54,X40,ATH,IT
43,INFY,2.23,-11.14,51.08,34.24,142017.0,-34859.0,278029.0,1972.00,-29.97,49.0,X-LC,14.03,3.0,-0.25,1.97,6.92,X40,NTT,IT
75,TMPV,3.62,-18.51,67.60,36.58,196026.0,-65861.0,289980.0,600.00,-83.62,63.0,X-LC,11.83,4.0,-0.34,2.06,20.86,XY24,NTT,AUTO
33,HCLTECH,1.63,-5.73,31.35,23.83,71501.0,-13850.0,228074.0,1908.19,-1.16,58.0,X-LC,9.02,8.0,-0.19,1.62,10.74,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,2.99,1.43,37.13,39.09,38096.0,1443.0,102602.0,804.02,-19.66,70.0,M-MC,8.63,193.0,0.04,0.73,45.15,AR,ATH,AUTO
26,FINCABLES,4.26,11.81,85.95,107.91,141890.0,17440.0,165084.0,1641.55,0.46,59.0,M-SC,1.50,220.0,0.12,1.17,24.20,OX40N,ATH,CABLES
65,SIEMENS,7.19,-3.71,30.35,25.51,54384.0,-6905.0,179190.0,4671.50,50.45,69.0,H-LC,1.41,51.0,-0.13,1.27,27.54,AR,ATH,ELECTRICAL
11,BANDHANBNK,4.26,-16.38,130.11,92.42,303068.0,-45627.0,232932.0,400.00,99.71,60.0,H-SC,4.67,174.0,-0.15,1.65,28.32,XY24,NTT,BANKS
62,SATIN,-0.90,-11.28,71.14,51.83,174373.0,-31171.0,245113.0,274.00,-21.16,65.0,H-SC,2.38,159.0,-0.18,1.74,19.41,XY24,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,6.10,21.96,1.82,24.18,6770.0,66975.0,371975.0,303.00,-82.34,76.0,X-SC,2.16,97.0,9.89,2.64,42.31,X40N,NTT,FINANCE
80,VALIANTORG,1.05,-44.56,214.15,74.15,194223.0,-72910.0,90695.0,838.00,-263.44,60.0,H-SC,20.88,145.0,-0.38,0.64,34.97,XR,NTT,CHEMICALS
52,PAGEIND,1.90,-4.72,40.76,34.11,104227.0,-12669.0,255710.0,51418.64,-31.67,72.0,X-MC,16.03,55.0,-0.12,1.81,20.96,X40,ATH,APPARELS
67,SONACOMS,2.99,1.43,37.13,39.09,38096.0,1443.0,102602.0,804.02,-19.66,70.0,M-MC,8.63,193.0,0.04,0.73,45.15,AR,ATH,AUTO
31,HATHWAY,2.66,-36.15,171.39,73.29,118979.0,-39300.0,69420.0,31.40,704.35,67.0,H-SC,22.68,171.0,-0.33,0.49,30.44,XR,NTT,ENTERTAINMENT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.06
1     25       45.77
2     50       77.70

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.25
MC    29.51
LC    25.28
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.23
X40      24.66
X40N     15.75
AR        9.37
XR        8.40
XY25      7.00
OX40N     6.84
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    22.98
X-MC    21.98
H-SC    21.98
X-SC    12.52
M-SC    10.14
H-MC     5.09
M-MC     2.10
H-LC     1.27
M-LC     1.03
L-SC     0.61
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.61        -21.18   64.18
FINANCE             13.49        -13.00   59.05
IT                  11.70        -36.42  105.84
MISC                 7.13        -33.24   91.11
ELECTRICAL           6.60         -3.97   43.78
PAINTS               5.33        -30.98   53.72
BANKS                4.61        -18.35   78.43
INSURANCE            4.54         -5.88   42.12
PHARMA               3.95         -5.74   39.02
AUTO                 3.92        -18.38   65.34
AC                   2.03        -11.57   41.83
HEALTHCARE           1.96        -29.70   63.55
FOOTWEAR             1.85        -69.91  138.03
TRAVEL               1.83        -73.22  159.95
APPARELS             1.81         -4.95   40.76
DURABLES             1.74        -58.00   96.44
BREWERIES            1.52         -8.82   31.41
REALTY               1.45         -8.49   26.31
CERAMICS             1.37        -59.54  108.02
REFINERIES           1.23        -15.89   45.21
CEMENT               1.22        -56.01  172.73
CABLES               1.17         10.56   85.95
ENGINEERING          1.16        -48.14  115.90
JEWELLERY            1.10       -106.44  178.17
CHEMICALS            1.07        -75.08  217.92
ENTERTAINMENT        0.82        -66.77  166.24
TEXTILES             0.45        -45.22   86.63
HOTELS               0.38       -109.94  183.99

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3758070.0     21
X40       1694860.0     16
XR        1305746.0     12
AR        1250650.0     10
X40N      1077787.0     10
OX40N      827972.0     10
XY25       452316.0      5
SR         308580.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3693797.0     24
X-MC        1633193.0     15
X-LC        1533534.0     13
M-SC        1487165.0     14
X-SC        1417404.0     10
H-MC         361345.0      3
L-SC         204718.0      2
M-LC         146058.0      1
M-MC          89650.0      2
L-MC          54733.0      1
H-LC          54384.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1256182.0      6
           AR         956469.0      5
M-SC       XY24       857939.0      6
X-LC       X40        841147.0      7
X-SC       XY24       827526.0      4
H-SC       XR         819448.0      7
X-MC       X40        646630.0      7
           X40N       496207.0      4
X-SC       X40N       382795.0      4
M-SC       OX40N      369649.0      5
H-SC       OX40N      353118.0      4
X-LC       XY24       338996.0      2
H-SC       SR         308580.0      2
X-MC       XY25       246156.0      2
           XY24       244200.0      2
H-MC       XY24       233227.0      1
X-SC       X40        207083.0      2
X-LC       X40N       198785.0      2
M-SC       XR         185994.0      2
X-LC       XY25       154606.0      2
M-LC       XR         146058.0      1
H-MC       AR         128118.0      2
L-SC       OX40N      105205.0      1
           XR          99513.0      1
M-SC       AR          73583.0      1
L-MC       XR          54733.0      1
H-LC       AR          54384.0      1
M-MC       XY25        51554.0      1
           AR          38096.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 24.0 seconds