<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-26 15:09:03
-------------------
qualified stocks: 86
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  5.73 L
Current:  1.58 C
-------------------
Today PnL: -3.98 K (-0.03%)
Current PnL: -35.54 L (-18.81%)
CY Booked + Current PnL: -30.31 L (-16.04%)
-------------------
Total profit:  3.73 L
Total loss:  -39.27 L
-------------------
Total Booked + Current PnL: 12.56 L (8.6%)
Total Booked PnL: 48.10 L (32.94%)
Curr Year Booked PnL: 5.24 L (3.32%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.47%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.41%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,UNITDSPR,-1.67,11.96,7.87,20.77,20631.0,28001.0,262145.0,1644.00,-4.62,55.0,X-MC,12.30,64.0,1.36,1.73,26.01,X40N,NTT,BREWERIES
76,TTKPRESTIG,2.51,-20.64,26.13,0.09,20898.0,-20801.0,79976.0,770.00,-3.33,51.0,M-SC,8.42,250.0,-1.00,0.53,43.95,OX40N,NTT,DURABLES
50,KOTAKBANK,3.76,9.52,8.58,18.92,22524.0,22819.0,262521.0,452.46,-7.40,71.0,X-LC,2.08,12.0,1.01,1.73,18.12,X40,ATH,BANKS
52,M&M,-0.88,7.77,10.26,18.82,26612.0,18692.0,259373.0,3762.88,-6.96,56.0,X-LC,5.25,25.0,0.70,1.71,17.66,X40N,ATH,AUTO
66,SIS,1.90,-3.32,25.43,21.26,27297.0,-3690.0,107342.0,528.00,106.30,47.0,H-SC,19.64,168.0,-0.14,0.71,59.60,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SURYODAY,4.77,-9.88,36.52,23.03,58937.0,-17687.0,161384.0,216.00,-25.86,46.0,H-SC,14.48,166.0,-0.30,1.06,36.99,XR,NTT,BANKS
43,INDIGOPNTS,4.47,-15.70,18.65,0.02,27444.0,-27408.0,147151.0,1408.00,-19.63,66.0,M-SC,9.11,222.0,-1.00,0.97,66.95,OX40N,NTT,PAINTS
50,KOTAKBANK,3.76,9.52,8.58,18.92,22524.0,22819.0,262521.0,452.46,-7.40,71.0,X-LC,2.08,12.0,1.01,1.73,18.12,X40,ATH,BANKS
63,ROUTE,3.06,-60.29,318.76,66.28,168426.0,-80228.0,52838.0,2190.73,NaN,51.0,NaN,6.92,141.0,-0.48,0.35,27.30,SR,ATH,IT
12,BOSCH-HCIL,2.59,-25.16,33.61,-0.01,32147.0,-32157.0,95648.0,2282.00,746.26,64.0,M-SC,14.51,231.0,-1.00,0.63,62.81,OX40N,BTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
70,TANLA,-5.76,-40.77,266.82,117.25,427870.0,-110402.0,160359.0,1922.32,NaN,32.0,NaN,13.75,147.0,-0.26,1.06,40.40,AR,ATH,IT
81,VBL,-3.66,-14.49,58.65,35.66,176449.0,-50994.0,300850.0,669.42,-29.98,37.0,X-LC,7.01,13.0,-0.29,1.98,10.77,X40N,ATH,FMCG
23,DMART,-2.55,-7.13,41.51,31.42,120196.0,-22230.0,289560.0,5391.45,-22.07,35.0,X-LC,2.12,14.0,-0.18,1.91,4.49,X40N,ATH,FMCG
45,INFY,-1.95,-20.15,75.80,40.38,227867.0,-75854.0,300616.0,1972.00,-41.25,47.0,X-LC,15.35,3.0,-0.33,1.98,13.84,X40,NTT,IT
41,IEX,-1.88,-17.30,79.71,48.63,131812.0,-34590.0,165364.0,219.00,NaN,41.0,NaN,1.85,137.0,-0.26,1.09,7.88,XR,NTT,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UTIAMC,1.04,-0.91,52.54,51.15,115748.0,-2026.0,220304.0,1371.68,25.0,47.0,M-SC,7.09,229.0,-0.02,1.45,3.19,XY24,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.19,63.07,27.50,107.91,66210.0,93118.0,240762.0,1641.55,18.78,65.0,M-SC,26.14,220.0,1.41,1.59,81.13,OX40N,ATH,CABLES
66,SIS,1.90,-3.32,25.43,21.26,27297.0,-3690.0,107342.0,528.00,106.30,47.0,H-SC,19.64,168.0,-0.14,0.71,59.60,OX40N,NTT,MISC
43,INDIGOPNTS,4.47,-15.70,18.65,0.02,27444.0,-27408.0,147151.0,1408.00,-19.63,66.0,M-SC,9.11,222.0,-1.00,0.97,66.95,OX40N,NTT,PAINTS
76,TTKPRESTIG,2.51,-20.64,26.13,0.09,20898.0,-20801.0,79976.0,770.00,-3.33,51.0,M-SC,8.42,250.0,-1.00,0.53,43.95,OX40N,NTT,DURABLES
12,BOSCH-HCIL,2.59,-25.16,33.61,-0.01,32147.0,-32157.0,95648.0,2282.00,746.26,64.0,M-SC,14.51,231.0,-1.00,0.63,62.81,OX40N,BTT,AC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.19,63.07,27.50,107.91,66210.0,93118.0,240762.0,1641.55,18.78,65.0,M-SC,26.14,220.0,1.41,1.59,81.13,OX40N,ATH,CABLES
85,ZYDUSLIFE,2.01,20.96,12.02,35.51,30472.0,43935.0,253509.0,1285.01,19.66,55.0,H-LC,14.88,120.0,1.44,1.67,33.41,AR,ATH,PHARMA
27,GLAXO,2.23,21.62,11.57,35.69,28042.0,43084.0,242368.0,3380.16,-8.73,75.0,X-MC,13.52,56.0,1.54,1.60,44.05,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.19,63.07,27.50,107.91,66210.0,93118.0,240762.0,1641.55,18.78,65.0,M-SC,26.14,220.0,1.41,1.59,81.13,OX40N,ATH,CABLES
67,STARHEALTH,0.32,13.15,30.15,47.26,95900.0,36954.0,318077.0,761.00,-0.37,52.0,H-SC,15.48,173.0,0.39,2.09,37.53,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.19,63.07,27.50,107.91,66210.0,93118.0,240762.0,1641.55,18.78,65.0,M-SC,26.14,220.0,1.41,1.59,81.13,OX40N,ATH,CABLES
3,ALKYLAMINE,1.53,-10.86,115.99,92.54,104394.0,-10960.0,90003.0,4520.85,NaN,68.0,NaN,17.70,142.0,-0.10,0.59,70.91,SR,ATH,CHEMICALS
66,SIS,1.90,-3.32,25.43,21.26,27297.0,-3690.0,107342.0,528.00,106.30,47.0,H-SC,19.64,168.0,-0.14,0.71,59.60,OX40N,NTT,MISC
42,INDIAMART,0.13,-24.69,166.80,100.92,154927.0,-30454.0,92882.0,4675.60,NaN,40.0,NaN,13.18,140.0,-0.20,0.61,1.05,AR,ATH,MISC
70,TANLA,-5.76,-40.77,266.82,117.25,427870.0,-110402.0,160359.0,1922.32,NaN,32.0,NaN,13.75,147.0,-0.26,1.06,40.40,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,0.45,-39.12,116.82,32.01,151866.0,-83520.0,130000.0,17616.87,-55.19,26.0,X-SC,20.10,57.0,-0.55,0.86,0.45,X40,ATH,FMCG
55,PAGEIND,-0.99,-8.32,44.91,32.85,110501.0,-22329.0,246050.0,50936.07,-31.87,29.0,X-MC,8.22,55.0,-0.20,1.62,17.49,X40,ATH,APPARELS
19,COLPAL,-0.39,-29.01,97.03,39.86,181398.0,-76415.0,186950.0,3683.41,-14.08,30.0,X-MC,4.11,62.0,-0.42,1.23,5.75,XY25,ATH,FMCG
20,DABUR,-0.03,-22.78,86.10,43.70,164925.0,-56517.0,191551.0,735.00,-33.42,30.0,X-MC,11.19,70.0,-0.34,1.26,0.00,XY24,BTT,FMCG
74,TMPV,0.21,-25.08,90.54,42.75,282259.0,-104356.0,311751.0,600.00,-84.91,32.0,X-LC,4.40,4.0,-0.37,2.05,7.20,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABBOTINDIA,0.51,-10.93,29.53,15.37,47041.0,-19555.0,159300.0,34390.26,-27.58,42.0,X-MC,2.06,58.0,-0.42,1.05,7.91,X40,ATH,PHARMA
50,KOTAKBANK,3.76,9.52,8.58,18.92,22524.0,22819.0,262521.0,452.46,-7.40,71.0,X-LC,2.08,12.0,1.01,1.73,18.12,X40,ATH,BANKS
23,DMART,-2.55,-7.13,41.51,31.42,120196.0,-22230.0,289560.0,5391.45,-22.07,35.0,X-LC,2.12,14.0,-0.18,1.91,4.49,X40N,ATH,FMCG
53,MARUTI,-1.08,-1.50,26.53,24.64,64611.0,-3698.0,243540.0,17120.06,-7.22,42.0,X-LC,3.67,33.0,-0.06,1.60,11.05,XR,ATH,AUTO
19,COLPAL,-0.39,-29.01,97.03,39.86,181398.0,-76415.0,186950.0,3683.41,-14.08,30.0,X-MC,4.11,62.0,-0.42,1.23,5.75,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.03,-22.78,86.10,43.70,164925.0,-56517.0,191551.0,735.00,-33.42,30.0,X-MC,11.19,70.0,-0.34,1.26,0.00,XY24,BTT,FMCG
36,HINDUNILVR,-0.01,-15.80,44.37,21.56,125727.0,-53157.0,283360.0,2922.00,-41.98,39.0,X-LC,7.10,9.0,-0.42,1.87,0.45,XY25,NTT,FMCG
56,PGHH,0.45,-39.12,116.82,32.01,151866.0,-83520.0,130000.0,17616.87,-55.19,26.0,X-SC,20.10,57.0,-0.55,0.86,0.45,X40,ATH,FMCG
82,VOLTAS,-1.63,-4.35,51.80,45.20,95004.0,-8337.0,183405.0,1856.00,31.69,37.0,X-MC,5.87,79.0,-0.09,1.21,0.52,XY25,NTT,AC
39,ICICIGI,-1.41,-15.61,40.87,18.89,69021.0,-31230.0,168879.0,2244.41,-15.87,36.0,X-MC,10.26,66.0,-0.45,1.11,0.61,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,0.45,-39.12,116.82,32.01,151866.0,-83520.0,130000.0,17616.87,-55.19,26.0,X-SC,20.10,57.0,-0.55,0.86,0.45,X40,ATH,FMCG
1,ABBOTINDIA,0.51,-10.93,29.53,15.37,47041.0,-19555.0,159300.0,34390.26,-27.58,42.0,X-MC,2.06,58.0,-0.42,1.05,7.91,X40,ATH,PHARMA
2,ACC,1.85,-40.48,193.68,74.81,309113.0,-108528.0,159600.0,3906.00,-40.88,49.0,X-SC,11.32,85.0,-0.35,1.05,6.62,XY24,BTT,CEMENT
39,ICICIGI,-1.41,-15.61,40.87,18.89,69021.0,-31230.0,168879.0,2244.41,-15.87,36.0,X-MC,10.26,66.0,-0.45,1.11,0.61,X40,ATH,INSURANCE
40,ICICIPRULI,2.01,-13.91,51.33,30.28,87057.0,-27403.0,169602.0,787.27,-44.81,60.0,X-MC,11.52,78.0,-0.31,1.12,13.00,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.17,-25.25,66.82,24.70,198429.0,-100317.0,296961.0,452.00,-30.35,39.0,X-LC,10.92,1.0,-0.51,1.96,1.46,X40,NTT,FMCG
72,TCS,-1.13,-33.36,86.36,24.20,266634.0,-154526.0,308747.0,4230.71,-44.65,45.0,X-LC,13.12,2.0,-0.58,2.03,15.13,X40,ATH,IT
45,INFY,-1.95,-20.15,75.80,40.38,227867.0,-75854.0,300616.0,1972.00,-41.25,47.0,X-LC,15.35,3.0,-0.33,1.98,13.84,X40,NTT,IT
74,TMPV,0.21,-25.08,90.54,42.75,282259.0,-104356.0,311751.0,600.00,-84.91,32.0,X-LC,4.40,4.0,-0.37,2.05,7.20,XY24,NTT,AUTO
33,HCLTECH,-1.14,-13.00,42.48,23.97,114384.0,-40220.0,269266.0,1853.42,-15.10,49.0,X-LC,9.42,8.0,-0.35,1.77,27.06,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.53,-26.21,80.09,32.89,45629.0,-20234.0,56972.0,1800.00,319.52,46.0,L-MC,11.79,258.0,-0.44,0.38,40.46,XR,NTT,BANKS
30,HAPPSTMNDS,0.63,-43.98,226.81,83.08,162850.0,-56365.0,71800.0,1466.54,NaN,69.0,NaN,7.30,152.0,-0.35,0.47,34.49,AR,ATH,IT
76,TTKPRESTIG,2.51,-20.64,26.13,0.09,20898.0,-20801.0,79976.0,770.00,-3.33,51.0,M-SC,8.42,250.0,-1.00,0.53,43.95,OX40N,NTT,DURABLES
3,ALKYLAMINE,1.53,-10.86,115.99,92.54,104394.0,-10960.0,90003.0,4520.85,NaN,68.0,NaN,17.70,142.0,-0.10,0.59,70.91,SR,ATH,CHEMICALS
12,BOSCH-HCIL,2.59,-25.16,33.61,-0.01,32147.0,-32157.0,95648.0,2282.00,746.26,64.0,M-SC,14.51,231.0,-1.00,0.63,62.81,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.19,63.07,27.50,107.91,66210.0,93118.0,240762.0,1641.55,18.78,65.0,M-SC,26.14,220.0,1.41,1.59,81.13,OX40N,ATH,CABLES
12,BOSCH-HCIL,2.59,-25.16,33.61,-0.01,32147.0,-32157.0,95648.0,2282.00,746.26,64.0,M-SC,14.51,231.0,-1.00,0.63,62.81,OX40N,BTT,AC
27,GLAXO,2.23,21.62,11.57,35.69,28042.0,43084.0,242368.0,3380.16,-8.73,75.0,X-MC,13.52,56.0,1.54,1.60,44.05,X40,ATH,PHARMA
30,HAPPSTMNDS,0.63,-43.98,226.81,83.08,162850.0,-56365.0,71800.0,1466.54,NaN,69.0,NaN,7.30,152.0,-0.35,0.47,34.49,AR,ATH,IT
38,HYUNDAI,1.28,16.95,23.08,43.94,67839.0,42598.0,293930.0,2782.73,21.12,68.0,X-LC,7.28,29.0,0.63,1.94,34.95,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.87
1     25       45.63
2     50       78.37

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    37.32
MC    22.46
SC    22.08
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      27.20
XY24     24.31
X40N     18.85
XR        9.19
OX40N     7.45
XY25      7.23
AR        4.87
SR        0.94
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.84
X-MC    19.85
H-SC     8.68
X-SC     7.83
M-SC     5.57
H-LC     1.67
M-MC     1.17
H-MC     1.06
M-LC     0.81
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.55        -26.35   71.67
IT                  11.27        -39.29  108.38
FINANCE             10.85        -17.25   67.74
AUTO                 8.39         -6.12   44.13
BANKS                6.42         -9.70   57.00
PHARMA               6.03          9.42   16.27
MISC                 5.98        -35.93   90.61
INSURANCE            5.90         -3.62   40.27
PAINTS               5.52        -17.73   37.81
ELECTRICAL           2.95        -16.35   61.29
AC                   1.84        -14.51   45.57
REFINERIES           1.75        -12.23   49.93
BREWERIES            1.73         10.68    7.87
FOOTWEAR             1.66        -73.84  143.54
APPARELS             1.62         -9.07   44.91
CABLES               1.59         38.68   27.50
DURABLES             1.52        -67.95  108.81
TRAVEL               1.45       -103.08  204.76
CERAMICS             1.31        -54.73  101.74
CHEMICALS            1.26        -38.28  150.53
ENGINEERING          1.24        -28.62   87.45
CEMENT               1.05        -68.00  193.68
JEWELLERY            0.96       -117.90  193.61
HEALTHCARE           0.71        -67.34  109.35
ENTERTAINMENT        0.71        -79.02  185.79
TEXTILES             0.40        -52.89   96.48
HOTELS               0.38        -99.19  169.45

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3635491.0     19
X40       2091578.0     18
XR        1402233.0     13
X40N      1218664.0     12
AR        1060301.0      7
OX40N      663094.0     10
XY25       602554.0      5
SR         272820.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2437330.0     19
X-MC        1490068.0     14
X-SC        1087055.0      6
H-SC         834276.0      8
M-SC         320665.0      6
H-MC         253335.0      1
M-LC         168639.0      1
M-MC          67817.0      1
L-MC          45629.0      1
H-LC          30472.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1210761.0      9
X-SC       XY24       656364.0      2
H-SC       XY24       524289.0      3
X-MC       X40        507190.0      6
X-LC       XY24       469176.0      2
X-MC       X40N       458110.0      4
X-LC       X40N       434447.0      5
X-MC       XY25       276402.0      2
X-LC       XY25       258335.0      2
X-SC       X40        256590.0      2
H-MC       XY24       253335.0      1
X-MC       XY24       248366.0      2
H-SC       OX40N      221465.0      3
X-SC       X40N       174101.0      2
M-LC       XR         168639.0      1
M-SC       OX40N      146699.0      4
           XY24       115748.0      1
H-SC       XR          88522.0      2
M-MC       XY25        67817.0      1
X-LC       XR          64611.0      1
M-SC       XR          58218.0      1
L-MC       XR          45629.0      1
H-LC       AR          30472.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds