<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-28 11:41:42
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: 1.04 L (0.69%)
Current PnL: -31.91 L (-17.5%)
CY Booked + Current PnL: -29.83 L (-16.36%)
-------------------
Total profit:  2.64 L
Total loss:  -34.55 L
-------------------
Total Booked + Current PnL: 13.04 L (9.35%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.79%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.89%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.15,4.93,12.80,18.37,18953.0,6960.0,148070.0,1670.26,-26.53,62.0,X-LC,5.18,5.0,0.37,0.98,16.26,X40,ATH,CHEMICALS
51,KOTAKBANK,0.01,3.86,16.60,21.11,23874.0,5346.0,143819.0,453.24,-10.71,56.0,X-LC,7.51,12.0,0.22,0.95,9.99,X40,ATH,BANKS
55,MASFIN,3.00,-3.43,25.88,21.57,24488.0,-3360.0,94620.0,397.04,-16.89,47.0,H-SC,4.38,167.0,-0.14,0.63,12.78,XR,ATH,FINANCE
17,CIPLA,0.05,14.82,17.30,34.69,30423.0,22696.0,175857.0,1663.60,-11.14,65.0,X-LC,9.66,18.0,0.75,1.16,18.94,X40N,ATH,PHARMA
53,M&M,0.46,1.29,21.81,23.38,30637.0,1791.0,140472.0,3802.40,-14.09,48.0,X-LC,8.90,25.0,0.06,0.93,6.50,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,13.51,-50.98,175.96,35.27,97941.0,-57888.0,55661.0,80.00,-61.77,71.0,L-SC,25.60,266.0,-0.59,0.37,37.26,XR,NTT,HOTELS
25,FINCABLES,8.39,49.11,39.44,107.91,86826.0,72502.0,220146.0,1641.55,33.94,72.0,M-SC,26.86,220.0,0.84,1.46,65.62,OX40N,ATH,CABLES
71,SIEMENS,5.48,4.21,20.44,25.51,39640.0,7840.0,193935.0,4671.50,62.95,61.0,H-LC,14.83,51.0,0.20,1.28,36.16,AR,ATH,ELECTRICAL
86,VALIANTORG,5.42,-37.19,177.25,74.15,182151.0,-60840.0,102765.0,838.00,-284.65,60.0,H-SC,8.81,145.0,-0.33,0.68,52.93,XR,NTT,CHEMICALS
26,GILLETTE,4.85,-2.24,32.70,29.72,81163.0,-5691.0,248205.0,10978.86,-24.97,66.0,X-SC,8.30,83.0,-0.07,1.64,14.06,X40,ATH,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,EASEMYTRIP,-7.37,-59.11,256.28,45.70,185308.0,-104508.0,72307.0,26.40,-24.87,42.0,M-SC,6.18,204.0,-0.56,0.48,26.67,XY24,NTT,TRAVEL
46,IRCTC,-2.61,-36.95,142.55,52.93,243138.0,-99945.0,170563.0,1269.00,-53.32,39.0,H-MC,15.63,119.0,-0.41,1.13,5.80,XY24,BTT,TRAVEL
34,HDFCBANK,-2.60,-9.24,41.44,28.37,88342.0,-21704.0,213181.0,1073.00,-23.00,43.0,X-LC,16.07,26.0,-0.25,1.41,3.70,X40,BTT,BANKS
3,ALKYLAMINE,-2.22,-27.94,168.70,93.63,122739.0,-28207.0,72756.0,4546.37,-22.90,55.0,H-SC,11.56,142.0,-0.23,0.48,37.38,SR,ATH,CHEMICALS
56,MEDANTA,-1.71,3.32,23.03,27.12,42002.0,5861.0,182378.0,1486.00,0.19,55.0,X-SC,8.03,87.0,0.14,1.21,25.67,XY24,NTT,HEALTHCARE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,2.71,-0.99,94.34,92.42,260201.0,-2747.0,275812.0,400.0,136.35,66.0,H-SC,21.45,174.0,-0.01,1.82,51.94,XY24,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,8.39,49.11,39.44,107.91,86826.0,72502.0,220146.0,1641.55,33.94,72.0,M-SC,26.86,220.0,0.84,1.46,65.62,OX40N,ATH,CABLES
72,SIS,-0.88,-9.31,33.70,21.26,33936.0,-10332.0,100700.0,528.00,2395.34,62.0,H-SC,17.08,168.0,-0.30,0.67,49.73,OX40N,NTT,MISC
16,CERA,0.95,-24.20,63.43,23.89,84579.0,-42561.0,133342.0,9475.00,-26.97,60.0,H-SC,7.15,153.0,-0.50,0.88,28.14,OX40N,NTT,CERAMICS
50,KANSAINER,0.27,-27.13,55.72,13.47,109493.0,-73161.0,196506.0,340.00,-37.29,62.0,H-SC,12.56,162.0,-0.67,1.30,37.26,XY24,NTT,PAINTS
43,INDIGOPNTS,0.90,-29.02,40.91,0.02,50690.0,-50652.0,123907.0,1408.00,89.17,66.0,M-SC,17.86,222.0,-1.00,0.82,40.58,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,8.39,49.11,39.44,107.91,86826.0,72502.0,220146.0,1641.55,33.94,72.0,M-SC,26.86,220.0,0.84,1.46,65.62,OX40N,ATH,CABLES
68,SATIN,-0.48,22.93,23.51,51.83,79849.0,63353.0,339637.0,274.00,10.38,68.0,H-SC,35.67,159.0,0.79,2.25,65.45,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.11,1.52,45.05,47.26,128577.0,4287.0,285410.0,761.00,60.18,61.0,H-SC,9.88,173.0,0.03,1.89,25.30,XY24,NTT,INSURANCE
25,FINCABLES,8.39,49.11,39.44,107.91,86826.0,72502.0,220146.0,1641.55,33.94,72.0,M-SC,26.86,220.0,0.84,1.46,65.62,OX40N,ATH,CABLES
68,SATIN,-0.48,22.93,23.51,51.83,79849.0,63353.0,339637.0,274.00,10.38,68.0,H-SC,35.67,159.0,0.79,2.25,65.45,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.63,14.50,18.45,35.63,44273.0,30388.0,239962.0,1286.17,-0.45,76.0,H-MC,4.87,120.0,0.69,1.59,26.17,AR,ATH,PHARMA
73,SONACOMS,1.76,7.03,29.95,39.09,32428.0,7114.0,108273.0,804.02,-15.20,65.0,M-MC,18.93,193.0,0.22,0.72,53.17,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,8.39,49.11,39.44,107.91,86826.0,72502.0,220146.0,1641.55,33.94,72.0,M-SC,26.86,220.0,0.84,1.46,65.62,OX40N,ATH,CABLES
91,ZYDUSLIFE,0.63,14.50,18.45,35.63,44273.0,30388.0,239962.0,1286.17,-0.45,76.0,H-MC,4.87,120.0,0.69,1.59,26.17,AR,ATH,PHARMA
73,SONACOMS,1.76,7.03,29.95,39.09,32428.0,7114.0,108273.0,804.02,-15.20,65.0,M-MC,18.93,193.0,0.22,0.72,53.17,AR,ATH,AUTO
42,INDIAMART,-0.87,-13.19,138.14,106.72,147900.0,-16271.0,107065.0,4810.62,-60.94,45.0,H-SC,10.67,140.0,-0.11,0.71,3.65,AR,ATH,MISC
55,MASFIN,3.00,-3.43,25.88,21.57,24488.0,-3360.0,94620.0,397.04,-16.89,47.0,H-SC,4.38,167.0,-0.14,0.63,12.78,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,0.51,-0.86,30.72,29.60,76021.0,-2136.0,247464.0,5391.45,-16.39,36.0,X-LC,3.69,14.0,-0.03,1.64,13.11,X40N,ATH,FMCG
27,GLAXO,0.60,-7.82,50.95,39.15,93593.0,-15588.0,183696.0,3466.20,-29.60,37.0,X-MC,6.58,56.0,-0.17,1.21,1.62,X40,ATH,PHARMA
33,HCLTECH,0.28,-24.38,60.69,21.51,111024.0,-58988.0,182936.0,1872.35,-20.60,38.0,X-LC,18.81,8.0,-0.53,1.21,3.67,X40,ATH,IT
88,VOLTAS,-0.76,-1.29,47.09,45.20,89127.0,-2472.0,189270.0,1856.00,13.01,40.0,X-MC,5.02,79.0,-0.03,1.25,3.41,XY25,NTT,AC
79,TCS,0.35,-32.94,86.23,24.88,267874.0,-152622.0,310651.0,4253.91,-43.30,40.0,X-LC,17.53,2.0,-0.57,2.05,3.08,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,0.51,-0.86,30.72,29.60,76021.0,-2136.0,247464.0,5391.45,-16.39,36.0,X-LC,3.69,14.0,-0.03,1.64,13.11,X40N,ATH,FMCG
65,RELIANCE,-0.43,-13.31,44.54,25.30,77595.0,-26749.0,174214.0,1952.00,-15.42,45.0,X-LC,3.90,21.0,-0.34,1.15,3.52,XY25,BTT,REFINERIES
84,UNITDSPR,0.70,-4.32,26.22,20.77,58741.0,-10114.0,224030.0,1644.00,-15.10,51.0,X-MC,4.15,64.0,-0.17,1.48,6.87,X40N,NTT,BREWERIES
39,ICICIGI,-0.52,-1.97,21.74,19.34,42646.0,-3945.0,196164.0,2252.93,-17.63,56.0,X-MC,4.97,66.0,-0.09,1.30,9.56,X40,ATH,INSURANCE
88,VOLTAS,-0.76,-1.29,47.09,45.20,89127.0,-2472.0,189270.0,1856.00,13.01,40.0,X-MC,5.02,79.0,-0.03,1.25,3.41,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,0.60,-7.82,50.95,39.15,93593.0,-15588.0,183696.0,3466.20,-29.60,37.0,X-MC,6.58,56.0,-0.17,1.21,1.62,X40,ATH,PHARMA
79,TCS,0.35,-32.94,86.23,24.88,267874.0,-152622.0,310651.0,4253.91,-43.30,40.0,X-LC,17.53,2.0,-0.57,2.05,3.08,X40,ATH,IT
32,HAVELLS,0.83,-22.46,69.50,31.42,176745.0,-73681.0,254310.0,2052.62,-27.08,45.0,X-MC,12.64,63.0,-0.42,1.68,3.09,X40,ATH,ELECTRICAL
88,VOLTAS,-0.76,-1.29,47.09,45.20,89127.0,-2472.0,189270.0,1856.00,13.01,40.0,X-MC,5.02,79.0,-0.03,1.25,3.41,XY25,NTT,AC
65,RELIANCE,-0.43,-13.31,44.54,25.30,77595.0,-26749.0,174214.0,1952.00,-15.42,45.0,X-LC,3.90,21.0,-0.34,1.15,3.52,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.87,-55.32,202.63,35.20,116484.0,-71184.0,57486.0,2096.00,-24.62,43.0,X-SC,25.35,91.0,-0.61,0.38,14.01,X40,NTT,FOOTWEAR
64,RELAXO,0.17,-60.89,289.40,52.31,164310.0,-88384.0,56776.0,1176.00,-58.38,55.0,X-SC,24.56,92.0,-0.54,0.38,26.94,X40N,NTT,FOOTWEAR
60,QUESS,4.16,-12.57,98.91,73.90,92346.0,-13429.0,93364.0,424.00,-53.17,60.0,X-SC,9.62,80.0,-0.15,0.62,27.27,XY24,NTT,MISC
28,GODREJCP,1.22,-6.53,40.66,31.47,56479.0,-9709.0,138905.0,1469.04,-1.64,50.0,X-LC,8.84,32.0,-0.17,0.92,6.58,X40N,ATH,FMCG
53,M&M,0.46,1.29,21.81,23.38,30637.0,1791.0,140472.0,3802.40,-14.09,48.0,X-LC,8.90,25.0,0.06,0.93,6.50,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.58,-23.10,54.82,19.06,143402.0,-78579.0,261587.0,452.00,-57.95,41.0,X-LC,14.61,1.0,-0.55,1.73,4.24,X40,NTT,FMCG
79,TCS,0.35,-32.94,86.23,24.88,267874.0,-152622.0,310651.0,4253.91,-43.30,40.0,X-LC,17.53,2.0,-0.57,2.05,3.08,X40,ATH,IT
45,INFY,-0.67,-21.04,70.01,34.24,172966.0,-65829.0,247059.0,1972.00,-37.95,44.0,X-LC,18.85,3.0,-0.38,1.63,5.93,X40,NTT,IT
81,TMPV,3.98,-8.73,49.64,36.58,161216.0,-31071.0,324770.0,600.00,-81.44,75.0,X-LC,22.06,4.0,-0.19,2.15,35.36,XY24,NTT,AUTO
59,PIDILITIND,0.15,4.93,12.80,18.37,18953.0,6960.0,148070.0,1670.26,-26.53,62.0,X-LC,5.18,5.0,0.37,0.98,16.26,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.00,-31.17,93.07,32.89,49458.0,-24066.0,53141.0,1800.00,-350.00,61.0,L-MC,8.86,258.0,-0.49,0.35,30.80,XR,NTT,BANKS
72,SIS,-0.88,-9.31,33.70,21.26,33936.0,-10332.0,100700.0,528.00,2395.34,62.0,H-SC,17.08,168.0,-0.30,0.67,49.73,OX40N,NTT,MISC
86,VALIANTORG,5.42,-37.19,177.25,74.15,182151.0,-60840.0,102765.0,838.00,-284.65,60.0,H-SC,8.81,145.0,-0.33,0.68,52.93,XR,NTT,CHEMICALS
73,SONACOMS,1.76,7.03,29.95,39.09,32428.0,7114.0,108273.0,804.02,-15.20,65.0,M-MC,18.93,193.0,0.22,0.72,53.17,AR,ATH,AUTO
75,SURYODAY,2.62,-5.56,30.28,23.03,51208.0,-9955.0,169116.0,216.00,84.21,61.0,H-SC,18.89,166.0,-0.19,1.12,42.39,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,-0.48,22.93,23.51,51.83,79849.0,63353.0,339637.0,274.00,10.38,68.0,H-SC,35.67,159.0,0.79,2.25,65.45,XY24,NTT,FINANCE
69,SFL,-0.10,-38.40,105.57,26.63,170518.0,-100697.0,161521.0,1287.00,22.30,65.0,M-SC,10.56,242.0,-0.59,1.07,34.62,XY24,NTT,MISC
91,ZYDUSLIFE,0.63,14.50,18.45,35.63,44273.0,30388.0,239962.0,1286.17,-0.45,76.0,H-MC,4.87,120.0,0.69,1.59,26.17,AR,ATH,PHARMA
25,FINCABLES,8.39,49.11,39.44,107.91,86826.0,72502.0,220146.0,1641.55,33.94,72.0,M-SC,26.86,220.0,0.84,1.46,65.62,OX40N,ATH,CABLES
37,HONAUT,1.71,-6.19,61.30,51.31,110892.0,-11938.0,180900.0,58357.33,-22.03,71.0,X-SC,10.37,90.0,-0.11,1.20,37.44,X40N,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.43
1     25       42.71
2     50       72.83

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.90
LC    31.40
MC    25.75
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.62
X40      25.22
X40N     16.99
XR        8.95
OX40N     7.09
AR        6.89
XY25      6.47
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.19
H-SC    22.37
X-MC    20.72
M-SC    10.10
X-SC     9.85
H-MC     2.72
M-MC     1.96
H-LC     1.28
M-LC     0.93
L-SC     0.58
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.08        -16.02   56.91
FINANCE             10.79        -13.16   62.37
IT                  10.19        -46.04  119.05
MISC                 6.95        -27.91   83.48
AUTO                 6.89         -5.27   44.73
BANKS                5.65         -6.21   55.33
PAINTS               5.57        -16.86   37.15
INSURANCE            5.31         -3.32   38.49
PHARMA               5.06          3.27   27.82
ELECTRICAL           4.16        -12.36   52.02
CHEMICALS            2.14        -25.37  100.08
HEALTHCARE           2.00        -18.51   49.43
AC                   1.77        -19.42   51.80
APPARELS             1.77         -0.51   34.27
FOOTWEAR             1.71        -70.72  139.17
TRAVEL               1.61        -84.18  176.41
DURABLES             1.59        -60.88  100.03
BREWERIES            1.48         -4.51   26.22
CABLES               1.46         32.93   39.44
REALTY               1.40         -5.08   22.34
CERAMICS             1.35        -49.77   95.26
ENGINEERING          1.28        -25.38   82.72
REFINERIES           1.15        -15.35   44.54
CEMENT               1.13        -56.62  173.80
JEWELLERY            1.06        -99.04  168.20
ENTERTAINMENT        0.73        -74.92  179.24
TEXTILES             0.40        -51.40   94.57
HOTELS               0.37       -104.00  175.96

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3423079.0     21
X40       1877242.0     19
XR        1330352.0     13
X40N      1157663.0     13
AR        1141674.0      9
OX40N      719226.0     10
XY25       461476.0      5
SR         294509.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3404026.0     24
X-LC        1873821.0     21
X-MC        1597665.0     15
M-SC        1391427.0     14
X-SC        1316239.0      9
H-MC         287411.0      2
L-SC         202849.0      2
M-LC         151796.0      1
M-MC          90889.0      2
L-MC          49458.0      1
H-LC          39640.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1042415.0      6
X-LC       X40       1023230.0     10
H-SC       AR         949893.0      5
M-SC       XY24       830925.0      6
H-SC       XR         799645.0      7
X-SC       XY24       789604.0      4
X-MC       X40        656365.0      7
           X40N       475114.0      4
X-LC       X40N       353561.0      6
X-SC       X40N       328988.0      3
H-SC       OX40N      317564.0      4
X-LC       XY24       303882.0      2
M-SC       OX40N      296754.0      5
H-SC       SR         294509.0      2
X-MC       XY25       253071.0      2
H-MC       XY24       243138.0      1
X-MC       XY24       213115.0      2
X-SC       X40        197647.0      2
M-SC       XR         188308.0      2
M-LC       XR         151796.0      1
X-LC       XY25       149944.0      2
L-SC       OX40N      104908.0      1
           XR          97941.0      1
M-SC       AR          75440.0      1
M-MC       XY25        58461.0      1
L-MC       XR          49458.0      1
H-MC       AR          44273.0      1
X-LC       XR          43204.0      1
H-LC       AR          39640.0      1
M-MC       AR          32428.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 24.0 seconds