<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-23 09:59:08
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.28 C
-------------------
Today PnL: -3.23 L (-2.46%)
Current PnL: -48.85 L (-30.06%)
CY Booked + Current PnL: -32.96 L (-20.28%)
-------------------
Total profit:  42.03 K
Total loss:  -49.27 L
-------------------
Total Booked + Current PnL: -5.98 L (-4.41%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.39%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.20 C (93.24%)
===================
Deployed:  1.36 C
Current:  1.28 C
CAGR/XIRR %: -2.69%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-3.16,-10.29,35.51,21.57,31213.0,-10080.0,87900.0,397.04,-22.76,39.0,H-SC,1.73,167.0,-0.32,0.69,19.89,XR,ATH,FINANCE
77,TTKPRESTIG,2.22,-38.03,61.51,0.09,38415.0,-38323.0,62454.0,770.00,44.93,41.0,M-SC,18.41,250.0,-1.00,0.49,5.52,OX40N,NTT,DURABLES
37,ICICIGI,-2.36,-8.08,29.84,19.34,54885.0,-16178.0,183931.0,2252.93,-22.78,26.0,X-MC,3.17,66.0,-0.29,1.43,1.68,X40,ATH,INSURANCE
2,ABBOTINDIA,-2.64,-12.74,35.31,18.07,55105.0,-22795.0,156060.0,35195.00,-25.68,39.0,X-MC,10.64,58.0,-0.41,1.22,0.00,X40,ATH,PHARMA
67,SONACOMS,-4.31,-16.19,65.97,39.09,55929.0,-16380.0,84779.0,804.02,-33.57,41.0,M-MC,7.89,193.0,-0.29,0.66,19.93,AR,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,2.22,-38.03,61.51,0.09,38415.0,-38323.0,62454.0,770.00,44.93,41.0,M-SC,18.41,250.0,-1.00,0.49,5.52,OX40N,NTT,DURABLES
62,SATIN,2.14,-17.84,84.80,51.83,192497.0,-49283.0,227001.0,274.00,-26.41,47.0,H-SC,1.76,159.0,-0.26,1.77,10.58,XY24,NTT,FINANCE
33,HCLTECH,0.80,-12.75,41.94,23.83,88523.0,-30853.0,211071.0,1908.19,-8.19,39.0,X-LC,11.78,8.0,-0.35,1.65,2.49,X40,ATH,IT
73,TCS,0.08,-29.76,80.21,26.57,260987.0,-137893.0,325380.0,4311.59,-40.68,28.0,X-LC,17.04,2.0,-0.53,2.54,1.55,X40,ATH,IT
43,INFY,-0.52,-14.95,57.84,34.24,153925.0,-46766.0,266122.0,1972.00,-33.24,35.0,X-LC,15.11,3.0,-0.30,2.07,2.34,X40,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-6.32,-38.03,169.52,67.02,374298.0,-135510.0,220799.0,485.0,-66.62,42.0,X-SC,25.95,81.0,-0.36,1.72,4.44,XY24,NTT,FMCG
82,VOLTAS,-5.75,-2.34,48.67,45.20,91139.0,-4482.0,187260.0,1856.0,11.79,27.0,X-MC,4.91,79.0,-0.05,1.46,4.30,XY25,NTT,AC
83,WHIRLPOOL,-5.72,-36.81,187.89,81.92,136299.0,-42256.0,72542.0,2270.0,-62.95,36.0,M-SC,25.38,210.0,-0.31,0.57,1.90,XR,NTT,DURABLES
11,BANDHANBNK,-5.13,-27.69,166.12,92.42,334591.0,-77144.0,201415.0,400.0,72.41,34.0,H-SC,6.91,174.0,-0.23,1.57,10.95,XY24,NTT,BANKS
55,RAJESHEXPO,-5.00,-82.75,480.00,0.07,113602.0,-113510.0,23667.0,518.0,767.42,15.0,L-SC,32.51,268.0,-1.00,0.18,0.00,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.77,7.02,94.27,107.91,148961.0,10371.0,158015.0,1641.55,-3.60,48.0,M-SC,8.46,220.0,0.07,1.23,18.88,OX40N,ATH,CABLES
77,TTKPRESTIG,2.22,-38.03,61.51,0.09,38415.0,-38323.0,62454.0,770.00,44.93,41.0,M-SC,18.41,250.0,-1.00,0.49,5.52,OX40N,NTT,DURABLES
66,SIS,-3.64,-39.44,100.23,21.26,67399.0,-43788.0,67244.0,528.00,1566.32,27.0,H-SC,14.18,168.0,-0.65,0.52,0.00,OX40N,NTT,MISC
18,CERA,-3.24,-39.85,105.98,23.89,112125.0,-70105.0,105798.0,9475.00,-42.00,41.0,H-SC,18.73,153.0,-0.63,0.82,1.67,OX40N,NTT,CERAMICS
72,TATAELXSI,-1.89,-40.08,120.35,32.03,95067.0,-52843.0,78992.0,9161.00,-25.07,35.0,H-SC,20.60,158.0,-0.56,0.62,2.93,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-3.77,7.02,94.27,107.91,148961.0,10371.0,158015.0,1641.55,-3.60,48.0,M-SC,8.46,220.0,0.07,1.23,18.88,OX40N,ATH,CABLES
1,ABB,-2.97,12.10,29.85,45.57,87544.0,31661.0,293280.0,7934.00,-27.96,52.0,H-MC,13.13,125.0,0.36,2.29,30.24,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.97,12.10,29.85,45.57,87544.0,31661.0,293280.0,7934.00,-27.96,52.0,H-MC,13.13,125.0,0.36,2.29,30.24,AR,NTT,ELECTRICAL
26,FINCABLES,-3.77,7.02,94.27,107.91,148961.0,10371.0,158015.0,1641.55,-3.60,48.0,M-SC,8.46,220.0,0.07,1.23,18.88,OX40N,ATH,CABLES
40,INDIAMART,-1.52,-15.60,144.94,106.72,150871.0,-19244.0,104092.0,4810.62,-61.91,30.0,H-SC,11.24,140.0,-0.13,0.81,4.13,AR,ATH,MISC
85,ZYDUSLIFE,-1.25,-7.27,46.26,35.63,89900.0,-15238.0,194336.0,1286.17,-19.37,42.0,H-MC,5.35,120.0,-0.17,1.52,8.19,AR,ATH,PHARMA
84,WIPRO,-0.92,-22.42,122.06,72.27,160450.0,-37996.0,131452.0,420.00,-30.18,30.0,M-LC,17.44,98.0,-0.24,1.02,0.39,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-2.37,-28.98,85.89,32.01,130237.0,-61888.0,151632.0,17616.87,-51.96,12.0,X-MC,15.17,57.0,-0.48,1.18,0.0,X40,ATH,FMCG
38,ICICIPRULI,-3.15,-11.52,47.75,30.73,83234.0,-22693.0,174312.0,790.00,-35.24,18.0,X-MC,3.87,78.0,-0.27,1.36,0.0,X40,ATH,INSURANCE
58,RELAXO,-4.91,-66.26,351.44,52.31,172114.0,-96186.0,48974.0,1176.00,-64.09,18.0,X-SC,25.51,92.0,-0.56,0.38,0.0,X40N,NTT,FOOTWEAR
12,BATAINDIA,-4.08,-58.96,229.46,35.20,121166.0,-75865.0,52805.0,2096.00,-30.83,19.0,X-SC,30.54,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
34,HDFCBANK,-3.04,-9.47,41.80,28.37,88881.0,-22252.0,212633.0,1073.00,-23.00,21.0,X-LC,11.48,26.0,-0.25,1.66,0.0,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-2.00,-6.41,29.03,20.77,63618.0,-14999.0,219145.0,1644.00,-16.95,37.0,X-MC,1.44,64.0,-0.24,1.71,0.00,X40N,NTT,BREWERIES
37,ICICIGI,-2.36,-8.08,29.84,19.34,54885.0,-16178.0,183931.0,2252.93,-22.78,26.0,X-MC,3.17,66.0,-0.29,1.43,1.68,X40,ATH,INSURANCE
65,SIEMENS,-3.56,-18.91,54.78,25.51,82666.0,-35190.0,150905.0,4671.50,26.69,40.0,H-LC,3.28,51.0,-0.43,1.18,11.13,AR,ATH,ELECTRICAL
59,RELIANCE,-0.66,-9.81,38.93,25.30,70559.0,-19718.0,181245.0,1952.00,-12.34,49.0,X-LC,3.41,21.0,-0.28,1.41,21.01,XY25,BTT,REFINERIES
38,ICICIPRULI,-3.15,-11.52,47.75,30.73,83234.0,-22693.0,174312.0,790.00,-35.24,18.0,X-MC,3.87,78.0,-0.27,1.36,0.00,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-2.64,-12.74,35.31,18.07,55105.0,-22795.0,156060.0,35195.00,-25.68,39.0,X-MC,10.64,58.0,-0.41,1.22,0.0,X40,ATH,PHARMA
3,ACC,-2.29,-39.59,189.38,74.81,306750.0,-106152.0,161976.0,3906.00,-57.01,26.0,X-SC,17.05,85.0,-0.35,1.26,0.0,XY24,BTT,CEMENT
6,ASIANPAINT,-2.04,-22.61,60.90,24.52,133591.0,-64078.0,219361.0,3460.26,-22.00,30.0,X-LC,9.36,30.0,-0.48,1.71,0.0,X40,ATH,PAINTS
9,BAJAJHFL,-2.74,-29.24,129.11,62.13,249464.0,-79828.0,193218.0,181.50,-41.72,26.0,X-MC,19.98,60.0,-0.32,1.51,0.0,X40N,ATH,FINANCE
12,BATAINDIA,-4.08,-58.96,229.46,35.20,121166.0,-75865.0,52805.0,2096.00,-30.83,19.0,X-SC,30.54,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-4.91,-66.26,351.44,52.31,172114.0,-96186.0,48974.0,1176.00,-64.09,18.0,X-SC,25.51,92.0,-0.56,0.38,0.0,X40N,NTT,FOOTWEAR
12,BATAINDIA,-4.08,-58.96,229.46,35.20,121166.0,-75865.0,52805.0,2096.00,-30.83,19.0,X-SC,30.54,91.0,-0.63,0.41,0.0,X40,NTT,FOOTWEAR
54,QUESS,-1.79,-28.41,142.91,73.90,109259.0,-30340.0,76453.0,424.00,-61.43,34.0,X-SC,20.77,80.0,-0.28,0.60,0.0,XY24,NTT,MISC
36,HONAUT,-2.65,-28.49,111.59,51.31,153883.0,-54938.0,137900.0,58357.33,-40.50,22.0,X-SC,15.38,90.0,-0.36,1.08,0.0,X40N,ATH,ELECTRICAL
51,MEDANTA,-2.18,-15.84,51.05,27.12,75837.0,-27963.0,148554.0,1486.00,-18.36,25.0,X-SC,11.55,87.0,-0.37,1.16,0.0,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-1.88,-22.48,53.58,19.06,141287.0,-76473.0,263693.0,452.00,-57.54,32.0,X-LC,18.15,1.0,-0.54,2.06,0.00,X40,NTT,FMCG
73,TCS,0.08,-29.76,80.21,26.57,260987.0,-137893.0,325380.0,4311.59,-40.68,28.0,X-LC,17.04,2.0,-0.53,2.54,1.55,X40,ATH,IT
43,INFY,-0.52,-14.95,57.84,34.24,153925.0,-46766.0,266122.0,1972.00,-33.24,35.0,X-LC,15.11,3.0,-0.30,2.07,2.34,X40,NTT,IT
75,TMPV,-2.44,-30.24,95.79,36.58,237774.0,-107617.0,248224.0,600.00,-85.81,32.0,X-LC,6.00,4.0,-0.45,1.94,0.00,XY24,NTT,AUTO
33,HCLTECH,0.80,-12.75,41.94,23.83,88523.0,-30853.0,211071.0,1908.19,-8.19,39.0,X-LC,11.78,8.0,-0.35,1.65,2.49,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-2.97,12.1,29.85,45.57,87544.0,31661.0,293280.0,7934.0,-27.96,52.0,H-MC,13.13,125.0,0.36,2.29,30.24,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,-2.81,-45.61,220.18,74.15,195934.0,-74617.0,88988.0,838.00,-260.32,62.0,H-SC,28.08,145.0,-0.38,0.69,32.43,XR,NTT,CHEMICALS
30,HAPPSTMNDS,-4.98,-51.26,279.28,84.85,174449.0,-65701.0,62464.0,1480.71,-41.98,52.0,H-SC,26.98,152.0,-0.38,0.49,15.67,AR,ATH,IT
1,ABB,-2.97,12.10,29.85,45.57,87544.0,31661.0,293280.0,7934.00,-27.96,52.0,H-MC,13.13,125.0,0.36,2.29,30.24,AR,NTT,ELECTRICAL
69,SURYODAY,-1.51,-30.69,77.51,23.03,96201.0,-54957.0,124114.0,216.00,35.96,41.0,H-SC,6.72,166.0,-0.57,0.97,21.30,XR,NTT,BANKS
26,FINCABLES,-3.77,7.02,94.27,107.91,148961.0,10371.0,158015.0,1641.55,-3.60,48.0,M-SC,8.46,220.0,0.07,1.23,18.88,OX40N,ATH,CABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.78
1     25       45.79
2     50       78.05

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.43
MC    30.07
LC    25.52
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.94
X40      25.57
X40N     15.09
AR        9.22
XR        8.37
XY25      7.27
OX40N     6.79
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.32
X-MC    22.58
H-SC    21.62
X-SC    12.23
M-SC    10.05
H-MC     5.12
M-MC     2.02
H-LC     1.18
M-LC     1.02
L-SC     0.53
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.10        -29.01   74.82
FINANCE             13.11        -27.98   80.14
IT                  11.92        -47.32  122.29
MISC                 6.92        -50.77  116.27
ELECTRICAL           6.59        -14.81   58.77
PAINTS               5.04        -52.16   78.58
INSURANCE            4.67        -13.22   51.97
BANKS                4.55        -31.95   98.93
PHARMA               4.20         -9.27   43.67
AUTO                 3.66        -39.32   94.60
AC                   2.01        -23.81   57.38
HEALTHCARE           1.89        -47.84   86.42
TRAVEL               1.82        -92.35  188.67
DURABLES             1.82        -66.19  106.62
FOOTWEAR             1.76        -95.41  173.76
APPARELS             1.73        -21.29   62.67
BREWERIES            1.71         -6.84   29.03
REALTY               1.44        -20.14   39.88
REFINERIES           1.41        -10.88   38.93
CERAMICS             1.37        -74.29  127.24
CEMENT               1.26        -65.54  189.38
CABLES               1.23          6.56   94.27
CHEMICALS            1.11        -84.91  235.77
ENGINEERING          1.08        -74.54  154.38
JEWELLERY            1.06       -134.66  216.18
ENTERTAINMENT        0.76        -97.82  215.80
TEXTILES             0.45        -61.55  107.61
HOTELS               0.35       -153.06  242.32

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4142714.0     21
X40       1895383.0     16
XR        1418097.0     12
AR        1390706.0     10
X40N      1366476.0     10
OX40N      919583.0     10
XY25       507919.0      5
SR         319649.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4018626.0     24
X-MC        1838577.0     15
X-LC        1786735.0     13
M-SC        1629070.0     14
X-SC        1614118.0     10
H-MC         423471.0      3
L-SC         222331.0      2
M-LC         160450.0      1
M-MC         127049.0      2
H-LC          82666.0      1
L-MC          57434.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1406188.0      6
           AR         995323.0      5
X-LC       X40        954867.0      7
M-SC       XY24       949727.0      6
H-SC       XR         893733.0      7
X-SC       XY24       866144.0      4
X-MC       X40        723673.0      7
           X40N       555003.0      4
X-SC       X40N       531131.0      4
H-SC       OX40N      403733.0      4
M-SC       OX40N      402248.0      5
X-LC       XY24       392718.0      2
H-SC       SR         319649.0      2
X-MC       XY24       281910.0      2
X-LC       X40N       280342.0      2
X-MC       XY25       277991.0      2
H-MC       XY24       246027.0      1
X-SC       X40        216843.0      2
M-SC       XR         197751.0      2
H-MC       AR         177444.0      2
M-LC       XR         160450.0      1
X-LC       XY25       158808.0      2
L-SC       OX40N      113602.0      1
           XR         108729.0      1
H-LC       AR          82666.0      1
M-SC       AR          79344.0      1
M-MC       XY25        71120.0      1
L-MC       XR          57434.0      1
M-MC       AR          55929.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds