<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-01 15:06:45
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16

-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.29 C
-------------------
Today PnL: 4.46 L (3.58%)
Current PnL: -48.28 L (-29.71%)
CY Booked + Current PnL: -32.39 L (-19.93%)
-------------------
Total profit:  37.63 K
Total loss:  -48.65 L
-------------------
Total Booked + Current PnL: -5.41 L (-3.99%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.33%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.19 C (92.39%)
===================
Deployed:  1.36 C
Current:  1.29 C
CAGR/XIRR %: -2.44%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,5.13,-9.98,35.05,21.57,30914.0,-9780.0,88200.0,397.04,-22.31,44.0,H-SC,4.66,167.0,-0.32,0.68,20.30,XR,ATH,FINANCE
77,TTKPRESTIG,4.23,-41.91,72.32,0.09,42334.0,-42240.0,58537.0,770.00,35.97,39.0,M-SC,21.77,250.0,-1.00,0.45,4.23,OX40N,NTT,DURABLES
2,ABBOTINDIA,2.12,-11.22,32.99,18.07,52385.0,-20065.0,158790.0,35195.00,-24.45,48.0,X-MC,10.42,58.0,-0.38,1.23,3.85,X40,ATH,PHARMA
67,SONACOMS,3.32,-13.94,61.61,39.09,53639.0,-14097.0,87062.0,804.02,-31.81,48.0,M-MC,6.58,193.0,-0.26,0.68,23.16,AR,ATH,AUTO
42,INDUSINDBK,4.41,-42.00,129.12,32.89,57819.0,-32428.0,44779.0,1800.00,-310.78,39.0,L-MC,6.99,258.0,-0.56,0.35,16.23,XR,NTT,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,14.10,-52.09,263.46,74.15,206526.0,-85215.0,78390.0,838.00,-240.99,50.0,H-SC,27.97,145.0,-0.41,0.61,16.66,XR,NTT,CHEMICALS
19,COFFEEDAY,12.36,-59.87,237.13,35.27,108041.0,-67987.0,45562.0,80.00,-69.82,40.0,L-SC,30.56,266.0,-0.63,0.35,12.36,XR,NTT,HOTELS
56,RAJOOENG,11.59,-49.18,174.72,39.61,91012.0,-50410.0,52090.0,143.10,-65.63,41.0,H-SC,33.72,136.0,-0.55,0.40,11.59,AR,ATH,MISC
71,TANLA,11.00,-52.65,364.00,119.69,466644.0,-142562.0,128199.0,1943.92,-52.36,47.0,H-SC,27.06,147.0,-0.31,1.00,10.99,AR,ATH,IT
25,EASEMYTRIP,9.91,-64.51,310.58,45.70,194870.0,-114071.0,62744.0,26.40,-34.84,41.0,M-SC,12.68,204.0,-0.59,0.49,9.91,XY24,NTT,TRAVEL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VOLTAS,-1.52,-1.94,48.07,45.20,90384.0,-3717.0,188025.0,1856.00,12.20,35.0,X-MC,2.84,79.0,-0.04,1.46,4.73,XY25,NTT,AC
85,ZYDUSLIFE,-0.97,-9.02,49.08,35.63,93580.0,-18906.0,190668.0,1286.17,-20.72,41.0,H-MC,5.42,120.0,-0.20,1.48,6.15,AR,ATH,PHARMA
37,ICICIGI,-0.53,-9.87,32.41,19.34,58454.0,-19750.0,180359.0,2252.93,-24.25,29.0,X-MC,5.46,66.0,-0.34,1.40,0.00,X40,ATH,INSURANCE
32,HAVELLS,-0.36,-24.05,73.89,32.08,184077.0,-78868.0,249123.0,2062.85,-28.51,30.0,X-MC,10.82,63.0,-0.43,1.93,0.00,X40,ATH,ELECTRICAL
35,HINDUNILVR,0.44,-19.70,41.55,13.67,85772.0,-50633.0,206430.0,2922.00,-40.44,34.0,X-LC,10.49,9.0,-0.59,1.60,0.59,XY25,NTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.94,1.24,105.37,107.91,157495.0,1825.0,149469.0,1641.55,-9.18,44.0,M-SC,6.59,220.0,0.01,1.16,12.45,OX40N,ATH,CABLES
66,SIS,2.64,-33.93,83.52,21.26,61274.0,-37668.0,73364.0,528.00,1718.13,48.0,H-SC,14.72,168.0,-0.61,0.57,9.08,OX40N,NTT,MISC
18,CERA,2.24,-39.00,103.10,23.89,110623.0,-68606.0,107297.0,9475.00,-41.05,46.0,H-SC,19.37,153.0,-0.62,0.83,3.11,OX40N,NTT,CERAMICS
72,TATAELXSI,3.88,-40.47,121.77,32.03,95574.0,-53348.0,78487.0,9161.00,-25.57,40.0,H-SC,21.73,158.0,-0.56,0.61,3.88,OX40N,NTT,IT
48,KANSAINER,4.93,-41.44,93.78,13.47,148092.0,-111753.0,157914.0,340.00,-49.75,43.0,H-SC,22.72,162.0,-0.75,1.23,10.30,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.94,1.24,105.37,107.91,157495.0,1825.0,149469.0,1641.55,-9.18,44.0,M-SC,6.59,220.0,0.01,1.16,12.45,OX40N,ATH,CABLES
1,ABB,2.15,11.36,30.72,45.57,89498.0,29717.0,291336.0,7934.00,-28.45,50.0,H-MC,13.20,125.0,0.33,2.26,29.37,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.15,11.36,30.72,45.57,89498.0,29717.0,291336.0,7934.00,-28.45,50.0,H-MC,13.20,125.0,0.33,2.26,29.37,AR,NTT,ELECTRICAL
26,FINCABLES,2.94,1.24,105.37,107.91,157495.0,1825.0,149469.0,1641.55,-9.18,44.0,M-SC,6.59,220.0,0.01,1.16,12.45,OX40N,ATH,CABLES
40,INDIAMART,3.08,-12.02,134.97,106.72,146452.0,-14829.0,108507.0,4810.62,-60.35,46.0,H-SC,12.79,140.0,-0.10,0.84,8.54,AR,ATH,MISC
85,ZYDUSLIFE,-0.97,-9.02,49.08,35.63,93580.0,-18906.0,190668.0,1286.17,-20.72,41.0,H-MC,5.42,120.0,-0.20,1.48,6.15,AR,ATH,PHARMA
84,WIPRO,1.89,-21.58,119.68,72.27,159027.0,-36571.0,132877.0,420.00,-29.24,39.0,M-LC,18.42,98.0,-0.23,1.03,1.95,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,0.81,-14.99,53.79,30.73,90080.0,-29539.0,167466.0,790.00,-37.88,21.0,X-MC,7.66,78.0,-0.33,1.30,0.81,X40,ATH,INSURANCE
21,DABUR,1.17,-18.81,77.00,43.70,155075.0,-46672.0,201396.0,735.00,-26.30,29.0,X-MC,10.21,70.0,-0.30,1.56,1.17,XY24,BTT,FMCG
37,ICICIGI,-0.53,-9.87,32.41,19.34,58454.0,-19750.0,180359.0,2252.93,-24.25,29.0,X-MC,5.46,66.0,-0.34,1.40,0.00,X40,ATH,INSURANCE
32,HAVELLS,-0.36,-24.05,73.89,32.08,184077.0,-78868.0,249123.0,2062.85,-28.51,30.0,X-MC,10.82,63.0,-0.43,1.93,0.00,X40,ATH,ELECTRICAL
34,HDFCBANK,1.44,-11.22,44.59,28.37,92984.0,-26355.0,208530.0,1073.00,-24.48,30.0,X-LC,14.91,26.0,-0.28,1.62,1.44,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,2.89,-18.87,54.70,25.51,82589.0,-35110.0,150985.0,4671.50,26.90,44.0,H-LC,0.52,51.0,-0.43,1.17,11.19,AR,ATH,ELECTRICAL
82,VOLTAS,-1.52,-1.94,48.07,45.20,90384.0,-3717.0,188025.0,1856.00,12.20,35.0,X-MC,2.84,79.0,-0.04,1.46,4.73,XY25,NTT,AC
78,UNITDSPR,2.35,-8.37,31.79,20.77,68206.0,-19591.0,214553.0,1644.00,-18.80,39.0,X-MC,3.28,64.0,-0.29,1.67,2.35,X40N,NTT,BREWERIES
59,RELIANCE,1.74,-12.23,42.76,25.30,75421.0,-24581.0,176382.0,1952.00,-14.65,43.0,X-LC,3.92,21.0,-0.33,1.37,17.76,XY25,BTT,REFINERIES
37,ICICIGI,-0.53,-9.87,32.41,19.34,58454.0,-19750.0,180359.0,2252.93,-24.25,29.0,X-MC,5.46,66.0,-0.34,1.40,0.00,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,-0.53,-9.87,32.41,19.34,58454.0,-19750.0,180359.0,2252.93,-24.25,29.0,X-MC,5.46,66.0,-0.34,1.40,0.00,X40,ATH,INSURANCE
32,HAVELLS,-0.36,-24.05,73.89,32.08,184077.0,-78868.0,249123.0,2062.85,-28.51,30.0,X-MC,10.82,63.0,-0.43,1.93,0.00,X40,ATH,ELECTRICAL
35,HINDUNILVR,0.44,-19.70,41.55,13.67,85772.0,-50633.0,206430.0,2922.00,-40.44,34.0,X-LC,10.49,9.0,-0.59,1.60,0.59,XY25,NTT,FMCG
38,ICICIPRULI,0.81,-14.99,53.79,30.73,90080.0,-29539.0,167466.0,790.00,-37.88,21.0,X-MC,7.66,78.0,-0.33,1.30,0.81,X40,ATH,INSURANCE
21,DABUR,1.17,-18.81,77.00,43.70,155075.0,-46672.0,201396.0,735.00,-26.30,29.0,X-MC,10.21,70.0,-0.30,1.56,1.17,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,8.77,-66.49,354.46,52.31,172441.0,-96511.0,48649.0,1176.00,-64.28,33.0,X-SC,30.66,92.0,-0.56,0.38,8.77,X40N,NTT,FOOTWEAR
12,BATAINDIA,3.70,-59.36,232.72,35.20,121680.0,-76384.0,52286.0,2096.00,-31.41,32.0,X-SC,33.64,91.0,-0.63,0.41,3.70,X40,NTT,FOOTWEAR
54,QUESS,3.61,-27.88,141.13,73.90,108696.0,-29775.0,77018.0,424.00,-61.43,41.0,X-SC,22.39,80.0,-0.27,0.60,3.61,XY24,NTT,MISC
36,HONAUT,3.68,-29.23,113.80,51.31,155309.0,-56363.0,136475.0,58357.33,-41.12,35.0,X-SC,17.61,90.0,-0.36,1.06,3.68,X40N,ATH,ELECTRICAL
51,MEDANTA,3.01,-15.31,50.10,27.12,74894.0,-27027.0,149490.0,1486.00,-17.88,37.0,X-SC,14.63,87.0,-0.36,1.16,3.01,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.51,-23.07,54.77,19.06,143320.0,-78489.0,261677.0,452.00,-57.95,37.0,X-LC,19.41,1.0,-0.55,2.03,1.51,X40,NTT,FMCG
73,TCS,2.06,-29.33,79.10,26.57,258978.0,-135867.0,327406.0,4311.59,-40.02,36.0,X-LC,18.44,2.0,-0.52,2.54,2.18,X40,ATH,IT
43,INFY,1.82,-13.32,54.87,34.24,148815.0,-41675.0,271213.0,1972.00,-31.79,43.0,X-LC,15.12,3.0,-0.28,2.11,4.30,X40,NTT,IT
75,TMPV,2.26,-31.05,98.09,36.58,240663.0,-110492.0,245349.0,600.00,-85.81,36.0,X-LC,10.50,4.0,-0.46,1.90,2.26,XY24,NTT,AUTO
33,HCLTECH,1.13,-11.96,40.65,23.83,86585.0,-28922.0,213002.0,1908.19,-7.36,44.0,X-LC,11.67,8.0,-0.33,1.65,3.42,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,2.15,11.36,30.72,45.57,89498.0,29717.0,291336.0,7934.0,-28.45,50.0,H-MC,13.2,125.0,0.33,2.26,29.37,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,8.46,-51.11,278.12,84.85,174259.0,-65509.0,62656.0,1480.71,-41.79,52.0,H-SC,24.96,152.0,-0.38,0.49,16.03,AR,ATH,IT
24,DMART,7.70,2.44,26.52,29.60,67807.0,6084.0,255684.0,5391.45,-13.63,70.0,X-LC,6.59,14.0,0.09,1.98,16.87,X40N,ATH,FMCG
5,ANGELONE,5.86,-1.28,25.79,24.18,77651.0,-3912.0,301088.0,303.00,-85.87,55.0,X-SC,9.91,97.0,-0.05,2.34,15.89,X40N,NTT,FINANCE
52,PAGEIND,2.63,-14.94,57.68,34.11,131666.0,-40109.0,228270.0,51418.64,-38.95,54.0,X-MC,20.78,55.0,-0.30,1.77,7.98,X40,ATH,APPARELS
80,VALIANTORG,14.10,-52.09,263.46,74.15,206526.0,-85215.0,78390.0,838.00,-240.99,50.0,H-SC,27.97,145.0,-0.41,0.61,16.66,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.06
1     25       46.23
2     50       78.28

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.51
MC    29.78
LC    25.72
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.10
X40      25.34
X40N     15.52
AR        9.16
XR        8.27
XY25      7.22
OX40N     6.61
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.52
X-MC    22.34
H-SC    21.75
X-SC    12.36
M-SC     9.88
H-MC     5.03
M-MC     2.06
H-LC     1.17
M-LC     1.03
L-SC     0.52
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.26        -26.97   72.06
FINANCE             13.19        -26.56   78.13
IT                  11.98        -45.95  120.22
MISC                 7.00        -48.56  113.10
ELECTRICAL           6.42        -16.99   61.78
PAINTS               5.26        -45.61   70.90
INSURANCE            4.68        -12.40   50.86
BANKS                4.50        -33.02  100.54
PHARMA               4.16         -9.73   44.27
AUTO                 3.67        -38.36   93.25
AC                   1.95        -27.18   61.67
HEALTHCARE           1.91        -45.43   83.38
DURABLES             1.78        -68.22  109.15
TRAVEL               1.78        -95.24  192.99
APPARELS             1.77        -17.57   57.68
FOOTWEAR             1.77        -93.88  171.62
BREWERIES            1.67         -9.13   31.79
REALTY               1.45        -18.47   37.93
REFINERIES           1.37        -13.94   42.76
CERAMICS             1.36        -75.15  128.35
CEMENT               1.24        -68.38  194.35
CABLES               1.16          1.22  105.37
ENGINEERING          1.08        -74.74  154.67
CHEMICALS            1.05        -95.92  255.75
JEWELLERY            0.98       -152.90  240.76
ENTERTAINMENT        0.76        -98.23  216.45
TEXTILES             0.46        -56.21  100.75
HOTELS               0.35       -149.22  237.13

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4107736.0     21
X40       1911739.0     16
XR        1424410.0     12
AR        1392422.0     10
X40N      1300677.0     10
OX40N      939270.0     10
XY25       510224.0      5
SR         317131.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3991523.0     24
X-MC        1854061.0     15
X-LC        1745718.0     13
M-SC        1644461.0     14
X-SC        1592985.0     10
H-MC         430393.0      3
L-SC         223310.0      2
M-LC         159027.0      1
M-MC         121723.0      2
H-LC          82589.0      1
L-MC          57819.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1372263.0      6
           AR         992731.0      5
X-LC       X40        950224.0      7
M-SC       XY24       949950.0      6
H-SC       XR         907559.0      7
X-SC       XY24       864068.0      4
X-MC       X40        735325.0      7
           X40N       558214.0      4
X-SC       X40N       502727.0      4
M-SC       OX40N      422162.0      5
H-SC       OX40N      401839.0      4
X-LC       XY24       394565.0      2
H-SC       SR         317131.0      2
X-MC       XY25       280947.0      2
           XY24       279575.0      2
H-MC       XY24       247315.0      1
X-LC       X40N       239736.0      2
X-SC       X40        226190.0      2
M-SC       XR         191964.0      2
H-MC       AR         183078.0      2
X-LC       XY25       161193.0      2
M-LC       XR         159027.0      1
L-SC       OX40N      115269.0      1
           XR         108041.0      1
H-LC       AR          82589.0      1
M-SC       AR          80385.0      1
M-MC       XY25        68084.0      1
L-MC       XR          57819.0      1
M-MC       AR          53639.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 43.0 seconds