<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-09 15:27:54
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: 1.55 L (1.04%)
Current PnL: -31.74 L (-17.4%)
CY Booked + Current PnL: -29.66 L (-16.26%)
-------------------
Total profit:  4.23 L
Total loss:  -35.97 L
-------------------
Total Booked + Current PnL: 13.21 L (9.47%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.39%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.74%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,1.13,12.54,5.17,18.37,8210.0,17700.0,158810.0,1670.26,-21.16,57.0,X-LC,8.28,5.0,2.16,1.05,24.69,X40,ATH,CHEMICALS
49,JSWINFRA,3.07,10.27,5.59,16.43,13670.0,22770.0,244544.0,342.00,-5.50,60.0,X-MC,13.32,61.0,1.67,1.62,38.65,X40N,NTT,REALTY
83,TTKPRESTIG,2.41,-18.52,22.85,0.09,18762.0,-18666.0,82111.0,770.00,90.61,64.0,M-SC,5.52,250.0,-0.99,0.54,46.21,OX40N,NTT,DURABLES
56,MEDANTA,3.30,15.31,10.24,27.12,20843.0,27031.0,203548.0,1486.00,11.76,65.0,X-SC,8.68,87.0,1.30,1.34,40.26,XY24,NTT,HEALTHCARE
72,SIS,2.01,0.75,20.36,21.26,22776.0,836.0,111868.0,528.00,2672.02,62.0,H-SC,25.31,168.0,0.04,0.74,66.33,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,6.08,-54.40,305.34,84.85,178465.0,-69717.0,58448.0,1480.71,-45.69,59.0,H-SC,17.99,152.0,-0.39,0.39,8.43,AR,ATH,IT
3,ALKYLAMINE,5.91,-16.39,130.29,92.54,109982.0,-16550.0,84413.0,4520.85,-10.41,67.0,H-SC,9.73,142.0,-0.15,0.56,60.29,SR,ATH,CHEMICALS
85,VAIBHAVGBL,5.07,-21.29,104.25,60.77,149979.0,-38910.0,143865.0,521.00,65.84,69.0,H-SC,4.54,160.0,-0.26,0.95,46.37,XR,NTT,JEWELLERY
22,DIXON,4.08,-1.92,40.63,37.92,103923.0,-5020.0,255778.0,18931.72,-58.33,68.0,X-MC,6.87,54.0,-0.05,1.69,39.17,X40N,ATH,IT
15,CAMS,3.71,1.89,22.17,24.48,56890.0,4752.0,256608.0,950.00,-2.41,48.0,X-SC,6.59,89.0,0.08,1.69,24.93,X40N,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PAGEIND,-2.14,5.71,26.37,33.59,74814.0,15331.0,283710.0,51217.29,-24.26,51.0,X-MC,10.26,55.0,0.20,1.87,34.73,X40,ATH,APPARELS
50,KANSAINER,-1.90,-33.20,69.87,13.47,125860.0,-89532.0,180135.0,340.00,-42.69,36.0,H-SC,3.46,162.0,-0.71,1.19,27.32,XY24,NTT,PAINTS
84,UNITDSPR,-1.85,1.57,18.90,20.77,44949.0,3680.0,237824.0,1644.00,-9.86,59.0,X-MC,3.40,64.0,0.08,1.57,14.32,X40N,NTT,BREWERIES
54,MARUTI,-1.75,2.00,26.15,28.68,39428.0,2960.0,150777.0,17292.00,-16.04,49.0,X-LC,8.91,33.0,0.08,1.00,12.28,XR,ATH,AUTO
32,HAVELLS,-1.47,-23.80,72.47,31.42,181118.0,-78070.0,249921.0,2052.62,-28.37,51.0,X-MC,11.63,63.0,-0.43,1.65,5.41,X40,ATH,ELECTRICAL

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,2.01,0.75,20.36,21.26,22776.0,836.0,111868.0,528.0,2672.02,62.0,H-SC,25.31,168.0,0.04,0.74,66.33,OX40N,NTT,MISC
75,SURYODAY,0.85,0.90,21.94,23.03,39642.0,1612.0,180683.0,216.0,97.37,56.0,H-SC,19.97,166.0,0.04,1.19,52.13,XR,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.59,32.39,57.04,107.91,111497.0,47827.0,195471.0,1641.55,19.23,43.0,M-SC,26.87,220.0,0.43,1.29,47.06,OX40N,ATH,CABLES
72,SIS,2.01,0.75,20.36,21.26,22776.0,836.0,111868.0,528.00,2672.02,62.0,H-SC,25.31,168.0,0.04,0.74,66.33,OX40N,NTT,MISC
16,CERA,-0.69,-17.89,50.88,23.89,73491.0,-31463.0,144440.0,9475.00,-20.76,56.0,H-SC,15.62,153.0,-0.43,0.95,40.41,OX40N,NTT,CERAMICS
83,TTKPRESTIG,2.41,-18.52,22.85,0.09,18762.0,-18666.0,82111.0,770.00,90.61,64.0,M-SC,5.52,250.0,-0.99,0.54,46.21,OX40N,NTT,DURABLES
69,SFL,1.84,-25.91,70.92,26.63,137779.0,-67944.0,194274.0,1287.00,47.18,65.0,M-SC,21.27,242.0,-0.49,1.28,62.14,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.59,32.39,57.04,107.91,111497.0,47827.0,195471.0,1641.55,19.23,43.0,M-SC,26.87,220.0,0.43,1.29,47.06,OX40N,ATH,CABLES
68,SATIN,2.47,41.31,7.45,51.83,29085.0,114121.0,390405.0,274.00,26.15,60.0,H-SC,42.20,159.0,3.92,2.58,90.18,XY24,NTT,FINANCE
91,ZYDUSLIFE,1.13,22.43,10.78,35.63,27659.0,47007.0,256581.0,1286.17,6.76,70.0,H-MC,15.36,120.0,1.70,1.69,34.91,AR,ATH,PHARMA
60,QUESS,1.48,20.91,43.83,73.90,56594.0,22329.0,129122.0,424.00,-34.99,78.0,X-SC,23.92,80.0,0.39,0.85,76.02,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,2.01,0.75,20.36,21.26,22776.0,836.0,111868.0,528.00,2672.02,62.0,H-SC,25.31,168.0,0.04,0.74,66.33,OX40N,NTT,MISC
75,SURYODAY,0.85,0.90,21.94,23.03,39642.0,1612.0,180683.0,216.00,97.37,56.0,H-SC,19.97,166.0,0.04,1.19,52.13,XR,NTT,BANKS
74,STARHEALTH,3.65,17.17,25.68,47.26,84588.0,48269.0,329392.0,761.00,84.98,73.0,H-SC,17.15,173.0,0.57,2.18,43.42,XY24,NTT,INSURANCE
68,SATIN,2.47,41.31,7.45,51.83,29085.0,114121.0,390405.0,274.00,26.15,60.0,H-SC,42.20,159.0,3.92,2.58,90.18,XY24,NTT,FINANCE
25,FINCABLES,1.59,32.39,57.04,107.91,111497.0,47827.0,195471.0,1641.55,19.23,43.0,M-SC,26.87,220.0,0.43,1.29,47.06,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,1.13,22.43,10.78,35.63,27659.0,47007.0,256581.0,1286.17,6.76,70.0,H-MC,15.36,120.0,1.70,1.69,34.91,AR,ATH,PHARMA
73,SONACOMS,1.19,15.89,19.67,38.69,23060.0,16073.0,117232.0,801.69,-8.18,73.0,M-MC,20.36,193.0,0.70,0.77,66.32,AR,ATH,AUTO
25,FINCABLES,1.59,32.39,57.04,107.91,111497.0,47827.0,195471.0,1641.55,19.23,43.0,M-SC,26.87,220.0,0.43,1.29,47.06,OX40N,ATH,CABLES
75,SURYODAY,0.85,0.90,21.94,23.03,39642.0,1612.0,180683.0,216.00,97.37,56.0,H-SC,19.97,166.0,0.04,1.19,52.13,XR,NTT,BANKS
72,SIS,2.01,0.75,20.36,21.26,22776.0,836.0,111868.0,528.00,2672.02,62.0,H-SC,25.31,168.0,0.04,0.74,66.33,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
81,TMPV,-0.11,-24.50,80.89,36.58,217333.0,-87164.0,268677.0,600.00,-84.72,33.0,X-LC,7.67,4.0,-0.40,1.77,12.92,XY24,NTT,AUTO
35,HDFCLIFE,-0.66,-9.71,46.98,32.71,63541.0,-14548.0,135252.0,811.41,-29.56,35.0,X-LC,15.31,31.0,-0.23,0.89,1.61,X40,ATH,INSURANCE
87,VBL,1.40,-2.80,39.27,35.37,120561.0,-8836.0,307006.0,670.16,-14.17,36.0,X-LC,9.05,13.0,-0.07,2.03,26.18,X40N,ATH,FMCG
47,ITC,0.46,-25.73,60.31,19.06,152359.0,-87539.0,252627.0,452.00,-59.16,38.0,X-LC,12.45,1.0,-0.57,1.67,1.79,X40,NTT,FMCG
71,SIEMENS,1.05,-6.44,34.15,25.51,59460.0,-11980.0,174115.0,4671.50,46.28,40.0,H-LC,10.64,51.0,-0.20,1.15,22.25,AR,ATH,ELECTRICAL

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,0.71,16.75,14.30,33.43,25570.0,25647.0,178808.0,1648.14,-9.73,57.0,X-LC,2.26,18.0,1.00,1.18,22.07,X40N,ATH,PHARMA
19,COLPAL,2.08,-21.70,78.62,39.86,162130.0,-57145.0,206220.0,3683.41,-5.18,54.0,X-MC,2.86,62.0,-0.35,1.36,16.65,XY25,ATH,FMCG
23,DMART,0.93,-2.01,32.27,29.60,78923.0,-5028.0,244572.0,5391.45,-17.37,42.0,X-LC,3.09,14.0,-0.06,1.62,11.79,X40N,ATH,FMCG
11,BERGEPAINT,-0.22,-8.41,36.82,25.32,86923.0,-21674.0,236075.0,680.00,-13.36,42.0,X-MC,3.23,68.0,-0.25,1.56,22.87,XY24,NTT,PAINTS
84,UNITDSPR,-1.85,1.57,18.90,20.77,44949.0,3680.0,237824.0,1644.00,-9.86,59.0,X-MC,3.40,64.0,0.08,1.57,14.32,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.22,-33.46,98.39,32.01,139793.0,-71440.0,142080.0,17616.87,-55.05,40.0,X-MC,20.70,57.0,-0.51,0.94,0.76,X40,ATH,FMCG
35,HDFCLIFE,-0.66,-9.71,46.98,32.71,63541.0,-14548.0,135252.0,811.41,-29.56,35.0,X-LC,15.31,31.0,-0.23,0.89,1.61,X40,ATH,INSURANCE
47,ITC,0.46,-25.73,60.31,19.06,152359.0,-87539.0,252627.0,452.00,-59.16,38.0,X-LC,12.45,1.0,-0.57,1.67,1.79,X40,NTT,FMCG
65,RELIANCE,0.46,-17.72,52.29,25.30,86463.0,-35611.0,165352.0,1952.00,-20.03,41.0,X-LC,7.22,21.0,-0.41,1.09,1.83,XY25,BTT,REFINERIES
79,TCS,-0.06,-39.64,106.88,24.88,298882.0,-183630.0,279643.0,4253.91,-48.87,42.0,X-LC,21.66,2.0,-0.61,1.85,3.71,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.50,-56.63,211.74,35.20,118162.0,-72865.0,55805.0,2096.00,-26.79,43.0,X-SC,19.43,91.0,-0.62,0.37,10.67,X40,NTT,FOOTWEAR
64,RELAXO,0.82,-49.76,203.13,52.31,148153.0,-72225.0,72935.0,1176.00,-46.47,58.0,X-SC,11.78,92.0,-0.49,0.48,63.07,X40N,NTT,FOOTWEAR
60,QUESS,1.48,20.91,43.83,73.90,56594.0,22329.0,129122.0,424.00,-34.99,78.0,X-SC,23.92,80.0,0.39,0.85,76.02,XY24,NTT,MISC
35,HDFCLIFE,-0.66,-9.71,46.98,32.71,63541.0,-14548.0,135252.0,811.41,-29.56,35.0,X-LC,15.31,31.0,-0.23,0.89,1.61,X40,ATH,INSURANCE
51,KOTAKBANK,2.01,0.88,20.05,21.11,28009.0,1222.0,139694.0,453.24,-13.31,40.0,X-LC,4.35,12.0,0.04,0.92,6.83,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.46,-25.73,60.31,19.06,152359.0,-87539.0,252627.0,452.00,-59.16,38.0,X-LC,12.45,1.0,-0.57,1.67,1.79,X40,NTT,FMCG
79,TCS,-0.06,-39.64,106.88,24.88,298882.0,-183630.0,279643.0,4253.91,-48.87,42.0,X-LC,21.66,2.0,-0.61,1.85,3.71,X40,ATH,IT
45,INFY,-1.44,-28.26,87.11,34.24,195545.0,-88407.0,224481.0,1972.00,-43.40,45.0,X-LC,21.18,3.0,-0.45,1.48,6.96,X40,NTT,IT
81,TMPV,-0.11,-24.50,80.89,36.58,217333.0,-87164.0,268677.0,600.00,-84.72,33.0,X-LC,7.67,4.0,-0.40,1.77,12.92,XY24,NTT,AUTO
59,PIDILITIND,1.13,12.54,5.17,18.37,8210.0,17700.0,158810.0,1670.26,-21.16,57.0,X-LC,8.28,5.0,2.16,1.05,24.69,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,2.14,-24.99,77.17,32.89,44688.0,-19298.0,57909.0,1800.00,-372.41,67.0,L-MC,9.36,258.0,-0.43,0.38,42.77,XR,NTT,BANKS
64,RELAXO,0.82,-49.76,203.13,52.31,148153.0,-72225.0,72935.0,1176.00,-46.47,58.0,X-SC,11.78,92.0,-0.49,0.48,63.07,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,2.41,-18.52,22.85,0.09,18762.0,-18666.0,82111.0,770.00,90.61,64.0,M-SC,5.52,250.0,-0.99,0.54,46.21,OX40N,NTT,DURABLES
3,ALKYLAMINE,5.91,-16.39,130.29,92.54,109982.0,-16550.0,84413.0,4520.85,-10.41,67.0,H-SC,9.73,142.0,-0.15,0.56,60.29,SR,ATH,CHEMICALS
72,SIS,2.01,0.75,20.36,21.26,22776.0,836.0,111868.0,528.00,2672.02,62.0,H-SC,25.31,168.0,0.04,0.74,66.33,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,1.48,20.91,43.83,73.90,56594.0,22329.0,129122.0,424.00,-34.99,78.0,X-SC,23.92,80.0,0.39,0.85,76.02,XY24,NTT,MISC
0,5PAISA,3.17,-28.03,56.88,12.90,89443.0,-61248.0,157248.0,593.00,131.97,67.0,H-SC,6.91,170.0,-0.68,1.04,51.75,OX40N,NTT,FINANCE
74,STARHEALTH,3.65,17.17,25.68,47.26,84588.0,48269.0,329392.0,761.00,84.98,73.0,H-SC,17.15,173.0,0.57,2.18,43.42,XY24,NTT,INSURANCE
22,DIXON,4.08,-1.92,40.63,37.92,103923.0,-5020.0,255778.0,18931.72,-58.33,68.0,X-MC,6.87,54.0,-0.05,1.69,39.17,X40N,ATH,IT
83,TTKPRESTIG,2.41,-18.52,22.85,0.09,18762.0,-18666.0,82111.0,770.00,90.61,64.0,M-SC,5.52,250.0,-0.99,0.54,46.21,OX40N,NTT,DURABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.23
1     25       42.70
2     50       72.65

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.71
LC    30.06
MC    26.21
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.83
X40      24.60
X40N     17.47
XR        8.81
OX40N     7.12
AR        6.82
XY25      6.41
SR        0.92
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.12
H-SC    22.99
X-MC    21.02
X-SC    10.12
M-SC    10.03
H-MC     2.76
M-MC     2.05
H-LC     1.15
M-LC     0.79
L-SC     0.57
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.47        -20.93   63.35
FINANCE             11.33         -7.58   54.19
IT                   9.72        -52.98  129.46
MISC                 7.23        -22.16   74.58
AUTO                 6.60         -9.45   50.27
BANKS                5.78         -3.68   51.62
PAINTS               5.40        -20.42   40.96
INSURANCE            5.39         -1.55   35.80
PHARMA               5.22          6.29   22.72
ELECTRICAL           4.06        -15.06   55.66
CHEMICALS            2.23        -20.36   91.75
HEALTHCARE           2.12        -11.33   40.39
APPARELS             1.87          5.40   26.37
AC                   1.76        -19.89   52.40
FOOTWEAR             1.70        -71.07  139.66
DURABLES             1.62        -57.05   95.25
REALTY               1.62          9.31    5.59
BREWERIES            1.57          1.55   18.90
TRAVEL               1.51        -96.40  194.74
CERAMICS             1.41        -43.34   86.89
CABLES               1.29         24.47   57.04
ENGINEERING          1.25        -28.18   86.81
JEWELLERY            1.11        -89.72  155.64
REFINERIES           1.09        -21.54   52.29
CEMENT               1.08        -63.72  186.20
ENTERTAINMENT        0.73        -74.39  178.40
TEXTILES             0.41        -46.93   88.83
HOTELS               0.41        -85.10  150.39

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3383537.0     21
X40       1950842.0     19
XR        1346447.0     13
AR        1142565.0      9
X40N      1076849.0     13
OX40N      711468.0     10
XY25       464755.0      5
SR         279402.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3297927.0     24
X-LC        2022559.0     21
X-MC        1535554.0     15
M-SC        1395936.0     14
X-SC        1269505.0      9
H-MC         279556.0      2
L-SC         204751.0      2
M-LC         171710.0      1
M-MC          74219.0      2
H-LC          59460.0      1
L-MC          44688.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1071060.0     10
H-SC       XY24       963156.0      6
           AR         957761.0      5
M-SC       XY24       821581.0      6
H-SC       XR         806711.0      7
X-SC       XY24       749165.0      4
X-MC       X40        665898.0      7
           X40N       391685.0      4
X-LC       X40N       378708.0      6
           XY24       369204.0      2
M-SC       OX40N      308075.0      5
X-SC       X40N       306456.0      3
H-SC       OX40N      290897.0      4
           SR         279402.0      2
H-MC       XY24       251897.0      1
X-MC       XY25       249437.0      2
           XY24       228534.0      2
X-SC       X40        213884.0      2
M-SC       XR         191655.0      2
M-LC       XR         171710.0      1
X-LC       XY25       164159.0      2
L-SC       OX40N      112496.0      1
           XR          92255.0      1
M-SC       AR          74625.0      1
H-LC       AR          59460.0      1
M-MC       XY25        51159.0      1
L-MC       XR          44688.0      1
X-LC       XR          39428.0      1
H-MC       AR          27659.0      1
M-MC       AR          23060.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 46.0 seconds