<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-10 15:38:54
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.37 C
-------------------
Today PnL: 2.13 L (1.58%)
Current PnL: -39.54 L (-24.33%)
CY Booked + Current PnL: -23.86 L (-14.68%)
-------------------
Total profit:  1.11 L
Total loss:  -40.64 L
-------------------
Total Booked + Current PnL: 3.12 L (2.3%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.41%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.10 C (79.99%)
===================
Deployed:  1.36 C
Current:  1.37 C
CAGR/XIRR %: 0.7%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.35,9.07,7.88,17.67,12932.0,13654.0,164114.0,478.51,31.99,60.0,L-LC,11.53,185.0,1.06,1.20,27.45,XY25,ATH,MINING
50,MASFIN,2.69,-5.28,28.35,21.57,26310.0,-5175.0,92805.0,397.04,-18.25,42.0,H-SC,5.09,167.0,-0.20,0.68,29.49,XR,ATH,FINANCE
77,TTKPRESTIG,7.24,-37.02,58.93,0.09,37403.0,-37307.0,63470.0,770.00,47.28,34.0,M-SC,14.90,250.0,-1.00,0.46,7.24,OX40N,NTT,DURABLES
37,ICICIGI,-0.02,0.08,19.25,19.34,38551.0,157.0,200266.0,2252.93,-15.91,48.0,X-MC,1.60,66.0,0.00,1.46,14.22,X40,ATH,INSURANCE
78,UNITDSPR,3.78,3.36,16.84,20.77,40756.0,7877.0,242021.0,1644.00,-8.32,55.0,X-MC,1.54,64.0,0.19,1.77,10.30,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
31,HAPPSTMNDS,17.59,-50.01,269.76,84.85,172841.0,-64093.0,64072.0,1480.71,-40.49,59.0,H-SC,28.83,152.0,-0.37,0.47,18.65,AR,ATH,IT
24,DIXON,11.26,-20.53,73.56,37.92,152455.0,-53546.0,207252.0,18931.72,-66.19,52.0,X-MC,25.39,54.0,-0.35,1.52,11.26,X40N,ATH,IT
77,TTKPRESTIG,7.24,-37.02,58.93,0.09,37403.0,-37307.0,63470.0,770.00,47.28,34.0,M-SC,14.90,250.0,-1.00,0.46,7.24,OX40N,NTT,DURABLES
11,BANDHANBNK,4.67,-12.32,119.47,92.42,291779.0,-34331.0,244228.0,400.00,109.77,61.0,H-SC,9.99,174.0,-0.12,1.79,34.54,XY24,NTT,BANKS
79,VAIBHAVGBL,4.55,-32.67,138.77,60.77,170777.0,-59710.0,123065.0,521.00,42.15,43.0,H-SC,1.94,160.0,-0.35,0.90,11.57,XR,NTT,JEWELLERY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-3.48,17.66,76.70,107.91,133246.0,26079.0,173723.0,1641.55,6.04,63.0,M-SC,7.65,220.0,0.20,1.27,30.70,OX40N,ATH,CABLES
55,RAJESHEXPO,-3.33,-78.91,374.40,0.07,108333.0,-108242.0,28935.0,518.00,960.61,17.0,L-SC,16.84,268.0,-1.00,0.21,0.00,OX40N,NTT,JEWELLERY
43,INFY,-1.48,-11.80,52.21,34.24,144080.0,-36925.0,275963.0,1972.00,-30.70,28.0,X-LC,11.45,3.0,-0.26,2.02,1.58,X40,NTT,IT
16,CAMPUS,-1.46,-19.91,66.42,33.28,89248.0,-33406.0,134369.0,393.00,-35.50,30.0,M-SC,4.31,218.0,-0.37,0.98,4.15,XY24,NTT,FOOTWEAR
2,ABBOTINDIA,-1.38,-10.06,31.28,18.07,50317.0,-17995.0,160860.0,35195.00,-23.42,47.0,X-MC,11.14,58.0,-0.36,1.18,1.98,X40,ATH,PHARMA

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-3.48,17.66,76.70,107.91,133246.0,26079.0,173723.0,1641.55,6.04,63.0,M-SC,7.65,220.0,0.20,1.27,30.70,OX40N,ATH,CABLES
66,SIS,1.45,-33.33,81.88,21.26,60612.0,-37006.0,74026.0,528.00,1734.20,36.0,H-SC,9.18,168.0,-0.61,0.54,2.05,OX40N,NTT,MISC
77,TTKPRESTIG,7.24,-37.02,58.93,0.09,37403.0,-37307.0,63470.0,770.00,47.28,34.0,M-SC,14.90,250.0,-1.00,0.46,7.24,OX40N,NTT,DURABLES
72,TATAELXSI,1.23,-37.21,110.28,32.03,91284.0,-49060.0,82775.0,9161.00,-21.54,30.0,H-SC,15.80,158.0,-0.54,0.61,1.23,OX40N,NTT,IT
48,KANSAINER,0.15,-38.06,83.19,13.47,138961.0,-102627.0,167040.0,340.00,-46.84,24.0,H-SC,16.17,162.0,-0.74,1.22,0.15,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.35,9.07,7.88,17.67,12932.0,13654.0,164114.0,478.51,31.99,60.0,L-LC,11.53,185.0,1.06,1.20,27.45,XY25,ATH,MINING
27,FINCABLES,-3.48,17.66,76.70,107.91,133246.0,26079.0,173723.0,1641.55,6.04,63.0,M-SC,7.65,220.0,0.20,1.27,30.70,OX40N,ATH,CABLES
1,ABB,4.05,14.20,27.46,45.57,82044.0,37157.0,298776.0,7934.00,-26.59,64.0,H-MC,9.72,125.0,0.45,2.19,32.68,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,4.05,14.20,27.46,45.57,82044.0,37157.0,298776.0,7934.00,-26.59,64.0,H-MC,9.72,125.0,0.45,2.19,32.68,AR,NTT,ELECTRICAL
27,FINCABLES,-3.48,17.66,76.70,107.91,133246.0,26079.0,173723.0,1641.55,6.04,63.0,M-SC,7.65,220.0,0.20,1.27,30.70,OX40N,ATH,CABLES
40,INDIAMART,-0.18,-6.34,120.71,106.72,139443.0,-7817.0,115519.0,4810.62,-57.81,50.0,H-SC,8.98,140.0,-0.06,0.84,15.56,AR,ATH,MISC
85,ZYDUSLIFE,1.57,-2.66,39.33,35.63,80235.0,-5569.0,204005.0,1286.17,-15.32,55.0,H-MC,5.09,120.0,-0.07,1.49,13.57,AR,ATH,PHARMA
84,WIPRO,1.10,-17.59,109.03,72.27,152256.0,-29802.0,139646.0,420.00,-25.49,32.0,M-LC,13.87,98.0,-0.20,1.02,2.83,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BATAINDIA,-0.09,-53.76,192.37,35.20,114466.0,-69167.0,59503.0,2096.00,-22.02,20.0,X-SC,24.75,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
58,RELAXO,-0.98,-60.12,281.88,52.31,163194.0,-87265.0,57895.0,1176.00,-57.51,20.0,X-SC,18.12,92.0,-0.53,0.42,0.00,X40N,NTT,FOOTWEAR
8,AWL,1.94,-38.36,170.93,67.02,375439.0,-136664.0,219645.0,485.00,-66.76,21.0,X-SC,22.42,81.0,-0.36,1.61,1.94,XY24,NTT,FMCG
3,ACC,1.62,-34.03,164.99,74.81,291834.0,-91248.0,176880.0,3906.00,-53.43,24.0,X-SC,11.66,85.0,-0.31,1.29,1.62,XY24,BTT,CEMENT
73,TCS,-0.57,-26.22,71.56,26.57,244579.0,-121491.0,341782.0,4311.59,-37.40,24.0,X-LC,13.09,2.0,-0.50,2.50,0.00,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,3.04,-5.98,52.84,43.70,123242.0,-14832.0,233236.0,735.00,-14.67,38.0,X-MC,0.93,70.0,-0.12,1.71,8.17,XY24,BTT,FMCG
78,UNITDSPR,3.78,3.36,16.84,20.77,40756.0,7877.0,242021.0,1644.00,-8.32,55.0,X-MC,1.54,64.0,0.19,1.77,10.30,X40N,NTT,BREWERIES
37,ICICIGI,-0.02,0.08,19.25,19.34,38551.0,157.0,200266.0,2252.93,-15.91,48.0,X-MC,1.60,66.0,0.00,1.46,14.22,X40,ATH,INSURANCE
59,RELIANCE,-1.07,-9.57,38.56,25.30,70077.0,-19228.0,181735.0,1952.00,-11.96,48.0,X-LC,2.24,21.0,-0.27,1.33,21.34,XY25,BTT,REFINERIES
75,TMPV,3.98,-21.42,73.81,36.58,206382.0,-76229.0,279612.0,600.00,-83.62,39.0,X-LC,2.32,4.0,-0.37,2.05,3.98,XY24,NTT,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BATAINDIA,-0.09,-53.76,192.37,35.20,114466.0,-69167.0,59503.0,2096.00,-22.02,20.0,X-SC,24.75,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
58,RELAXO,-0.98,-60.12,281.88,52.31,163194.0,-87265.0,57895.0,1176.00,-57.51,20.0,X-SC,18.12,92.0,-0.53,0.42,0.00,X40N,NTT,FOOTWEAR
73,TCS,-0.57,-26.22,71.56,26.57,244579.0,-121491.0,341782.0,4311.59,-37.40,24.0,X-LC,13.09,2.0,-0.50,2.50,0.00,X40,ATH,IT
10,BAJAJHLDNG,0.38,-8.00,40.46,29.22,70770.0,-15212.0,174913.0,14451.52,-15.20,32.0,X-LC,11.94,28.0,-0.21,1.28,0.38,X40,ATH,FINANCE
13,BERGEPAINT,0.58,-19.52,55.71,25.32,115560.0,-50317.0,207432.0,680.00,-23.91,31.0,X-MC,15.23,68.0,-0.44,1.52,0.58,XY24,NTT,PAINTS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.98,-60.12,281.88,52.31,163194.0,-87265.0,57895.0,1176.00,-57.51,20.0,X-SC,18.12,92.0,-0.53,0.42,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-0.09,-53.76,192.37,35.20,114466.0,-69167.0,59503.0,2096.00,-22.02,20.0,X-SC,24.75,91.0,-0.60,0.44,0.00,X40,NTT,FOOTWEAR
54,QUESS,2.31,-22.34,123.91,73.90,102771.0,-23853.0,82940.0,424.00,-58.13,39.0,X-SC,17.77,80.0,-0.23,0.61,2.31,XY24,NTT,MISC
36,HONAUT,3.59,-20.23,89.69,51.31,137966.0,-39013.0,153825.0,58357.33,-33.73,44.0,X-SC,13.50,90.0,-0.28,1.13,3.59,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-1.38,-10.06,31.28,18.07,50317.0,-17995.0,160860.0,35195.00,-23.42,47.0,X-MC,11.14,58.0,-0.36,1.18,1.98,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.00,-18.60,46.25,19.06,128070.0,-63257.0,276909.0,452.00,-55.52,38.0,X-LC,16.93,1.0,-0.49,2.03,1.00,X40,NTT,FMCG
73,TCS,-0.57,-26.22,71.56,26.57,244579.0,-121491.0,341782.0,4311.59,-37.40,24.0,X-LC,13.09,2.0,-0.50,2.50,0.00,X40,ATH,IT
43,INFY,-1.48,-11.80,52.21,34.24,144080.0,-36925.0,275963.0,1972.00,-30.70,28.0,X-LC,11.45,3.0,-0.26,2.02,1.58,X40,NTT,IT
75,TMPV,3.98,-21.42,73.81,36.58,206382.0,-76229.0,279612.0,600.00,-83.62,39.0,X-LC,2.32,4.0,-0.37,2.05,3.98,XY24,NTT,AUTO
34,HCLTECH,0.21,-11.64,40.15,23.83,85823.0,-28168.0,213756.0,1908.19,-7.36,29.0,X-LC,9.11,8.0,-0.33,1.56,2.56,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,1.99,-33.65,100.29,32.89,51375.0,-25980.0,51226.0,1800.00,-340.90,43.0,L-MC,11.58,258.0,-0.51,0.37,41.07,XR,NTT,BANKS
67,SONACOMS,2.21,-11.47,57.11,39.09,51145.0,-11603.0,89556.0,804.02,-29.79,48.0,M-MC,10.28,193.0,-0.23,0.66,26.69,AR,ATH,AUTO
19,COALINDIA,1.35,9.07,7.88,17.67,12932.0,13654.0,164114.0,478.51,31.99,60.0,L-LC,11.53,185.0,1.06,1.20,27.45,XY25,ATH,MINING
27,FINCABLES,-3.48,17.66,76.70,107.91,133246.0,26079.0,173723.0,1641.55,6.04,63.0,M-SC,7.65,220.0,0.20,1.27,30.70,OX40N,ATH,CABLES
82,VOLTAS,0.86,13.35,28.10,45.20,61071.0,25593.0,217335.0,1856.00,29.81,46.0,X-MC,9.73,79.0,0.42,1.59,21.05,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-3.48,17.66,76.70,107.91,133246.0,26079.0,173723.0,1641.55,6.04,63.0,M-SC,7.65,220.0,0.20,1.27,30.70,OX40N,ATH,CABLES
11,BANDHANBNK,4.67,-12.32,119.47,92.42,291779.0,-34331.0,244228.0,400.00,109.77,61.0,H-SC,9.99,174.0,-0.12,1.79,34.54,XY24,NTT,BANKS
1,ABB,4.05,14.20,27.46,45.57,82044.0,37157.0,298776.0,7934.00,-26.59,64.0,H-MC,9.72,125.0,0.45,2.19,32.68,AR,NTT,ELECTRICAL
65,SIEMENS,1.42,-12.01,42.65,25.51,69837.0,-22350.0,163745.0,4671.50,37.53,54.0,H-LC,3.55,51.0,-0.32,1.20,20.58,AR,ATH,ELECTRICAL
26,EASEMYTRIP,1.94,-59.44,259.18,45.70,185886.0,-105094.0,71721.0,26.40,-25.60,44.0,M-SC,18.18,204.0,-0.57,0.52,18.17,XY24,NTT,TRAVEL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.56
1     25       45.48
2     50       77.96

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.50
MC    30.54
LC    24.97
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.25
X40      23.80
X40N     15.25
AR        9.14
XY25      8.68
XR        8.25
OX40N     6.87
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.17
H-SC    21.62
X-LC    21.55
X-SC    12.18
M-SC    10.12
H-MC     4.99
M-MC     2.01
H-LC     1.20
L-LC     1.20
M-LC     1.02
L-SC     0.58
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.37        -18.90   61.11
FINANCE             12.85        -22.42   72.31
IT                  11.75        -40.28  111.66
MISC                 6.93        -41.54  103.03
ELECTRICAL           6.61         -7.43   48.57
PAINTS               5.20        -38.56   62.62
INSURANCE            4.68         -5.68   41.85
PHARMA               4.13         -4.24   37.05
AUTO                 3.78        -26.75   77.04
BANKS                3.16        -23.84   98.88
AC                   2.14         -9.36   39.01
HEALTHCARE           1.96        -33.41   68.23
FOOTWEAR             1.84        -75.40  145.73
TRAVEL               1.83        -78.68  168.14
DURABLES             1.81        -55.88   93.80
BREWERIES            1.77          3.25   16.84
APPARELS             1.61        -21.58   63.05
REALTY               1.45        -11.73   30.09
REFINERIES           1.33        -10.58   38.56
CERAMICS             1.32        -69.45  120.93
CEMENT               1.29        -51.59  164.99
CABLES               1.27         15.01   76.70
MINING               1.20          8.32    7.88
JEWELLERY            1.11       -110.49  183.62
ENGINEERING          1.11        -60.11  133.34
CHEMICALS            0.96       -101.70  266.25
ENTERTAINMENT        0.76        -85.50  196.13
TEXTILES             0.42        -60.71  106.54
HOTELS               0.37       -121.66  199.85

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3873931.0     21
X40       1618251.0     15
XR        1361642.0     12
AR        1322484.0     10
X40N      1216279.0     10
OX40N      852188.0     10
XY25       431477.0      6
SR         313481.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3835821.0     24
X-MC        1566741.0     15
M-SC        1533023.0     14
X-LC        1529480.0     12
X-SC        1517700.0     10
H-MC         397341.0      3
L-SC         210708.0      2
M-LC         152256.0      1
M-MC         112519.0      2
H-LC          69837.0      1
L-MC          51375.0      1
L-LC          12932.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1310716.0      6
           AR         962649.0      5
M-SC       XY24       905933.0      6
H-SC       XR         866388.0      7
X-SC       XY24       827553.0      4
X-LC       X40        793670.0      6
X-MC       X40        624743.0      7
X-SC       X40N       490309.0      4
X-MC       X40N       489277.0      4
H-SC       OX40N      382587.0      4
M-SC       OX40N      361268.0      5
X-LC       XY24       355865.0      2
H-SC       SR         313481.0      2
X-MC       XY24       238802.0      2
X-LC       X40N       236693.0      2
H-MC       XY24       235062.0      1
X-MC       XY25       213919.0      2
X-SC       X40        199838.0      2
M-SC       XR         189248.0      2
H-MC       AR         162279.0      2
M-LC       XR         152256.0      1
X-LC       XY25       143252.0      2
L-SC       OX40N      108333.0      1
           XR         102375.0      1
M-SC       AR          76574.0      1
H-LC       AR          69837.0      1
M-MC       XY25        61374.0      1
L-MC       XR          51375.0      1
M-MC       AR          51145.0      1
L-LC       XY25        12932.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 42.0 seconds