<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-25 15:14:45
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: -19.43 K (-0.13%)
Current PnL: -31.45 L (-17.24%)
CY Booked + Current PnL: -29.37 L (-16.1%)
-------------------
Total profit:  3.99 L
Total loss:  -35.44 L
-------------------
Total Booked + Current PnL: 13.50 L (9.68%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (68.09%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 3.9%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,1.33,13.39,4.39,18.37,7024.0,18890.0,160000.0,1670.26,-20.60,74.0,X-LC,4.36,5.0,2.69,1.05,25.63,X40,ATH,CHEMICALS
49,JSWINFRA,-2.45,12.38,3.60,16.43,8972.0,27452.0,249226.0,342.00,-3.70,73.0,X-MC,4.76,61.0,3.06,1.64,41.30,X40N,NTT,REALTY
51,KOTAKBANK,0.74,9.27,10.83,21.11,16387.0,12840.0,151312.0,453.24,-6.37,67.0,X-LC,4.95,12.0,0.78,1.00,15.72,X40,ATH,BANKS
72,SIS,-1.42,-0.04,21.31,21.26,23652.0,-43.0,110989.0,528.00,2650.26,62.0,H-SC,24.95,168.0,-0.00,0.73,65.02,OX40N,NTT,MISC
55,MASFIN,-0.81,-4.55,27.36,21.57,25588.0,-4455.0,93525.0,397.04,-17.80,50.0,H-SC,3.12,167.0,-0.17,0.62,11.48,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,10.87,-47.02,187.50,52.31,144189.0,-68259.0,76901.0,1176.0,-43.57,77.0,X-SC,14.31,92.0,-0.47,0.51,71.94,X40N,NTT,FOOTWEAR
66,REPCOHOME,7.90,-9.02,108.63,89.82,283168.0,-25833.0,260672.0,880.0,-54.55,71.0,H-SC,2.87,161.0,-0.09,1.72,25.31,XY24,NTT,FINANCE
53,M&M,3.81,3.23,19.52,23.38,27945.0,4482.0,143163.0,3802.4,-12.35,59.0,X-LC,10.51,25.0,0.16,0.94,8.54,X40N,ATH,AUTO
54,MARUTI,3.71,2.24,25.86,28.68,39082.0,3312.0,151129.0,17292.0,-16.04,60.0,X-LC,10.43,33.0,0.08,1.00,12.54,XR,ATH,AUTO
14,CAMPUS,2.23,-19.28,65.13,33.28,88200.0,-32353.0,135422.0,393.0,-34.97,48.0,M-SC,6.86,218.0,-0.37,0.89,8.75,XY24,NTT,FOOTWEAR

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-5.00,-81.26,433.91,0.07,111558.0,-111467.0,25710.0,518.0,841.92,47.0,L-SC,37.05,268.0,-1.00,0.17,26.97,OX40N,NTT,JEWELLERY
21,DEN,-4.79,-41.31,142.09,42.07,70431.0,-34896.0,49568.0,75.0,76.17,59.0,M-SC,6.51,235.0,-0.50,0.33,34.81,AR,NTT,ENTERTAINMENT
9,BANDHANBNK,-4.68,-2.90,98.17,92.42,265529.0,-8080.0,270479.0,400.0,132.04,48.0,H-SC,23.26,174.0,-0.03,1.78,49.00,XY24,NTT,BANKS
24,EASEMYTRIP,-4.38,-60.21,266.16,45.70,187257.0,-106460.0,70355.0,26.4,-27.06,40.0,M-SC,4.48,204.0,-0.57,0.46,23.25,XY24,NTT,TRAVEL
80,TITAGARH,-3.65,-16.35,74.23,45.74,150374.0,-39599.0,202578.0,1548.0,11.43,57.0,H-SC,7.72,175.0,-0.26,1.34,54.56,XY24,NTT,ENGINEERING

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-1.42,-0.04,21.31,21.26,23652.0,-43.0,110989.0,528.0,2650.26,62.0,H-SC,24.95,168.0,-0.0,0.73,65.02,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.80,41.36,47.08,107.91,98261.0,61067.0,208711.0,1641.55,27.35,55.0,M-SC,24.21,220.0,0.62,1.38,57.02,OX40N,ATH,CABLES
72,SIS,-1.42,-0.04,21.31,21.26,23652.0,-43.0,110989.0,528.00,2650.26,62.0,H-SC,24.95,168.0,-0.00,0.73,65.02,OX40N,NTT,MISC
16,CERA,-0.28,-17.33,49.86,23.89,72505.0,-30485.0,145418.0,9475.00,-20.29,62.0,H-SC,8.47,153.0,-0.42,0.96,39.75,OX40N,NTT,CERAMICS
83,TTKPRESTIG,0.76,-25.89,35.06,0.09,26184.0,-26094.0,74683.0,770.00,73.32,63.0,M-SC,8.58,250.0,-1.00,0.49,32.98,OX40N,NTT,DURABLES
43,INDIGOPNTS,-1.94,-28.41,39.70,0.02,49614.0,-49586.0,124973.0,1408.00,90.85,56.0,M-SC,7.65,222.0,-1.00,0.82,41.79,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.80,41.36,47.08,107.91,98261.0,61067.0,208711.0,1641.55,27.35,55.0,M-SC,24.21,220.0,0.62,1.38,57.02,OX40N,ATH,CABLES
68,SATIN,-3.17,28.41,18.25,51.83,64744.0,78479.0,354763.0,274.00,15.64,54.0,H-SC,41.03,159.0,1.21,2.34,72.82,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,1.34,12.62,30.76,47.26,97389.0,35485.0,316608.0,761.00,77.79,73.0,H-SC,12.61,173.0,0.36,2.09,39.00,XY24,NTT,INSURANCE
25,FINCABLES,-1.80,41.36,47.08,107.91,98261.0,61067.0,208711.0,1641.55,27.35,55.0,M-SC,24.21,220.0,0.62,1.38,57.02,OX40N,ATH,CABLES
68,SATIN,-3.17,28.41,18.25,51.83,64744.0,78479.0,354763.0,274.00,15.64,54.0,H-SC,41.03,159.0,1.21,2.34,72.82,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.16,16.11,16.81,35.63,40906.0,33769.0,243343.0,1286.17,0.90,61.0,H-MC,13.75,120.0,0.83,1.60,27.95,AR,ATH,PHARMA
73,SONACOMS,-0.05,7.08,29.51,38.69,31967.0,7166.0,108325.0,801.69,-15.20,61.0,M-MC,18.06,193.0,0.22,0.71,53.69,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.16,16.11,16.81,35.63,40906.0,33769.0,243343.0,1286.17,0.90,61.0,H-MC,13.75,120.0,0.83,1.60,27.95,AR,ATH,PHARMA
25,FINCABLES,-1.80,41.36,47.08,107.91,98261.0,61067.0,208711.0,1641.55,27.35,55.0,M-SC,24.21,220.0,0.62,1.38,57.02,OX40N,ATH,CABLES
73,SONACOMS,-0.05,7.08,29.51,38.69,31967.0,7166.0,108325.0,801.69,-15.20,61.0,M-MC,18.06,193.0,0.22,0.71,53.69,AR,ATH,AUTO
72,SIS,-1.42,-0.04,21.31,21.26,23652.0,-43.0,110989.0,528.00,2650.26,62.0,H-SC,24.95,168.0,-0.00,0.73,65.02,OX40N,NTT,MISC
75,SURYODAY,-0.70,-1.89,25.40,23.03,44627.0,-3376.0,175695.0,216.00,90.79,56.0,H-SC,19.42,166.0,-0.08,1.16,47.93,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-1.53,-29.17,89.54,34.24,198425.0,-91283.0,221605.0,1972.00,-44.12,36.0,X-LC,17.69,3.0,-0.46,1.46,1.08,X40,NTT,IT
33,HCLTECH,-1.31,-28.66,70.32,21.51,121365.0,-69334.0,172590.0,1872.35,-25.14,36.0,X-LC,18.73,8.0,-0.57,1.14,0.00,X40,ATH,IT
1,ABBOTINDIA,-0.18,-14.29,37.75,18.07,57871.0,-25555.0,153300.0,35195.00,-27.11,38.0,X-MC,6.26,58.0,-0.44,1.01,1.47,X40,ATH,PHARMA
79,TCS,-0.62,-38.47,102.96,24.88,293479.0,-178231.0,285042.0,4253.91,-47.89,38.0,X-LC,20.00,2.0,-0.61,1.88,1.76,X40,ATH,IT
58,PGHH,0.58,-32.33,95.07,32.01,137372.0,-69024.0,144496.0,17616.87,-54.24,39.0,X-MC,20.64,57.0,-0.50,0.95,0.58,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,1.46,-0.80,26.32,25.32,67298.0,-2057.0,255692.0,680.00,-6.27,59.0,X-MC,2.71,68.0,-0.03,1.69,33.08,XY24,NTT,PAINTS
17,CIPLA,0.22,16.67,14.37,33.43,25679.0,25535.0,178696.0,1648.14,-9.73,67.0,X-LC,3.70,18.0,0.99,1.18,21.99,X40N,ATH,PHARMA
56,MEDANTA,-0.55,12.16,13.34,27.12,26410.0,21459.0,197976.0,1486.00,8.75,68.0,X-SC,3.70,87.0,0.81,1.30,36.42,XY24,NTT,HEALTHCARE
19,COLPAL,1.38,-24.35,84.87,39.86,169095.0,-64125.0,199240.0,3683.41,-8.54,43.0,X-MC,4.10,62.0,-0.38,1.31,12.70,XY25,ATH,FMCG
84,UNITDSPR,1.96,1.79,18.64,20.77,44427.0,4196.0,238340.0,1644.00,-9.71,68.0,X-MC,4.11,64.0,0.09,1.57,13.69,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-1.31,-28.66,70.32,21.51,121365.0,-69334.0,172590.0,1872.35,-25.14,36.0,X-LC,18.73,8.0,-0.57,1.14,0.00,X40,ATH,IT
58,PGHH,0.58,-32.33,95.07,32.01,137372.0,-69024.0,144496.0,17616.87,-54.24,39.0,X-MC,20.64,57.0,-0.50,0.95,0.58,X40,ATH,FMCG
45,INFY,-1.53,-29.17,89.54,34.24,198425.0,-91283.0,221605.0,1972.00,-44.12,36.0,X-LC,17.69,3.0,-0.46,1.46,1.08,X40,NTT,IT
1,ABBOTINDIA,-0.18,-14.29,37.75,18.07,57871.0,-25555.0,153300.0,35195.00,-27.11,38.0,X-MC,6.26,58.0,-0.44,1.01,1.47,X40,ATH,PHARMA
79,TCS,-0.62,-38.47,102.96,24.88,293479.0,-178231.0,285042.0,4253.91,-47.89,38.0,X-LC,20.00,2.0,-0.61,1.88,1.76,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.06,-53.85,192.96,35.20,114584.0,-69288.0,59382.0,2096.00,-22.17,54.0,X-SC,22.59,91.0,-0.60,0.39,17.77,X40,NTT,FOOTWEAR
64,RELAXO,10.87,-47.02,187.50,52.31,144189.0,-68259.0,76901.0,1176.00,-43.57,77.0,X-SC,14.31,92.0,-0.47,0.51,71.94,X40N,NTT,FOOTWEAR
60,QUESS,0.36,2.94,68.94,73.90,75785.0,3136.0,109929.0,424.00,-44.90,73.0,X-SC,11.57,80.0,0.04,0.72,49.86,XY24,NTT,MISC
28,GODREJCP,1.40,-7.39,41.96,31.47,57749.0,-10986.0,137628.0,1469.04,-2.65,54.0,X-LC,9.32,32.0,-0.19,0.91,5.60,X40N,ATH,FMCG
53,M&M,3.81,3.23,19.52,23.38,27945.0,4482.0,143163.0,3802.40,-12.35,59.0,X-LC,10.51,25.0,0.16,0.94,8.54,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.19,-23.67,55.97,19.06,145332.0,-80505.0,259661.0,452.00,-57.95,50.0,X-LC,14.72,1.0,-0.55,1.71,4.62,X40,NTT,FMCG
79,TCS,-0.62,-38.47,102.96,24.88,293479.0,-178231.0,285042.0,4253.91,-47.89,38.0,X-LC,20.00,2.0,-0.61,1.88,1.76,X40,ATH,IT
45,INFY,-1.53,-29.17,89.54,34.24,198425.0,-91283.0,221605.0,1972.00,-44.12,36.0,X-LC,17.69,3.0,-0.46,1.46,1.08,X40,NTT,IT
81,TMPV,1.10,-19.52,69.71,36.58,199633.0,-69465.0,286376.0,600.00,-83.62,41.0,X-LC,9.90,4.0,-0.35,1.89,20.35,XY24,NTT,AUTO
59,PIDILITIND,1.33,13.39,4.39,18.37,7024.0,18890.0,160000.0,1670.26,-20.60,74.0,X-LC,4.36,5.0,2.69,1.05,25.63,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.64,-32.06,95.61,32.89,50148.0,-24756.0,52451.0,1800.00,-347.20,52.0,L-MC,6.98,258.0,-0.49,0.35,29.31,XR,NTT,BANKS
3,ALKYLAMINE,1.37,-23.52,151.76,92.54,117181.0,-23748.0,77215.0,4520.85,-18.07,55.0,H-SC,7.69,142.0,-0.20,0.51,46.62,SR,ATH,CHEMICALS
64,RELAXO,10.87,-47.02,187.50,52.31,144189.0,-68259.0,76901.0,1176.00,-43.57,77.0,X-SC,14.31,92.0,-0.47,0.51,71.94,X40N,NTT,FOOTWEAR
73,SONACOMS,-0.05,7.08,29.51,38.69,31967.0,7166.0,108325.0,801.69,-15.20,61.0,M-MC,18.06,193.0,0.22,0.71,53.69,AR,ATH,AUTO
60,QUESS,0.36,2.94,68.94,73.90,75785.0,3136.0,109929.0,424.00,-44.90,73.0,X-SC,11.57,80.0,0.04,0.72,49.86,XY24,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,10.87,-47.02,187.50,52.31,144189.0,-68259.0,76901.0,1176.00,-43.57,77.0,X-SC,14.31,92.0,-0.47,0.51,71.94,X40N,NTT,FOOTWEAR
18,COFFEEDAY,-2.66,-43.76,140.53,35.27,89741.0,-49690.0,63859.0,80.00,-57.75,52.0,L-SC,16.79,266.0,-0.55,0.42,57.48,XR,NTT,HOTELS
60,QUESS,0.36,2.94,68.94,73.90,75785.0,3136.0,109929.0,424.00,-44.90,73.0,X-SC,11.57,80.0,0.04,0.72,49.86,XY24,NTT,MISC
49,JSWINFRA,-2.45,12.38,3.60,16.43,8972.0,27452.0,249226.0,342.00,-3.70,73.0,X-MC,4.76,61.0,3.06,1.64,41.30,X40N,NTT,REALTY
37,HONAUT,1.00,2.17,48.10,51.31,94769.0,4187.0,197025.0,58357.33,-15.00,74.0,X-SC,8.27,90.0,0.04,1.30,49.69,X40N,ATH,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.24
1     25       42.62
2     50       72.71

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.56
LC    30.56
MC    25.91
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.73
X40      24.60
X40N     17.61
XR        8.88
OX40N     7.13
AR        6.75
XY25      6.47
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.57
H-SC    22.87
X-MC    20.83
M-SC    10.09
X-SC    10.01
H-MC     2.70
M-MC     2.03
H-LC     1.19
M-LC     0.80
L-SC     0.59
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.51        -20.22   62.39
FINANCE             11.13         -9.23   56.74
IT                   9.57        -55.41  133.11
MISC                 7.20        -22.50   75.06
AUTO                 6.66         -8.43   49.04
BANKS                5.76         -3.96   52.03
PAINTS               5.55        -17.02   36.98
INSURANCE            5.37         -1.96   36.35
PHARMA               5.03          2.97   27.06
ELECTRICAL           4.12        -12.97   52.84
CHEMICALS            2.20        -21.45   93.50
HEALTHCARE           2.09        -12.68   42.08
APPARELS             1.89          6.44   24.98
AC                   1.80        -17.25   49.04
FOOTWEAR             1.79        -62.53  127.70
REALTY               1.64         11.01    3.60
BREWERIES            1.57          1.76   18.64
DURABLES             1.57        -62.69  102.27
TRAVEL               1.56        -88.07  182.23
CERAMICS             1.43        -41.91   85.02
CABLES               1.38         29.26   47.08
ENGINEERING          1.34        -19.55   74.23
REFINERIES           1.12        -18.11   47.99
CEMENT               1.06        -66.75  191.49
JEWELLERY            1.04       -103.71  174.49
ENTERTAINMENT        0.80        -60.65  156.47
TEXTILES             0.43        -41.05   81.27
HOTELS               0.42        -77.81  140.53

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3388949.0     21
X40       1948182.0     19
XR        1338848.0     13
AR        1151179.0      9
X40N      1052120.0     13
OX40N      711324.0     10
XY25       452684.0      5
SR         287906.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3313189.0     24
X-LC        1951185.0     21
X-MC        1558726.0     15
M-SC        1387415.0     14
X-SC        1283161.0      9
H-MC         287096.0      2
L-SC         201299.0      2
M-LC         170275.0      1
M-MC          76301.0      2
H-LC          52397.0      1
L-MC          50148.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1061032.0     10
H-SC       XY24       975415.0      6
           AR         955478.0      5
M-SC       XY24       822006.0      6
H-SC       XR         801374.0      7
X-SC       XY24       781777.0      4
X-MC       X40        675020.0      7
           X40N       413712.0      4
X-LC       X40N       349154.0      6
           XY24       345473.0      2
M-SC       OX40N      306750.0      5
H-SC       OX40N      293016.0      4
X-SC       X40N       289254.0      3
H-SC       SR         287906.0      2
X-MC       XY25       251906.0      2
H-MC       XY24       246190.0      1
X-MC       XY24       218088.0      2
X-SC       X40        212130.0      2
M-SC       XR         188228.0      2
M-LC       XR         170275.0      1
X-LC       XY25       156444.0      2
L-SC       OX40N      111558.0      1
           XR          89741.0      1
M-SC       AR          70431.0      1
H-LC       AR          52397.0      1
L-MC       XR          50148.0      1
M-MC       XY25        44334.0      1
H-MC       AR          40906.0      1
X-LC       XR          39082.0      1
M-MC       AR          31967.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 32.0 seconds