<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-07 15:47:47
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16

-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: 70.27 K (0.54%)
Current PnL: -45.50 L (-28.0%)
CY Booked + Current PnL: -29.61 L (-18.22%)
-------------------
Total profit:  64.20 K
Total loss:  -46.14 L
-------------------
Total Booked + Current PnL: -2.63 L (-1.94%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.07%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (88.33%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.4%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-1.27,-8.36,32.66,21.57,29325.0,-8190.0,89790.0,397.04,-20.96,48.0,H-SC,4.94,167.0,-0.28,0.68,22.47,XR,ATH,FINANCE
77,TTKPRESTIG,3.19,-38.83,63.62,0.09,39221.0,-39128.0,61649.0,770.00,43.01,46.0,M-SC,22.37,250.0,-1.00,0.47,9.77,OX40N,NTT,DURABLES
67,SONACOMS,1.13,-10.88,56.07,39.09,50548.0,-11008.0,90151.0,804.02,-29.38,54.0,M-MC,7.30,193.0,-0.22,0.68,27.53,AR,ATH,AUTO
24,DMART,-1.87,7.36,20.72,29.60,55521.0,18360.0,267960.0,5391.45,-9.43,72.0,X-LC,5.67,14.0,0.33,2.04,22.48,X40N,ATH,FMCG
37,ICICIGI,0.79,-8.54,30.48,19.34,55784.0,-17089.0,183020.0,2252.93,-23.02,37.0,X-MC,6.63,66.0,-0.31,1.39,2.22,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,9.47,-45.64,220.35,74.15,195981.0,-74664.0,88941.0,838.0,-259.70,60.0,H-SC,26.10,145.0,-0.38,0.68,32.36,XR,NTT,CHEMICALS
74,TITAGARH,8.74,-34.54,122.65,45.74,194421.0,-83660.0,158517.0,1548.0,-12.73,58.0,H-SC,23.47,175.0,-0.43,1.20,20.94,XY24,NTT,ENGINEERING
55,RAJESHEXPO,4.98,-81.42,438.57,0.07,111783.0,-111689.0,25488.0,518.0,834.34,38.0,L-SC,44.02,268.0,-1.00,0.19,19.66,OX40N,NTT,JEWELLERY
84,WIPRO,3.77,-16.03,105.16,72.27,149622.0,-27168.0,142280.0,420.0,-24.09,57.0,M-LC,17.93,98.0,-0.18,1.08,9.16,XR,NTT,IT
77,TTKPRESTIG,3.19,-38.83,63.62,0.09,39221.0,-39128.0,61649.0,770.0,43.01,46.0,M-SC,22.37,250.0,-1.00,0.47,9.77,OX40N,NTT,DURABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SURYODAY,-2.93,-27.04,68.64,23.03,89673.0,-48429.0,130642.0,216.00,42.54,50.0,H-SC,5.39,166.0,-0.54,0.99,18.21,XR,NTT,BANKS
82,VOLTAS,-2.54,-4.54,52.11,45.20,95377.0,-8712.0,183030.0,1856.00,9.21,33.0,X-MC,4.27,79.0,-0.09,1.39,1.94,XY25,NTT,AC
49,LAOPALA,-2.46,-47.57,165.26,39.09,113606.0,-62361.0,68744.0,464.00,50.07,40.0,H-SC,18.06,154.0,-0.55,0.52,6.66,AR,NTT,CERAMICS
11,BANDHANBNK,-2.26,-28.26,168.22,92.42,336161.0,-78725.0,199834.0,400.00,71.70,41.0,H-SC,1.48,174.0,-0.23,1.52,10.08,XY24,NTT,BANKS
30,HAPPSTMNDS,-1.97,-52.84,291.93,84.85,176466.0,-67717.0,60448.0,1480.71,-43.83,48.0,H-SC,23.24,152.0,-0.38,0.46,11.94,AR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.16,2.66,102.54,107.91,155414.0,3920.0,151564.0,1641.55,-7.66,46.0,M-SC,4.19,220.0,0.03,1.15,14.03,OX40N,ATH,CABLES
66,SIS,-0.29,-33.81,83.21,21.26,61152.0,-37541.0,73491.0,528.00,1721.24,49.0,H-SC,14.92,168.0,-0.61,0.56,9.27,OX40N,NTT,MISC
18,CERA,0.43,-37.12,97.02,23.89,107316.0,-65291.0,110612.0,9475.00,-39.38,52.0,H-SC,18.96,153.0,-0.61,0.84,6.30,OX40N,NTT,CERAMICS
72,TATAELXSI,2.00,-37.20,110.23,32.03,91264.0,-49041.0,82794.0,9161.00,-21.37,50.0,H-SC,21.58,158.0,-0.54,0.63,9.58,OX40N,NTT,IT
77,TTKPRESTIG,3.19,-38.83,63.62,0.09,39221.0,-39128.0,61649.0,770.00,43.01,46.0,M-SC,22.37,250.0,-1.00,0.47,9.77,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.16,2.66,102.54,107.91,155414.0,3920.0,151564.0,1641.55,-7.66,46.0,M-SC,4.19,220.0,0.03,1.15,14.03,OX40N,ATH,CABLES
1,ABB,1.22,15.02,26.56,45.57,79922.0,39293.0,300912.0,7934.00,-26.10,57.0,H-MC,13.92,125.0,0.49,2.29,33.62,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.22,15.02,26.56,45.57,79922.0,39293.0,300912.0,7934.00,-26.10,57.0,H-MC,13.92,125.0,0.49,2.29,33.62,AR,NTT,ELECTRICAL
26,FINCABLES,0.16,2.66,102.54,107.91,155414.0,3920.0,151564.0,1641.55,-7.66,46.0,M-SC,4.19,220.0,0.03,1.15,14.03,OX40N,ATH,CABLES
40,INDIAMART,-0.69,-11.76,134.26,106.72,146123.0,-14500.0,108836.0,4810.62,-60.16,47.0,H-SC,12.87,140.0,-0.10,0.83,8.87,AR,ATH,MISC
84,WIPRO,3.77,-16.03,105.16,72.27,149622.0,-27168.0,142280.0,420.00,-24.09,57.0,M-LC,17.93,98.0,-0.18,1.08,9.16,XR,NTT,IT
85,ZYDUSLIFE,0.83,-7.89,47.24,35.63,91194.0,-16530.0,193044.0,1286.17,-19.82,45.0,H-MC,5.92,120.0,-0.18,1.47,7.47,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,0.69,-14.51,52.91,30.73,89115.0,-28577.0,168428.0,790.00,-37.42,28.0,X-MC,10.37,78.0,-0.32,1.28,2.63,X40,ATH,INSURANCE
21,DABUR,0.13,-19.01,77.43,43.70,155565.0,-47157.0,200911.0,735.00,-26.49,30.0,X-MC,12.40,70.0,-0.30,1.53,0.93,XY24,BTT,FMCG
82,VOLTAS,-2.54,-4.54,52.11,45.20,95377.0,-8712.0,183030.0,1856.00,9.21,33.0,X-MC,4.27,79.0,-0.09,1.39,1.94,XY25,NTT,AC
59,RELIANCE,-0.01,-16.26,49.62,25.30,83507.0,-32670.0,168293.0,1952.00,-18.49,33.0,X-LC,4.24,21.0,-0.39,1.28,12.36,XY25,BTT,REFINERIES
53,PGHH,0.18,-27.25,81.47,32.01,126546.0,-58192.0,155328.0,17616.87,-50.75,36.0,X-MC,19.90,57.0,-0.46,1.18,6.24,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,0.90,-17.37,51.89,25.51,79794.0,-32320.0,153775.0,4671.50,29.19,47.0,H-LC,0.71,51.0,-0.41,1.17,13.24,AR,ATH,ELECTRICAL
78,UNITDSPR,0.15,-9.05,32.78,20.77,69806.0,-21191.0,212953.0,1644.00,-19.26,40.0,X-MC,4.14,64.0,-0.30,1.62,1.58,X40N,NTT,BREWERIES
59,RELIANCE,-0.01,-16.26,49.62,25.30,83507.0,-32670.0,168293.0,1952.00,-18.49,33.0,X-LC,4.24,21.0,-0.39,1.28,12.36,XY25,BTT,REFINERIES
82,VOLTAS,-2.54,-4.54,52.11,45.20,95377.0,-8712.0,183030.0,1856.00,9.21,33.0,X-MC,4.27,79.0,-0.09,1.39,1.94,XY25,NTT,AC
24,DMART,-1.87,7.36,20.72,29.60,55521.0,18360.0,267960.0,5391.45,-9.43,72.0,X-LC,5.67,14.0,0.33,2.04,22.48,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,JSWINFRA,-1.81,-20.23,45.96,16.43,81305.0,-44870.0,176904.0,342.0,-31.54,38.0,X-MC,12.21,61.0,-0.55,1.34,0.00,X40N,NTT,REALTY
2,ABBOTINDIA,-0.89,-13.90,37.13,18.07,57176.0,-24865.0,153990.0,35195.0,-26.70,41.0,X-MC,10.92,58.0,-0.43,1.17,0.71,X40,ATH,PHARMA
21,DABUR,0.13,-19.01,77.43,43.70,155565.0,-47157.0,200911.0,735.0,-26.49,30.0,X-MC,12.40,70.0,-0.30,1.53,0.93,XY24,BTT,FMCG
78,UNITDSPR,0.15,-9.05,32.78,20.77,69806.0,-21191.0,212953.0,1644.0,-19.26,40.0,X-MC,4.14,64.0,-0.30,1.62,1.58,X40N,NTT,BREWERIES
82,VOLTAS,-2.54,-4.54,52.11,45.20,95377.0,-8712.0,183030.0,1856.0,9.21,33.0,X-MC,4.27,79.0,-0.09,1.39,1.94,XY25,NTT,AC

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-1.20,-65.05,335.78,52.31,170355.0,-94426.0,50734.0,1176.00,-62.83,40.0,X-SC,32.35,92.0,-0.55,0.39,13.43,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.45,-56.81,213.07,35.20,118399.0,-73102.0,55568.0,2096.00,-27.08,43.0,X-SC,34.36,91.0,-0.62,0.42,10.21,X40,NTT,FOOTWEAR
54,QUESS,2.32,-25.20,132.49,73.90,105830.0,-26915.0,79878.0,424.00,-59.78,49.0,X-SC,22.40,80.0,-0.25,0.61,7.45,XY24,NTT,MISC
36,HONAUT,-0.98,-29.44,114.43,51.31,155711.0,-56763.0,136075.0,58357.33,-41.36,37.0,X-SC,18.48,90.0,-0.36,1.03,3.38,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-0.89,-13.90,37.13,18.07,57176.0,-24865.0,153990.0,35195.00,-26.70,41.0,X-MC,10.92,58.0,-0.43,1.17,0.71,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.22,-21.39,51.45,19.06,137583.0,-72755.0,267411.0,452.00,-56.73,45.0,X-LC,19.89,1.0,-0.53,2.03,3.74,X40,NTT,FMCG
73,TCS,2.66,-25.44,69.76,26.57,240960.0,-117860.0,345413.0,4311.59,-36.74,53.0,X-LC,18.61,2.0,-0.49,2.62,7.80,X40,ATH,IT
43,INFY,2.54,-8.82,47.23,34.24,134743.0,-27596.0,285292.0,1972.00,-28.16,56.0,X-LC,14.74,3.0,-0.20,2.17,9.71,X40,NTT,IT
75,TMPV,0.42,-29.73,94.36,36.58,235944.0,-105794.0,250047.0,600.00,-85.81,40.0,X-LC,12.43,4.0,-0.45,1.90,4.22,XY24,NTT,AUTO
33,HCLTECH,2.73,-6.45,32.37,23.83,73263.0,-15593.0,226331.0,1908.19,-1.57,59.0,X-LC,10.93,8.0,-0.21,1.72,9.89,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,1.13,-10.88,56.07,39.09,50548.0,-11008.0,90151.0,804.02,-29.38,54.0,M-MC,7.30,193.0,-0.22,0.68,27.53,AR,ATH,AUTO
24,DMART,-1.87,7.36,20.72,29.60,55521.0,18360.0,267960.0,5391.45,-9.43,72.0,X-LC,5.67,14.0,0.33,2.04,22.48,X40N,ATH,FMCG
1,ABB,1.22,15.02,26.56,45.57,79922.0,39293.0,300912.0,7934.00,-26.10,57.0,H-MC,13.92,125.0,0.49,2.29,33.62,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,9.47,-45.64,220.35,74.15,195981.0,-74664.0,88941.0,838.00,-259.70,60.0,H-SC,26.10,145.0,-0.38,0.68,32.36,XR,NTT,CHEMICALS
5,ANGELONE,0.02,0.86,23.12,24.18,71123.0,2625.0,307625.0,303.00,-85.37,58.0,X-SC,8.61,97.0,0.04,2.34,18.41,X40N,NTT,FINANCE
24,DMART,-1.87,7.36,20.72,29.60,55521.0,18360.0,267960.0,5391.45,-9.43,72.0,X-LC,5.67,14.0,0.33,2.04,22.48,X40N,ATH,FMCG
52,PAGEIND,0.83,-8.61,46.74,34.11,114644.0,-23099.0,245280.0,51418.64,-34.43,67.0,X-MC,19.16,55.0,-0.20,1.86,16.03,X40,ATH,APPARELS
30,HAPPSTMNDS,-1.97,-52.84,291.93,84.85,176466.0,-67717.0,60448.0,1480.71,-43.83,48.0,H-SC,23.24,152.0,-0.38,0.46,11.94,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.20
1     25       46.26
2     50       78.03

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.64
MC    29.50
LC    25.85
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.05
X40      25.47
X40N     15.34
AR        9.15
XR        8.44
XY25      7.06
OX40N     6.68
SR        0.80
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.60
X-MC    22.06
H-SC    21.95
X-SC    12.27
M-SC     9.89
H-MC     5.04
M-MC     2.06
H-LC     1.17
M-LC     1.08
L-SC     0.53
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.11        -25.62   70.22
FINANCE             13.24        -23.28   73.52
IT                  12.20        -40.26  111.64
MISC                 7.10        -43.59  105.96
ELECTRICAL           6.46        -13.96   57.59
PAINTS               5.18        -44.38   69.45
INSURANCE            4.57        -12.64   51.18
BANKS                4.50        -29.99   95.97
PHARMA               4.06        -10.12   44.78
AUTO                 3.65        -36.17   90.19
HEALTHCARE           1.96        -39.29   75.63
AC                   1.88        -28.83   63.77
APPARELS             1.86         -9.42   46.74
FOOTWEAR             1.81        -85.20  159.46
TRAVEL               1.78        -91.28  187.06
DURABLES             1.76        -67.11  107.77
BREWERIES            1.62         -9.95   32.78
CERAMICS             1.36        -71.17  123.18
REALTY               1.34        -25.36   45.96
REFINERIES           1.28        -19.41   49.62
CEMENT               1.22        -66.75  191.49
ENGINEERING          1.20        -52.78  122.65
CABLES               1.15          2.59  102.54
CHEMICALS            1.12        -80.82  228.35
JEWELLERY            1.02       -138.46  221.30
ENTERTAINMENT        0.77        -90.65  204.36
TEXTILES             0.45        -55.17   99.42
HOTELS               0.34       -151.66  240.43

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4038053.0     21
X40       1820229.0     16
XR        1379354.0     12
AR        1367717.0     10
X40N      1281865.0     10
OX40N      912016.0     10
XY25       511824.0      5
SR         314690.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3903499.0     24
X-MC        1830220.0     15
X-LC        1668745.0     13
M-SC        1615758.0     14
X-SC        1568749.0     10
H-MC         416520.0      3
L-SC         220265.0      2
M-LC         149622.0      1
M-MC         114708.0      2
H-LC          79794.0      1
L-MC          57868.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1344798.0      6
           AR         986866.0      5
M-SC       XY24       929895.0      6
X-LC       X40        889734.0      7
H-SC       XR         870989.0      7
X-SC       XY24       857481.0      4
X-MC       X40        707921.0      7
           X40N       564896.0      4
X-SC       X40N       488694.0      4
M-SC       OX40N      414077.0      5
H-SC       OX40N      386156.0      4
X-LC       XY24       386098.0      2
H-SC       SR         314690.0      2
X-MC       XY25       283026.0      2
           XY24       274377.0      2
H-MC       XY24       245404.0      1
X-LC       X40N       228275.0      2
X-SC       X40        222574.0      2
M-SC       XR         192393.0      2
H-MC       AR         171116.0      2
X-LC       XY25       164638.0      2
M-LC       XR         149622.0      1
L-SC       OX40N      111783.0      1
           XR         108482.0      1
H-LC       AR          79794.0      1
M-SC       AR          79393.0      1
M-MC       XY25        64160.0      1
L-MC       XR          57868.0      1
M-MC       AR          50548.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 43.0 seconds