<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-10 12:39:45
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15

-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.37 C
-------------------
Today PnL: 1.26 L (0.93%)
Current PnL: -40.37 L (-24.85%)
CY Booked + Current PnL: -24.69 L (-15.2%)
-------------------
Total profit:  1.13 L
Total loss:  -41.51 L
-------------------
Total Booked + Current PnL: 2.29 L (1.69%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.48%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.11 C (81.09%)
===================
Deployed:  1.36 C
Current:  1.37 C
CAGR/XIRR %: 0.39%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.66,8.34,8.62,17.67,14051.0,12544.0,163004.0,478.51,30.56,58.0,L-LC,11.49,185.0,0.89,1.20,26.58,XY25,ATH,MINING
50,MASFIN,1.69,-6.20,29.60,21.57,27204.0,-6075.0,91905.0,397.04,-19.15,40.0,H-SC,5.05,167.0,-0.22,0.68,28.24,XR,ATH,FINANCE
37,ICICIGI,0.24,0.34,18.93,19.34,38011.0,687.0,200796.0,2252.93,-15.67,49.0,X-MC,1.59,66.0,0.02,1.48,14.52,X40,ATH,INSURANCE
77,TTKPRESTIG,5.96,-37.77,60.84,0.09,38156.0,-38061.0,62716.0,770.00,45.57,31.0,M-SC,14.95,250.0,-1.00,0.46,5.97,OX40N,NTT,DURABLES
78,UNITDSPR,3.12,2.70,17.59,20.77,42299.0,6329.0,240473.0,1644.00,-8.94,53.0,X-MC,1.52,64.0,0.15,1.77,9.59,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,5.96,-37.77,60.84,0.09,38156.0,-38061.0,62716.0,770.00,45.57,31.0,M-SC,14.95,250.0,-1.00,0.46,5.97,OX40N,NTT,DURABLES
15,BSOFT,4.19,-30.38,116.59,50.79,114165.0,-42733.0,97920.0,831.70,-10.71,46.0,H-SC,5.01,172.0,-0.37,0.72,14.01,XR,ATH,IT
26,EASEMYTRIP,3.61,-58.77,253.41,45.70,184716.0,-103923.0,72892.0,26.40,-24.39,45.0,M-SC,18.16,204.0,-0.56,0.54,20.10,XY24,NTT,TRAVEL
11,BANDHANBNK,3.43,-13.36,122.10,92.42,294669.0,-37225.0,241334.0,400.00,106.90,60.0,H-SC,9.95,174.0,-0.13,1.78,32.94,XY24,NTT,BANKS
33,HAVELLS,3.35,-11.90,49.92,32.08,144249.0,-39031.0,288960.0,2062.85,-17.09,50.0,X-MC,6.03,63.0,-0.27,2.13,8.01,X40,ATH,ELECTRICAL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-2.61,-78.75,370.91,0.07,108120.0,-108027.0,29150.0,518.00,968.18,17.0,L-SC,16.82,268.0,-1.00,0.21,0.00,OX40N,NTT,JEWELLERY
54,QUESS,-2.47,-24.09,129.09,73.90,104647.0,-25728.0,81065.0,424.00,-59.23,32.0,X-SC,17.67,80.0,-0.25,0.60,0.00,XY24,NTT,MISC
24,DIXON,-2.24,-28.57,93.10,37.92,173423.0,-74522.0,186276.0,18931.72,-69.68,32.0,X-MC,25.20,54.0,-0.43,1.37,0.00,X40N,ATH,IT
43,INFY,-2.05,-12.32,53.11,34.24,145704.0,-38544.0,274344.0,1972.00,-31.06,28.0,X-LC,11.48,3.0,-0.26,2.02,0.98,X40,NTT,IT
73,TCS,-1.24,-26.73,72.74,26.57,246920.0,-123817.0,339456.0,4311.59,-38.05,23.0,X-LC,13.12,2.0,-0.50,2.50,0.00,X40,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.11,21.77,70.75,107.91,127196.0,32138.0,179782.0,1641.55,9.59,70.0,M-SC,7.77,220.0,0.25,1.32,35.26,OX40N,ATH,CABLES
66,SIS,0.73,-33.80,83.17,21.26,61133.0,-37528.0,73504.0,528.00,1721.24,34.0,H-SC,9.21,168.0,-0.61,0.54,1.33,OX40N,NTT,MISC
77,TTKPRESTIG,5.96,-37.77,60.84,0.09,38156.0,-38061.0,62716.0,770.00,45.57,31.0,M-SC,14.95,250.0,-1.00,0.46,5.97,OX40N,NTT,DURABLES
72,TATAELXSI,-0.27,-38.14,113.44,32.03,92508.0,-50287.0,81548.0,9161.00,-22.55,26.0,H-SC,15.85,158.0,-0.54,0.60,0.00,OX40N,NTT,IT
48,KANSAINER,-0.13,-38.23,83.69,13.47,139412.0,-103086.0,166581.0,340.00,-46.84,23.0,H-SC,16.18,162.0,-0.74,1.23,0.00,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.11,21.77,70.75,107.91,127196.0,32138.0,179782.0,1641.55,9.59,70.0,M-SC,7.77,220.0,0.25,1.32,35.26,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.66,8.34,8.62,17.67,14051.0,12544.0,163004.0,478.51,30.56,58.0,L-LC,11.49,185.0,0.89,1.20,26.58,XY25,ATH,MINING
27,FINCABLES,-0.11,21.77,70.75,107.91,127196.0,32138.0,179782.0,1641.55,9.59,70.0,M-SC,7.77,220.0,0.25,1.32,35.26,OX40N,ATH,CABLES
1,ABB,3.18,13.26,28.53,45.57,84536.0,34685.0,296304.0,7934.00,-27.18,63.0,H-MC,9.67,125.0,0.41,2.18,31.58,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,3.18,13.26,28.53,45.57,84536.0,34685.0,296304.0,7934.00,-27.18,63.0,H-MC,9.67,125.0,0.41,2.18,31.58,AR,NTT,ELECTRICAL
27,FINCABLES,-0.11,21.77,70.75,107.91,127196.0,32138.0,179782.0,1641.55,9.59,70.0,M-SC,7.77,220.0,0.25,1.32,35.26,OX40N,ATH,CABLES
40,INDIAMART,-0.86,-6.97,122.22,106.72,140228.0,-8602.0,114734.0,4810.62,-58.01,48.0,H-SC,9.02,140.0,-0.06,0.84,14.77,AR,ATH,MISC
85,ZYDUSLIFE,1.00,-3.21,40.12,35.63,81386.0,-6718.0,202856.0,1286.17,-15.77,54.0,H-MC,5.10,120.0,-0.08,1.49,12.93,AR,ATH,PHARMA
84,WIPRO,-0.32,-18.74,111.99,72.27,154202.0,-31755.0,137693.0,420.00,-26.90,27.0,M-LC,13.93,98.0,-0.21,1.01,1.39,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,0.77,-39.06,174.09,67.02,377981.0,-139191.0,217118.0,485.0,-67.16,16.0,X-SC,22.46,81.0,-0.37,1.60,0.77,XY24,NTT,FMCG
12,BATAINDIA,-0.45,-53.92,193.41,35.20,114675.0,-69379.0,59291.0,2096.0,-22.31,20.0,X-SC,24.77,91.0,-0.61,0.44,0.00,X40,NTT,FOOTWEAR
58,RELAXO,-0.34,-59.86,279.42,52.31,162821.0,-86889.0,58271.0,1176.0,-57.22,20.0,X-SC,18.10,92.0,-0.53,0.43,0.00,X40N,NTT,FOOTWEAR
46,JIOFIN,0.06,-22.88,66.52,28.43,153047.0,-68251.0,230076.0,387.0,-24.04,22.0,X-LC,14.48,34.0,-0.45,1.69,9.01,XY24,BTT,FINANCE
3,ACC,1.34,-34.21,165.71,74.81,292312.0,-91728.0,176400.0,3906.0,-53.43,23.0,X-SC,11.67,85.0,-0.31,1.30,1.34,XY24,BTT,CEMENT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,2.46,-6.51,53.70,43.70,124545.0,-16141.0,231927.0,735.00,-15.22,36.0,X-MC,0.92,70.0,-0.13,1.71,7.56,XY24,BTT,FMCG
78,UNITDSPR,3.12,2.70,17.59,20.77,42299.0,6329.0,240473.0,1644.00,-8.94,53.0,X-MC,1.52,64.0,0.15,1.77,9.59,X40N,NTT,BREWERIES
37,ICICIGI,0.24,0.34,18.93,19.34,38011.0,687.0,200796.0,2252.93,-15.67,49.0,X-MC,1.59,66.0,0.02,1.48,14.52,X40,ATH,INSURANCE
59,RELIANCE,1.37,-8.59,37.08,25.30,68114.0,-17267.0,183696.0,1952.00,-10.80,51.0,X-LC,2.06,21.0,-0.25,1.35,22.65,XY25,BTT,REFINERIES
75,TMPV,2.21,-22.75,76.81,36.58,211131.0,-80967.0,274874.0,600.00,-83.62,36.0,X-LC,2.27,4.0,-0.38,2.02,2.21,XY24,NTT,AUTO

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BAJAJHLDNG,-1.01,-9.28,42.44,29.22,73201.0,-17643.0,172482.0,14451.52,-15.85,29.0,X-LC,11.96,28.0,-0.24,1.27,0.0,X40,ATH,FINANCE
12,BATAINDIA,-0.45,-53.92,193.41,35.20,114675.0,-69379.0,59291.0,2096.00,-22.31,20.0,X-SC,24.77,91.0,-0.61,0.44,0.0,X40,NTT,FOOTWEAR
24,DIXON,-2.24,-28.57,93.10,37.92,173423.0,-74522.0,186276.0,18931.72,-69.68,32.0,X-MC,25.20,54.0,-0.43,1.37,0.0,X40N,ATH,IT
54,QUESS,-2.47,-24.09,129.09,73.90,104647.0,-25728.0,81065.0,424.00,-59.23,32.0,X-SC,17.67,80.0,-0.25,0.60,0.0,XY24,NTT,MISC
58,RELAXO,-0.34,-59.86,279.42,52.31,162821.0,-86889.0,58271.0,1176.00,-57.22,20.0,X-SC,18.10,92.0,-0.53,0.43,0.0,X40N,NTT,FOOTWEAR

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.34,-59.86,279.42,52.31,162821.0,-86889.0,58271.0,1176.00,-57.22,20.0,X-SC,18.10,92.0,-0.53,0.43,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-0.45,-53.92,193.41,35.20,114675.0,-69379.0,59291.0,2096.00,-22.31,20.0,X-SC,24.77,91.0,-0.61,0.44,0.00,X40,NTT,FOOTWEAR
54,QUESS,-2.47,-24.09,129.09,73.90,104647.0,-25728.0,81065.0,424.00,-59.23,32.0,X-SC,17.67,80.0,-0.25,0.60,0.00,XY24,NTT,MISC
36,HONAUT,2.91,-20.75,90.93,51.31,138964.0,-40013.0,152825.0,58357.33,-34.10,42.0,X-SC,13.52,90.0,-0.29,1.12,2.91,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,-0.90,-9.63,30.64,18.07,49526.0,-17215.0,161640.0,35195.00,-23.01,48.0,X-MC,11.13,58.0,-0.35,1.19,2.47,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.38,-19.10,47.16,19.06,129787.0,-64960.0,275206.0,452.00,-55.52,35.0,X-LC,16.95,1.0,-0.50,2.03,0.38,X40,NTT,FMCG
73,TCS,-1.24,-26.73,72.74,26.57,246920.0,-123817.0,339456.0,4311.59,-38.05,23.0,X-LC,13.12,2.0,-0.50,2.50,0.00,X40,ATH,IT
43,INFY,-2.05,-12.32,53.11,34.24,145704.0,-38544.0,274344.0,1972.00,-31.06,28.0,X-LC,11.48,3.0,-0.26,2.02,0.98,X40,NTT,IT
75,TMPV,2.21,-22.75,76.81,36.58,211131.0,-80967.0,274874.0,600.00,-83.62,36.0,X-LC,2.27,4.0,-0.38,2.02,2.21,XY24,NTT,AUTO
34,HCLTECH,-0.52,-12.29,41.19,23.83,87399.0,-29738.0,212186.0,1908.19,-7.78,27.0,X-LC,9.13,8.0,-0.34,1.56,1.80,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,1.19,-34.17,101.87,32.89,51774.0,-26382.0,50824.0,1800.00,-339.50,41.0,L-MC,11.54,258.0,-0.51,0.37,39.97,XR,NTT,BANKS
67,SONACOMS,0.61,-12.85,59.61,39.09,52550.0,-13003.0,88156.0,804.02,-31.00,45.0,M-MC,10.20,193.0,-0.25,0.65,24.71,AR,ATH,AUTO
19,COALINDIA,0.66,8.34,8.62,17.67,14051.0,12544.0,163004.0,478.51,30.56,58.0,L-LC,11.49,185.0,0.89,1.20,26.58,XY25,ATH,MINING
27,FINCABLES,-0.11,21.77,70.75,107.91,127196.0,32138.0,179782.0,1641.55,9.59,70.0,M-SC,7.77,220.0,0.25,1.32,35.26,OX40N,ATH,CABLES
82,VOLTAS,0.95,13.44,27.99,45.20,60882.0,25773.0,217515.0,1856.00,29.81,46.0,X-MC,9.74,79.0,0.42,1.60,21.15,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.11,21.77,70.75,107.91,127196.0,32138.0,179782.0,1641.55,9.59,70.0,M-SC,7.77,220.0,0.25,1.32,35.26,OX40N,ATH,CABLES
11,BANDHANBNK,3.43,-13.36,122.10,92.42,294669.0,-37225.0,241334.0,400.00,106.90,60.0,H-SC,9.95,174.0,-0.13,1.78,32.94,XY24,NTT,BANKS
26,EASEMYTRIP,3.61,-58.77,253.41,45.70,184716.0,-103923.0,72892.0,26.40,-24.39,45.0,M-SC,18.16,204.0,-0.56,0.54,20.10,XY24,NTT,TRAVEL
65,SIEMENS,2.19,-11.35,41.58,25.51,68599.0,-21115.0,164980.0,4671.50,38.57,55.0,H-LC,3.57,51.0,-0.31,1.21,21.49,AR,ATH,ELECTRICAL
1,ABB,3.18,13.26,28.53,45.57,84536.0,34685.0,296304.0,7934.00,-27.18,63.0,H-MC,9.67,125.0,0.41,2.18,31.58,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.62
1     25       45.51
2     50       77.99

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.56
MC    30.50
LC    24.94
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.27
X40      23.92
X40N     15.12
AR        9.08
XY25      8.70
XR        8.25
OX40N     6.89
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.16
H-SC    21.57
X-LC    21.52
X-SC    12.20
M-SC    10.20
H-MC     4.98
M-MC     1.99
H-LC     1.21
L-LC     1.20
M-LC     1.01
L-SC     0.59
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.42        -19.33   61.70
FINANCE             12.79        -23.69   74.09
IT                  11.52        -43.90  117.13
MISC                 6.93        -42.25  104.05
ELECTRICAL           6.64         -7.25   48.32
PAINTS               5.21        -39.18   63.35
INSURANCE            4.75         -5.02   40.96
PHARMA               4.15         -4.05   36.80
AUTO                 3.74        -28.71   79.77
BANKS                3.15        -24.99  100.73
AC                   2.15         -9.23   38.84
HEALTHCARE           1.97        -33.38   68.19
FOOTWEAR             1.86        -74.79  144.88
TRAVEL               1.85        -78.09  167.26
DURABLES             1.80        -57.49   95.80
BREWERIES            1.77          2.63   17.59
APPARELS             1.61        -22.81   64.70
REALTY               1.46        -11.62   29.96
REFINERIES           1.35         -9.40   37.08
CERAMICS             1.33        -70.28  122.01
CABLES               1.32         17.88   70.75
CEMENT               1.30        -52.00  165.71
MINING               1.20          7.70    8.62
ENGINEERING          1.10        -61.63  135.56
JEWELLERY            1.10       -113.97  188.32
CHEMICALS            0.96       -103.32  269.21
ENTERTAINMENT        0.77        -85.70  196.46
TEXTILES             0.42        -61.69  107.79
HOTELS               0.38       -122.75  201.32

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3891595.0     21
X40       1624635.0     15
XR        1370713.0     12
AR        1337878.0     10
X40N      1245183.0     10
OX40N      853846.0     10
XY25       434338.0      6
SR         314935.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3864470.0     24
X-MC        1587053.0     15
X-LC        1549542.0     12
M-SC        1530021.0     14
X-SC        1525725.0     10
H-MC         401335.0      3
L-SC         210745.0      2
M-LC         154202.0      1
M-MC         115606.0      2
H-LC          68599.0      1
L-MC          51774.0      1
L-LC          14051.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1315543.0      6
           AR         974294.0      5
M-SC       XY24       905368.0      6
H-SC       XR         872412.0      7
X-SC       XY24       831600.0      4
X-LC       X40        805726.0      6
X-MC       X40        620258.0      7
           X40N       512471.0      4
X-SC       X40N       495474.0      4
H-SC       OX40N      387286.0      4
X-LC       XY24       364178.0      2
M-SC       OX40N      358440.0      5
H-SC       SR         314935.0      2
X-MC       XY24       239493.0      2
X-LC       X40N       237238.0      2
H-MC       XY24       235413.0      1
X-MC       XY25       214831.0      2
X-SC       X40        198651.0      2
M-SC       XR         189700.0      2
H-MC       AR         165922.0      2
M-LC       XR         154202.0      1
X-LC       XY25       142400.0      2
L-SC       OX40N      108120.0      1
           XR         102625.0      1
M-SC       AR          76513.0      1
H-LC       AR          68599.0      1
M-MC       XY25        63056.0      1
           AR          52550.0      1
L-MC       XR          51774.0      1
L-LC       XY25        14051.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 35.0 seconds