<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-04 09:39:17
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.33 C
CY Investment:  1.60 C
Reserve:  2.44 L
Current:  1.32 C
-------------------
Today PnL: -2.45 L (-1.82%)
Current PnL: -42.49 L (-26.56%)
CY Booked + Current PnL: -26.81 L (-16.76%)
-------------------
Total profit:  89.22 K
Total loss:  -43.38 L
-------------------
Total Booked + Current PnL: 17.24 K (0.13%)
Total Booked PnL: 42.66 L (32.07%)
Curr Year Booked PnL: 15.68 L (11.88%)
Prev Year Booked PnL: 26.98 L (20.29%)
===================
Est FTT:  2.41 C
Est FTT PnL: 1.09 C (82.68%)
===================
Deployed:  1.33 C
Current:  1.32 C
CAGR/XIRR %: -0.4%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.76,6.66,10.32,17.67,16562.0,10028.0,160488.0,478.51,29.12,57.0,L-LC,10.99,185.0,0.61,1.24,27.59,XY25,ATH,MINING
50,MASFIN,-2.65,-6.00,29.33,21.57,27013.0,-5880.0,92100.0,397.04,-19.15,37.0,H-SC,6.53,167.0,-0.22,0.71,33.38,XR,ATH,FINANCE
77,TTKPRESTIG,-3.01,-36.82,58.42,0.09,37198.0,-37104.0,63673.0,770.00,47.71,22.0,M-SC,12.51,250.0,-1.00,0.49,0.00,OX40N,NTT,DURABLES
37,ICICIGI,-1.24,-0.84,20.35,19.34,40381.0,-1677.0,198432.0,2252.93,-16.65,43.0,X-MC,1.29,66.0,-0.04,1.53,14.97,X40,ATH,INSURANCE
51,MEDANTA,-2.67,-8.17,35.12,24.08,40943.0,-10371.0,116579.0,1486.00,-8.85,42.0,X-SC,8.05,87.0,-0.25,0.90,6.78,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
43,INFY,1.81,-10.67,50.28,34.24,140532.0,-33389.0,279499.0,1972.00,-29.61,30.0,X-LC,10.08,3.0,-0.24,2.16,2.88,X40,NTT,IT
19,COALINDIA,1.76,6.66,10.32,17.67,16562.0,10028.0,160488.0,478.51,29.12,57.0,L-LC,10.99,185.0,0.61,1.24,27.59,XY25,ATH,MINING
34,HCLTECH,0.11,-10.93,39.03,23.83,84103.0,-26442.0,215482.0,1908.19,-6.53,29.0,X-LC,7.41,8.0,-0.31,1.66,3.38,X40,ATH,IT
73,TCS,0.11,-25.01,64.78,23.58,210176.0,-108183.0,324446.0,4311.59,-35.10,30.0,X-LC,10.76,2.0,-0.51,2.51,1.66,X40,ATH,IT
45,ITC,-0.51,-17.48,44.27,19.06,124273.0,-59449.0,280717.0,452.00,-54.71,39.0,X-LC,16.87,1.0,-0.48,2.17,1.64,X40,NTT,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,RAJESHEXPO,-4.96,-74.55,293.17,0.07,102357.0,-102263.0,34914.0,518.00,1179.04,24.0,L-SC,11.11,268.0,-1.00,0.27,0.00,OX40N,NTT,JEWELLERY
82,VOLTAS,-3.71,12.93,28.58,45.20,61883.0,24783.0,216525.0,1856.00,29.27,44.0,X-MC,9.83,79.0,0.40,1.67,20.60,XY25,NTT,AC
67,SONACOMS,-3.65,-13.79,61.34,39.09,53495.0,-13948.0,87211.0,804.02,-31.68,41.0,M-MC,10.91,193.0,-0.26,0.67,23.38,AR,ATH,AUTO
26,EASEMYTRIP,-3.63,-57.51,242.86,45.70,182478.0,-101678.0,75137.0,26.40,-21.95,47.0,M-SC,18.06,204.0,-0.56,0.58,23.79,XY24,NTT,TRAVEL
59,RELIANCE,-3.62,-15.99,49.14,25.30,82966.0,-32128.0,168835.0,1952.00,-18.11,27.0,X-LC,2.26,21.0,-0.39,1.30,13.09,XY25,BTT,REFINERIES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-3.12,16.13,79.03,107.91,135505.0,23816.0,171460.0,1641.55,4.52,69.0,M-SC,6.36,220.0,0.18,1.32,29.00,OX40N,ATH,CABLES
66,SIS,-2.21,-31.56,77.18,21.26,58649.0,-35042.0,75990.0,528.00,1782.90,37.0,H-SC,6.47,168.0,-0.60,0.59,4.76,OX40N,NTT,MISC
48,KANSAINER,-1.35,-35.37,75.57,13.47,131707.0,-95382.0,174285.0,340.00,-44.56,29.0,H-SC,14.15,162.0,-0.72,1.35,0.00,XY24,NTT,PAINTS
41,INDIGOPNTS,-1.63,-35.83,55.87,0.02,62579.0,-62550.0,112009.0,1408.00,70.76,21.0,M-SC,13.19,222.0,-1.00,0.86,0.00,OX40N,NTT,PAINTS
77,TTKPRESTIG,-3.01,-36.82,58.42,0.09,37198.0,-37104.0,63673.0,770.00,47.71,22.0,M-SC,12.51,250.0,-1.00,0.49,0.00,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,1.76,6.66,10.32,17.67,16562.0,10028.0,160488.0,478.51,29.12,57.0,L-LC,10.99,185.0,0.61,1.24,27.59,XY25,ATH,MINING
27,FINCABLES,-3.12,16.13,79.03,107.91,135505.0,23816.0,171460.0,1641.55,4.52,69.0,M-SC,6.36,220.0,0.18,1.32,29.00,OX40N,ATH,CABLES
1,ABB,-1.88,7.71,35.15,45.57,99047.0,20165.0,281784.0,7934.00,-30.81,55.0,H-MC,8.88,125.0,0.20,2.18,25.13,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.88,7.71,35.15,45.57,99047.0,20165.0,281784.0,7934.00,-30.81,55.0,H-MC,8.88,125.0,0.20,2.18,25.13,AR,NTT,ELECTRICAL
27,FINCABLES,-3.12,16.13,79.03,107.91,135505.0,23816.0,171460.0,1641.55,4.52,69.0,M-SC,6.36,220.0,0.18,1.32,29.00,OX40N,ATH,CABLES
40,INDIAMART,-1.45,-10.49,130.94,106.72,144563.0,-12932.0,110404.0,4810.62,-59.57,33.0,H-SC,8.26,140.0,-0.09,0.85,10.44,AR,ATH,MISC
85,ZYDUSLIFE,-0.72,-5.06,42.85,35.63,85262.0,-10597.0,198977.0,1286.17,-17.57,48.0,H-MC,4.94,120.0,-0.12,1.54,10.77,AR,ATH,PHARMA
84,WIPRO,-1.72,-19.95,115.21,72.27,156266.0,-33812.0,135636.0,420.00,-27.84,20.0,M-LC,11.41,98.0,-0.22,1.05,0.00,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
8,AWL,-0.73,-41.99,170.98,57.19,323463.0,-136945.0,189182.0,485.00,-66.76,13.0,X-SC,19.87,81.0,-0.42,1.46,0.0,XY24,NTT,FMCG
53,PGHH,-1.91,-17.53,60.07,32.01,105781.0,-37424.0,176096.0,17616.87,-44.18,19.0,X-MC,9.86,57.0,-0.35,1.36,0.0,X40,ATH,FMCG
12,BATAINDIA,-2.16,-51.43,178.39,35.20,111478.0,-66179.0,62491.0,2096.00,-18.12,21.0,X-SC,22.93,91.0,-0.59,0.48,0.0,X40,NTT,FOOTWEAR
9,BAJAJHFL,-2.34,-28.66,117.94,55.47,204692.0,-69730.0,173556.0,181.50,-38.88,21.0,X-MC,17.77,60.0,-0.34,1.34,0.0,X40N,ATH,FINANCE
3,ACC,-2.47,-36.34,157.86,64.15,239126.0,-86471.0,151480.0,3906.00,-52.08,22.0,X-SC,9.96,85.0,-0.36,1.17,0.0,XY24,BTT,CEMENT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
37,ICICIGI,-1.24,-0.84,20.35,19.34,40381.0,-1677.0,198432.0,2252.93,-16.65,43.0,X-MC,1.29,66.0,-0.04,1.53,14.97,X40,ATH,INSURANCE
78,UNITDSPR,-1.32,-0.94,21.91,20.77,50818.0,-2202.0,231942.0,1644.00,-12.17,40.0,X-MC,1.42,64.0,-0.04,1.79,6.10,X40N,NTT,BREWERIES
22,DABUR,-2.02,-2.76,47.78,43.70,115253.0,-6853.0,241215.0,735.00,-11.71,39.0,X-MC,1.53,70.0,-0.06,1.86,11.87,XY24,BTT,FMCG
59,RELIANCE,-3.62,-15.99,49.14,25.30,82966.0,-32128.0,168835.0,1952.00,-18.11,27.0,X-LC,2.26,21.0,-0.39,1.30,13.09,XY25,BTT,REFINERIES
35,HINDUNILVR,-0.89,-10.53,27.04,13.67,62192.0,-27063.0,230000.0,2922.00,-33.67,42.0,X-LC,2.53,9.0,-0.44,1.78,8.58,XY25,NTT,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ACC,-2.47,-36.34,157.86,64.15,239126.0,-86471.0,151480.0,3906.00,-52.08,22.0,X-SC,9.96,85.0,-0.36,1.17,0.0,XY24,BTT,CEMENT
12,BATAINDIA,-2.16,-51.43,178.39,35.20,111478.0,-66179.0,62491.0,2096.00,-18.12,21.0,X-SC,22.93,91.0,-0.59,0.48,0.0,X40,NTT,FOOTWEAR
9,BAJAJHFL,-2.34,-28.66,117.94,55.47,204692.0,-69730.0,173556.0,181.50,-38.88,21.0,X-MC,17.77,60.0,-0.34,1.34,0.0,X40N,ATH,FINANCE
8,AWL,-0.73,-41.99,170.98,57.19,323463.0,-136945.0,189182.0,485.00,-66.76,13.0,X-SC,19.87,81.0,-0.42,1.46,0.0,XY24,NTT,FMCG
24,DIXON,-3.15,-31.84,92.57,31.26,145609.0,-73472.0,157296.0,18931.72,-69.52,32.0,X-MC,24.24,54.0,-0.50,1.21,0.0,X40N,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-2.97,-91.01,1281.08,24.20,351669.0,-277799.0,27451.0,3033.0,-86.88,29.0,X-SC,2.67,97.0,-0.79,0.21,14.97,X40N,NTT,FINANCE
54,QUESS,-1.96,-36.65,125.50,42.84,51680.0,-23827.0,41179.0,424.0,-58.68,32.0,X-SC,16.97,80.0,-0.46,0.32,0.00,XY24,NTT,MISC
58,RELAXO,-1.23,-57.78,260.74,52.31,159802.0,-83872.0,61288.0,1176.0,-55.09,25.0,X-SC,15.88,92.0,-0.52,0.47,0.00,X40N,NTT,FOOTWEAR
12,BATAINDIA,-2.16,-51.43,178.39,35.20,111478.0,-66179.0,62491.0,2096.0,-18.12,21.0,X-SC,22.93,91.0,-0.59,0.48,0.00,X40,NTT,FOOTWEAR
51,MEDANTA,-2.67,-8.17,35.12,24.08,40943.0,-10371.0,116579.0,1486.0,-8.85,42.0,X-SC,8.05,87.0,-0.25,0.90,6.78,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.51,-17.48,44.27,19.06,124273.0,-59449.0,280717.0,452.00,-54.71,39.0,X-LC,16.87,1.0,-0.48,2.17,1.64,X40,NTT,FMCG
73,TCS,0.11,-25.01,64.78,23.58,210176.0,-108183.0,324446.0,4311.59,-35.10,30.0,X-LC,10.76,2.0,-0.51,2.51,1.66,X40,ATH,IT
43,INFY,1.81,-10.67,50.28,34.24,140532.0,-33389.0,279499.0,1972.00,-29.61,30.0,X-LC,10.08,3.0,-0.24,2.16,2.88,X40,NTT,IT
75,TMPV,-3.15,-17.64,61.90,33.33,166086.0,-57486.0,268314.0,600.00,-82.53,48.0,X-LC,3.88,4.0,-0.35,2.07,9.69,XY24,NTT,AUTO
34,HCLTECH,0.11,-10.93,39.03,23.83,84103.0,-26442.0,215482.0,1908.19,-6.53,29.0,X-LC,7.41,8.0,-0.31,1.66,3.38,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-1.86,-31.71,94.59,32.89,49873.0,-24482.0,52725.0,1800.00,-347.90,50.0,L-MC,12.17,258.0,-0.49,0.41,45.20,XR,NTT,BANKS
19,COALINDIA,1.76,6.66,10.32,17.67,16562.0,10028.0,160488.0,478.51,29.12,57.0,L-LC,10.99,185.0,0.61,1.24,27.59,XY25,ATH,MINING
27,FINCABLES,-3.12,16.13,79.03,107.91,135505.0,23816.0,171460.0,1641.55,4.52,69.0,M-SC,6.36,220.0,0.18,1.32,29.00,OX40N,ATH,CABLES
82,VOLTAS,-3.71,12.93,28.58,45.20,61883.0,24783.0,216525.0,1856.00,29.27,44.0,X-MC,9.83,79.0,0.40,1.67,20.60,XY25,NTT,AC
11,BANDHANBNK,-1.24,-15.60,127.99,92.42,300908.0,-43456.0,235103.0,400.00,101.87,60.0,H-SC,8.90,174.0,-0.14,1.82,29.51,XY24,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-3.12,16.13,79.03,107.91,135505.0,23816.0,171460.0,1641.55,4.52,69.0,M-SC,6.36,220.0,0.18,1.32,29.00,OX40N,ATH,CABLES
26,EASEMYTRIP,-3.63,-57.51,242.86,45.70,182478.0,-101678.0,75137.0,26.40,-21.95,47.0,M-SC,18.06,204.0,-0.56,0.58,23.79,XY24,NTT,TRAVEL
83,WHIRLPOOL,-2.55,-28.59,154.77,81.92,126868.0,-32826.0,81972.0,2270.00,-58.16,50.0,M-SC,25.86,210.0,-0.26,0.63,15.15,XR,NTT,DURABLES
11,BANDHANBNK,-1.24,-15.60,127.99,92.42,300908.0,-43456.0,235103.0,400.00,101.87,60.0,H-SC,8.90,174.0,-0.14,1.82,29.51,XY24,NTT,BANKS
7,ATULAUTO,-3.41,-20.46,83.00,45.57,130151.0,-40324.0,156808.0,844.00,3391.89,47.0,M-SC,7.25,248.0,-0.31,1.21,18.67,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.96
1     25       46.05
2     50       78.06

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.60
MC    30.79
LC    25.59
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.32
X40      24.58
X40N     12.86
AR        9.32
XY25      9.08
XR        8.64
OX40N     7.34
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.19
H-SC    22.60
X-LC    22.05
M-SC    10.92
X-SC     9.39
H-MC     5.12
M-MC     2.07
H-LC     1.25
L-LC     1.24
M-LC     1.05
L-SC     0.69
L-MC     0.41
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                16.05        -18.74   58.90
IT                  11.81        -43.21  114.98
FINANCE             11.13        -44.93  101.97
MISC                 6.91        -45.24  104.65
ELECTRICAL           6.50        -11.43   52.09
PAINTS               5.09        -39.86   60.64
INSURANCE            5.01         -4.45   40.20
PHARMA               4.31         -5.50   38.71
AUTO                 3.95        -21.81   68.26
BANKS                3.20        -29.38  107.79
AC                   2.25         -9.59   39.31
FOOTWEAR             2.02        -68.16  135.59
TRAVEL               1.98        -74.49  161.86
DURABLES             1.90        -56.81   94.95
BREWERIES            1.79         -0.95   21.91
HEALTHCARE           1.68        -41.60   76.55
REALTY               1.43        -19.43   39.05
APPARELS             1.43        -27.88   66.43
CERAMICS             1.43        -66.01  116.45
CABLES               1.32         13.89   79.03
REFINERIES           1.30        -19.03   49.14
MINING               1.24          6.25   10.32
JEWELLERY            1.22       -103.04  173.58
CEMENT               1.17        -57.08  157.86
ENGINEERING          1.14        -63.79  138.70
CHEMICALS            1.05        -93.91  252.10
ENTERTAINMENT        0.80        -87.30  199.01
TEXTILES             0.45        -58.13  103.22
HOTELS               0.42       -110.09  184.19

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3590150.0     21
X40       1537016.0     15
X40N      1453766.0     10
XR        1373122.0     12
AR        1364057.0     10
OX40N      840652.0     10
XY25       441302.0      6
SR         310176.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3866271.0     24
X-SC        1586054.0     10
X-MC        1507193.0     15
M-SC        1501995.0     14
X-LC        1418140.0     12
H-MC         416782.0      3
L-SC         201908.0      2
M-LC         156266.0      1
M-MC         117425.0      2
H-LC          71772.0      1
L-MC          49873.0      1
L-LC          16562.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1318375.0      6
           AR         977201.0      5
           XR         880344.0      7
M-SC       XY24       879507.0      6
X-LC       X40        732262.0      6
X-SC       X40N       730111.0      4
           XY24       655212.0      4
X-MC       X40        604023.0      7
           X40N       473632.0      4
H-SC       OX40N      380175.0      4
M-SC       OX40N      358120.0      5
H-SC       SR         310176.0      2
X-LC       XY24       290697.0      2
           X40N       250023.0      2
H-MC       XY24       232473.0      1
X-MC       XY25       215652.0      2
           XY24       213886.0      2
X-SC       X40        200731.0      2
M-SC       XR         187088.0      2
H-MC       AR         184309.0      2
M-LC       XR         156266.0      1
X-LC       XY25       145158.0      2
L-SC       OX40N      102357.0      1
           XR          99551.0      1
M-SC       AR          77280.0      1
H-LC       AR          71772.0      1
M-MC       XY25        63930.0      1
           AR          53495.0      1
L-MC       XR          49873.0      1
L-LC       XY25        16562.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 33.0 seconds