<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-21 13:11:08
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -19.10 K (-0.12%)
Current PnL: -34.96 L (-18.5%)
CY Booked + Current PnL: -29.90 L (-15.83%)
-------------------
Total profit:  3.49 L
Total loss:  -38.45 L
-------------------
Total Booked + Current PnL: 12.97 L (8.88%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.06%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.55%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.88,5.16,5.39,10.83,10548.0,9610.0,195705.0,4125.00,-14.70,58.0,H-LC,14.32,51.0,0.91,1.27,38.08,AR,NTT,ELECTRICAL
78,UNITDSPR,2.42,14.66,5.32,20.77,14283.0,34331.0,268475.0,1644.00,-2.19,66.0,X-MC,11.79,64.0,2.40,1.74,29.05,X40N,NTT,BREWERIES
77,TTKPRESTIG,1.77,-22.60,29.31,0.09,22863.0,-22773.0,78004.0,770.00,-5.78,43.0,M-SC,9.46,250.0,-1.00,0.51,40.40,OX40N,NTT,DURABLES
52,M&M,0.10,8.26,9.76,18.82,25430.0,19870.0,260551.0,3762.88,-6.55,59.0,X-LC,5.03,25.0,0.78,1.69,18.19,X40N,ATH,AUTO
67,SIS,1.69,-3.50,25.65,21.26,27484.0,-3881.0,107151.0,528.00,105.79,44.0,H-SC,20.13,168.0,-0.14,0.69,59.32,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SURYODAY,4.61,-9.59,36.09,23.03,58428.0,-17177.0,161894.0,216.00,-25.86,43.0,H-SC,15.27,166.0,-0.29,1.05,37.42,XR,NTT,BANKS
3,ALKYLAMINE,3.93,-13.41,122.37,92.54,106975.0,-13544.0,87419.0,4520.85,NaN,67.0,NaN,15.18,142.0,-0.13,0.57,66.00,SR,ATH,CHEMICALS
21,DEN,3.51,-46.32,164.64,42.07,74654.0,-39120.0,45344.0,75.00,NaN,57.0,NaN,5.34,235.0,-0.52,0.29,23.32,AR,NTT,ENTERTAINMENT
30,HAPPSTMNDS,3.51,-46.97,245.23,83.08,166678.0,-60197.0,67968.0,1466.54,NaN,64.0,NaN,7.22,152.0,-0.36,0.44,27.31,AR,ATH,IT
31,HATHWAY,3.45,-40.45,191.01,73.29,123660.0,-43980.0,64740.0,31.40,NaN,49.0,NaN,2.75,171.0,-0.36,0.42,21.65,XR,NTT,ENTERTAINMENT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,-4.68,-26.39,53.39,12.90,85865.0,-57670.0,160826.0,593.00,3.20,56.0,H-SC,11.56,170.0,-0.67,1.04,55.20,OX40N,NTT,FINANCE
51,LAOPALA,-4.25,-47.69,165.90,39.09,113771.0,-62527.0,68578.0,464.00,NaN,38.0,NaN,3.21,154.0,-0.55,0.44,9.32,AR,NTT,CERAMICS
27,GLAXO,-3.79,17.12,15.86,35.69,37017.0,34116.0,233400.0,3380.16,-12.14,71.0,X-MC,10.66,56.0,0.92,1.51,38.72,X40,ATH,PHARMA
81,VALIANTORG,-3.33,-36.41,173.86,74.15,180884.0,-59565.0,104040.0,838.00,NaN,55.0,NaN,8.79,145.0,-0.33,0.67,54.83,XR,NTT,CHEMICALS
57,RAJESHEXPO,-3.01,-84.83,559.79,0.07,116464.0,-116372.0,20805.0,518.00,NaN,32.0,NaN,36.88,268.0,-1.00,0.13,2.75,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.95,60.35,29.66,107.91,70220.0,89107.0,236751.0,1641.55,16.85,66.0,M-SC,22.47,220.0,1.27,1.53,78.12,OX40N,ATH,CABLES
67,SIS,1.69,-3.50,25.65,21.26,27484.0,-3881.0,107151.0,528.00,105.79,44.0,H-SC,20.13,168.0,-0.14,0.69,59.32,OX40N,NTT,MISC
43,INDIGOPNTS,0.32,-18.13,22.17,0.02,31683.0,-31649.0,142910.0,1408.00,-21.90,63.0,M-SC,7.85,222.0,-1.00,0.93,62.14,OX40N,NTT,PAINTS
77,TTKPRESTIG,1.77,-22.60,29.31,0.09,22863.0,-22773.0,78004.0,770.00,-5.78,43.0,M-SC,9.46,250.0,-1.00,0.51,40.40,OX40N,NTT,DURABLES
12,BOSCH-HCIL,-1.14,-23.24,30.27,-0.01,29695.0,-29704.0,98101.0,2282.00,767.99,75.0,M-SC,10.76,231.0,-1.00,0.64,66.98,OX40N,BTT,AC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.95,60.35,29.66,107.91,70220.0,89107.0,236751.0,1641.55,16.85,66.0,M-SC,22.47,220.0,1.27,1.53,78.12,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.95,60.35,29.66,107.91,70220.0,89107.0,236751.0,1641.55,16.85,66.0,M-SC,22.47,220.0,1.27,1.53,78.12,OX40N,ATH,CABLES
68,STARHEALTH,-1.64,10.93,32.75,47.26,102130.0,30725.0,311848.0,761.00,-2.33,43.0,H-SC,16.00,173.0,0.30,2.02,34.83,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.95,60.35,29.66,107.91,70220.0,89107.0,236751.0,1641.55,16.85,66.0,M-SC,22.47,220.0,1.27,1.53,78.12,OX40N,ATH,CABLES
3,ALKYLAMINE,3.93,-13.41,122.37,92.54,106975.0,-13544.0,87419.0,4520.85,NaN,67.0,NaN,15.18,142.0,-0.13,0.57,66.00,SR,ATH,CHEMICALS
67,SIS,1.69,-3.50,25.65,21.26,27484.0,-3881.0,107151.0,528.00,105.79,44.0,H-SC,20.13,168.0,-0.14,0.69,59.32,OX40N,NTT,MISC
42,INDIAMART,0.61,-25.02,167.96,100.92,155329.0,-30856.0,92480.0,4675.60,NaN,37.0,NaN,13.69,140.0,-0.20,0.60,0.61,AR,ATH,MISC
71,TANLA,0.13,-35.18,235.16,117.25,412720.0,-95255.0,175506.0,1922.32,NaN,46.0,NaN,15.01,147.0,-0.23,1.14,53.66,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.49,-38.56,114.87,32.01,150691.0,-82336.0,131184.0,17616.87,-54.78,26.0,X-SC,19.44,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
55,PAGEIND,0.65,-7.49,43.60,32.85,108254.0,-20089.0,248290.0,50936.07,-31.21,30.0,X-MC,8.71,55.0,-0.19,1.61,18.56,X40,ATH,APPARELS
19,COLPAL,-1.15,-28.31,95.10,39.86,179549.0,-74565.0,188800.0,3683.41,-13.17,31.0,X-MC,2.32,62.0,-0.42,1.22,6.80,XY25,ATH,FMCG
20,DABUR,-0.45,-22.15,84.58,43.70,163347.0,-54941.0,193127.0,735.00,-32.86,32.0,X-MC,10.35,70.0,-0.34,1.25,0.00,XY24,BTT,FMCG
1,ABBOTINDIA,-0.46,-12.78,32.27,15.37,50341.0,-22855.0,156000.0,34390.26,-29.03,32.0,X-MC,2.88,58.0,-0.45,1.01,5.67,X40,ATH,PHARMA

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KOTAKBANK,1.55,6.05,12.13,18.92,30835.0,14503.0,254205.0,452.46,-10.12,63.0,X-LC,2.09,12.0,0.47,1.65,14.37,X40,ATH,BANKS
19,COLPAL,-1.15,-28.31,95.10,39.86,179549.0,-74565.0,188800.0,3683.41,-13.17,31.0,X-MC,2.32,62.0,-0.42,1.22,6.80,XY25,ATH,FMCG
23,DMART,-2.02,-5.30,38.78,31.42,114502.0,-16530.0,295260.0,5391.45,-20.63,39.0,X-LC,2.46,14.0,-0.14,1.91,6.55,X40N,ATH,FMCG
1,ABBOTINDIA,-0.46,-12.78,32.27,15.37,50341.0,-22855.0,156000.0,34390.26,-29.03,32.0,X-MC,2.88,58.0,-0.45,1.01,5.67,X40,ATH,PHARMA
26,GILLETTE,0.20,-11.14,46.00,29.72,103776.0,-28296.0,225600.0,10978.86,-35.84,37.0,X-SC,3.74,83.0,-0.27,1.46,3.67,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.45,-22.15,84.58,43.70,163347.0,-54941.0,193127.0,735.00,-32.86,32.0,X-MC,10.35,70.0,-0.34,1.25,0.00,XY24,BTT,FMCG
56,PGHH,-0.49,-38.56,114.87,32.01,150691.0,-82336.0,131184.0,17616.87,-54.78,26.0,X-SC,19.44,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
36,HINDUNILVR,0.06,-15.88,44.52,21.56,126021.0,-53451.0,283066.0,2922.00,-41.98,37.0,X-LC,6.63,9.0,-0.42,1.83,0.06,XY25,NTT,FMCG
83,VOLTAS,0.29,-4.32,51.76,45.20,94954.0,-8292.0,183450.0,1856.00,31.81,35.0,X-MC,5.11,79.0,-0.09,1.19,0.54,XY25,NTT,AC
47,ITC,-0.72,-25.60,67.59,24.70,199790.0,-101687.0,295591.0,452.00,-30.75,36.0,X-LC,10.48,1.0,-0.51,1.92,0.99,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.49,-38.56,114.87,32.01,150691.0,-82336.0,131184.0,17616.87,-54.78,26.0,X-SC,19.44,57.0,-0.55,0.85,0.00,X40,ATH,FMCG
1,ABBOTINDIA,-0.46,-12.78,32.27,15.37,50341.0,-22855.0,156000.0,34390.26,-29.03,32.0,X-MC,2.88,58.0,-0.45,1.01,5.67,X40,ATH,PHARMA
2,ACC,1.64,-41.38,198.21,74.81,311539.0,-110952.0,157176.0,3906.00,-41.79,41.0,X-SC,11.33,85.0,-0.36,1.02,5.00,XY24,BTT,CEMENT
40,ICICIPRULI,3.31,-14.61,52.56,30.28,88423.0,-28773.0,168232.0,787.27,-45.28,57.0,X-MC,12.16,78.0,-0.33,1.09,12.09,X40,ATH,INSURANCE
39,ICICIGI,0.22,-14.23,38.61,18.89,66268.0,-28474.0,171635.0,2244.41,-14.59,41.0,X-MC,10.04,66.0,-0.43,1.11,2.25,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.72,-25.60,67.59,24.70,199790.0,-101687.0,295591.0,452.00,-30.75,36.0,X-LC,10.48,1.0,-0.51,1.92,0.99,X40,NTT,FMCG
73,TCS,0.24,-32.38,83.66,24.20,262087.0,-149997.0,313276.0,4230.71,-43.98,48.0,X-LC,13.65,2.0,-0.57,2.03,16.82,X40,ATH,IT
45,INFY,-0.11,-19.65,74.71,40.38,225992.0,-73978.0,302492.0,1972.00,-40.86,49.0,X-LC,15.60,3.0,-0.33,1.96,14.55,X40,NTT,IT
75,TMPV,-0.87,-24.47,89.01,42.75,279737.0,-101831.0,314276.0,600.00,-84.91,33.0,X-LC,4.41,4.0,-0.36,2.04,8.06,XY24,NTT,AUTO
33,HCLTECH,-0.87,-12.16,41.13,23.97,111813.0,-37633.0,271853.0,1853.42,-14.26,53.0,X-LC,10.70,8.0,-0.34,1.76,28.28,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.56,-25.99,79.57,32.89,45464.0,-20070.0,57137.0,1800.00,320.94,47.0,L-MC,12.15,258.0,-0.44,0.37,40.87,XR,NTT,BANKS
30,HAPPSTMNDS,3.51,-46.97,245.23,83.08,166678.0,-60197.0,67968.0,1466.54,NaN,64.0,NaN,7.22,152.0,-0.36,0.44,27.31,AR,ATH,IT
3,ALKYLAMINE,3.93,-13.41,122.37,92.54,106975.0,-13544.0,87419.0,4520.85,NaN,67.0,NaN,15.18,142.0,-0.13,0.57,66.00,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-1.14,-23.24,30.27,-0.01,29695.0,-29704.0,98101.0,2282.00,767.99,75.0,M-SC,10.76,231.0,-1.00,0.64,66.98,OX40N,BTT,AC
81,VALIANTORG,-3.33,-36.41,173.86,74.15,180884.0,-59565.0,104040.0,838.00,NaN,55.0,NaN,8.79,145.0,-0.33,0.67,54.83,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-1.14,-23.24,30.27,-0.01,29695.0,-29704.0,98101.0,2282.00,767.99,75.0,M-SC,10.76,231.0,-1.00,0.64,66.98,OX40N,BTT,AC
25,FINCABLES,-1.95,60.35,29.66,107.91,70220.0,89107.0,236751.0,1641.55,16.85,66.0,M-SC,22.47,220.0,1.27,1.53,78.12,OX40N,ATH,CABLES
27,GLAXO,-3.79,17.12,15.86,35.69,37017.0,34116.0,233400.0,3380.16,-12.14,71.0,X-MC,10.66,56.0,0.92,1.51,38.72,X40,ATH,PHARMA
38,HYUNDAI,2.34,15.11,25.04,43.94,72441.0,37970.0,289302.0,2782.73,19.16,66.0,X-LC,5.69,29.0,0.52,1.87,32.83,X40N,ATH,AUTO
81,VALIANTORG,-3.33,-36.41,173.86,74.15,180884.0,-59565.0,104040.0,838.00,NaN,55.0,NaN,8.79,145.0,-0.33,0.67,54.83,XR,NTT,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.62
1     25       44.98
2     50       77.55

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.04
MC    22.16
SC    21.63
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.73
XY24     23.97
X40N     18.69
XR        9.14
OX40N     7.32
XY25      7.14
AR        6.09
SR        0.90
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.37
X-MC    19.60
H-SC     8.56
X-SC     7.65
M-SC     5.42
H-LC     2.85
M-MC     1.17
H-MC     1.02
M-LC     0.82
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.33        -25.98   71.27
IT                  11.26        -37.22  105.27
FINANCE             10.73        -16.49   66.68
AUTO                 8.26         -6.18   44.21
BANKS                6.30         -9.97   57.40
MISC                 5.95        -34.37   88.41
PHARMA               5.79          7.21   19.10
INSURANCE            5.75         -4.61   41.60
PAINTS               5.46        -17.11   37.09
ELECTRICAL           4.19         -9.54   43.84
AC                   1.83        -13.50   44.27
BREWERIES            1.74         12.79    5.32
REFINERIES           1.73        -11.41   48.84
FOOTWEAR             1.68        -69.99  138.14
APPARELS             1.61         -8.09   43.60
CABLES               1.53         37.64   29.66
DURABLES             1.49        -68.69  109.73
TRAVEL               1.42       -104.44  206.81
CERAMICS             1.31        -50.88   96.71
ENGINEERING          1.25        -25.29   82.60
CHEMICALS            1.24        -38.19  150.35
CEMENT               1.02        -70.59  198.21
JEWELLERY            0.96       -114.93  189.60
ENTERTAINMENT        0.71        -75.49  180.15
HEALTHCARE           0.69        -69.55  112.10
TEXTILES             0.39        -52.08   95.44
HOTELS               0.36       -105.63  178.16

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3628895.0     19
X40       2099687.0     18
XR        1386149.0     13
X40N      1194570.0     12
AR        1066806.0      8
OX40N      660968.0     10
XY25       596718.0      5
SR         277687.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2421955.0     19
X-MC        1474978.0     14
X-SC        1099633.0      6
H-SC         829615.0      8
M-SC         328925.0      6
H-MC         255884.0      1
M-LC         166044.0      1
M-MC          65525.0      1
H-LC          51355.0      2
L-MC          45464.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1214717.0      9
X-SC       XY24       672478.0      2
H-SC       XY24       526632.0      3
X-MC       X40        515104.0      6
X-LC       XY24       463758.0      2
X-MC       X40N       447926.0      4
X-LC       X40N       423709.0      5
X-MC       XY25       274503.0      2
X-LC       XY25       256690.0      2
H-MC       XY24       255884.0      1
X-SC       X40        254467.0      2
X-MC       XY24       237445.0      2
H-SC       OX40N      216689.0      3
X-SC       X40N       172688.0      2
M-LC       XR         166044.0      1
M-SC       OX40N      154461.0      4
           XY24       116567.0      1
H-SC       XR          86294.0      2
M-MC       XY25        65525.0      1
X-LC       XR          63081.0      1
M-SC       XR          57897.0      1
H-LC       AR          51355.0      2
L-MC       XR          45464.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds