<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-07 10:03:26
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.31 C
-------------------
Today PnL: -29.55 K (-0.23%)
Current PnL: -46.50 L (-28.62%)
CY Booked + Current PnL: -30.61 L (-18.84%)
-------------------
Total profit:  56.60 K
Total loss:  -47.06 L
-------------------
Total Booked + Current PnL: -3.63 L (-2.68%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.16%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.17 C (89.77%)
===================
Deployed:  1.36 C
Current:  1.31 C
CAGR/XIRR %: -1.77%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,0.20,-7.00,30.71,21.57,27984.0,-6855.0,91125.0,397.04,-19.60,50.0,H-SC,4.89,167.0,-0.24,0.70,24.29,XR,ATH,FINANCE
77,TTKPRESTIG,5.09,-37.70,60.67,0.09,38090.0,-37995.0,62782.0,770.00,45.78,49.0,M-SC,22.30,250.0,-1.00,0.48,11.79,OX40N,NTT,DURABLES
67,SONACOMS,-0.27,-12.12,58.27,39.09,51802.0,-12259.0,88900.0,804.02,-30.33,52.0,M-MC,7.27,193.0,-0.24,0.68,25.76,AR,ATH,AUTO
24,DMART,-1.22,8.07,19.93,29.60,53758.0,20136.0,269736.0,5391.45,-8.90,74.0,X-LC,5.65,14.0,0.37,2.07,23.29,X40N,ATH,FMCG
2,ABBOTINDIA,0.04,-13.10,35.86,18.07,55737.0,-23425.0,155430.0,35195.00,-26.09,43.0,X-MC,10.88,58.0,-0.42,1.19,1.65,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,6.81,-42.98,98.00,12.90,122100.0,-93904.0,124592.0,593.0,83.89,53.0,H-SC,16.68,170.0,-0.77,0.95,20.23,OX40N,NTT,FINANCE
77,TTKPRESTIG,5.09,-37.70,60.67,0.09,38090.0,-37995.0,62782.0,770.0,45.78,49.0,M-SC,22.30,250.0,-1.00,0.48,11.79,OX40N,NTT,DURABLES
55,RAJESHEXPO,5.00,-81.42,438.46,0.07,111777.0,-111684.0,25493.0,518.0,834.34,38.0,L-SC,44.02,268.0,-1.00,0.20,19.68,OX40N,NTT,JEWELLERY
84,WIPRO,2.63,-16.95,107.43,72.27,151180.0,-28724.0,140724.0,420.0,-25.02,55.0,M-LC,17.98,98.0,-0.19,1.08,7.97,XR,NTT,IT
74,TITAGARH,2.50,-38.30,136.21,45.74,203525.0,-92757.0,149420.0,1548.0,-17.88,51.0,H-SC,23.71,175.0,-0.46,1.14,14.00,XY24,NTT,ENGINEERING

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COFFEEDAY,-2.37,-61.01,246.92,35.27,109324.0,-69274.0,44275.0,80.0,-69.82,41.0,L-SC,32.81,266.0,-0.63,0.34,9.19,XR,NTT,HOTELS
11,BANDHANBNK,-2.26,-28.26,168.22,92.42,336161.0,-78725.0,199834.0,400.0,71.70,41.0,H-SC,1.48,174.0,-0.23,1.53,10.08,XY24,NTT,BANKS
69,SURYODAY,-1.96,-26.32,66.98,23.03,88378.0,-47124.0,131947.0,216.0,44.74,52.0,H-SC,5.34,166.0,-0.53,1.01,19.39,XR,NTT,BANKS
82,VOLTAS,-1.88,-3.89,51.08,45.20,94128.0,-7467.0,184275.0,1856.0,10.03,34.0,X-MC,4.25,79.0,-0.08,1.41,2.64,XY25,NTT,AC
47,JSWINFRA,-1.45,-19.95,45.44,16.43,80673.0,-44236.0,177538.0,342.0,-31.31,39.0,X-MC,12.19,61.0,-0.55,1.36,0.00,X40N,NTT,REALTY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.04,1.42,105.00,107.91,157227.0,2096.0,149740.0,1641.55,-8.68,44.0,M-SC,4.15,220.0,0.01,1.15,12.65,OX40N,ATH,CABLES
66,SIS,-1.18,-34.40,84.84,21.26,61798.0,-38191.0,72841.0,528.00,1705.18,47.0,H-SC,14.96,168.0,-0.62,0.56,8.30,OX40N,NTT,MISC
77,TTKPRESTIG,5.09,-37.70,60.67,0.09,38090.0,-37995.0,62782.0,770.00,45.78,49.0,M-SC,22.30,250.0,-1.00,0.48,11.79,OX40N,NTT,DURABLES
18,CERA,-0.84,-37.91,99.53,23.89,108707.0,-66683.0,109220.0,9475.00,-40.10,49.0,H-SC,19.01,153.0,-0.61,0.84,4.96,OX40N,NTT,CERAMICS
72,TATAELXSI,0.52,-38.11,113.32,32.03,92465.0,-50239.0,81596.0,9161.00,-22.55,47.0,H-SC,21.63,158.0,-0.54,0.62,7.99,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-1.04,1.42,105.00,107.91,157227.0,2096.0,149740.0,1641.55,-8.68,44.0,M-SC,4.15,220.0,0.01,1.15,12.65,OX40N,ATH,CABLES
1,ABB,-1.14,12.34,29.58,45.57,86937.0,32285.0,293904.0,7934.00,-27.77,52.0,H-MC,13.81,125.0,0.37,2.25,30.51,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-1.14,12.34,29.58,45.57,86937.0,32285.0,293904.0,7934.00,-27.77,52.0,H-MC,13.81,125.0,0.37,2.25,30.51,AR,NTT,ELECTRICAL
26,FINCABLES,-1.04,1.42,105.00,107.91,157227.0,2096.0,149740.0,1641.55,-8.68,44.0,M-SC,4.15,220.0,0.01,1.15,12.65,OX40N,ATH,CABLES
40,INDIAMART,-0.91,-11.95,134.79,106.72,146371.0,-14744.0,108592.0,4810.62,-60.35,47.0,H-SC,12.84,140.0,-0.10,0.83,8.63,AR,ATH,MISC
84,WIPRO,2.63,-16.95,107.43,72.27,151180.0,-28724.0,140724.0,420.00,-25.02,55.0,M-LC,17.98,98.0,-0.19,1.08,7.97,XR,NTT,IT
85,ZYDUSLIFE,-0.43,-9.04,49.10,35.63,93602.0,-18939.0,190635.0,1286.17,-20.72,41.0,H-MC,5.98,120.0,-0.20,1.46,6.13,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,-0.91,-15.86,55.37,30.73,91779.0,-31250.0,165755.0,790.00,-38.45,24.0,X-MC,10.43,78.0,-0.34,1.27,1.00,X40,ATH,INSURANCE
21,DABUR,-0.36,-19.41,78.31,43.70,156555.0,-48151.0,199917.0,735.00,-26.86,29.0,X-MC,12.42,70.0,-0.31,1.53,0.43,XY24,BTT,FMCG
37,ICICIGI,-0.83,-10.02,32.63,19.34,58754.0,-20047.0,180062.0,2252.93,-24.25,32.0,X-MC,6.70,66.0,-0.34,1.38,0.57,X40,ATH,INSURANCE
20,COLPAL,-1.01,-31.22,105.75,41.51,191545.0,-82235.0,181130.0,3726.84,-16.83,32.0,X-MC,11.65,62.0,-0.43,1.39,1.26,XY25,ATH,FMCG
59,RELIANCE,-0.64,-16.79,50.58,25.30,84581.0,-33740.0,167223.0,1952.00,-18.88,32.0,X-LC,4.27,21.0,-0.40,1.28,11.65,XY25,BTT,REFINERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-0.94,-18.87,54.71,25.51,82598.0,-35120.0,150975.0,4671.50,26.90,44.0,H-LC,0.77,51.0,-0.43,1.16,11.18,AR,ATH,ELECTRICAL
78,UNITDSPR,-1.37,-10.43,34.83,20.77,73045.0,-24424.0,209720.0,1644.00,-20.49,37.0,X-MC,4.21,64.0,-0.33,1.61,0.04,X40N,NTT,BREWERIES
82,VOLTAS,-1.88,-3.89,51.08,45.20,94128.0,-7467.0,184275.0,1856.00,10.03,34.0,X-MC,4.25,79.0,-0.08,1.41,2.64,XY25,NTT,AC
59,RELIANCE,-0.64,-16.79,50.58,25.30,84581.0,-33740.0,167223.0,1952.00,-18.88,32.0,X-LC,4.27,21.0,-0.40,1.28,11.65,XY25,BTT,REFINERIES
24,DMART,-1.22,8.07,19.93,29.60,53758.0,20136.0,269736.0,5391.45,-8.90,74.0,X-LC,5.65,14.0,0.37,2.07,23.29,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,JSWINFRA,-1.45,-19.95,45.44,16.43,80673.0,-44236.0,177538.0,342.00,-31.31,39.0,X-MC,12.19,61.0,-0.55,1.36,0.00,X40N,NTT,REALTY
78,UNITDSPR,-1.37,-10.43,34.83,20.77,73045.0,-24424.0,209720.0,1644.00,-20.49,37.0,X-MC,4.21,64.0,-0.33,1.61,0.04,X40N,NTT,BREWERIES
21,DABUR,-0.36,-19.41,78.31,43.70,156555.0,-48151.0,199917.0,735.00,-26.86,29.0,X-MC,12.42,70.0,-0.31,1.53,0.43,XY24,BTT,FMCG
37,ICICIGI,-0.83,-10.02,32.63,19.34,58754.0,-20047.0,180062.0,2252.93,-24.25,32.0,X-MC,6.70,66.0,-0.34,1.38,0.57,X40,ATH,INSURANCE
35,HINDUNILVR,-0.94,-19.66,41.49,13.67,85685.0,-50543.0,206520.0,2922.00,-40.44,36.0,X-LC,11.67,9.0,-0.59,1.58,0.63,XY25,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,2.44,-63.76,320.30,52.31,168484.0,-92558.0,52602.0,1176.00,-61.38,44.0,X-SC,32.23,92.0,-0.55,0.40,17.61,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.80,-56.66,211.97,35.20,118203.0,-72906.0,55764.0,2096.00,-26.93,43.0,X-SC,34.35,91.0,-0.62,0.43,10.59,X40,NTT,FOOTWEAR
54,QUESS,1.75,-25.62,133.80,73.90,106279.0,-27362.0,79431.0,424.00,-59.78,48.0,X-SC,22.42,80.0,-0.26,0.61,6.85,XY24,NTT,MISC
36,HONAUT,-0.78,-29.29,114.00,51.31,155439.0,-56488.0,136350.0,58357.33,-41.24,37.0,X-SC,18.47,90.0,-0.36,1.04,3.59,X40N,ATH,ELECTRICAL
65,SIEMENS,-0.94,-18.87,54.71,25.51,82598.0,-35120.0,150975.0,4671.50,26.90,44.0,H-LC,0.77,51.0,-0.43,1.16,11.18,AR,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.03,-22.31,53.25,19.06,140726.0,-75891.0,264275.0,452.00,-57.54,40.0,X-LC,19.72,1.0,-0.54,2.02,2.52,X40,NTT,FMCG
73,TCS,0.74,-26.84,73.00,26.57,247436.0,-124320.0,338953.0,4311.58,-38.05,48.0,X-LC,18.67,2.0,-0.50,2.60,5.79,X40,ATH,IT
43,INFY,0.98,-10.21,49.51,34.24,139097.0,-31941.0,280947.0,1972.00,-29.25,53.0,X-LC,14.81,3.0,-0.23,2.15,8.04,X40,NTT,IT
75,TMPV,-0.85,-30.62,96.85,36.58,239111.0,-108953.0,246888.0,600.00,-85.81,38.0,X-LC,12.49,4.0,-0.46,1.89,2.90,XY24,NTT,AUTO
33,HCLTECH,1.79,-7.30,33.59,23.83,75329.0,-17665.0,224259.0,1908.19,-2.81,57.0,X-LC,10.97,8.0,-0.23,1.72,8.89,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-0.27,-12.12,58.27,39.09,51802.0,-12259.0,88900.0,804.02,-30.33,52.0,M-MC,7.27,193.0,-0.24,0.68,25.76,AR,ATH,AUTO
24,DMART,-1.22,8.07,19.93,29.60,53758.0,20136.0,269736.0,5391.45,-8.90,74.0,X-LC,5.65,14.0,0.37,2.07,23.29,X40N,ATH,FMCG
1,ABB,-1.14,12.34,29.58,45.57,86937.0,32285.0,293904.0,7934.00,-27.77,52.0,H-MC,13.81,125.0,0.37,2.25,30.51,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,0.42,-50.13,249.20,74.15,203330.0,-82012.0,81593.0,838.00,-246.60,53.0,H-SC,26.46,145.0,-0.40,0.62,21.42,XR,NTT,CHEMICALS
24,DMART,-1.22,8.07,19.93,29.60,53758.0,20136.0,269736.0,5391.45,-8.90,74.0,X-LC,5.65,14.0,0.37,2.07,23.29,X40N,ATH,FMCG
5,ANGELONE,-0.15,0.68,23.34,24.18,71674.0,2088.0,307088.0,303.00,-85.37,57.0,X-SC,8.62,97.0,0.03,2.35,18.20,X40N,NTT,FINANCE
30,HAPPSTMNDS,-1.02,-52.38,288.18,84.85,175882.0,-67133.0,61032.0,1480.71,-43.46,49.0,H-SC,23.22,152.0,-0.38,0.47,13.02,AR,ATH,IT
52,PAGEIND,-0.69,-9.99,49.00,34.11,118369.0,-26809.0,241570.0,51418.64,-35.44,64.0,X-MC,19.23,55.0,-0.23,1.85,14.27,X40,ATH,APPARELS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.14
1     25       46.17
2     50       77.90

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.81
MC    29.40
LC    25.79
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.06
X40      25.42
X40N     15.38
AR        9.12
XR        8.45
XY25      7.03
OX40N     6.75
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.55
X-MC    22.02
H-SC    21.97
X-SC    12.35
M-SC     9.95
H-MC     4.99
M-MC     2.05
H-LC     1.16
M-LC     1.08
L-SC     0.54
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.13        -26.44   71.33
FINANCE             13.26        -23.89   74.39
IT                  12.16        -41.81  113.99
MISC                 7.09        -44.80  107.70
ELECTRICAL           6.38        -16.18   60.66
PAINTS               5.20        -45.08   70.27
INSURANCE            4.59        -13.30   52.07
BANKS                4.53        -30.15   96.21
PHARMA               4.09        -10.15   44.82
AUTO                 3.64        -37.45   91.98
HEALTHCARE           1.94        -40.72   77.44
AC                   1.91        -28.29   63.07
APPARELS             1.85        -11.10   49.00
FOOTWEAR             1.85        -83.21  156.67
TRAVEL               1.79        -91.64  187.61
DURABLES             1.77        -66.87  107.46
BREWERIES            1.61        -11.65   34.83
CERAMICS             1.38        -71.26  123.29
REALTY               1.36        -24.92   45.44
REFINERIES           1.28        -20.18   50.58
CEMENT               1.24        -65.76  189.76
CABLES               1.15          1.40  105.00
ENGINEERING          1.14        -62.08  136.21
CHEMICALS            1.05        -91.23  247.24
JEWELLERY            1.03       -139.14  222.23
ENTERTAINMENT        0.78        -88.58  201.04
TEXTILES             0.46        -55.04   99.25
HOTELS               0.34       -156.46  246.92

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4062297.0     21
X40       1855105.0     16
XR        1388363.0     12
AR        1380297.0     10
X40N      1291052.0     10
OX40N      911797.0     10
XY25       521715.0      5
SR         315017.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3920948.0     24
X-MC        1857524.0     15
X-LC        1700696.0     13
M-SC        1619446.0     14
X-SC        1569184.0     10
H-MC         427077.0      3
L-SC         221101.0      2
M-LC         151180.0      1
M-MC         117578.0      2
H-LC          82598.0      1
L-MC          58311.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1358128.0      6
           AR         986303.0      5
M-SC       XY24       932323.0      6
X-LC       X40        910872.0      7
H-SC       XR         876430.0      7
X-SC       XY24       857699.0      4
X-MC       X40        722505.0      7
           X40N       572314.0      4
X-SC       X40N       489757.0      4
M-SC       OX40N      414950.0      5
X-LC       XY24       390577.0      2
H-SC       OX40N      385070.0      4
           SR         315017.0      2
X-MC       XY25       285673.0      2
           XY24       277032.0      2
H-MC       XY24       246538.0      1
X-LC       X40N       228981.0      2
X-SC       X40        221728.0      2
M-SC       XR         193118.0      2
H-MC       AR         180539.0      2
X-LC       XY25       170266.0      2
M-LC       XR         151180.0      1
L-SC       OX40N      111777.0      1
           XR         109324.0      1
H-LC       AR          82598.0      1
M-SC       AR          79055.0      1
M-MC       XY25        65776.0      1
L-MC       XR          58311.0      1
M-MC       AR          51802.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds