<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-25 14:01:55
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.32 C
-------------------
Today PnL: 3.18 L (2.47%)
Current PnL: -44.81 L (-27.58%)
CY Booked + Current PnL: -28.92 L (-17.8%)
-------------------
Total profit:  60.56 K
Total loss:  -45.42 L
-------------------
Total Booked + Current PnL: -1.94 L (-1.43%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.01%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.16 C (87.35%)
===================
Deployed:  1.36 C
Current:  1.32 C
CAGR/XIRR %: -1.17%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,1.66,-7.27,31.10,21.57,28256.0,-7125.0,90855.0,397.04,-20.05,46.0,H-SC,2.86,167.0,-0.25,0.69,23.92,XR,ATH,FINANCE
77,TTKPRESTIG,1.03,-42.41,73.80,0.09,42834.0,-42737.0,58040.0,770.00,34.69,35.0,M-SC,19.98,250.0,-1.00,0.44,1.03,OX40N,NTT,DURABLES
37,ICICIGI,2.75,-5.84,26.74,19.34,50385.0,-11683.0,188426.0,2252.93,-20.81,38.0,X-MC,4.01,66.0,-0.23,1.42,4.16,X40,ATH,INSURANCE
67,SONACOMS,3.99,-11.00,56.29,39.09,50677.0,-11130.0,90029.0,804.02,-29.52,52.0,M-MC,7.30,193.0,-0.22,0.68,27.36,AR,ATH,AUTO
2,ABBOTINDIA,-0.34,-10.40,31.77,18.07,50915.0,-18595.0,160260.0,35195.00,-23.83,49.0,X-MC,10.47,58.0,-0.37,1.21,4.81,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,RAJOOENG,8.68,-46.11,159.05,39.61,87859.0,-47260.0,55240.0,143.1,-63.52,41.0,H-SC,32.16,136.0,-0.54,0.42,8.68,AR,ATH,MISC
16,CAMPUS,6.30,-20.15,66.91,33.28,89640.0,-33804.0,133971.0,393.0,-35.71,44.0,M-SC,10.92,218.0,-0.38,1.01,7.44,XY24,NTT,FOOTWEAR
48,KANSAINER,6.18,-42.85,98.54,13.47,151875.0,-115542.0,154125.0,340.0,-50.79,35.0,H-SC,21.13,162.0,-0.76,1.17,7.66,XY24,NTT,PAINTS
41,INDIGOPNTS,6.06,-45.00,81.87,0.02,78596.0,-78558.0,96001.0,1408.0,46.21,33.0,M-SC,25.08,222.0,-1.00,0.73,8.59,OX40N,NTT,PAINTS
5,ANGELONE,5.39,-0.47,24.77,24.18,75192.0,-1438.0,303562.0,303.0,-85.37,56.0,X-SC,9.92,97.0,-0.02,2.29,16.00,X40N,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
4,ALKYLAMINE,-1.65,-40.74,226.77,93.63,135667.0,-41137.0,59826.0,4546.37,-36.55,50.0,H-SC,25.92,142.0,-0.30,0.45,12.26,SR,ATH,CHEMICALS
76,TRIDENT,-1.42,-32.93,91.62,28.51,56689.0,-30380.0,61874.0,48.00,-13.75,53.0,M-SC,14.14,223.0,-0.54,0.47,13.55,XR,NTT,TEXTILES
78,UNITDSPR,-0.75,-3.18,24.73,20.77,56062.0,-7448.0,226696.0,1644.00,-14.18,46.0,X-MC,1.92,64.0,-0.13,1.71,3.36,X40N,NTT,BREWERIES
2,ABBOTINDIA,-0.34,-10.40,31.77,18.07,50915.0,-18595.0,160260.0,35195.00,-23.83,49.0,X-MC,10.47,58.0,-0.37,1.21,4.81,X40,ATH,PHARMA
73,TCS,0.04,-29.55,79.66,26.57,259989.0,-136900.0,326373.0,4311.58,-40.35,30.0,X-LC,17.55,2.0,-0.53,2.47,1.86,X40,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.72,6.07,96.02,107.91,150370.0,8959.0,156603.0,1641.55,-4.62,48.0,M-SC,8.14,220.0,0.06,1.18,17.82,OX40N,ATH,CABLES
66,SIS,0.21,-35.32,87.47,21.26,62822.0,-39211.0,71821.0,528.00,1679.79,43.0,H-SC,14.39,168.0,-0.62,0.54,6.79,OX40N,NTT,MISC
18,CERA,2.11,-37.24,97.40,23.89,107528.0,-65505.0,110398.0,9475.00,-39.38,50.0,H-SC,19.00,153.0,-0.61,0.83,6.09,OX40N,NTT,CERAMICS
72,TATAELXSI,2.14,-38.46,114.55,32.03,92930.0,-50709.0,81126.0,9161.00,-23.05,42.0,H-SC,21.00,158.0,-0.55,0.61,5.71,OX40N,NTT,IT
77,TTKPRESTIG,1.03,-42.41,73.80,0.09,42834.0,-42737.0,58040.0,770.00,34.69,35.0,M-SC,19.98,250.0,-1.00,0.44,1.03,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,2.72,6.07,96.02,107.91,150370.0,8959.0,156603.0,1641.55,-4.62,48.0,M-SC,8.14,220.0,0.06,1.18,17.82,OX40N,ATH,CABLES
1,ABB,1.28,14.51,27.13,45.57,81273.0,37949.0,299568.0,7934.00,-26.39,56.0,H-MC,13.44,125.0,0.47,2.26,33.03,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.28,14.51,27.13,45.57,81273.0,37949.0,299568.0,7934.00,-26.39,56.0,H-MC,13.44,125.0,0.47,2.26,33.03,AR,NTT,ELECTRICAL
26,FINCABLES,2.72,6.07,96.02,107.91,150370.0,8959.0,156603.0,1641.55,-4.62,48.0,M-SC,8.14,220.0,0.06,1.18,17.82,OX40N,ATH,CABLES
85,ZYDUSLIFE,2.94,-3.78,40.95,35.63,82581.0,-7912.0,201662.0,1286.17,-16.22,53.0,H-MC,5.37,120.0,-0.10,1.52,12.27,AR,ATH,PHARMA
40,INDIAMART,3.48,-12.67,136.71,106.72,147253.0,-15624.0,107712.0,4810.62,-60.55,41.0,H-SC,11.96,140.0,-0.11,0.81,7.75,AR,ATH,MISC
67,SONACOMS,3.99,-11.00,56.29,39.09,50677.0,-11130.0,90029.0,804.02,-29.52,52.0,M-MC,7.30,193.0,-0.22,0.68,27.36,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,2.21,-27.27,81.50,32.01,126566.0,-58224.0,155296.0,17616.87,-50.75,24.0,X-MC,16.43,57.0,-0.46,1.17,2.64,X40,ATH,FMCG
38,ICICIPRULI,1.13,-10.05,45.34,30.73,80341.0,-19808.0,177197.0,790.00,-34.21,26.0,X-MC,4.94,78.0,-0.25,1.34,2.32,X40,ATH,INSURANCE
58,RELAXO,3.35,-65.40,340.20,52.31,170862.0,-94936.0,50224.0,1176.00,-63.12,27.0,X-SC,27.42,92.0,-0.56,0.38,4.83,X40N,NTT,FOOTWEAR
12,BATAINDIA,2.27,-57.78,220.22,35.20,119641.0,-74342.0,54328.0,2096.00,-28.81,29.0,X-SC,31.78,91.0,-0.62,0.41,4.60,X40,NTT,FOOTWEAR
73,TCS,0.04,-29.55,79.66,26.57,259989.0,-136900.0,326373.0,4311.58,-40.35,30.0,X-LC,17.55,2.0,-0.53,2.47,1.86,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
78,UNITDSPR,-0.75,-3.18,24.73,20.77,56062.0,-7448.0,226696.0,1644.00,-14.18,46.0,X-MC,1.92,64.0,-0.13,1.71,3.36,X40N,NTT,BREWERIES
65,SIEMENS,4.02,-16.10,49.61,25.51,77454.0,-29970.0,156125.0,4671.50,31.07,47.0,H-LC,2.35,51.0,-0.39,1.18,14.97,AR,ATH,ELECTRICAL
59,RELIANCE,0.74,-8.70,37.24,25.30,68327.0,-17486.0,183477.0,1952.00,-11.19,53.0,X-LC,3.48,21.0,-0.26,1.39,22.50,XY25,BTT,REFINERIES
82,VOLTAS,5.16,7.12,35.54,45.20,72997.0,13653.0,205395.0,1856.00,22.63,45.0,X-MC,3.56,79.0,0.19,1.55,14.40,XY25,NTT,AC
37,ICICIGI,2.75,-5.84,26.74,19.34,50385.0,-11683.0,188426.0,2252.93,-20.81,38.0,X-MC,4.01,66.0,-0.23,1.42,4.16,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BAJAJHFL,1.30,-28.74,127.53,62.13,248121.0,-78487.0,194559.0,181.50,-41.28,32.0,X-MC,20.78,60.0,-0.32,1.47,1.60,X40N,ATH,FINANCE
73,TCS,0.04,-29.55,79.66,26.57,259989.0,-136900.0,326373.0,4311.58,-40.35,30.0,X-LC,17.55,2.0,-0.53,2.47,1.86,X40,ATH,IT
38,ICICIPRULI,1.13,-10.05,45.34,30.73,80341.0,-19808.0,177197.0,790.00,-34.21,26.0,X-MC,4.94,78.0,-0.25,1.34,2.32,X40,ATH,INSURANCE
45,ITC,2.09,-21.68,52.01,19.06,138568.0,-73740.0,266426.0,452.00,-57.14,39.0,X-LC,18.79,1.0,-0.53,2.01,2.38,X40,NTT,FMCG
53,PGHH,2.21,-27.27,81.50,32.01,126566.0,-58224.0,155296.0,17616.87,-50.75,24.0,X-MC,16.43,57.0,-0.46,1.17,2.64,X40,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,3.35,-65.40,340.20,52.31,170862.0,-94936.0,50224.0,1176.00,-63.12,27.0,X-SC,27.42,92.0,-0.56,0.38,4.83,X40N,NTT,FOOTWEAR
12,BATAINDIA,2.27,-57.78,220.22,35.20,119641.0,-74342.0,54328.0,2096.00,-28.81,29.0,X-SC,31.78,91.0,-0.62,0.41,4.60,X40,NTT,FOOTWEAR
54,QUESS,1.12,-27.23,138.98,73.90,108001.0,-29083.0,77710.0,424.00,-60.88,40.0,X-SC,21.61,80.0,-0.27,0.59,4.44,XY24,NTT,MISC
36,HONAUT,2.06,-26.86,106.87,51.31,150740.0,-51788.0,141050.0,58357.33,-39.15,34.0,X-SC,16.19,90.0,-0.34,1.07,3.66,X40N,ATH,ELECTRICAL
51,MEDANTA,4.71,-12.77,45.73,27.12,70413.0,-22542.0,153975.0,1486.00,-15.50,39.0,X-SC,12.77,87.0,-0.32,1.16,5.17,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,2.09,-21.68,52.01,19.06,138568.0,-73740.0,266426.0,452.00,-57.14,39.0,X-LC,18.79,1.0,-0.53,2.01,2.38,X40,NTT,FMCG
73,TCS,0.04,-29.55,79.66,26.57,259989.0,-136900.0,326373.0,4311.58,-40.35,30.0,X-LC,17.55,2.0,-0.53,2.47,1.86,X40,ATH,IT
43,INFY,0.61,-12.45,53.33,34.24,146092.0,-38949.0,273939.0,1972.00,-31.06,43.0,X-LC,15.04,3.0,-0.27,2.07,5.35,X40,NTT,IT
75,TMPV,3.05,-27.00,87.09,36.58,226231.0,-96074.0,259767.0,600.00,-84.72,41.0,X-LC,7.48,4.0,-0.42,1.96,5.06,XY24,NTT,AUTO
33,HCLTECH,1.76,-9.31,36.54,23.83,80172.0,-22516.0,219408.0,1908.19,-4.88,50.0,X-LC,11.60,8.0,-0.28,1.66,6.53,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,3.99,-11.00,56.29,39.09,50677.0,-11130.0,90029.0,804.02,-29.52,52.0,M-MC,7.30,193.0,-0.22,0.68,27.36,AR,ATH,AUTO
1,ABB,1.28,14.51,27.13,45.57,81273.0,37949.0,299568.0,7934.00,-26.39,56.0,H-MC,13.44,125.0,0.47,2.26,33.03,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
30,HAPPSTMNDS,1.00,-49.64,267.06,84.85,172371.0,-63621.0,64544.0,1480.71,-40.12,56.0,H-SC,26.09,152.0,-0.37,0.49,19.53,AR,ATH,IT
69,SURYODAY,3.56,-25.95,66.15,23.03,87715.0,-46471.0,132600.0,216.00,44.74,52.0,H-SC,5.84,166.0,-0.53,1.00,29.60,XR,NTT,BANKS
47,JSWINFRA,2.95,-11.52,31.59,16.43,61987.0,-25550.0,196224.0,342.00,-24.13,52.0,X-MC,11.49,61.0,-0.41,1.48,7.71,X40N,NTT,REALTY
59,RELIANCE,0.74,-8.70,37.24,25.30,68327.0,-17486.0,183477.0,1952.00,-11.19,53.0,X-LC,3.48,21.0,-0.26,1.39,22.50,XY25,BTT,REFINERIES
52,PAGEIND,3.25,-13.37,54.81,34.11,127436.0,-35874.0,232505.0,51418.64,-37.82,58.0,X-MC,21.01,55.0,-0.28,1.76,9.98,X40,ATH,APPARELS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.74
1     25       45.97
2     50       78.21

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.29
MC    30.12
LC    25.56
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.05
X40      25.41
X40N     15.26
AR        9.17
XR        8.26
XY25      7.38
OX40N     6.63
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.38
X-MC    22.64
H-SC    21.53
X-SC    12.28
M-SC     9.95
H-MC     5.08
M-MC     2.05
H-LC     1.18
M-LC     1.00
L-SC     0.53
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.11        -24.94   69.30
FINANCE             13.10        -24.01   74.55
IT                  11.80        -44.43  117.92
MISC                 6.92        -46.35  109.93
ELECTRICAL           6.55        -11.82   54.63
PAINTS               5.19        -43.78   68.75
INSURANCE            4.65        -10.24   47.97
BANKS                4.60        -26.31   90.43
PHARMA               4.14         -7.08   40.79
AUTO                 3.72        -32.88   85.59
AC                   2.07        -16.69   48.33
HEALTHCARE           1.88        -43.15   80.51
TRAVEL               1.81        -85.88  178.96
FOOTWEAR             1.80        -85.14  159.37
APPARELS             1.76        -15.43   54.81
DURABLES             1.74        -67.91  108.76
BREWERIES            1.71         -3.29   24.73
REALTY               1.48        -13.02   31.59
REFINERIES           1.39         -9.53   37.24
CERAMICS             1.37        -68.68  119.93
CEMENT               1.24        -63.00  184.94
CABLES               1.18          5.72   96.02
ENGINEERING          1.10        -67.08  143.49
CHEMICALS            1.06        -88.43  242.16
JEWELLERY            1.03       -136.34  218.45
ENTERTAINMENT        0.75        -93.25  208.50
TEXTILES             0.47        -49.10   91.62
HOTELS               0.35       -145.19  231.67

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4019194.0     21
X40       1811744.0     16
XR        1398522.0     12
AR        1356532.0     10
X40N      1280588.0     10
OX40N      913661.0     10
XY25       464523.0      5
SR         312362.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3945306.0     24
X-MC        1736819.0     15
X-LC        1682518.0     13
M-SC        1600238.0     14
X-SC        1557720.0     10
H-MC         405008.0      3
L-SC         221129.0      2
M-LC         159926.0      1
M-MC         115331.0      2
H-LC          77454.0      1
L-MC          55677.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1367025.0      6
           AR         985955.0      5
M-SC       XY24       926159.0      6
X-LC       X40        907190.0      7
H-SC       XR         884392.0      7
X-SC       XY24       846793.0      4
X-MC       X40        689753.0      7
           X40N       527309.0      4
X-SC       X40N       496126.0      4
M-SC       OX40N      404246.0      5
H-SC       OX40N      395572.0      4
X-LC       XY24       372199.0      2
H-SC       SR         312362.0      2
X-MC       XY24       265864.0      2
X-LC       X40N       257153.0      2
X-MC       XY25       253893.0      2
H-MC       XY24       241154.0      1
X-SC       X40        214801.0      2
M-SC       XR         191241.0      2
H-MC       AR         163854.0      2
M-LC       XR         159926.0      1
X-LC       XY25       145976.0      2
L-SC       OX40N      113843.0      1
           XR         107286.0      1
M-SC       AR          78592.0      1
H-LC       AR          77454.0      1
M-MC       XY25        64654.0      1
L-MC       XR          55677.0      1
M-MC       AR          50677.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds