<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-18 14:04:51
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -1.20 L (-0.75%)
Current PnL: -34.91 L (-18.48%)
CY Booked + Current PnL: -29.85 L (-15.8%)
-------------------
Total profit:  3.31 L
Total loss:  -38.22 L
-------------------
Total Booked + Current PnL: 13.02 L (8.91%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.03%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.58%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.61,6.59,3.98,10.83,7894.0,12255.0,198350.0,4125.00,-13.70,64.0,H-LC,13.67,51.0,1.55,1.29,39.95,AR,NTT,ELECTRICAL
78,UNITDSPR,-1.02,12.34,7.50,20.77,19728.0,28896.0,263040.0,1644.00,-4.30,62.0,X-MC,10.94,64.0,1.46,1.70,26.44,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.32,-22.79,29.63,0.09,23056.0,-22963.0,77814.0,770.00,-6.01,42.0,M-SC,10.22,250.0,-1.00,0.50,40.05,OX40N,NTT,DURABLES
52,M&M,1.19,8.34,9.68,18.82,25240.0,20067.0,260748.0,3762.88,-6.55,59.0,X-LC,4.80,25.0,0.80,1.69,18.28,X40N,ATH,AUTO
54,MASFIN,0.50,-7.23,31.04,21.57,28215.0,-7080.0,90900.0,397.04,-28.13,42.0,H-SC,1.23,167.0,-0.25,0.59,8.35,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,4.05,-24.58,32.58,-0.01,31403.0,-31418.0,96387.0,2282.00,752.82,76.0,M-SC,6.02,231.0,-1.00,0.62,64.06,OX40N,BTT,AC
18,COFFEEDAY,3.05,-49.78,169.36,35.27,96576.0,-56525.0,57024.0,80.00,NaN,41.0,NaN,3.93,266.0,-0.59,0.37,40.62,XR,NTT,HOTELS
0,5PAISA,2.50,-25.10,50.74,12.90,83038.0,-54842.0,163654.0,593.00,4.96,63.0,H-SC,11.10,170.0,-0.66,1.06,57.93,OX40N,NTT,FINANCE
52,M&M,1.19,8.34,9.68,18.82,25240.0,20067.0,260748.0,3762.88,-6.55,59.0,X-LC,4.80,25.0,0.80,1.69,18.28,X40N,ATH,AUTO
24,EASEMYTRIP,0.98,-65.84,326.49,45.70,197206.0,-116413.0,60402.0,26.40,NaN,35.0,NaN,7.23,204.0,-0.59,0.39,5.81,XY24,NTT,TRAVEL

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,-5.19,-55.89,224.49,43.14,181296.0,-102319.0,80759.0,537.00,NaN,28.0,NaN,10.96,225.0,-0.56,0.52,0.00,XY24,NTT,MISC
81,VALIANTORG,-5.08,-35.99,172.08,74.15,180202.0,-58885.0,104720.0,838.00,NaN,58.0,NaN,6.28,145.0,-0.33,0.68,55.84,XR,NTT,CHEMICALS
33,HCLTECH,-4.78,-13.38,43.12,23.97,115590.0,-41421.0,268065.0,1853.42,-15.52,50.0,X-LC,11.79,8.0,-0.36,1.74,26.50,X40,ATH,IT
19,COLPAL,-3.56,-27.46,92.80,39.86,177294.0,-72315.0,191050.0,3683.41,-12.03,31.0,X-MC,1.61,62.0,-0.41,1.24,8.07,XY25,ATH,FMCG
60,RELAXO,-3.12,-50.28,206.33,52.31,148915.0,-72987.0,72173.0,1176.00,NaN,42.0,NaN,13.20,92.0,-0.49,0.47,61.37,X40N,NTT,FOOTWEAR

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.77,68.58,23.33,107.91,58068.0,101253.0,248897.0,1641.55,22.65,76.0,M-SC,19.24,220.0,1.74,1.61,87.25,OX40N,ATH,CABLES
67,SIS,-0.49,-4.83,27.41,21.26,28965.0,-5360.0,105672.0,528.00,103.25,37.0,H-SC,20.95,168.0,-0.19,0.68,57.12,OX40N,NTT,MISC
43,INDIGOPNTS,0.36,-18.11,22.14,0.02,31648.0,-31612.0,142947.0,1408.00,-21.90,65.0,M-SC,6.75,222.0,-1.00,0.93,62.18,OX40N,NTT,PAINTS
77,TTKPRESTIG,0.32,-22.79,29.63,0.09,23056.0,-22963.0,77814.0,770.00,-6.01,42.0,M-SC,10.22,250.0,-1.00,0.50,40.05,OX40N,NTT,DURABLES
16,CERA,-1.43,-24.32,63.70,23.89,84800.0,-42779.0,133124.0,9475.00,NaN,35.0,NaN,12.95,153.0,-0.50,0.86,29.41,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.77,68.58,23.33,107.91,58068.0,101253.0,248897.0,1641.55,22.65,76.0,M-SC,19.24,220.0,1.74,1.61,87.25,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.77,68.58,23.33,107.91,58068.0,101253.0,248897.0,1641.55,22.65,76.0,M-SC,19.24,220.0,1.74,1.61,87.25,OX40N,ATH,CABLES
68,STARHEALTH,-0.20,13.01,30.31,47.26,96294.0,36573.0,317696.0,761.00,-0.37,51.0,H-SC,16.51,173.0,0.38,2.06,37.36,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.77,68.58,23.33,107.91,58068.0,101253.0,248897.0,1641.55,22.65,76.0,M-SC,19.24,220.0,1.74,1.61,87.25,OX40N,ATH,CABLES
3,ALKYLAMINE,-0.82,-19.03,137.79,92.54,112646.0,-19211.0,81752.0,4520.85,NaN,54.0,NaN,14.01,142.0,-0.17,0.53,55.24,SR,ATH,CHEMICALS
67,SIS,-0.49,-4.83,27.41,21.26,28965.0,-5360.0,105672.0,528.00,103.25,37.0,H-SC,20.95,168.0,-0.19,0.68,57.12,OX40N,NTT,MISC
42,INDIAMART,-2.41,-24.94,167.67,100.92,155229.0,-30756.0,92580.0,4675.60,NaN,37.0,NaN,13.44,140.0,-0.20,0.60,0.22,AR,ATH,MISC
71,TANLA,-1.68,-35.32,235.89,117.25,413100.0,-95637.0,175124.0,1922.32,NaN,46.0,NaN,15.49,147.0,-0.23,1.13,53.32,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,PAGEIND,-0.41,-4.54,39.94,33.59,102326.0,-12179.0,256200.0,51217.29,-29.08,30.0,X-MC,8.64,55.0,-0.12,1.66,21.67,X40,ATH,APPARELS
28,GODREJCP,-0.14,-15.13,56.59,32.90,119853.0,-37746.0,211791.0,1460.97,-16.72,31.0,X-MC,5.70,32.0,-0.31,1.37,3.09,X40N,ATH,FMCG
47,ITC,-1.23,-25.60,67.59,24.70,199790.0,-101687.0,295591.0,452.00,-30.75,31.0,X-LC,10.47,1.0,-0.51,1.92,0.00,X40,NTT,FMCG
19,COLPAL,-3.56,-27.46,92.80,39.86,177294.0,-72315.0,191050.0,3683.41,-12.03,31.0,X-MC,1.61,62.0,-0.41,1.24,8.07,XY25,ATH,FMCG
56,PGHH,-1.31,-37.68,111.83,32.01,148805.0,-80456.0,133064.0,17616.87,-54.25,31.0,X-SC,19.63,57.0,-0.54,0.86,0.00,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-3.56,-27.46,92.80,39.86,177294.0,-72315.0,191050.0,3683.41,-12.03,31.0,X-MC,1.61,62.0,-0.41,1.24,8.07,XY25,ATH,FMCG
23,DMART,-0.13,-2.74,35.12,31.42,106498.0,-8550.0,303240.0,5391.45,-18.43,47.0,X-LC,2.37,14.0,-0.08,1.96,9.43,X40N,ATH,FMCG
50,KOTAKBANK,-0.69,2.50,16.02,18.92,39361.0,5998.0,245700.0,452.46,-13.30,50.0,X-LC,2.63,12.0,0.15,1.59,10.55,X40,ATH,BANKS
26,GILLETTE,-0.65,-11.14,45.99,29.72,103760.0,-28281.0,225615.0,10978.86,-35.84,37.0,X-SC,3.48,83.0,-0.27,1.46,3.68,X40,ATH,FMCG
11,BERGEPAINT,-0.60,0.09,25.21,25.32,65035.0,223.0,257972.0,680.00,-12.92,59.0,X-MC,4.06,68.0,0.00,1.67,35.28,XY24,NTT,PAINTS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.69,-21.01,81.93,43.70,160534.0,-52128.0,195940.0,735.00,-31.92,35.0,X-MC,9.87,70.0,-0.32,1.27,0.00,XY24,BTT,FMCG
47,ITC,-1.23,-25.60,67.59,24.70,199790.0,-101687.0,295591.0,452.00,-30.75,31.0,X-LC,10.47,1.0,-0.51,1.92,0.00,X40,NTT,FMCG
56,PGHH,-1.31,-37.68,111.83,32.01,148805.0,-80456.0,133064.0,17616.87,-54.25,31.0,X-SC,19.63,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.69,-11.57,48.20,31.05,124931.0,-33928.0,259192.0,1073.00,-28.50,33.0,X-LC,12.68,26.0,-0.27,1.68,0.60,X40,BTT,BANKS
35,HDFCLIFE,-0.55,-7.39,50.26,39.15,116704.0,-18537.0,232200.0,811.41,-31.88,42.0,X-LC,16.48,31.0,-0.16,1.50,0.77,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-1.31,-37.68,111.83,32.01,148805.0,-80456.0,133064.0,17616.87,-54.25,31.0,X-SC,19.63,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
2,ACC,-0.77,-41.53,198.97,74.81,311945.0,-111348.0,156780.0,3906.00,-41.79,38.0,X-SC,11.67,85.0,-0.36,1.02,4.74,XY24,BTT,CEMENT
1,ABBOTINDIA,-1.63,-10.70,29.19,15.37,46622.0,-19135.0,159720.0,34390.26,-27.37,39.0,X-MC,4.40,58.0,-0.41,1.03,8.19,X40,ATH,PHARMA
40,ICICIPRULI,-1.44,-16.96,56.89,30.28,93065.0,-33418.0,163587.0,787.27,-46.81,47.0,X-MC,12.73,78.0,-0.36,1.06,8.99,X40,ATH,INSURANCE
39,ICICIGI,-0.02,-13.87,38.03,18.89,65547.0,-27753.0,172356.0,2244.41,-14.07,41.0,X-MC,10.51,66.0,-0.42,1.12,2.68,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.23,-25.60,67.59,24.70,199790.0,-101687.0,295591.0,452.00,-30.75,31.0,X-LC,10.47,1.0,-0.51,1.92,0.00,X40,NTT,FMCG
73,TCS,-1.27,-32.96,85.25,24.20,264784.0,-152676.0,310597.0,4230.71,-44.31,46.0,X-LC,14.50,2.0,-0.58,2.01,15.82,X40,ATH,IT
45,INFY,-2.09,-20.55,76.69,40.38,229391.0,-77355.0,299115.0,1972.00,-41.63,46.0,X-LC,15.93,3.0,-0.34,1.94,13.28,X40,NTT,IT
75,TMPV,-2.12,-23.10,85.64,42.75,274021.0,-96139.0,319968.0,600.00,-84.91,36.0,X-LC,4.44,4.0,-0.35,2.07,10.02,XY24,NTT,AUTO
33,HCLTECH,-4.78,-13.38,43.12,23.97,115590.0,-41421.0,268065.0,1853.42,-15.52,50.0,X-LC,11.79,8.0,-0.36,1.74,26.50,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.81,-25.25,77.78,32.89,44888.0,-19494.0,57712.0,1800.00,325.21,51.0,L-MC,13.17,258.0,-0.43,0.37,42.28,XR,NTT,BANKS
60,RELAXO,-3.12,-50.28,206.33,52.31,148915.0,-72987.0,72173.0,1176.00,NaN,42.0,NaN,13.20,92.0,-0.49,0.47,61.37,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.82,-19.03,137.79,92.54,112646.0,-19211.0,81752.0,4520.85,NaN,54.0,NaN,14.01,142.0,-0.17,0.53,55.24,SR,ATH,CHEMICALS
12,BOSCH-HCIL,4.05,-24.58,32.58,-0.01,31403.0,-31418.0,96387.0,2282.00,752.82,76.0,M-SC,6.02,231.0,-1.00,0.62,64.06,OX40N,BTT,AC
81,VALIANTORG,-5.08,-35.99,172.08,74.15,180202.0,-58885.0,104720.0,838.00,NaN,58.0,NaN,6.28,145.0,-0.33,0.68,55.84,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.77,68.58,23.33,107.91,58068.0,101253.0,248897.0,1641.55,22.65,76.0,M-SC,19.24,220.0,1.74,1.61,87.25,OX40N,ATH,CABLES
12,BOSCH-HCIL,4.05,-24.58,32.58,-0.01,31403.0,-31418.0,96387.0,2282.00,752.82,76.0,M-SC,6.02,231.0,-1.00,0.62,64.06,OX40N,BTT,AC
81,VALIANTORG,-5.08,-35.99,172.08,74.15,180202.0,-58885.0,104720.0,838.00,NaN,58.0,NaN,6.28,145.0,-0.33,0.68,55.84,XR,NTT,CHEMICALS
38,HYUNDAI,0.68,14.04,26.21,43.94,75124.0,35292.0,286624.0,2782.73,18.18,65.0,X-LC,5.00,29.0,0.47,1.86,31.60,X40N,ATH,AUTO
11,BERGEPAINT,-0.60,0.09,25.21,25.32,65035.0,223.0,257972.0,680.00,-12.92,59.0,X-MC,4.06,68.0,0.00,1.67,35.28,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.75
1     25       45.12
2     50       77.59

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.09
MC    22.18
SC    21.64
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.57
XY24     24.01
X40N     18.65
XR        9.11
OX40N     7.37
XY25      7.26
AR        6.13
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.39
X-MC    19.56
H-SC     8.50
X-SC     7.66
M-SC     5.48
H-LC     2.89
M-MC     1.21
H-MC     1.04
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.47        -24.84   69.72
IT                  11.09        -39.37  108.49
FINANCE             10.77        -16.15   66.19
AUTO                 8.31         -5.44   43.21
BANKS                6.13        -12.76   61.39
MISC                 5.94        -34.09   88.03
PHARMA               5.74          6.63   19.86
INSURANCE            5.74         -4.87   41.95
PAINTS               5.51        -15.93   35.71
ELECTRICAL           4.23         -8.44   42.39
AC                   1.83        -12.55   43.07
REFINERIES           1.75        -10.33   47.39
BREWERIES            1.70         10.99    7.50
FOOTWEAR             1.68        -71.13  139.75
APPARELS             1.66         -4.75   39.94
CABLES               1.61         40.68   23.33
DURABLES             1.48        -68.73  109.78
TRAVEL               1.43       -101.84  202.90
CERAMICS             1.34        -48.05   93.03
ENGINEERING          1.22        -28.92   87.89
CHEMICALS            1.21        -41.88  157.05
CEMENT               1.02        -71.02  198.97
JEWELLERY            0.96       -116.20  191.32
ENTERTAINMENT        0.69        -80.34  187.89
HEALTHCARE           0.69        -70.90  113.80
TEXTILES             0.39        -51.40   94.57
HOTELS               0.37        -99.12  169.36

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3620349.0     19
X40       2124978.0     18
XR        1391292.0     13
X40N      1200983.0     12
AR        1057773.0      8
OX40N      651637.0     10
XY25       578297.0      5
SR         283308.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2419144.0     19
X-MC        1482975.0     14
X-SC        1096331.0      6
H-SC         837897.0      8
M-SC         317825.0      6
H-MC         252475.0      1
M-LC         167453.0      1
M-MC          58518.0      1
L-MC          44888.0      1
H-LC          44504.0      2

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1240386.0      9
X-SC       XY24       671943.0      2
H-SC       XY24       527356.0      3
X-MC       X40        520627.0      6
           X40N       468608.0      4
X-LC       XY24       455331.0      2
           X40N       411637.0      5
X-MC       XY25       268171.0      2
X-SC       X40        252565.0      2
H-MC       XY24       252475.0      1
X-LC       XY25       251608.0      2
X-MC       XY24       225569.0      2
H-SC       OX40N      216554.0      3
X-SC       X40N       171823.0      2
M-LC       XR         167453.0      1
M-SC       OX40N      144175.0      4
           XY24       116024.0      1
H-SC       XR          93987.0      2
X-LC       XR          60182.0      1
M-MC       XY25        58518.0      1
M-SC       XR          57626.0      1
L-MC       XR          44888.0      1
H-LC       AR          44504.0      2

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds