<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-08 14:30:34
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.36 C
-------------------
Today PnL: 4.73 L (3.6%)
Current PnL: -40.77 L (-25.09%)
CY Booked + Current PnL: -24.88 L (-15.31%)
-------------------
Total profit:  1.05 L
Total loss:  -41.82 L
-------------------
Total Booked + Current PnL: 2.10 L (1.55%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.65%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.12 C (81.79%)
===================
Deployed:  1.36 C
Current:  1.36 C
CAGR/XIRR %: 0.3%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,3.69,-4.98,27.93,21.57,26004.0,-4875.0,93105.0,397.04,-18.25,54.0,H-SC,4.86,167.0,-0.19,0.68,22.50,XR,ATH,FINANCE
77,TTKPRESTIG,2.78,-37.12,59.19,0.09,37506.0,-37412.0,63365.0,770.00,47.07,50.0,M-SC,22.12,250.0,-1.00,0.46,12.83,OX40N,NTT,DURABLES
5,ANGELONE,8.40,9.33,13.58,24.18,45284.0,28462.0,333462.0,303.00,-84.36,67.0,X-SC,7.63,97.0,0.63,2.45,27.57,X40N,NTT,FINANCE
67,SONACOMS,3.96,-7.35,50.13,39.09,46982.0,-7438.0,93721.0,804.02,-26.55,60.0,M-MC,7.69,193.0,-0.16,0.69,32.58,AR,ATH,AUTO
37,ICICIGI,0.98,-7.64,29.22,19.34,54002.0,-15298.0,184811.0,2252.93,-22.28,41.0,X-MC,6.94,66.0,-0.28,1.36,3.22,X40,ATH,INSURANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,EASEMYTRIP,19.94,-55.52,227.54,45.70,178958.0,-98166.0,78649.0,26.4,-18.31,63.0,M-SC,14.48,204.0,-0.55,0.58,37.78,XY24,NTT,TRAVEL
56,RAJOOENG,12.34,-37.66,123.94,39.61,79198.0,-38600.0,63900.0,143.1,-57.76,61.0,H-SC,33.53,136.0,-0.49,0.47,36.89,AR,ATH,MISC
14,BOSCH-HCIL,9.99,-44.05,78.73,-0.01,56293.0,-56304.0,71501.0,2282.0,14530.43,53.0,M-SC,9.53,231.0,-1.00,0.52,21.70,OX40N,BTT,AC
11,BANDHANBNK,8.68,-22.03,146.79,92.42,318809.0,-61372.0,217187.0,400.0,86.06,52.0,H-SC,2.42,174.0,-0.19,1.59,19.64,XY24,NTT,BANKS
19,COFFEEDAY,8.55,-56.87,213.60,35.27,104619.0,-64570.0,48979.0,80.0,-67.81,50.0,L-SC,32.97,266.0,-0.62,0.36,20.79,XR,NTT,HOTELS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,-1.90,5.31,23.06,29.60,60616.0,13260.0,262860.0,5391.45,-11.22,67.0,X-LC,5.36,14.0,0.22,1.93,20.15,X40N,ATH,FMCG
84,WIPRO,-0.79,-16.70,106.79,72.27,150738.0,-28294.0,141154.0,420.00,-25.02,55.0,M-LC,17.77,98.0,-0.19,1.04,8.30,XR,NTT,IT
53,PGHH,-0.09,-27.32,81.64,32.01,126692.0,-58336.0,155184.0,17616.87,-50.89,36.0,X-MC,20.27,57.0,-0.46,1.14,6.14,X40,ATH,FMCG
49,LAOPALA,0.05,-47.54,165.14,39.09,113575.0,-62330.0,68775.0,464.00,50.07,40.0,H-SC,18.55,154.0,-0.55,0.50,6.71,AR,NTT,CERAMICS
8,AWL,0.27,-38.17,170.13,67.02,374790.0,-136013.0,220296.0,485.00,-66.76,45.0,X-SC,25.68,81.0,-0.36,1.62,4.20,XY24,NTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,4.02,6.78,94.70,107.91,149304.0,10016.0,157660.0,1641.55,-4.11,52.0,M-SC,3.11,220.0,0.07,1.16,18.61,OX40N,ATH,CABLES
66,SIS,2.71,-32.02,78.38,21.26,59161.0,-35552.0,75480.0,528.00,1770.47,54.0,H-SC,14.70,168.0,-0.60,0.55,12.23,OX40N,NTT,MISC
18,CERA,5.34,-33.76,87.03,23.89,101406.0,-59385.0,116518.0,9475.00,-36.04,61.0,H-SC,18.54,153.0,-0.59,0.85,11.97,OX40N,NTT,CERAMICS
72,TATAELXSI,1.53,-36.24,107.06,32.03,89997.0,-47773.0,84062.0,9161.00,-20.19,53.0,H-SC,21.34,158.0,-0.53,0.62,11.26,OX40N,NTT,IT
77,TTKPRESTIG,2.78,-37.12,59.19,0.09,37506.0,-37412.0,63365.0,770.00,47.07,50.0,M-SC,22.12,250.0,-1.00,0.46,12.83,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,4.68,20.4,20.9,45.57,65835.0,53381.0,315000.0,7934.0,-22.66,65.0,H-MC,14.34,125.0,0.81,2.31,39.88,AR,NTT,ELECTRICAL

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,4.02,6.78,94.7,107.91,149304.0,10016.0,157660.0,1641.55,-4.11,52.0,M-SC,3.11,220.0,0.07,1.16,18.61,OX40N,ATH,CABLES
1,ABB,4.68,20.40,20.9,45.57,65835.0,53381.0,315000.0,7934.00,-22.66,65.0,H-MC,14.34,125.0,0.81,2.31,39.88,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,4.68,20.40,20.90,45.57,65835.0,53381.0,315000.0,7934.00,-22.66,65.0,H-MC,14.34,125.0,0.81,2.31,39.88,AR,NTT,ELECTRICAL
26,FINCABLES,4.02,6.78,94.70,107.91,149304.0,10016.0,157660.0,1641.55,-4.11,52.0,M-SC,3.11,220.0,0.07,1.16,18.61,OX40N,ATH,CABLES
40,INDIAMART,2.34,-9.69,128.90,106.72,143575.0,-11951.0,111385.0,4810.62,-59.18,53.0,H-SC,12.83,140.0,-0.08,0.82,8.05,AR,ATH,MISC
85,ZYDUSLIFE,1.93,-6.11,44.46,35.63,87483.0,-12807.0,196767.0,1286.17,-18.47,50.0,H-MC,6.04,120.0,-0.15,1.44,9.54,AR,ATH,PHARMA
67,SONACOMS,3.96,-7.35,50.13,39.09,46982.0,-7438.0,93721.0,804.02,-26.55,60.0,M-MC,7.69,193.0,-0.16,0.69,32.58,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
53,PGHH,-0.09,-27.32,81.64,32.01,126692.0,-58336.0,155184.0,17616.87,-50.89,36.0,X-MC,20.27,57.0,-0.46,1.14,6.14,X40,ATH,FMCG
21,DABUR,3.08,-16.52,72.13,43.70,149378.0,-40973.0,207095.0,735.00,-24.27,39.0,X-MC,12.91,70.0,-0.27,1.52,4.03,XY24,BTT,FMCG
36,HONAUT,0.68,-28.96,112.98,51.31,154783.0,-55838.0,137000.0,58357.33,-40.87,39.0,X-SC,18.72,90.0,-0.36,1.00,4.08,X40N,ATH,ELECTRICAL
38,ICICIPRULI,4.64,-10.54,46.13,30.73,81298.0,-20769.0,176236.0,790.00,-34.56,40.0,X-MC,10.81,78.0,-0.26,1.29,7.39,X40,ATH,INSURANCE
82,VOLTAS,3.45,-1.25,47.03,45.20,89049.0,-2397.0,189345.0,1856.00,13.01,40.0,X-MC,5.01,79.0,-0.03,1.39,5.46,XY25,NTT,AC

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,4.33,-13.79,45.58,25.51,73129.0,-25655.0,160440.0,4671.50,34.82,55.0,H-LC,0.95,51.0,-0.35,1.18,18.15,AR,ATH,ELECTRICAL
59,RELIANCE,3.31,-13.48,44.83,25.30,77944.0,-27097.0,173866.0,1952.00,-15.80,44.0,X-LC,4.44,21.0,-0.35,1.28,14.46,XY25,BTT,REFINERIES
78,UNITDSPR,0.85,-8.28,31.67,20.77,68014.0,-19385.0,214759.0,1644.00,-18.64,41.0,X-MC,4.59,64.0,-0.29,1.58,2.45,X40N,NTT,BREWERIES
82,VOLTAS,3.45,-1.25,47.03,45.20,89049.0,-2397.0,189345.0,1856.00,13.01,40.0,X-MC,5.01,79.0,-0.03,1.39,5.46,XY25,NTT,AC
24,DMART,-1.90,5.31,23.06,29.60,60616.0,13260.0,262860.0,5391.45,-11.22,67.0,X-LC,5.36,14.0,0.22,1.93,20.15,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,0.84,-13.18,35.99,18.07,55885.0,-23575.0,155280.0,35195.00,-26.09,44.0,X-MC,11.08,58.0,-0.42,1.14,1.55,X40,ATH,PHARMA
78,UNITDSPR,0.85,-8.28,31.67,20.77,68014.0,-19385.0,214759.0,1644.00,-18.64,41.0,X-MC,4.59,64.0,-0.29,1.58,2.45,X40N,NTT,BREWERIES
37,ICICIGI,0.98,-7.64,29.22,19.34,54002.0,-15298.0,184811.0,2252.93,-22.28,41.0,X-MC,6.94,66.0,-0.28,1.36,3.22,X40,ATH,INSURANCE
21,DABUR,3.08,-16.52,72.13,43.70,149378.0,-40973.0,207095.0,735.00,-24.27,39.0,X-MC,12.91,70.0,-0.27,1.52,4.03,XY24,BTT,FMCG
36,HONAUT,0.68,-28.96,112.98,51.31,154783.0,-55838.0,137000.0,58357.33,-40.87,39.0,X-SC,18.72,90.0,-0.36,1.00,4.08,X40N,ATH,ELECTRICAL

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,3.83,-63.71,319.70,52.31,168412.0,-92482.0,52678.0,1176.00,-61.38,45.0,X-SC,32.69,92.0,-0.55,0.39,17.78,X40N,NTT,FOOTWEAR
12,BATAINDIA,4.97,-54.67,198.26,35.20,115641.0,-70342.0,58328.0,2096.00,-23.47,51.0,X-SC,34.37,91.0,-0.61,0.43,15.68,X40,NTT,FOOTWEAR
54,QUESS,3.83,-22.34,123.91,73.90,102771.0,-23853.0,82940.0,424.00,-58.13,55.0,X-SC,22.41,80.0,-0.23,0.61,11.57,XY24,NTT,MISC
36,HONAUT,0.68,-28.96,112.98,51.31,154783.0,-55838.0,137000.0,58357.33,-40.87,39.0,X-SC,18.72,90.0,-0.36,1.00,4.08,X40N,ATH,ELECTRICAL
53,PGHH,-0.09,-27.32,81.64,32.01,126692.0,-58336.0,155184.0,17616.87,-50.89,36.0,X-MC,20.27,57.0,-0.46,1.14,6.14,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,1.74,-20.02,48.86,19.06,132933.0,-68096.0,272070.0,452.00,-55.92,51.0,X-LC,19.76,1.0,-0.51,2.00,5.54,X40,NTT,FMCG
73,TCS,0.65,-24.96,68.66,26.57,238701.0,-115616.0,347657.0,4311.58,-36.41,55.0,X-LC,18.48,2.0,-0.48,2.55,8.50,X40,ATH,IT
43,INFY,0.37,-8.49,46.69,34.24,133690.0,-26552.0,286336.0,1972.00,-28.16,57.0,X-LC,14.51,3.0,-0.20,2.10,10.12,X40,NTT,IT
75,TMPV,8.54,-23.73,79.08,36.58,214615.0,-84451.0,271390.0,600.00,-83.62,54.0,X-LC,12.41,4.0,-0.39,1.99,13.12,XY24,NTT,AUTO
33,HCLTECH,0.79,-5.71,31.33,23.83,71470.0,-13803.0,228121.0,1908.19,-0.74,61.0,X-LC,10.56,8.0,-0.19,1.67,10.76,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,3.96,-7.35,50.13,39.09,46982.0,-7438.0,93721.0,804.02,-26.55,60.0,M-MC,7.69,193.0,-0.16,0.69,32.58,AR,ATH,AUTO
24,DMART,-1.90,5.31,23.06,29.60,60616.0,13260.0,262860.0,5391.45,-11.22,67.0,X-LC,5.36,14.0,0.22,1.93,20.15,X40N,ATH,FMCG
1,ABB,4.68,20.40,20.90,45.57,65835.0,53381.0,315000.0,7934.00,-22.66,65.0,H-MC,14.34,125.0,0.81,2.31,39.88,AR,NTT,ELECTRICAL
5,ANGELONE,8.40,9.33,13.58,24.18,45284.0,28462.0,333462.0,303.00,-84.36,67.0,X-SC,7.63,97.0,0.63,2.45,27.57,X40N,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,1.84,-44.64,214.58,74.15,194352.0,-73032.0,90573.0,838.00,-262.82,61.0,H-SC,25.01,145.0,-0.38,0.66,34.79,XR,NTT,CHEMICALS
5,ANGELONE,8.40,9.33,13.58,24.18,45284.0,28462.0,333462.0,303.00,-84.36,67.0,X-SC,7.63,97.0,0.63,2.45,27.57,X40N,NTT,FINANCE
52,PAGEIND,1.37,-7.35,44.76,34.11,111291.0,-19739.0,248640.0,51418.63,-33.55,69.0,X-MC,18.57,55.0,-0.18,1.82,17.62,X40,ATH,APPARELS
30,HAPPSTMNDS,1.11,-52.31,287.62,84.85,175793.0,-67045.0,61120.0,1480.71,-43.28,49.0,H-SC,23.19,152.0,-0.38,0.45,13.19,AR,ATH,IT
25,EASEMYTRIP,19.94,-55.52,227.54,45.70,178958.0,-98166.0,78649.0,26.40,-18.31,63.0,M-SC,14.48,204.0,-0.55,0.58,37.78,XY24,NTT,TRAVEL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.10
1     25       46.05
2     50       77.80

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.03
MC    29.31
LC    25.68
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.28
X40      25.11
X40N     15.41
AR        9.20
XR        8.46
XY25      7.03
OX40N     6.74
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.46
H-SC    22.10
X-MC    21.86
X-SC    12.31
M-SC    10.06
H-MC     5.03
M-MC     2.07
H-LC     1.18
M-LC     1.04
L-SC     0.56
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.85        -23.55   67.39
FINANCE             13.47        -17.04   64.74
IT                  12.00        -37.86  108.02
MISC                 7.12        -38.09   98.08
ELECTRICAL           6.41        -10.80   53.23
PAINTS               5.20        -38.94   63.06
BANKS                4.64        -21.58   83.30
INSURANCE            4.53         -9.97   47.60
PHARMA               3.97         -8.58   42.76
AUTO                 3.76        -27.51   78.10
HEALTHCARE           1.94        -34.87   70.06
AC                   1.91        -22.50   55.72
TRAVEL               1.86        -76.64  165.09
FOOTWEAR             1.84        -76.36  147.07
APPARELS             1.82         -7.94   44.76
DURABLES             1.75        -61.55  100.86
BREWERIES            1.58         -9.03   31.67
REALTY               1.40        -15.90   34.94
CERAMICS             1.35        -65.69  116.02
REFINERIES           1.28        -15.58   44.83
CEMENT               1.25        -57.84  175.93
ENGINEERING          1.19        -49.08  117.26
CABLES               1.16          6.35   94.70
CHEMICALS            1.09        -76.60  220.68
JEWELLERY            1.06       -122.00  199.12
ENTERTAINMENT        0.78        -82.52  191.39
TEXTILES             0.45        -48.92   91.39
HOTELS               0.36       -131.83  213.60

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3877393.0     21
X40       1750587.0     16
XR        1338255.0     12
AR        1318199.0     10
X40N      1200755.0     10
OX40N      871810.0     10
XY25       484090.0      5
SR         311077.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3779884.0     24
X-MC        1755821.0     15
X-LC        1576479.0     13
M-SC        1542556.0     14
X-SC        1506124.0     10
H-MC         392418.0      3
L-SC         215131.0      2
M-LC         150738.0      1
M-MC         104631.0      2
H-LC          73129.0      1
L-MC          55255.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1289816.0      6
           AR         967010.0      5
M-SC       XY24       887836.0      6
X-LC       X40        846910.0      7
X-SC       XY24       840961.0      4
H-SC       XR         840014.0      7
X-MC       X40        688804.0      7
           X40N       530455.0      4
X-SC       X40N       450290.0      4
M-SC       OX40N      389331.0      5
H-SC       OX40N      371967.0      4
X-LC       XY24       354409.0      2
H-SC       SR         311077.0      2
X-MC       XY25       271291.0      2
           XY24       265271.0      2
H-MC       XY24       239100.0      1
X-LC       X40N       220010.0      2
X-SC       X40        214873.0      2
M-SC       XR         187629.0      2
X-LC       XY25       155150.0      2
H-MC       AR         153318.0      2
M-LC       XR         150738.0      1
L-SC       OX40N      110512.0      1
           XR         104619.0      1
M-SC       AR          77760.0      1
H-LC       AR          73129.0      1
M-MC       XY25        57649.0      1
L-MC       XR          55255.0      1
M-MC       AR          46982.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 38.0 seconds