<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-18 12:44:31
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.58 C
-------------------
Today PnL: -1.20 L (-0.76%)
Current PnL: -34.92 L (-18.48%)
CY Booked + Current PnL: -29.86 L (-15.8%)
-------------------
Total profit:  3.30 L
Total loss:  -38.22 L
-------------------
Total Booked + Current PnL: 13.01 L (8.91%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.2%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (69.03%)
===================
Deployed:  1.46 C
Current:  1.58 C
CAGR/XIRR %: 3.58%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.10,6.04,4.52,10.83,8920.0,11245.0,197340.0,4125.00,-14.10,63.0,H-LC,13.58,51.0,1.26,1.28,39.23,AR,NTT,ELECTRICAL
78,UNITDSPR,-0.50,12.93,6.94,20.77,18350.0,30272.0,264416.0,1644.00,-3.65,64.0,X-MC,10.97,64.0,1.65,1.71,27.10,X40N,NTT,BREWERIES
77,TTKPRESTIG,0.41,-22.72,29.52,0.09,22990.0,-22897.0,77880.0,770.00,-6.01,42.0,M-SC,10.22,250.0,-1.00,0.50,40.17,OX40N,NTT,DURABLES
52,M&M,1.04,8.17,9.85,18.82,25643.0,19657.0,260338.0,3762.88,-6.55,59.0,X-LC,4.80,25.0,0.77,1.69,18.09,X40N,ATH,AUTO
54,MASFIN,0.45,-7.27,31.10,21.57,28256.0,-7125.0,90855.0,397.04,-28.64,42.0,H-SC,1.23,167.0,-0.25,0.59,8.30,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,3.51,-24.98,33.28,-0.01,31910.0,-31922.0,95883.0,2282.00,748.39,76.0,M-SC,6.00,231.0,-1.00,0.62,63.21,OX40N,BTT,AC
18,COFFEEDAY,2.46,-50.07,170.91,35.27,96903.0,-56851.0,56698.0,80.00,NaN,40.0,NaN,3.92,266.0,-0.59,0.37,39.82,XR,NTT,HOTELS
0,5PAISA,1.82,-25.59,51.74,12.90,84115.0,-55923.0,162573.0,593.00,4.20,61.0,H-SC,11.65,170.0,-0.66,1.05,56.88,OX40N,NTT,FINANCE
24,EASEMYTRIP,1.14,-65.78,325.81,45.70,197115.0,-116315.0,60500.0,26.40,NaN,35.0,NaN,7.22,204.0,-0.59,0.39,5.98,XY24,NTT,TRAVEL
38,HYUNDAI,1.10,14.52,25.68,43.94,73916.0,36501.0,287833.0,2782.73,18.51,66.0,X-LC,5.01,29.0,0.49,1.86,32.15,X40N,ATH,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,-4.67,-55.65,222.74,43.14,180860.0,-101880.0,81198.0,537.00,NaN,28.0,NaN,10.98,225.0,-0.56,0.53,0.00,XY24,NTT,MISC
33,HCLTECH,-4.61,-13.23,42.87,23.97,115124.0,-40945.0,268541.0,1853.42,-15.52,50.0,X-LC,11.79,8.0,-0.36,1.74,26.72,X40,ATH,IT
81,VALIANTORG,-4.47,-35.58,170.32,74.15,179517.0,-58205.0,105400.0,838.00,NaN,59.0,NaN,6.31,145.0,-0.32,0.68,56.85,XR,NTT,CHEMICALS
71,TANLA,-4.31,-37.06,245.15,117.25,417802.0,-100334.0,170427.0,1922.32,NaN,42.0,NaN,15.34,147.0,-0.24,1.10,49.21,AR,ATH,IT
19,COLPAL,-3.35,-27.30,92.38,39.86,176880.0,-71895.0,191470.0,3683.41,-12.03,31.0,X-MC,1.38,62.0,-0.41,1.24,8.31,XY25,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,UTIAMC,-1.05,-0.99,52.66,51.15,115922.0,-2198.0,220132.0,1371.68,25.0,44.0,M-SC,7.67,229.0,-0.02,1.43,3.11,XY24,ATH,FINANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.76,66.02,25.23,107.91,61844.0,97476.0,245120.0,1641.55,21.20,74.0,M-SC,19.20,220.0,1.58,1.59,84.41,OX40N,ATH,CABLES
67,SIS,-0.31,-4.66,27.18,21.26,28774.0,-5169.0,105863.0,528.00,103.25,38.0,H-SC,20.96,168.0,-0.18,0.69,57.40,OX40N,NTT,MISC
43,INDIGOPNTS,0.30,-18.15,22.20,0.02,31718.0,-31686.0,142873.0,1408.00,-21.90,65.0,M-SC,6.75,222.0,-1.00,0.93,62.10,OX40N,NTT,PAINTS
77,TTKPRESTIG,0.41,-22.72,29.52,0.09,22990.0,-22897.0,77880.0,770.00,-6.01,42.0,M-SC,10.22,250.0,-1.00,0.50,40.17,OX40N,NTT,DURABLES
12,BOSCH-HCIL,3.51,-24.98,33.28,-0.01,31910.0,-31922.0,95883.0,2282.00,748.39,76.0,M-SC,6.00,231.0,-1.00,0.62,63.21,OX40N,BTT,AC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.76,66.02,25.23,107.91,61844.0,97476.0,245120.0,1641.55,21.2,74.0,M-SC,19.2,220.0,1.58,1.59,84.41,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.76,66.02,25.23,107.91,61844.0,97476.0,245120.0,1641.55,21.20,74.0,M-SC,19.20,220.0,1.58,1.59,84.41,OX40N,ATH,CABLES
68,STARHEALTH,-0.24,12.96,30.36,47.26,96411.0,36437.0,317560.0,761.00,-0.37,50.0,H-SC,16.28,173.0,0.38,2.06,37.30,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.76,66.02,25.23,107.91,61844.0,97476.0,245120.0,1641.55,21.20,74.0,M-SC,19.20,220.0,1.58,1.59,84.41,OX40N,ATH,CABLES
3,ALKYLAMINE,-0.72,-18.95,137.55,92.54,112561.0,-19130.0,81833.0,4520.85,NaN,55.0,NaN,14.01,142.0,-0.17,0.53,55.39,SR,ATH,CHEMICALS
67,SIS,-0.31,-4.66,27.18,21.26,28774.0,-5169.0,105863.0,528.00,103.25,38.0,H-SC,20.96,168.0,-0.18,0.69,57.40,OX40N,NTT,MISC
42,INDIAMART,-2.49,-25.00,167.88,100.92,155299.0,-30830.0,92506.0,4675.60,NaN,36.0,NaN,13.44,140.0,-0.20,0.60,0.14,AR,ATH,MISC
71,TANLA,-4.31,-37.06,245.15,117.25,417802.0,-100334.0,170427.0,1922.32,NaN,42.0,NaN,15.34,147.0,-0.24,1.10,49.21,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-0.76,-15.65,57.57,32.90,121170.0,-39063.0,210474.0,1460.97,-17.22,30.0,X-MC,5.72,32.0,-0.32,1.36,2.45,X40N,ATH,FMCG
19,COLPAL,-3.35,-27.30,92.38,39.86,176880.0,-71895.0,191470.0,3683.41,-12.03,31.0,X-MC,1.38,62.0,-0.41,1.24,8.31,XY25,ATH,FMCG
55,PAGEIND,0.03,-4.12,39.33,33.59,101204.0,-11059.0,257320.0,51217.28,-28.69,31.0,X-MC,8.64,55.0,-0.11,1.67,22.20,X40,ATH,APPARELS
56,PGHH,-1.03,-37.50,111.23,32.01,148425.0,-80080.0,133440.0,17616.87,-54.11,31.0,X-SC,19.08,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
47,ITC,-0.84,-25.31,66.94,24.70,198639.0,-100536.0,296742.0,452.00,-30.35,32.0,X-LC,10.73,1.0,-0.51,1.92,0.00,X40,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-3.35,-27.30,92.38,39.86,176880.0,-71895.0,191470.0,3683.41,-12.03,31.0,X-MC,1.38,62.0,-0.41,1.24,8.31,XY25,ATH,FMCG
23,DMART,0.03,-2.59,34.91,31.42,106028.0,-8071.0,303719.0,5391.45,-18.33,48.0,X-LC,2.30,14.0,-0.08,1.97,9.60,X40N,ATH,FMCG
50,KOTAKBANK,-0.50,2.70,15.79,18.92,38871.0,6470.0,246172.0,452.46,-13.30,50.0,X-LC,2.33,12.0,0.17,1.60,10.76,X40,ATH,BANKS
26,GILLETTE,-0.65,-11.14,46.00,29.72,103776.0,-28296.0,225600.0,10978.86,-35.84,37.0,X-SC,3.54,83.0,-0.27,1.46,3.67,X40,ATH,FMCG
83,VOLTAS,-1.13,-2.00,48.16,45.20,90495.0,-3837.0,187905.0,1856.00,34.99,39.0,X-MC,4.29,79.0,-0.04,1.22,2.99,XY25,NTT,AC

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.95,-21.22,82.40,43.70,161035.0,-52637.0,195431.0,735.00,-32.11,35.0,X-MC,9.94,70.0,-0.33,1.27,0.00,XY24,BTT,FMCG
47,ITC,-0.84,-25.31,66.94,24.70,198639.0,-100536.0,296742.0,452.00,-30.35,32.0,X-LC,10.73,1.0,-0.51,1.92,0.00,X40,NTT,FMCG
56,PGHH,-1.03,-37.50,111.23,32.01,148425.0,-80080.0,133440.0,17616.87,-54.11,31.0,X-SC,19.08,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.58,-11.48,48.05,31.05,124671.0,-33660.0,259460.0,1073.00,-28.50,34.0,X-LC,12.67,26.0,-0.27,1.68,0.71,X40,BTT,BANKS
35,HDFCLIFE,-0.49,-7.33,50.16,39.15,116547.0,-18387.0,232350.0,811.41,-31.88,43.0,X-LC,16.67,31.0,-0.16,1.51,0.84,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-1.03,-37.50,111.23,32.01,148425.0,-80080.0,133440.0,17616.87,-54.11,31.0,X-SC,19.08,57.0,-0.54,0.86,0.00,X40,ATH,FMCG
2,ACC,-0.35,-41.28,197.71,74.81,311275.0,-110688.0,157440.0,3906.00,-41.79,39.0,X-SC,11.66,85.0,-0.36,1.02,5.18,XY24,BTT,CEMENT
1,ABBOTINDIA,-1.90,-10.95,29.55,15.37,47064.0,-19585.0,159270.0,34390.26,-27.58,40.0,X-MC,4.68,58.0,-0.42,1.03,7.89,X40,ATH,PHARMA
40,ICICIPRULI,-1.28,-16.82,56.62,30.28,92780.0,-33141.0,163864.0,787.27,-46.69,48.0,X-MC,12.73,78.0,-0.36,1.06,9.18,X40,ATH,INSURANCE
39,ICICIGI,-0.07,-13.91,38.10,18.89,65635.0,-27838.0,172271.0,2244.41,-14.33,41.0,X-MC,10.51,66.0,-0.42,1.12,2.63,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.84,-25.31,66.94,24.70,198639.0,-100536.0,296742.0,452.00,-30.35,32.0,X-LC,10.73,1.0,-0.51,1.92,0.00,X40,NTT,FMCG
73,TCS,-1.09,-32.84,84.92,24.20,264232.0,-152119.0,311154.0,4230.71,-44.31,47.0,X-LC,14.50,2.0,-0.58,2.02,16.03,X40,ATH,IT
45,INFY,-2.11,-20.57,76.73,40.38,229449.0,-77436.0,299034.0,1972.00,-41.63,46.0,X-LC,15.93,3.0,-0.34,1.94,13.24,X40,NTT,IT
75,TMPV,-1.70,-22.77,84.84,42.75,272637.0,-94753.0,321354.0,600.00,-83.84,37.0,X-LC,4.60,4.0,-0.35,2.08,10.50,XY24,NTT,AUTO
33,HCLTECH,-4.61,-13.23,42.87,23.97,115124.0,-40945.0,268541.0,1853.42,-15.52,50.0,X-LC,11.79,8.0,-0.36,1.74,26.72,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.89,-25.02,77.24,32.89,44713.0,-19318.0,57889.0,1800.00,325.93,54.0,L-MC,13.53,258.0,-0.43,0.38,42.72,XR,NTT,BANKS
60,RELAXO,-3.08,-50.26,206.21,52.31,148886.0,-72959.0,72201.0,1176.00,NaN,42.0,NaN,13.20,92.0,-0.49,0.47,61.43,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.72,-18.95,137.55,92.54,112561.0,-19130.0,81833.0,4520.85,NaN,55.0,NaN,14.01,142.0,-0.17,0.53,55.39,SR,ATH,CHEMICALS
12,BOSCH-HCIL,3.51,-24.98,33.28,-0.01,31910.0,-31922.0,95883.0,2282.00,748.39,76.0,M-SC,6.00,231.0,-1.00,0.62,63.21,OX40N,BTT,AC
81,VALIANTORG,-4.47,-35.58,170.32,74.15,179517.0,-58205.0,105400.0,838.00,NaN,59.0,NaN,6.31,145.0,-0.32,0.68,56.85,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.76,66.02,25.23,107.91,61844.0,97476.0,245120.0,1641.55,21.20,74.0,M-SC,19.20,220.0,1.58,1.59,84.41,OX40N,ATH,CABLES
12,BOSCH-HCIL,3.51,-24.98,33.28,-0.01,31910.0,-31922.0,95883.0,2282.00,748.39,76.0,M-SC,6.00,231.0,-1.00,0.62,63.21,OX40N,BTT,AC
81,VALIANTORG,-4.47,-35.58,170.32,74.15,179517.0,-58205.0,105400.0,838.00,NaN,59.0,NaN,6.31,145.0,-0.32,0.68,56.85,XR,NTT,CHEMICALS
38,HYUNDAI,1.10,14.52,25.68,43.94,73916.0,36501.0,287833.0,2782.73,18.51,66.0,X-LC,5.01,29.0,0.49,1.86,32.15,X40N,ATH,AUTO
11,BERGEPAINT,-0.33,0.12,25.16,25.32,64930.0,318.0,258067.0,680.00,-12.92,59.0,X-MC,4.84,68.0,0.00,1.67,35.33,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.79
1     25       45.19
2     50       77.64

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.15
MC    22.23
SC    21.65
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.62
XY24     24.05
X40N     18.67
XR        9.12
OX40N     7.34
XY25      7.27
AR        6.10
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.45
X-MC    19.59
H-SC     8.51
X-SC     7.67
M-SC     5.47
H-LC     2.89
M-MC     1.21
H-MC     1.05
M-LC     0.81
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.47        -24.82   69.70
IT                  11.06        -39.63  108.88
FINANCE             10.77        -16.17   66.21
AUTO                 8.32         -5.25   42.95
BANKS                6.15        -12.60   61.17
MISC                 5.97        -34.03   87.95
PHARMA               5.76          6.72   19.74
INSURANCE            5.75         -4.85   41.91
PAINTS               5.52        -15.86   35.62
ELECTRICAL           4.22         -8.63   42.64
AC                   1.84        -12.60   43.13
REFINERIES           1.75        -10.41   47.50
BREWERIES            1.71         11.45    6.94
FOOTWEAR             1.68        -71.13  139.75
APPARELS             1.67         -4.30   39.33
CABLES               1.59         39.77   25.23
DURABLES             1.48        -68.54  109.54
TRAVEL               1.44       -101.41  202.26
CERAMICS             1.33        -49.01   94.28
CHEMICALS            1.21        -41.30  156.00
ENGINEERING          1.21        -29.76   89.10
CEMENT               1.02        -70.30  197.71
JEWELLERY            0.96       -116.62  191.89
ENTERTAINMENT        0.69        -80.40  188.00
HEALTHCARE           0.69        -70.42  113.20
TEXTILES             0.40        -51.09   94.17
HOTELS               0.37       -100.27  170.91

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3618783.0     19
X40       2119709.0     18
XR        1390631.0     13
X40N      1199323.0     12
AR        1062678.0      8
OX40N      657908.0     10
XY25       577343.0      5
SR         283029.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2412134.0     19
X-MC        1480460.0     14
X-SC        1096331.0      6
H-SC         838020.0      8
M-SC         321882.0      6
H-MC         252093.0      1
M-LC         167253.0      1
M-MC          58220.0      1
L-MC          44713.0      1
H-LC          44690.0      2

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1237329.0      9
X-SC       XY24       672067.0      2
H-SC       XY24       526952.0      3
X-MC       X40        518751.0      6
           X40N       468369.0      4
X-LC       XY24       452968.0      2
           X40N       410005.0      5
X-MC       XY25       267375.0      2
X-SC       X40        252201.0      2
H-MC       XY24       252093.0      1
X-LC       XY25       251748.0      2
X-MC       XY24       225965.0      2
H-SC       OX40N      217124.0      3
X-SC       X40N       172063.0      2
M-LC       XR         167253.0      1
M-SC       OX40N      148462.0      4
           XY24       115922.0      1
H-SC       XR          93944.0      2
X-LC       XR          60084.0      1
M-MC       XY25        58220.0      1
M-SC       XR          57498.0      1
L-MC       XR          44713.0      1
H-LC       AR          44690.0      2

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds