<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-28 15:43:04
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: -91.34 K (-0.61%)
Current PnL: -34.41 L (-18.87%)
CY Booked + Current PnL: -32.33 L (-17.73%)
-------------------
Total profit:  1.39 L
Total loss:  -35.80 L
-------------------
Total Booked + Current PnL: 10.54 L (7.55%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.4%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.56 C
Est FTT PnL: 1.07 C (71.76%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 3.21%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-1.01,-2.43,24.60,21.57,23516.0,-2385.0,95595.0,397.04,-15.99,56.0,H-SC,1.37,167.0,-0.10,0.64,23.53,XR,ATH,FINANCE
59,PIDILITIND,-0.48,-1.31,19.94,18.37,27768.0,-1850.0,139260.0,1670.26,-30.89,54.0,X-LC,7.87,5.0,-0.07,0.94,9.34,X40,ATH,CHEMICALS
51,KOTAKBANK,0.31,0.99,19.92,21.11,27857.0,1370.0,139842.0,453.24,-13.31,50.0,X-LC,9.55,12.0,0.05,0.94,6.95,X40,ATH,BANKS
53,M&M,-0.46,0.20,23.13,23.38,32142.0,283.0,138964.0,3802.40,-15.13,46.0,X-LC,9.08,25.0,0.01,0.93,6.99,X40N,ATH,AUTO
83,TTKPRESTIG,-2.12,-33.19,49.82,0.09,33542.0,-33450.0,67327.0,770.00,56.24,58.0,M-SC,20.07,250.0,-1.00,0.45,19.89,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,4.03,-18.25,48.34,21.26,43877.0,-20265.0,90767.0,528.00,2149.22,77.0,H-SC,8.31,168.0,-0.46,0.61,34.96,OX40N,NTT,MISC
76,SYMPHONY,2.29,-33.13,49.49,-0.03,56640.0,-56693.0,114448.0,1306.00,-46.27,67.0,M-SC,14.38,205.0,-1.00,0.77,26.93,OX40N,NTT,DURABLES
73,SONACOMS,1.72,3.59,34.27,39.09,35912.0,3631.0,104790.0,804.02,-17.90,65.0,M-MC,14.13,193.0,0.10,0.70,48.24,AR,ATH,AUTO
65,RELIANCE,1.69,-10.85,40.54,25.30,72635.0,-21795.0,179168.0,1952.00,-13.11,55.0,X-LC,6.20,21.0,-0.30,1.20,6.46,XY25,BTT,REFINERIES
12,BOSCH-HCIL,1.30,-36.94,58.56,-0.01,47196.0,-47210.0,80595.0,2282.00,16400.00,64.0,M-SC,5.38,231.0,-1.00,0.54,37.18,OX40N,BTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TANLA,-4.01,-36.76,247.41,119.69,423620.0,-99539.0,171222.0,1943.92,-36.34,68.0,H-SC,19.65,147.0,-0.23,1.15,48.24,AR,ATH,IT
91,ZYDUSLIFE,-3.02,-3.90,41.14,35.63,82855.0,-8177.0,201397.0,1286.17,-16.22,49.0,H-MC,3.91,120.0,-0.10,1.35,5.89,AR,ATH,PHARMA
33,HCLTECH,-2.62,-22.38,56.55,21.51,106185.0,-54152.0,187772.0,1872.35,-18.53,29.0,X-LC,8.30,8.0,-0.51,1.26,0.00,X40,ATH,IT
56,MEDANTA,-2.59,-2.69,30.63,27.12,52613.0,-4747.0,171770.0,1486.00,-5.68,62.0,X-SC,12.83,87.0,-0.09,1.15,18.36,XY24,NTT,HEALTHCARE
54,MARUTI,-2.50,-4.06,34.13,28.68,48400.0,-6005.0,141812.0,17292.00,-21.27,42.0,X-LC,11.44,33.0,-0.12,0.95,10.05,XR,ATH,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.33,0.1,47.11,47.26,132573.0,288.0,281411.0,761.0,58.09,72.0,H-SC,5.19,173.0,0.0,1.89,45.74,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.08,27.21,63.44,107.91,119155.0,40179.0,187823.0,1641.55,14.66,73.0,M-SC,7.83,220.0,0.34,1.26,41.31,OX40N,ATH,CABLES
72,SIS,4.03,-18.25,48.34,21.26,43877.0,-20265.0,90767.0,528.00,2149.22,77.0,H-SC,8.31,168.0,-0.46,0.61,34.96,OX40N,NTT,MISC
16,CERA,-0.72,-31.65,81.25,23.89,97693.0,-55666.0,120237.0,9475.00,-34.13,56.0,H-SC,12.62,153.0,-0.57,0.81,15.55,OX40N,NTT,CERAMICS
76,SYMPHONY,2.29,-33.13,49.49,-0.03,56640.0,-56693.0,114448.0,1306.00,-46.27,67.0,M-SC,14.38,205.0,-1.00,0.77,26.93,OX40N,NTT,DURABLES
83,TTKPRESTIG,-2.12,-33.19,49.82,0.09,33542.0,-33450.0,67327.0,770.00,56.24,58.0,M-SC,20.07,250.0,-1.00,0.45,19.89,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.08,27.21,63.44,107.91,119155.0,40179.0,187823.0,1641.55,14.66,73.0,M-SC,7.83,220.0,0.34,1.26,41.31,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.33,0.10,47.11,47.26,132573.0,288.0,281411.0,761.00,58.09,72.0,H-SC,5.19,173.0,0.00,1.89,45.74,XY24,NTT,INSURANCE
25,FINCABLES,-0.08,27.21,63.44,107.91,119155.0,40179.0,187823.0,1641.55,14.66,73.0,M-SC,7.83,220.0,0.34,1.26,41.31,OX40N,ATH,CABLES
63,RECLTD,-0.60,1.73,18.68,20.74,38610.0,3520.0,206690.0,446.00,11.33,63.0,M-MC,3.45,191.0,0.09,1.39,23.17,XY25,NTT,FINANCE
73,SONACOMS,1.72,3.59,34.27,39.09,35912.0,3631.0,104790.0,804.02,-17.90,65.0,M-MC,14.13,193.0,0.10,0.70,48.24,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.08,27.21,63.44,107.91,119155.0,40179.0,187823.0,1641.55,14.66,73.0,M-SC,7.83,220.0,0.34,1.26,41.31,OX40N,ATH,CABLES
73,SONACOMS,1.72,3.59,34.27,39.09,35912.0,3631.0,104790.0,804.02,-17.90,65.0,M-MC,14.13,193.0,0.10,0.70,48.24,AR,ATH,AUTO
42,INDIAMART,0.46,-8.50,125.92,106.72,142104.0,-10483.0,112853.0,4810.62,-58.79,53.0,H-SC,9.98,140.0,-0.07,0.76,8.42,AR,ATH,MISC
55,MASFIN,-1.01,-2.43,24.60,21.57,23516.0,-2385.0,95595.0,397.04,-15.99,56.0,H-SC,1.37,167.0,-0.10,0.64,23.53,XR,ATH,FINANCE
91,ZYDUSLIFE,-3.02,-3.90,41.14,35.63,82855.0,-8177.0,201397.0,1286.17,-16.22,49.0,H-MC,3.91,120.0,-0.10,1.35,5.89,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-1.56,-21.57,71.17,34.24,174649.0,-67491.0,245397.0,1972.00,-38.32,29.0,X-LC,13.23,3.0,-0.39,1.65,0.00,X40,NTT,IT
33,HCLTECH,-2.62,-22.38,56.55,21.51,106185.0,-54152.0,187772.0,1872.35,-18.53,29.0,X-LC,8.30,8.0,-0.51,1.26,0.00,X40,ATH,IT
40,ICICIPRULI,0.18,-13.86,51.76,30.73,87836.0,-27306.0,169699.0,790.00,-36.96,36.0,X-MC,13.29,78.0,-0.31,1.14,3.41,X40,ATH,INSURANCE
1,ABBOTINDIA,-0.31,-14.98,38.86,18.07,59094.0,-26785.0,152070.0,35195.00,-27.72,40.0,X-MC,11.99,58.0,-0.45,1.02,0.66,X40,ATH,PHARMA
35,HDFCLIFE,-1.20,-3.48,37.98,33.18,54914.0,-5213.0,144587.0,814.30,-24.64,40.0,X-LC,17.77,31.0,-0.09,0.97,4.25,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-0.26,18.21,22.82,45.20,51725.0,34923.0,226665.0,1856.00,35.37,64.0,X-MC,4.16,79.0,0.68,1.52,26.25,XY25,NTT,AC
84,UNITDSPR,-1.24,0.96,19.62,20.77,46381.0,2253.0,236397.0,1644.00,-10.48,60.0,X-MC,4.55,64.0,0.05,1.59,12.77,X40N,NTT,BREWERIES
87,VBL,-0.06,4.75,29.36,35.50,97133.0,14993.0,330835.0,670.80,-7.61,75.0,X-LC,5.88,13.0,0.15,2.22,35.85,X40N,ATH,FMCG
65,RELIANCE,1.69,-10.85,40.54,25.30,72635.0,-21795.0,179168.0,1952.00,-13.11,55.0,X-LC,6.20,21.0,-0.30,1.20,6.46,XY25,BTT,REFINERIES
39,ICICIGI,0.07,-6.15,27.15,19.34,50991.0,-12298.0,187811.0,2252.93,-21.06,43.0,X-MC,6.37,66.0,-0.24,1.26,4.90,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-1.56,-21.57,71.17,34.24,174649.0,-67491.0,245397.0,1972.00,-38.32,29.0,X-LC,13.23,3.0,-0.39,1.65,0.00,X40,NTT,IT
33,HCLTECH,-2.62,-22.38,56.55,21.51,106185.0,-54152.0,187772.0,1872.35,-18.53,29.0,X-LC,8.30,8.0,-0.51,1.26,0.00,X40,ATH,IT
1,ABBOTINDIA,-0.31,-14.98,38.86,18.07,59094.0,-26785.0,152070.0,35195.00,-27.72,40.0,X-MC,11.99,58.0,-0.45,1.02,0.66,X40,ATH,PHARMA
40,ICICIPRULI,0.18,-13.86,51.76,30.73,87836.0,-27306.0,169699.0,790.00,-36.96,36.0,X-MC,13.29,78.0,-0.31,1.14,3.41,X40,ATH,INSURANCE
79,TCS,-0.12,-28.23,76.36,26.57,253881.0,-130794.0,332479.0,4311.59,-39.36,43.0,X-LC,14.73,2.0,-0.52,2.24,3.76,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-1.28,-60.58,286.41,52.31,163872.0,-87944.0,57216.0,1176.00,-57.99,53.0,X-SC,28.59,92.0,-0.54,0.38,27.93,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.77,-53.20,188.90,35.20,113748.0,-68454.0,60216.0,2096.00,-21.01,50.0,X-SC,28.27,91.0,-0.60,0.40,19.42,X40,NTT,FOOTWEAR
60,QUESS,0.54,-18.04,112.17,73.90,98182.0,-19263.0,87530.0,424.00,-55.92,60.0,X-SC,16.03,80.0,-0.20,0.59,17.75,XY24,NTT,MISC
53,M&M,-0.46,0.20,23.13,23.38,32142.0,283.0,138964.0,3802.40,-15.13,46.0,X-LC,9.08,25.0,0.01,0.93,6.99,X40N,ATH,AUTO
51,KOTAKBANK,0.31,0.99,19.92,21.11,27857.0,1370.0,139842.0,453.24,-13.31,50.0,X-LC,9.55,12.0,0.05,0.94,6.95,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.20,-19.81,48.46,19.06,132193.0,-67379.0,272787.0,452.00,-55.92,51.0,X-LC,17.81,1.0,-0.51,1.83,5.82,X40,NTT,FMCG
79,TCS,-0.12,-28.23,76.36,26.57,253881.0,-130794.0,332479.0,4311.59,-39.36,43.0,X-LC,14.73,2.0,-0.52,2.24,3.76,X40,ATH,IT
45,INFY,-1.56,-21.57,71.17,34.24,174649.0,-67491.0,245397.0,1972.00,-38.32,29.0,X-LC,13.23,3.0,-0.39,1.65,0.00,X40,NTT,IT
81,TMPV,-1.00,-20.15,71.04,36.58,201859.0,-71693.0,284148.0,600.00,-83.62,55.0,X-LC,6.48,4.0,-0.36,1.91,18.43,XY24,NTT,AUTO
59,PIDILITIND,-0.48,-1.31,19.94,18.37,27768.0,-1850.0,139260.0,1670.26,-30.89,54.0,X-LC,7.87,5.0,-0.07,0.94,9.34,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.62,-34.62,103.26,32.89,52122.0,-26730.0,50476.0,1800.00,-337.39,58.0,L-MC,4.35,258.0,-0.51,0.34,24.24,XR,NTT,BANKS
12,BOSCH-HCIL,1.30,-36.94,58.56,-0.01,47196.0,-47210.0,80595.0,2282.00,16400.00,64.0,M-SC,5.38,231.0,-1.00,0.54,37.18,OX40N,BTT,AC
72,SIS,4.03,-18.25,48.34,21.26,43877.0,-20265.0,90767.0,528.00,2149.22,77.0,H-SC,8.31,168.0,-0.46,0.61,34.96,OX40N,NTT,MISC
73,SONACOMS,1.72,3.59,34.27,39.09,35912.0,3631.0,104790.0,804.02,-17.90,65.0,M-MC,14.13,193.0,0.10,0.70,48.24,AR,ATH,AUTO
75,SURYODAY,0.43,-14.55,43.98,23.03,67298.0,-26051.0,153020.0,216.00,66.67,66.0,H-SC,4.74,166.0,-0.39,1.03,30.50,XR,NTT,BANKS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
61,RAJESHEXPO,-1.00,-75.45,307.65,0.07,103598.0,-103503.0,33674.0,518.00,1133.59,59.0,L-SC,35.26,268.0,-1.00,0.23,58.09,OX40N,NTT,JEWELLERY
62,RAJOOENG,-0.46,-30.82,101.81,39.61,72193.0,-31590.0,70910.0,143.10,-53.15,66.0,H-SC,24.50,136.0,-0.44,0.48,51.91,AR,ATH,MISC
77,TANLA,-4.01,-36.76,247.41,119.69,423620.0,-99539.0,171222.0,1943.92,-36.34,68.0,H-SC,19.65,147.0,-0.23,1.15,48.24,AR,ATH,IT
12,BOSCH-HCIL,1.30,-36.94,58.56,-0.01,47196.0,-47210.0,80595.0,2282.00,16400.00,64.0,M-SC,5.38,231.0,-1.00,0.54,37.18,OX40N,BTT,AC
80,TITAGARH,-1.53,-26.00,96.93,45.74,173717.0,-62958.0,179219.0,1548.00,-1.32,68.0,H-SC,15.01,175.0,-0.36,1.20,36.74,XY24,NTT,ENGINEERING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       18.94
1     25       42.58
2     50       72.69

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.04
LC    31.73
MC    26.20
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     26.58
X40      25.60
X40N     17.14
XR        8.99
XY25      7.08
AR        6.90
OX40N     6.87
SR        0.81
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.50
H-SC    21.71
X-MC    21.23
M-SC    10.00
X-SC     9.76
H-MC     2.54
M-MC     2.09
H-LC     1.29
M-LC     0.94
L-SC     0.57
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.74        -13.00   52.89
FINANCE             10.75        -15.32   65.48
IT                  10.62        -42.68  114.93
MISC                 6.85        -31.73   88.96
AUTO                 6.61        -11.20   52.90
BANKS                5.40        -13.15   65.47
INSURANCE            5.26         -5.68   41.65
PAINTS               5.09        -30.28   52.90
PHARMA               4.76         -4.60   38.22
ELECTRICAL           4.14        -14.98   55.91
AC                   2.06         -4.00   32.19
CHEMICALS            2.02        -35.60  116.41
HEALTHCARE           1.91        -25.39   58.10
DURABLES             1.84        -41.41   75.82
APPARELS             1.76         -2.23   37.10
FOOTWEAR             1.74        -69.97  138.12
TRAVEL               1.70        -76.18  164.41
BREWERIES            1.59          0.95   19.62
REALTY               1.45         -3.09   20.03
CERAMICS             1.28        -61.26  110.25
CABLES               1.26         21.39   63.44
ENGINEERING          1.20        -35.13   96.93
REFINERIES           1.20        -12.16   40.54
CEMENT               1.16        -55.24  171.38
JEWELLERY            1.06       -102.94  173.45
ENTERTAINMENT        0.75        -73.38  176.79
TEXTILES             0.43        -43.16   83.98
HOTELS               0.34       -122.08  200.41

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3641290.0     21
X40       1893995.0     19
XR        1343617.0     13
X40N      1176001.0     13
AR        1163813.0      9
OX40N      770135.0     10
XY25       386384.0      5
SR         299455.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3565076.0     24
X-LC        1909496.0     21
X-MC        1577113.0     15
M-SC        1427588.0     14
X-SC        1349434.0      9
H-MC         319260.0      2
L-SC         206068.0      2
M-LC         151796.0      1
M-MC          74522.0      2
L-MC          52122.0      1
H-LC          42215.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1177647.0      6
X-LC       X40       1032316.0     10
H-SC       AR         927711.0      5
M-SC       XY24       857365.0      6
H-SC       XR         817563.0      7
X-SC       XY24       790469.0      4
X-MC       X40        664654.0      7
           X40N       457862.0      4
X-SC       X40N       361940.0      3
X-LC       X40N       356199.0      6
H-SC       OX40N      342700.0      4
X-LC       XY24       336687.0      2
M-SC       OX40N      323837.0      5
H-SC       SR         299455.0      2
X-MC       XY24       242717.0      2
H-MC       XY24       236405.0      1
X-MC       XY25       211880.0      2
X-SC       X40        197025.0      2
M-SC       XR         171266.0      2
M-LC       XR         151796.0      1
X-LC       XY25       135894.0      2
L-SC       OX40N      103598.0      1
           XR         102470.0      1
H-MC       AR          82855.0      1
M-SC       AR          75120.0      1
L-MC       XR          52122.0      1
X-LC       XR          48400.0      1
H-LC       AR          42215.0      1
M-MC       XY25        38610.0      1
           AR          35912.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds