<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-06 16:12:54
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.31 C
-------------------
Today PnL: 1.50 L (1.16%)
Current PnL: -46.20 L (-28.43%)
CY Booked + Current PnL: -30.31 L (-18.66%)
-------------------
Total profit:  65.39 K
Total loss:  -46.86 L
-------------------
Total Booked + Current PnL: -3.33 L (-2.46%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.14%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.17 C (89.34%)
===================
Deployed:  1.36 C
Current:  1.31 C
CAGR/XIRR %: -1.66%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,2.55,-7.18,30.97,21.57,28166.0,-7035.0,90945.0,397.04,-20.05,50.0,H-SC,4.90,167.0,-0.25,0.69,24.04,XR,ATH,FINANCE
77,TTKPRESTIG,2.82,-40.72,68.84,0.09,41127.0,-41034.0,59743.0,770.00,38.74,42.0,M-SC,22.28,250.0,-1.00,0.46,6.38,OX40N,NTT,DURABLES
24,DMART,4.33,9.41,18.46,29.60,50410.0,23478.0,273078.0,5391.45,-7.74,78.0,X-LC,6.01,14.0,0.47,2.09,24.82,X40N,ATH,FMCG
67,SONACOMS,2.59,-11.88,57.84,39.09,51561.0,-12014.0,89145.0,804.02,-30.19,52.0,M-MC,7.01,193.0,-0.23,0.68,26.11,AR,ATH,AUTO
2,ABBOTINDIA,-1.48,-13.13,35.91,18.07,55793.0,-23485.0,155370.0,35195.00,-26.09,43.0,X-MC,10.68,58.0,-0.42,1.19,1.61,X40,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COFFEEDAY,7.27,-60.06,238.70,35.27,108250.0,-68199.0,45350.0,80.0,-69.82,43.0,L-SC,32.17,266.0,-0.63,0.35,11.84,XR,NTT,HOTELS
39,IEX,5.64,-14.38,73.59,48.63,125985.0,-28755.0,171199.0,219.0,-43.11,56.0,H-SC,15.84,137.0,-0.23,1.31,9.94,XR,NTT,MISC
55,RAJESHEXPO,4.97,-82.30,465.38,0.07,112990.0,-112898.0,24279.0,518.0,790.15,33.0,L-SC,43.20,268.0,-1.00,0.19,13.98,OX40N,NTT,JEWELLERY
56,RAJOOENG,4.92,-45.45,155.95,39.61,87192.0,-46590.0,55910.0,143.1,-63.13,48.0,H-SC,33.51,136.0,-0.53,0.43,19.77,AR,ATH,MISC
69,SURYODAY,4.81,-24.84,63.70,23.03,85733.0,-44482.0,134589.0,216.0,46.93,55.0,H-SC,5.23,166.0,-0.52,1.03,21.78,XR,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,RELIANCE,-3.39,-16.25,49.61,25.30,83497.0,-32657.0,168306.0,1952.00,-18.49,33.0,X-LC,4.02,21.0,-0.39,1.29,12.37,XY25,BTT,REFINERIES
68,STARHEALTH,-2.42,-11.27,65.96,47.26,164538.0,-31672.0,249451.0,761.00,40.01,49.0,H-SC,0.39,173.0,-0.19,1.91,32.43,XY24,NTT,INSURANCE
8,AWL,-2.08,-38.06,169.62,67.02,374373.0,-135596.0,220713.0,485.00,-66.62,45.0,X-SC,26.04,81.0,-0.36,1.69,4.40,XY24,NTT,FMCG
30,HAPPSTMNDS,-1.97,-51.89,284.20,84.85,175249.0,-66501.0,61664.0,1480.71,-42.72,50.0,H-SC,23.77,152.0,-0.38,0.47,14.19,AR,ATH,IT
0,5PAISA,-1.75,-46.61,111.48,12.90,130037.0,-101850.0,116646.0,593.00,71.88,44.0,H-SC,16.83,170.0,-0.78,0.89,12.57,OX40N,NTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.45,2.49,102.86,107.91,155648.0,3676.0,151320.0,1641.55,-7.66,46.0,M-SC,5.04,220.0,0.02,1.16,13.84,OX40N,ATH,CABLES
66,SIS,0.42,-33.62,82.67,21.26,60934.0,-37324.0,73708.0,528.00,1726.42,49.0,H-SC,14.82,168.0,-0.61,0.56,9.59,OX40N,NTT,MISC
18,CERA,2.38,-37.38,97.86,23.89,107785.0,-65761.0,110142.0,9475.00,-39.62,51.0,H-SC,19.15,153.0,-0.61,0.84,5.85,OX40N,NTT,CERAMICS
72,TATAELXSI,0.73,-38.43,114.43,32.03,92887.0,-50661.0,81174.0,9161.00,-23.05,46.0,H-SC,21.68,158.0,-0.55,0.62,7.44,OX40N,NTT,IT
48,KANSAINER,0.87,-39.87,88.72,13.47,143854.0,-107523.0,162144.0,340.00,-48.30,48.0,H-SC,23.42,162.0,-0.75,1.24,13.26,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,1.45,2.49,102.86,107.91,155648.0,3676.0,151320.0,1641.55,-7.66,46.0,M-SC,5.04,220.0,0.02,1.16,13.84,OX40N,ATH,CABLES
1,ABB,0.84,13.63,28.10,45.57,83538.0,35669.0,297288.0,7934.00,-26.98,55.0,H-MC,13.65,125.0,0.43,2.27,32.02,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,0.84,13.63,28.10,45.57,83538.0,35669.0,297288.0,7934.00,-26.98,55.0,H-MC,13.65,125.0,0.43,2.27,32.02,AR,NTT,ELECTRICAL
26,FINCABLES,1.45,2.49,102.86,107.91,155648.0,3676.0,151320.0,1641.55,-7.66,46.0,M-SC,5.04,220.0,0.02,1.16,13.84,OX40N,ATH,CABLES
40,INDIAMART,2.42,-11.15,132.66,106.72,145379.0,-13748.0,109588.0,4810.62,-59.96,49.0,H-SC,12.89,140.0,-0.09,0.84,9.63,AR,ATH,MISC
85,ZYDUSLIFE,0.24,-8.65,48.47,35.63,92797.0,-18122.0,191452.0,1286.17,-20.27,42.0,H-MC,5.70,120.0,-0.20,1.46,6.58,AR,ATH,PHARMA
84,WIPRO,1.22,-19.08,112.88,72.27,154778.0,-32331.0,137117.0,420.00,-26.90,48.0,M-LC,18.12,98.0,-0.21,1.05,5.20,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,1.93,-15.09,53.97,30.73,90276.0,-29734.0,167271.0,790.00,-37.88,25.0,X-MC,9.48,78.0,-0.33,1.28,1.93,X40,ATH,INSURANCE
21,DABUR,-0.85,-19.12,77.66,43.70,155820.0,-47424.0,200644.0,735.00,-26.67,29.0,X-MC,11.67,70.0,-0.30,1.53,0.79,XY24,BTT,FMCG
20,COLPAL,0.01,-30.53,103.69,41.51,189722.0,-80395.0,182970.0,3726.84,-15.94,33.0,X-MC,10.88,62.0,-0.42,1.40,2.29,XY25,ATH,FMCG
59,RELIANCE,-3.39,-16.25,49.61,25.30,83497.0,-32657.0,168306.0,1952.00,-18.49,33.0,X-LC,4.02,21.0,-0.39,1.29,12.37,XY25,BTT,REFINERIES
37,ICICIGI,1.41,-9.26,31.52,19.34,57233.0,-18531.0,181578.0,2252.93,-23.76,34.0,X-MC,6.29,66.0,-0.32,1.39,1.41,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,0.71,-18.11,53.26,25.51,81168.0,-33695.0,152400.0,4671.50,27.94,45.0,H-LC,0.49,51.0,-0.42,1.16,12.23,AR,ATH,ELECTRICAL
82,VOLTAS,1.34,-2.06,48.24,45.20,90595.0,-3942.0,187800.0,1856.00,12.06,36.0,X-MC,3.46,79.0,-0.04,1.43,4.60,XY25,NTT,AC
78,UNITDSPR,1.24,-9.18,32.98,20.77,70130.0,-21500.0,212644.0,1644.00,-19.41,39.0,X-MC,3.89,64.0,-0.31,1.62,1.44,X40N,NTT,BREWERIES
59,RELIANCE,-3.39,-16.25,49.61,25.30,83497.0,-32657.0,168306.0,1952.00,-18.49,33.0,X-LC,4.02,21.0,-0.39,1.29,12.37,XY25,BTT,REFINERIES
24,DMART,4.33,9.41,18.46,29.60,50410.0,23478.0,273078.0,5391.45,-7.74,78.0,X-LC,6.01,14.0,0.47,2.09,24.82,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,JSWINFRA,-1.09,-18.76,43.32,16.43,78044.0,-41616.0,180158.0,342.00,-30.42,40.0,X-MC,11.73,61.0,-0.53,1.38,0.00,X40N,NTT,REALTY
21,DABUR,-0.85,-19.12,77.66,43.70,155820.0,-47424.0,200644.0,735.00,-26.67,29.0,X-MC,11.67,70.0,-0.30,1.53,0.79,XY24,BTT,FMCG
37,ICICIGI,1.41,-9.26,31.52,19.34,57233.0,-18531.0,181578.0,2252.93,-23.76,34.0,X-MC,6.29,66.0,-0.32,1.39,1.41,X40,ATH,INSURANCE
78,UNITDSPR,1.24,-9.18,32.98,20.77,70130.0,-21500.0,212644.0,1644.00,-19.41,39.0,X-MC,3.89,64.0,-0.31,1.62,1.44,X40N,NTT,BREWERIES
35,HINDUNILVR,0.94,-18.90,40.16,13.67,83726.0,-48583.0,208480.0,2922.00,-39.73,38.0,X-LC,11.31,9.0,-0.58,1.59,1.59,XY25,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,2.13,-64.63,330.55,52.31,169737.0,-93810.0,51350.0,1176.00,-62.35,41.0,X-SC,31.87,92.0,-0.55,0.39,14.81,X40N,NTT,FOOTWEAR
12,BATAINDIA,1.42,-57.01,214.48,35.20,118650.0,-73350.0,55320.0,2096.00,-27.51,42.0,X-SC,34.13,91.0,-0.62,0.42,9.71,X40,NTT,FOOTWEAR
54,QUESS,-0.37,-26.90,137.89,73.90,107644.0,-28728.0,78065.0,424.00,-60.88,44.0,X-SC,22.54,80.0,-0.27,0.60,5.01,XY24,NTT,MISC
36,HONAUT,2.23,-28.74,112.32,51.31,154356.0,-55413.0,137425.0,58357.33,-40.75,39.0,X-SC,18.22,90.0,-0.36,1.05,4.41,X40N,ATH,ELECTRICAL
65,SIEMENS,0.71,-18.11,53.26,25.51,81168.0,-33695.0,152400.0,4671.50,27.94,45.0,H-LC,0.49,51.0,-0.42,1.16,12.23,AR,ATH,ELECTRICAL

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.68,-22.34,53.30,19.06,140811.0,-75980.0,264186.0,452.00,-57.54,40.0,X-LC,19.72,1.0,-0.54,2.02,2.49,X40,NTT,FMCG
73,TCS,0.95,-27.38,74.28,26.57,249915.0,-126823.0,336450.0,4311.58,-38.38,46.0,X-LC,18.66,2.0,-0.51,2.57,5.00,X40,ATH,IT
43,INFY,0.42,-11.08,50.97,34.24,141809.0,-34667.0,278221.0,1972.00,-29.97,50.0,X-LC,14.91,3.0,-0.24,2.13,7.00,X40,NTT,IT
75,TMPV,1.35,-30.03,95.19,36.58,237017.0,-106847.0,248994.0,600.00,-85.81,39.0,X-LC,11.79,4.0,-0.45,1.90,3.78,XY24,NTT,AUTO
33,HCLTECH,0.08,-8.93,35.98,23.83,79270.0,-21606.0,220318.0,1908.19,-4.47,53.0,X-LC,11.28,8.0,-0.27,1.68,6.98,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,2.59,-11.88,57.84,39.09,51561.0,-12014.0,89145.0,804.02,-30.19,52.0,M-MC,7.01,193.0,-0.23,0.68,26.11,AR,ATH,AUTO
24,DMART,4.33,9.41,18.46,29.60,50410.0,23478.0,273078.0,5391.45,-7.74,78.0,X-LC,6.01,14.0,0.47,2.09,24.82,X40N,ATH,FMCG
1,ABB,0.84,13.63,28.10,45.57,83538.0,35669.0,297288.0,7934.00,-26.98,55.0,H-MC,13.65,125.0,0.43,2.27,32.02,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,4.33,9.41,18.46,29.60,50410.0,23478.0,273078.0,5391.45,-7.74,78.0,X-LC,6.01,14.0,0.47,2.09,24.82,X40N,ATH,FMCG
30,HAPPSTMNDS,-1.97,-51.89,284.20,84.85,175249.0,-66501.0,61664.0,1480.71,-42.72,50.0,H-SC,23.77,152.0,-0.38,0.47,14.19,AR,ATH,IT
5,ANGELONE,2.16,0.84,23.15,24.18,71201.0,2562.0,307562.0,303.00,-85.37,58.0,X-SC,9.07,97.0,0.04,2.35,18.38,X40N,NTT,FINANCE
80,VALIANTORG,2.85,-50.34,250.67,74.15,203669.0,-82355.0,81250.0,838.00,-245.98,53.0,H-SC,27.10,145.0,-0.40,0.62,20.91,XR,NTT,CHEMICALS
52,PAGEIND,2.37,-9.36,47.97,34.11,116687.0,-25129.0,243250.0,51418.64,-35.06,66.0,X-MC,19.72,55.0,-0.22,1.86,15.07,X40,ATH,APPARELS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.13
1     25       46.22
2     50       78.03

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.71
MC    29.53
LC    25.76
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.08
X40      25.36
X40N     15.44
AR        9.14
XR        8.43
XY25      7.09
OX40N     6.67
SR        0.79
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.55
X-MC    22.12
H-SC    21.89
X-SC    12.34
M-SC     9.94
H-MC     5.01
M-MC     2.06
H-LC     1.16
M-LC     1.05
L-SC     0.54
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.17        -25.78   70.44
FINANCE             13.22        -24.18   74.79
IT                  12.02        -43.14  115.99
MISC                 7.09        -44.43  107.17
ELECTRICAL           6.42        -15.23   59.35
PAINTS               5.23        -43.83   68.80
BANKS                4.59        -28.18   93.24
INSURANCE            4.58        -13.36   52.16
PHARMA               4.08         -9.95   44.55
AUTO                 3.66        -36.53   90.71
HEALTHCARE           1.95        -39.66   76.11
AC                   1.93        -26.34   60.59
APPARELS             1.86        -10.33   47.97
FOOTWEAR             1.83        -83.62  157.25
TRAVEL               1.77        -92.41  188.75
DURABLES             1.76        -68.57  109.58
BREWERIES            1.62        -10.11   32.98
CERAMICS             1.38        -69.97  121.61
REALTY               1.38        -23.10   43.32
REFINERIES           1.29        -19.40   49.61
CEMENT               1.25        -64.04  186.76
CABLES               1.16          2.43  102.86
ENGINEERING          1.11        -66.13  142.12
CHEMICALS            1.05        -91.49  247.71
JEWELLERY            1.02       -141.45  225.35
ENTERTAINMENT        0.77        -90.95  204.83
TEXTILES             0.46        -54.40   98.43
HOTELS               0.35       -150.38  238.70

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4050529.0     21
X40       1856546.0     16
XR        1389239.0     12
AR        1373996.0     10
X40N      1277467.0     10
OX40N      920068.0     10
XY25       512683.0      5
SR         315480.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3926806.0     24
X-MC        1836664.0     15
X-LC        1694734.0     13
M-SC        1616777.0     14
X-SC        1567117.0     10
H-MC         422234.0      3
L-SC         221240.0      2
M-LC         154778.0      1
M-MC         116704.0      2
H-LC          81168.0      1
L-MC          57786.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1357771.0      6
           AR         985686.0      5
M-SC       XY24       929897.0      6
X-LC       X40        917255.0      7
H-SC       XR         876226.0      7
X-SC       XY24       855691.0      4
X-MC       X40        716177.0      7
           X40N       566080.0      4
X-SC       X40N       488312.0      4
M-SC       OX40N      415435.0      5
H-SC       OX40N      391643.0      4
X-LC       XY24       387181.0      2
H-SC       SR         315480.0      2
X-MC       XY25       280317.0      2
           XY24       274090.0      2
H-MC       XY24       245899.0      1
X-SC       X40        223114.0      2
X-LC       X40N       223075.0      2
M-SC       XR         192199.0      2
H-MC       AR         176335.0      2
X-LC       XY25       167223.0      2
M-LC       XR         154778.0      1
L-SC       OX40N      112990.0      1
           XR         108250.0      1
H-LC       AR          81168.0      1
M-SC       AR          79246.0      1
M-MC       XY25        65143.0      1
L-MC       XR          57786.0      1
M-MC       AR          51561.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds