<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-26 11:36:28
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: 78.33 K (0.52%)
Current PnL: -32.47 L (-17.8%)
CY Booked + Current PnL: -30.39 L (-16.66%)
-------------------
Total profit:  2.34 L
Total loss:  -34.81 L
-------------------
Total Booked + Current PnL: 12.48 L (8.94%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.05 C (69.43%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.72%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.25,4.42,13.35,18.37,19671.0,6240.0,147350.0,1670.26,-26.86,60.0,X-LC,5.31,5.0,0.32,0.98,15.70,X40,ATH,CHEMICALS
51,KOTAKBANK,-0.62,4.32,16.10,21.11,23256.0,5976.0,144448.0,453.24,-10.71,58.0,X-LC,7.79,12.0,0.26,0.96,10.47,X40,ATH,BANKS
55,MASFIN,1.03,-5.57,28.74,21.57,26590.0,-5460.0,92520.0,397.04,-18.70,39.0,H-SC,4.58,167.0,-0.21,0.61,10.28,XR,ATH,FINANCE
53,M&M,0.12,1.98,20.99,23.38,29685.0,2745.0,141426.0,3802.40,-13.39,49.0,X-LC,8.95,25.0,0.09,0.94,7.22,X40N,ATH,AUTO
17,CIPLA,0.33,14.85,17.27,34.69,30379.0,22745.0,175906.0,1663.60,-11.14,65.0,X-LC,9.79,18.0,0.75,1.17,18.97,X40N,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
14,CAMPUS,6.84,-14.47,55.83,33.28,80114.0,-24279.0,143496.0,393.00,-31.14,61.0,M-SC,7.92,218.0,-0.30,0.95,15.23,XY24,NTT,FOOTWEAR
61,RAJESHEXPO,5.00,-77.12,337.32,0.07,105881.0,-105788.0,31389.0,518.00,1050.25,56.0,L-SC,32.26,268.0,-1.00,0.21,47.36,OX40N,NTT,JEWELLERY
77,TANLA,3.36,-39.12,256.84,117.25,423380.0,-105919.0,164842.0,1922.32,-38.40,58.0,H-SC,12.39,147.0,-0.25,1.09,44.32,AR,ATH,IT
37,HONAUT,3.33,-7.82,64.16,51.31,114044.0,-15088.0,177750.0,58357.33,-23.38,70.0,X-SC,10.74,90.0,-0.13,1.18,35.04,X40N,ATH,ELECTRICAL
68,SATIN,2.68,23.05,23.40,51.83,79550.0,63675.0,339959.0,274.00,10.38,68.0,H-SC,34.34,159.0,0.80,2.26,65.61,XY24,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.62,-21.67,80.65,41.51,166381.0,-57065.0,206300.0,3726.84,-5.18,42.0,X-MC,5.50,62.0,-0.34,1.37,15.34,XY25,ATH,FMCG
76,SYMPHONY,-1.17,-45.39,83.04,-0.03,77616.0,-77673.0,93468.0,1306.00,-56.14,36.0,M-SC,10.58,205.0,-1.00,0.62,3.66,OX40N,NTT,DURABLES
66,REPCOHOME,-1.14,-15.51,124.66,89.82,301766.0,-44434.0,242071.0,880.00,-57.53,48.0,H-SC,2.81,161.0,-0.15,1.61,16.37,XY24,NTT,FINANCE
89,WHIRLPOOL,-0.89,-32.08,167.85,81.92,130873.0,-36828.0,77970.0,2270.00,-60.23,40.0,M-SC,15.80,210.0,-0.28,0.52,9.52,XR,NTT,DURABLES
79,TCS,-0.82,-32.79,85.82,24.88,267196.0,-151928.0,311345.0,4253.91,-42.97,40.0,X-LC,17.35,2.0,-0.57,2.07,3.31,X40,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.51,37.42,51.29,107.91,104065.0,55251.0,202895.0,1641.55,23.80,62.0,M-SC,26.11,220.0,0.53,1.35,52.64,OX40N,ATH,CABLES
72,SIS,2.66,-8.13,32.00,21.26,32640.0,-9032.0,102000.0,528.00,2427.46,65.0,H-SC,16.51,168.0,-0.28,0.68,51.66,OX40N,NTT,MISC
16,CERA,1.64,-23.86,62.72,23.89,84000.0,-41974.0,133929.0,9475.00,-26.49,61.0,H-SC,7.16,153.0,-0.50,0.89,28.70,OX40N,NTT,CERAMICS
50,KANSAINER,0.34,-26.88,55.18,13.47,108809.0,-72477.0,197190.0,340.00,-37.08,63.0,H-SC,12.83,162.0,-0.67,1.31,37.74,XY24,NTT,PAINTS
43,INDIGOPNTS,0.14,-29.16,41.18,0.02,50925.0,-50894.0,123665.0,1408.00,88.62,66.0,M-SC,18.27,222.0,-1.00,0.82,40.31,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,1.51,37.42,51.29,107.91,104065.0,55251.0,202895.0,1641.55,23.80,62.0,M-SC,26.11,220.0,0.53,1.35,52.64,OX40N,ATH,CABLES
68,SATIN,2.68,23.05,23.40,51.83,79550.0,63675.0,339959.0,274.00,10.38,68.0,H-SC,34.34,159.0,0.80,2.26,65.61,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.59,2.32,43.92,47.26,126331.0,6517.0,287640.0,761.00,61.57,64.0,H-SC,10.25,173.0,0.05,1.91,26.28,XY24,NTT,INSURANCE
25,FINCABLES,1.51,37.42,51.29,107.91,104065.0,55251.0,202895.0,1641.55,23.80,62.0,M-SC,26.11,220.0,0.53,1.35,52.64,OX40N,ATH,CABLES
68,SATIN,2.68,23.05,23.40,51.83,79550.0,63675.0,339959.0,274.00,10.38,68.0,H-SC,34.34,159.0,0.80,2.26,65.61,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.84,14.10,18.87,35.63,45122.0,29548.0,239122.0,1286.17,-0.90,75.0,H-MC,4.31,120.0,0.65,1.59,25.73,AR,ATH,PHARMA
73,SONACOMS,0.99,3.89,33.88,39.09,35607.0,3937.0,105096.0,804.02,-17.63,60.0,M-MC,18.90,193.0,0.11,0.70,48.67,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.84,14.10,18.87,35.63,45122.0,29548.0,239122.0,1286.17,-0.90,75.0,H-MC,4.31,120.0,0.65,1.59,25.73,AR,ATH,PHARMA
25,FINCABLES,1.51,37.42,51.29,107.91,104065.0,55251.0,202895.0,1641.55,23.80,62.0,M-SC,26.11,220.0,0.53,1.35,52.64,OX40N,ATH,CABLES
73,SONACOMS,0.99,3.89,33.88,39.09,35607.0,3937.0,105096.0,804.02,-17.63,60.0,M-MC,18.90,193.0,0.11,0.70,48.67,AR,ATH,AUTO
42,INDIAMART,0.51,-12.35,135.85,106.72,146859.0,-15232.0,108104.0,4810.62,-60.55,49.0,H-SC,10.54,140.0,-0.10,0.72,4.65,AR,ATH,MISC
90,WIPRO,0.23,-14.97,102.60,72.27,147826.0,-25368.0,144080.0,420.00,-23.15,64.0,M-LC,13.36,98.0,-0.17,0.96,10.54,XR,NTT,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,0.21,-1.30,31.31,29.60,77132.0,-3252.0,246348.0,5391.45,-16.75,34.0,X-LC,4.23,14.0,-0.04,1.63,12.60,X40N,ATH,FMCG
27,GLAXO,-0.10,-7.75,50.84,39.15,93460.0,-15452.0,183832.0,3466.20,-29.60,36.0,X-MC,6.52,56.0,-0.17,1.22,1.70,X40,ATH,PHARMA
33,HCLTECH,0.14,-24.25,60.40,21.51,110693.0,-58658.0,183266.0,1872.35,-20.60,39.0,X-LC,18.73,8.0,-0.53,1.22,3.85,X40,ATH,IT
79,TCS,-0.82,-32.79,85.82,24.88,267196.0,-151928.0,311345.0,4253.91,-42.97,40.0,X-LC,17.35,2.0,-0.57,2.07,3.31,X40,ATH,IT
32,HAVELLS,-0.12,-23.01,70.71,31.42,178546.0,-75487.0,252504.0,2052.62,-27.51,42.0,X-MC,12.63,63.0,-0.42,1.68,2.35,X40,ATH,ELECTRICAL

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
84,UNITDSPR,0.42,-5.27,27.49,20.77,60971.0,-12350.0,221794.0,1644.00,-16.02,48.0,X-MC,3.75,64.0,-0.20,1.47,5.80,X40N,NTT,BREWERIES
65,RELIANCE,-0.33,-12.54,43.27,25.30,76052.0,-25201.0,175762.0,1952.00,-14.65,47.0,X-LC,3.90,21.0,-0.33,1.17,4.44,XY25,BTT,REFINERIES
23,DMART,0.21,-1.30,31.31,29.60,77132.0,-3252.0,246348.0,5391.45,-16.75,34.0,X-LC,4.23,14.0,-0.04,1.63,12.60,X40N,ATH,FMCG
88,VOLTAS,-0.46,-0.01,45.22,45.20,86694.0,-27.0,191715.0,1856.00,14.50,42.0,X-MC,4.23,79.0,-0.00,1.27,4.75,XY25,NTT,AC
39,ICICIGI,-0.20,-1.98,21.75,19.34,42663.0,-3956.0,196153.0,2252.93,-17.63,57.0,X-MC,4.97,66.0,-0.09,1.30,9.56,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,GLAXO,-0.10,-7.75,50.84,39.15,93460.0,-15452.0,183832.0,3466.20,-29.60,36.0,X-MC,6.52,56.0,-0.17,1.22,1.70,X40,ATH,PHARMA
32,HAVELLS,-0.12,-23.01,70.71,31.42,178546.0,-75487.0,252504.0,2052.62,-27.51,42.0,X-MC,12.63,63.0,-0.42,1.68,2.35,X40,ATH,ELECTRICAL
79,TCS,-0.82,-32.79,85.82,24.88,267196.0,-151928.0,311345.0,4253.91,-42.97,40.0,X-LC,17.35,2.0,-0.57,2.07,3.31,X40,ATH,IT
40,ICICIPRULI,-0.82,-13.55,51.23,30.73,87246.0,-26703.0,170302.0,790.00,-36.73,44.0,X-MC,11.92,78.0,-0.31,1.13,3.77,X40,ATH,INSURANCE
33,HCLTECH,0.14,-24.25,60.40,21.51,110693.0,-58658.0,183266.0,1872.35,-20.60,39.0,X-LC,18.73,8.0,-0.53,1.22,3.85,X40,ATH,IT

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,1.97,-60.54,286.02,52.31,163815.0,-87886.0,57274.0,1176.00,-57.99,57.0,X-SC,24.72,92.0,-0.54,0.38,28.06,X40N,NTT,FOOTWEAR
10,BATAINDIA,1.05,-54.62,197.94,35.20,115577.0,-70280.0,58390.0,2096.00,-23.47,48.0,X-SC,25.46,91.0,-0.61,0.39,15.80,X40,NTT,FOOTWEAR
60,QUESS,0.50,-15.02,104.63,73.90,94956.0,-16039.0,90754.0,424.00,-54.27,55.0,X-SC,9.84,80.0,-0.17,0.60,23.72,XY24,NTT,MISC
28,GODREJCP,0.89,-7.87,42.69,31.47,58453.0,-11690.0,136924.0,1469.04,-3.15,45.0,X-LC,8.76,32.0,-0.20,0.91,5.06,X40N,ATH,FMCG
53,M&M,0.12,1.98,20.99,23.38,29685.0,2745.0,141426.0,3802.40,-13.39,49.0,X-LC,8.95,25.0,0.09,0.94,7.22,X40N,ATH,AUTO

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.38,-20.24,49.27,19.06,133674.0,-68857.0,271309.0,452.00,-56.33,44.0,X-LC,14.72,1.0,-0.52,1.80,5.25,X40,NTT,FMCG
79,TCS,-0.82,-32.79,85.82,24.88,267196.0,-151928.0,311345.0,4253.91,-42.97,40.0,X-LC,17.35,2.0,-0.57,2.07,3.31,X40,ATH,IT
45,INFY,0.66,-19.93,67.66,34.24,169509.0,-62357.0,250531.0,1972.00,-36.87,47.0,X-LC,18.85,3.0,-0.37,1.66,7.42,X40,NTT,IT
81,TMPV,2.25,-13.13,57.21,36.58,176857.0,-46705.0,309136.0,600.00,-81.44,69.0,X-LC,5.87,4.0,-0.26,2.05,28.85,XY24,NTT,AUTO
59,PIDILITIND,-0.25,4.42,13.35,18.37,19671.0,6240.0,147350.0,1670.26,-26.86,60.0,X-LC,5.31,5.0,0.32,0.98,15.70,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.13,-31.72,94.62,32.89,49883.0,-24488.0,52719.0,1800.00,-347.90,59.0,L-MC,8.83,258.0,-0.49,0.35,29.76,XR,NTT,BANKS
72,SIS,2.66,-8.13,32.00,21.26,32640.0,-9032.0,102000.0,528.00,2427.46,65.0,H-SC,16.51,168.0,-0.28,0.68,51.66,OX40N,NTT,MISC
73,SONACOMS,0.99,3.89,33.88,39.09,35607.0,3937.0,105096.0,804.02,-17.63,60.0,M-MC,18.90,193.0,0.11,0.70,48.67,AR,ATH,AUTO
75,SURYODAY,-0.32,-8.29,34.16,23.03,56098.0,-14851.0,164220.0,216.00,79.82,55.0,H-SC,18.30,166.0,-0.26,1.09,38.27,XR,NTT,BANKS
5,ATULAUTO,0.18,-15.32,71.91,45.57,120034.0,-30209.0,166923.0,844.00,3618.92,53.0,M-SC,7.25,248.0,-0.25,1.11,28.45,XY24,NTT,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,2.68,23.05,23.40,51.83,79550.0,63675.0,339959.0,274.00,10.38,68.0,H-SC,34.34,159.0,0.80,2.26,65.61,XY24,NTT,FINANCE
69,SFL,-0.32,-37.72,103.32,26.63,168736.0,-98904.0,163314.0,1287.00,23.68,68.0,M-SC,10.88,242.0,-0.59,1.08,36.11,XY24,NTT,MISC
72,SIS,2.66,-8.13,32.00,21.26,32640.0,-9032.0,102000.0,528.00,2427.46,65.0,H-SC,16.51,168.0,-0.28,0.68,51.66,OX40N,NTT,MISC
91,ZYDUSLIFE,0.84,14.10,18.87,35.63,45122.0,29548.0,239122.0,1286.17,-0.90,75.0,H-MC,4.31,120.0,0.65,1.59,25.73,AR,ATH,PHARMA
43,INDIGOPNTS,0.14,-29.16,41.18,0.02,50925.0,-50894.0,123665.0,1408.00,88.62,66.0,M-SC,18.27,222.0,-1.00,0.82,40.31,OX40N,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.39
1     25       42.68
2     50       72.84

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.76
LC    31.52
MC    25.75
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.68
X40      25.40
X40N     16.90
XR        8.87
OX40N     6.97
AR        6.84
XY25      6.53
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.35
H-SC    22.37
X-MC    20.69
M-SC    10.08
X-SC     9.77
H-MC     2.76
M-MC     1.95
H-LC     1.21
M-LC     0.96
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.08        -16.49   57.54
FINANCE             10.79        -13.46   62.80
IT                  10.34        -44.71  117.06
MISC                 6.94        -28.24   83.95
AUTO                 6.79         -7.07   47.21
BANKS                5.66         -6.50   55.75
PAINTS               5.55        -17.76   38.21
INSURANCE            5.35         -2.76   37.73
PHARMA               5.08          3.10   28.05
ELECTRICAL           4.07        -15.47   56.22
CHEMICALS            2.12        -26.88  102.50
HEALTHCARE           2.05        -15.64   45.82
AC                   1.79        -18.18   50.23
APPARELS             1.78          0.00   34.11
FOOTWEAR             1.72        -70.40  138.72
TRAVEL               1.69        -75.48  163.34
DURABLES             1.59        -61.36  100.61
BREWERIES            1.47         -5.57   27.49
REALTY               1.41         -4.72   21.93
CABLES               1.35         27.23   51.29
CERAMICS             1.35        -51.32   97.29
ENGINEERING          1.26        -27.64   86.02
REFINERIES           1.17        -14.34   43.27
CEMENT               1.12        -58.92  177.81
JEWELLERY            1.07        -98.23  167.10
ENTERTAINMENT        0.71        -79.45  186.48
TEXTILES             0.40        -51.22   94.33
HOTELS               0.33       -129.76  210.80

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3425481.0     21
X40       1867688.0     19
XR        1345759.0     13
X40N      1178261.0     13
AR        1153638.0      9
OX40N      741932.0     10
XY25       457904.0      5
SR         291962.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3416230.0     24
X-LC        1869252.0     21
X-MC        1614446.0     15
M-SC        1395877.0     14
X-SC        1331890.0      9
H-MC         282458.0      2
L-SC         210060.0      2
M-LC         147826.0      1
M-MC          93081.0      2
H-LC          51622.0      1
L-MC          49883.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1045883.0      6
X-LC       X40        996762.0     10
H-SC       AR         945640.0      5
M-SC       XY24       817443.0      6
H-SC       XR         811058.0      7
X-SC       XY24       787131.0      4
X-MC       X40        664705.0      7
           X40N       479090.0      4
X-LC       X40N       360633.0      6
X-SC       X40N       338538.0      3
H-SC       OX40N      321687.0      4
X-LC       XY24       320112.0      2
M-SC       OX40N      314364.0      5
H-SC       SR         291962.0      2
X-MC       XY25       253075.0      2
H-MC       XY24       237336.0      1
X-MC       XY24       217576.0      2
X-SC       X40        206221.0      2
M-SC       XR         188423.0      2
M-LC       XR         147826.0      1
X-LC       XY25       147355.0      2
L-SC       OX40N      105881.0      1
           XR         104179.0      1
M-SC       AR          75647.0      1
M-MC       XY25        57474.0      1
H-LC       AR          51622.0      1
L-MC       XR          49883.0      1
H-MC       AR          45122.0      1
X-LC       XR          44390.0      1
M-MC       AR          35607.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 36.0 seconds