<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-20 09:52:43
-------------------
qualified stocks: 87
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  3.69 L
Current:  1.59 C
-------------------
Today PnL: 82.22 K (0.52%)
Current PnL: -34.43 L (-18.22%)
CY Booked + Current PnL: -29.37 L (-15.54%)
-------------------
Total profit:  3.60 L
Total loss:  -38.03 L
-------------------
Total Booked + Current PnL: 13.50 L (9.25%)
Total Booked PnL: 47.93 L (32.82%)
Curr Year Booked PnL: 5.06 L (3.19%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.09 C (68.5%)
===================
Deployed:  1.46 C
Current:  1.59 C
CAGR/XIRR %: 3.71%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
66,SIEMENS,0.14,4.91,5.65,10.83,11030.0,9130.0,195225.0,4125.00,-15.10,57.0,H-LC,14.10,51.0,0.83,1.26,37.74,AR,NTT,ELECTRICAL
78,UNITDSPR,1.36,13.24,6.64,20.77,17606.0,31011.0,265155.0,1644.00,-3.49,64.0,X-MC,11.00,64.0,1.76,1.71,27.46,X40N,NTT,BREWERIES
77,TTKPRESTIG,-0.98,-23.46,30.77,0.09,23734.0,-23644.0,77133.0,770.00,-6.90,40.0,M-SC,9.68,250.0,-1.00,0.50,38.83,OX40N,NTT,DURABLES
52,M&M,0.18,8.03,9.99,18.82,25974.0,19323.0,260004.0,3762.88,-6.96,58.0,X-LC,4.87,25.0,0.74,1.68,17.94,X40N,ATH,AUTO
54,MASFIN,-0.53,-7.73,31.75,21.57,28704.0,-7575.0,90405.0,397.04,-28.64,42.0,H-SC,1.46,167.0,-0.26,0.58,7.76,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,3.80,-23.26,47.13,12.90,79022.0,-50827.0,167669.0,593.00,7.48,65.0,H-SC,11.89,170.0,-0.64,1.08,61.80,OX40N,NTT,FINANCE
14,CAMPUS,3.75,-23.78,74.86,33.28,95733.0,-39892.0,127883.0,393.00,NaN,53.0,NaN,10.56,218.0,-0.42,0.83,4.59,XY24,NTT,FOOTWEAR
62,REPCOHOME,3.74,-21.66,142.29,89.82,319381.0,-62047.0,224458.0,880.00,NaN,38.0,NaN,4.24,161.0,-0.19,1.45,7.90,XY24,NTT,FINANCE
71,TANLA,3.14,-33.42,226.29,117.25,407956.0,-90481.0,180280.0,1922.32,NaN,52.0,NaN,15.73,147.0,-0.22,1.16,57.84,AR,ATH,IT
30,HAPPSTMNDS,3.11,-47.17,246.58,83.08,166945.0,-60461.0,67704.0,1466.54,NaN,64.0,NaN,7.40,152.0,-0.36,0.44,26.81,AR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
51,LAOPALA,-5.31,-46.27,158.84,39.09,111901.0,-60656.0,70449.0,464.00,NaN,39.0,NaN,3.87,154.0,-0.54,0.46,9.30,AR,NTT,CERAMICS
29,GREENPANEL,-2.69,-56.90,232.14,43.14,183158.0,-104178.0,78900.0,537.00,NaN,26.0,NaN,11.94,225.0,-0.57,0.51,0.00,XY24,NTT,MISC
55,PAGEIND,-2.42,-7.80,44.09,32.85,109101.0,-20929.0,247450.0,50936.07,-31.47,29.0,X-MC,8.68,55.0,-0.19,1.60,18.16,X40,ATH,APPARELS
60,RELAXO,-1.94,-51.24,212.35,52.31,150306.0,-74378.0,70782.0,1176.00,NaN,39.0,NaN,11.87,92.0,-0.49,0.46,58.26,X40N,NTT,FOOTWEAR
18,COFFEEDAY,-1.82,-50.79,174.91,35.27,97726.0,-57677.0,55872.0,80.00,NaN,38.0,NaN,3.72,266.0,-0.59,0.36,37.78,XR,NTT,HOTELS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.19,66.70,24.72,107.91,60841.0,98476.0,246120.0,1641.55,21.68,74.0,M-SC,21.50,220.0,1.62,1.59,85.16,OX40N,ATH,CABLES
67,SIS,0.44,-4.60,27.11,21.26,28717.0,-5105.0,105927.0,528.00,103.76,39.0,H-SC,20.86,168.0,-0.18,0.68,57.50,OX40N,NTT,MISC
43,INDIGOPNTS,0.02,-18.24,22.33,0.02,31870.0,-31835.0,142724.0,1408.00,-22.11,65.0,M-SC,7.23,222.0,-1.00,0.92,61.93,OX40N,NTT,PAINTS
12,BOSCH-HCIL,-0.30,-23.00,29.85,-0.01,29377.0,-29391.0,98414.0,2282.00,770.72,77.0,M-SC,8.88,231.0,-1.00,0.64,67.52,OX40N,BTT,AC
0,5PAISA,3.80,-23.26,47.13,12.90,79022.0,-50827.0,167669.0,593.00,7.48,65.0,H-SC,11.89,170.0,-0.64,1.08,61.80,OX40N,NTT,FINANCE

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.19,66.7,24.72,107.91,60841.0,98476.0,246120.0,1641.55,21.68,74.0,M-SC,21.50,220.0,1.62,1.59,85.16,OX40N,ATH,CABLES
27,GLAXO,-0.85,20.7,12.42,35.69,29875.0,41252.0,240536.0,3380.16,-9.49,82.0,X-MC,10.84,56.0,1.38,1.55,42.96,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.19,66.70,24.72,107.91,60841.0,98476.0,246120.0,1641.55,21.68,74.0,M-SC,21.50,220.0,1.62,1.59,85.16,OX40N,ATH,CABLES
68,STARHEALTH,-0.04,12.94,30.39,47.26,96490.0,36383.0,317506.0,761.00,-0.37,50.0,H-SC,16.04,173.0,0.38,2.05,37.28,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.19,66.70,24.72,107.91,60841.0,98476.0,246120.0,1641.55,21.68,74.0,M-SC,21.50,220.0,1.62,1.59,85.16,OX40N,ATH,CABLES
3,ALKYLAMINE,0.95,-15.90,128.94,92.54,109486.0,-16051.0,84912.0,4520.85,NaN,62.0,NaN,15.09,142.0,-0.15,0.55,61.24,SR,ATH,CHEMICALS
67,SIS,0.44,-4.60,27.11,21.26,28717.0,-5105.0,105927.0,528.00,103.76,39.0,H-SC,20.86,168.0,-0.18,0.68,57.50,OX40N,NTT,MISC
42,INDIAMART,0.11,-24.58,166.42,100.92,154796.0,-30321.0,93015.0,4675.60,NaN,38.0,NaN,13.65,140.0,-0.20,0.60,0.69,AR,ATH,MISC
71,TANLA,3.14,-33.42,226.29,117.25,407956.0,-90481.0,180280.0,1922.32,NaN,52.0,NaN,15.73,147.0,-0.22,1.16,57.84,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.14,-28.73,96.24,39.86,180642.0,-75665.0,187700.0,3683.41,-13.63,27.0,X-MC,1.99,62.0,-0.42,1.21,6.17,XY25,ATH,FMCG
56,PGHH,-0.85,-38.21,113.64,32.01,149932.0,-81584.0,131936.0,17616.87,-54.51,28.0,X-SC,19.24,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
55,PAGEIND,-2.42,-7.80,44.09,32.85,109101.0,-20929.0,247450.0,50936.07,-31.47,29.0,X-MC,8.68,55.0,-0.19,1.60,18.16,X40,ATH,APPARELS
47,ITC,0.28,-26.12,68.78,24.70,201875.0,-103769.0,293509.0,452.00,-31.16,30.0,X-LC,10.61,1.0,-0.51,1.90,0.28,X40,NTT,FMCG
20,DABUR,0.16,-21.72,83.57,43.70,162288.0,-53874.0,194194.0,735.00,-32.48,33.0,X-MC,10.25,70.0,-0.33,1.25,0.16,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.14,-28.73,96.24,39.86,180642.0,-75665.0,187700.0,3683.41,-13.63,27.0,X-MC,1.99,62.0,-0.42,1.21,6.17,XY25,ATH,FMCG
50,KOTAKBANK,1.29,3.90,14.46,18.92,36011.0,9337.0,249039.0,452.46,-11.94,56.0,X-LC,2.20,12.0,0.26,1.61,12.05,X40,ATH,BANKS
23,DMART,1.69,-1.72,33.72,31.42,103329.0,-5358.0,306432.0,5391.45,-17.56,52.0,X-LC,2.24,14.0,-0.05,1.98,10.58,X40N,ATH,FMCG
26,GILLETTE,0.01,-11.16,46.02,29.72,103800.0,-28341.0,225555.0,10978.86,-35.84,37.0,X-SC,3.64,83.0,-0.27,1.46,3.65,X40,ATH,FMCG
1,ABBOTINDIA,-0.55,-11.32,30.09,15.37,47726.0,-20245.0,158610.0,34390.26,-27.79,38.0,X-MC,3.91,58.0,-0.42,1.02,7.44,X40,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.85,-38.21,113.64,32.01,149932.0,-81584.0,131936.0,17616.87,-54.51,28.0,X-SC,19.24,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
35,HDFCLIFE,0.07,-7.97,51.20,39.15,118149.0,-19977.0,230760.0,811.41,-32.34,41.0,X-LC,16.48,31.0,-0.17,1.49,0.15,X40,ATH,INSURANCE
20,DABUR,0.16,-21.72,83.57,43.70,162288.0,-53874.0,194194.0,735.00,-32.48,33.0,X-MC,10.25,70.0,-0.33,1.25,0.16,XY24,BTT,FMCG
83,VOLTAS,-0.33,-4.64,52.26,45.20,95557.0,-8892.0,182850.0,1856.00,31.32,34.0,X-MC,4.80,79.0,-0.09,1.18,0.22,XY25,NTT,AC
47,ITC,0.28,-26.12,68.78,24.70,201875.0,-103769.0,293509.0,452.00,-31.16,30.0,X-LC,10.61,1.0,-0.51,1.90,0.28,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.85,-38.21,113.64,32.01,149932.0,-81584.0,131936.0,17616.87,-54.51,28.0,X-SC,19.24,57.0,-0.54,0.85,0.00,X40,ATH,FMCG
2,ACC,1.11,-41.68,199.77,74.81,312360.0,-111768.0,156360.0,3906.00,-42.24,39.0,X-SC,11.60,85.0,-0.36,1.01,4.46,XY24,BTT,CEMENT
1,ABBOTINDIA,-0.55,-11.32,30.09,15.37,47726.0,-20245.0,158610.0,34390.26,-27.79,38.0,X-MC,3.91,58.0,-0.42,1.02,7.44,X40,ATH,PHARMA
40,ICICIPRULI,0.07,-17.29,57.50,30.28,93697.0,-34054.0,162951.0,787.27,-46.93,46.0,X-MC,12.22,78.0,-0.36,1.05,8.57,X40,ATH,INSURANCE
39,ICICIGI,-0.09,-14.06,38.35,18.89,65948.0,-28145.0,171964.0,2244.41,-14.33,40.0,X-MC,10.33,66.0,-0.43,1.11,2.45,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.28,-26.12,68.78,24.70,201875.0,-103769.0,293509.0,452.00,-31.16,30.0,X-LC,10.61,1.0,-0.51,1.90,0.28,X40,NTT,FMCG
73,TCS,0.79,-32.27,83.38,24.20,261618.0,-149507.0,313766.0,4230.71,-43.64,49.0,X-LC,13.86,2.0,-0.57,2.03,17.01,X40,ATH,IT
45,INFY,1.79,-18.85,73.00,40.38,223010.0,-70977.0,305493.0,1972.00,-40.08,51.0,X-LC,15.67,3.0,-0.32,1.97,15.69,X40,NTT,IT
75,TMPV,0.58,-23.12,85.67,42.75,274074.0,-96189.0,319918.0,600.00,-84.91,37.0,X-LC,4.28,4.0,-0.35,2.07,10.00,XY24,NTT,AUTO
33,HCLTECH,0.76,-10.72,38.84,23.97,107324.0,-33162.0,276324.0,1853.42,-13.01,57.0,X-LC,10.67,8.0,-0.31,1.78,30.39,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.44,-25.40,78.13,32.89,45001.0,-19608.0,57598.0,1800.00,323.79,51.0,L-MC,12.75,258.0,-0.44,0.37,42.00,XR,NTT,BANKS
30,HAPPSTMNDS,3.11,-47.17,246.58,83.08,166945.0,-60461.0,67704.0,1466.54,NaN,64.0,NaN,7.40,152.0,-0.36,0.44,26.81,AR,ATH,IT
3,ALKYLAMINE,0.95,-15.90,128.94,92.54,109486.0,-16051.0,84912.0,4520.85,NaN,62.0,NaN,15.09,142.0,-0.15,0.55,61.24,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-0.30,-23.00,29.85,-0.01,29377.0,-29391.0,98414.0,2282.00,770.72,77.0,M-SC,8.88,231.0,-1.00,0.64,67.52,OX40N,BTT,AC
67,SIS,0.44,-4.60,27.11,21.26,28717.0,-5105.0,105927.0,528.00,103.76,39.0,H-SC,20.86,168.0,-0.18,0.68,57.50,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-0.30,-23.00,29.85,-0.01,29377.0,-29391.0,98414.0,2282.00,770.72,77.0,M-SC,8.88,231.0,-1.00,0.64,67.52,OX40N,BTT,AC
25,FINCABLES,0.19,66.70,24.72,107.91,60841.0,98476.0,246120.0,1641.55,21.68,74.0,M-SC,21.50,220.0,1.62,1.59,85.16,OX40N,ATH,CABLES
27,GLAXO,-0.85,20.70,12.42,35.69,29875.0,41252.0,240536.0,3380.16,-9.49,82.0,X-MC,10.84,56.0,1.38,1.55,42.96,X40,ATH,PHARMA
81,VALIANTORG,2.13,-34.33,165.19,74.15,177480.0,-56165.0,107440.0,838.00,NaN,61.0,NaN,7.98,145.0,-0.32,0.69,59.89,XR,NTT,CHEMICALS
38,HYUNDAI,0.71,13.28,27.07,43.94,77068.0,33368.0,284700.0,2782.73,17.21,62.0,X-LC,5.64,29.0,0.43,1.84,30.72,X40N,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.74
1     25       45.04
2     50       77.66

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    38.03
MC    22.18
SC    21.63
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.65
XY24     24.06
X40N     18.70
XR        9.11
OX40N     7.37
XY25      7.13
AR        6.12
SR        0.88
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.37
X-MC    19.60
H-SC     8.56
X-SC     7.60
M-SC     5.47
H-LC     2.85
M-MC     1.18
H-MC     1.03
M-LC     0.81
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.38        -25.20   70.22
IT                  11.29        -36.28  103.87
FINANCE             10.80        -15.44   65.17
AUTO                 8.27         -5.78   43.66
BANKS                6.19        -11.40   59.44
MISC                 5.95        -34.05   87.97
PHARMA               5.86          8.73   17.15
INSURANCE            5.70         -5.19   42.38
PAINTS               5.48        -16.30   36.14
ELECTRICAL           4.17         -9.56   43.86
AC                   1.82        -13.61   44.42
REFINERIES           1.72        -11.61   49.10
BREWERIES            1.71         11.70    6.64
FOOTWEAR             1.68        -70.77  139.24
APPARELS             1.60         -8.46   44.09
CABLES               1.59         40.01   24.72
DURABLES             1.46        -70.77  112.31
TRAVEL               1.42       -103.53  205.44
CERAMICS             1.31        -51.86   97.99
ENGINEERING          1.25        -24.87   81.98
CHEMICALS            1.24        -37.54  149.19
CEMENT               1.01        -71.48  199.77
JEWELLERY            0.97       -113.19  187.26
HEALTHCARE           0.70        -68.03  110.21
ENTERTAINMENT        0.69        -80.91  188.81
TEXTILES             0.40        -50.30   93.16
HOTELS               0.36       -103.23  174.91

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3606590.0     19
X40       2097733.0     18
XR        1385681.0     13
X40N      1184441.0     12
AR        1059552.0      8
OX40N      650539.0     10
XY25       593996.0      5
SR         279750.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2406391.0     19
X-MC        1463732.0     14
X-SC        1103554.0      6
H-SC         824539.0      8
M-SC         319658.0      6
H-MC         253927.0      1
M-LC         166096.0      1
M-MC          62813.0      1
H-LC          49459.0      2
L-MC          45001.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1221698.0      9
X-SC       XY24       675469.0      2
H-SC       XY24       522407.0      3
X-MC       X40        508273.0      6
X-LC       XY24       457949.0      2
X-MC       X40N       448822.0      4
X-LC       X40N       410960.0      5
X-MC       XY25       276199.0      2
X-LC       XY25       254984.0      2
H-MC       XY24       253927.0      1
X-SC       X40        253732.0      2
X-MC       XY24       230438.0      2
H-SC       OX40N      211204.0      3
X-SC       X40N       174353.0      2
M-LC       XR         166096.0      1
M-SC       OX40N      145822.0      4
           XY24       116654.0      1
H-SC       XR          90928.0      2
M-MC       XY25        62813.0      1
X-LC       XR          60800.0      1
M-SC       XR          57182.0      1
H-LC       AR          49459.0      2
L-MC       XR          45001.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 32.0 seconds