<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-02 11:28:43
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.27 C
-------------------
Today PnL: -2.15 L (-1.67%)
Current PnL: -50.40 L (-31.02%)
CY Booked + Current PnL: -34.51 L (-21.24%)
-------------------
Total profit:  35.93 K
Total loss:  -50.76 L
-------------------
Total Booked + Current PnL: -7.53 L (-5.56%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (12.54%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.21 C (95.61%)
===================
Deployed:  1.36 C
Current:  1.27 C
CAGR/XIRR %: -3.24%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,MASFIN,-1.53,-11.59,37.50,21.57,32484.0,-11355.0,86625.0,397.04,-23.67,42.0,H-SC,4.96,167.0,-0.35,0.68,18.15,XR,ATH,FINANCE
77,TTKPRESTIG,-2.55,-43.60,77.48,0.09,44035.0,-43943.0,56834.0,770.00,31.91,36.0,M-SC,22.21,250.0,-1.00,0.45,1.20,OX40N,NTT,DURABLES
2,ABBOTINDIA,-0.53,-11.60,33.57,18.07,53074.0,-20755.0,158100.0,35195.00,-24.86,47.0,X-MC,10.42,58.0,-0.39,1.25,3.39,X40,ATH,PHARMA
67,SONACOMS,-1.75,-15.48,64.57,39.09,55205.0,-15663.0,85496.0,804.02,-33.03,45.0,M-MC,6.71,193.0,-0.28,0.67,20.95,AR,ATH,AUTO
42,INDUSINDBK,-3.54,-44.05,137.51,32.89,59400.0,-34010.0,43197.0,1800.00,-303.08,35.0,L-MC,6.65,258.0,-0.57,0.34,12.12,XR,NTT,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
52,PAGEIND,3.91,-11.59,51.70,34.11,122666.0,-31114.0,237265.0,51418.65,-36.57,62.0,X-MC,20.31,55.0,-0.25,1.87,12.24,X40,ATH,APPARELS
24,DMART,0.78,3.47,25.26,29.60,65236.0,8658.0,258258.0,5391.45,-12.73,72.0,X-LC,6.35,14.0,0.13,2.04,18.05,X40N,ATH,FMCG
33,HCLTECH,0.75,-11.45,39.85,23.83,85369.0,-27698.0,214226.0,1908.19,-6.95,45.0,X-LC,11.59,8.0,-0.32,1.69,4.02,X40,ATH,IT
15,BSOFT,0.61,-36.22,136.41,50.79,122372.0,-50944.0,89709.0,831.70,-18.05,44.0,H-SC,8.57,172.0,-0.42,0.71,5.79,XR,ATH,IT
49,LAOPALA,0.27,-47.94,167.16,39.09,114097.0,-62849.0,68256.0,464.00,49.34,38.0,H-SC,17.77,154.0,-0.55,0.54,5.90,AR,NTT,CERAMICS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
80,VALIANTORG,-4.75,-54.33,281.29,74.15,210194.0,-88880.0,74725.0,838.0,-234.12,47.0,H-SC,27.82,145.0,-0.42,0.59,11.20,XR,NTT,CHEMICALS
82,VOLTAS,-4.03,-6.18,54.76,45.20,98511.0,-11847.0,179895.0,1856.0,7.45,31.0,X-MC,3.07,79.0,-0.12,1.42,0.20,XY25,NTT,AC
11,BANDHANBNK,-3.85,-31.70,181.73,92.42,345747.0,-88306.0,190253.0,400.0,63.07,35.0,H-SC,0.98,174.0,-0.26,1.50,4.81,XY24,NTT,BANKS
47,JSWINFRA,-3.83,-18.82,43.42,16.43,78172.0,-41737.0,180037.0,342.0,-30.42,40.0,X-MC,11.95,61.0,-0.53,1.42,0.00,X40N,NTT,REALTY
38,ICICIPRULI,-3.69,-18.19,59.79,30.73,96366.0,-35831.0,161174.0,790.0,-40.17,18.0,X-MC,8.79,78.0,-0.37,1.27,0.00,X40,ATH,INSURANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,-2.85,-1.71,111.54,107.91,161858.0,-2532.0,145112.0,1641.55,-11.72,41.0,M-SC,5.57,220.0,-0.02,1.15,9.17,OX40N,ATH,CABLES
66,SIS,-1.72,-35.13,86.94,21.26,62619.0,-39007.0,72025.0,528.00,1684.97,45.0,H-SC,14.81,168.0,-0.62,0.57,7.09,OX40N,NTT,MISC
72,TATAELXSI,-0.00,-40.52,121.98,32.03,95648.0,-53422.0,78413.0,9161.00,-25.57,40.0,H-SC,21.85,158.0,-0.56,0.62,3.78,OX40N,NTT,IT
18,CERA,-2.65,-40.59,108.53,23.89,113421.0,-71396.0,104507.0,9475.00,-42.72,41.0,H-SC,19.41,153.0,-0.63,0.82,0.43,OX40N,NTT,CERAMICS
48,KANSAINER,0.16,-41.31,93.36,13.47,147748.0,-111411.0,158256.0,340.00,-49.54,43.0,H-SC,23.16,162.0,-0.75,1.25,10.54,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.73,10.42,31.83,45.57,91953.0,27269.0,288888.0,7934.0,-29.04,49.0,H-MC,13.23,125.0,0.3,2.28,28.29,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.73,10.42,31.83,45.57,91953.0,27269.0,288888.0,7934.00,-29.04,49.0,H-MC,13.23,125.0,0.30,2.28,28.29,AR,NTT,ELECTRICAL
26,FINCABLES,-2.85,-1.71,111.54,107.91,161858.0,-2532.0,145112.0,1641.55,-11.72,41.0,M-SC,5.57,220.0,-0.02,1.15,9.17,OX40N,ATH,CABLES
40,INDIAMART,-0.73,-13.03,137.69,106.72,147696.0,-16069.0,107267.0,4810.62,-60.74,43.0,H-SC,12.93,140.0,-0.11,0.85,7.30,AR,ATH,MISC
84,WIPRO,-0.15,-21.71,120.02,72.27,159229.0,-36779.0,132669.0,420.00,-29.24,38.0,M-LC,18.24,98.0,-0.23,1.05,1.79,XR,NTT,IT
85,ZYDUSLIFE,-1.73,-10.55,51.62,35.63,96774.0,-22100.0,187474.0,1286.17,-22.07,38.0,H-MC,5.73,120.0,-0.23,1.48,4.37,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
38,ICICIPRULI,-3.69,-18.19,59.79,30.73,96366.0,-35831.0,161174.0,790.00,-40.17,18.0,X-MC,8.79,78.0,-0.37,1.27,0.0,X40,ATH,INSURANCE
37,ICICIGI,-3.44,-13.31,37.66,19.34,65333.0,-26629.0,173480.0,2252.93,-27.19,23.0,X-MC,6.10,66.0,-0.41,1.37,0.0,X40,ATH,INSURANCE
21,DABUR,-2.17,-20.63,81.06,43.70,159596.0,-51182.0,196886.0,735.00,-27.96,26.0,X-MC,11.04,70.0,-0.32,1.55,0.0,XY24,BTT,FMCG
32,HAVELLS,-2.82,-26.21,78.99,32.08,191176.0,-85966.0,242025.0,2062.85,-30.65,27.0,X-MC,11.39,63.0,-0.45,1.91,0.0,X40,ATH,ELECTRICAL
34,HDFCBANK,-1.55,-12.58,46.84,28.37,96182.0,-29544.0,205341.0,1073.00,-25.47,28.0,X-LC,15.60,26.0,-0.31,1.62,0.0,X40,BTT,BANKS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,-2.77,-21.19,59.26,25.51,86914.0,-39430.0,146665.0,4671.50,23.15,40.0,H-LC,0.49,51.0,-0.45,1.16,8.01,AR,ATH,ELECTRICAL
82,VOLTAS,-4.03,-6.18,54.76,45.20,98511.0,-11847.0,179895.0,1856.00,7.45,31.0,X-MC,3.07,79.0,-0.12,1.42,0.20,XY25,NTT,AC
78,UNITDSPR,-2.63,-10.64,35.15,20.77,73541.0,-24923.0,209221.0,1644.00,-20.80,36.0,X-MC,3.75,64.0,-0.34,1.65,0.00,X40N,NTT,BREWERIES
59,RELIANCE,-2.25,-14.09,45.85,25.30,79162.0,-28309.0,172654.0,1952.00,-16.19,38.0,X-LC,3.92,21.0,-0.36,1.36,15.27,XY25,BTT,REFINERIES
37,ICICIGI,-3.44,-13.31,37.66,19.34,65333.0,-26629.0,173480.0,2252.93,-27.19,23.0,X-MC,6.10,66.0,-0.41,1.37,0.00,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BAJAJHLDNG,-2.82,-22.61,66.96,29.22,98528.0,-42981.0,147144.0,14451.52,-28.25,28.0,X-LC,19.86,28.0,-0.44,1.16,0.0,X40,ATH,FINANCE
21,DABUR,-2.17,-20.63,81.06,43.70,159596.0,-51182.0,196886.0,735.00,-27.96,26.0,X-MC,11.04,70.0,-0.32,1.55,0.0,XY24,BTT,FMCG
47,JSWINFRA,-3.83,-18.82,43.42,16.43,78172.0,-41737.0,180037.0,342.00,-30.42,40.0,X-MC,11.95,61.0,-0.53,1.42,0.0,X40N,NTT,REALTY
38,ICICIPRULI,-3.69,-18.19,59.79,30.73,96366.0,-35831.0,161174.0,790.00,-40.17,18.0,X-MC,8.79,78.0,-0.37,1.27,0.0,X40,ATH,INSURANCE
37,ICICIGI,-3.44,-13.31,37.66,19.34,65333.0,-26629.0,173480.0,2252.93,-27.19,23.0,X-MC,6.10,66.0,-0.41,1.37,0.0,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.96,-66.59,355.90,52.31,172594.0,-96665.0,48495.0,1176.00,-64.48,33.0,X-SC,31.51,92.0,-0.56,0.38,8.43,X40N,NTT,FOOTWEAR
12,BATAINDIA,-0.49,-59.68,235.36,35.20,122093.0,-76795.0,51875.0,2096.00,-31.99,31.0,X-SC,34.15,91.0,-0.63,0.41,2.88,X40,NTT,FOOTWEAR
54,QUESS,-0.66,-28.17,142.11,73.90,109008.0,-30086.0,76707.0,424.00,-61.43,41.0,X-SC,22.40,80.0,-0.28,0.61,3.19,XY24,NTT,MISC
36,HONAUT,-2.35,-30.90,118.98,51.31,158541.0,-59588.0,133250.0,58357.33,-42.60,32.0,X-SC,17.99,90.0,-0.38,1.05,1.23,X40N,ATH,ELECTRICAL
51,MEDANTA,-1.47,-16.62,52.46,27.12,77206.0,-29345.0,147172.0,1486.00,-19.15,35.0,X-SC,15.20,87.0,-0.38,1.16,1.41,XY24,NTT,HEALTHCARE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.58,-23.61,55.86,19.06,145147.0,-80326.0,259840.0,452.00,-57.95,35.0,X-LC,19.74,1.0,-0.55,2.05,0.80,X40,NTT,FMCG
73,TCS,-0.09,-29.37,79.20,26.57,259155.0,-136057.0,327216.0,4311.59,-40.35,36.0,X-LC,18.65,2.0,-0.53,2.58,2.12,X40,ATH,IT
43,INFY,-0.59,-13.67,55.50,34.24,149920.0,-42761.0,270127.0,1972.00,-32.15,42.0,X-LC,15.07,3.0,-0.29,2.13,3.88,X40,NTT,IT
75,TMPV,-2.43,-32.71,102.98,36.58,246571.0,-116405.0,239436.0,600.00,-85.81,34.0,X-LC,11.29,4.0,-0.47,1.89,0.00,XY24,NTT,AUTO
33,HCLTECH,0.75,-11.45,39.85,23.83,85369.0,-27698.0,214226.0,1908.19,-6.95,45.0,X-LC,11.59,8.0,-0.32,1.69,4.02,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,-0.73,10.42,31.83,45.57,91953.0,27269.0,288888.0,7934.0,-29.04,49.0,H-MC,13.23,125.0,0.3,2.28,28.29,AR,NTT,ELECTRICAL

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
24,DMART,0.78,3.47,25.26,29.60,65236.0,8658.0,258258.0,5391.45,-12.73,72.0,X-LC,6.35,14.0,0.13,2.04,18.05,X40N,ATH,FMCG
30,HAPPSTMNDS,-2.02,-51.96,284.80,84.85,175346.0,-66597.0,61568.0,1480.71,-42.90,50.0,H-SC,24.44,152.0,-0.38,0.49,14.01,AR,ATH,IT
52,PAGEIND,3.91,-11.59,51.70,34.11,122666.0,-31114.0,237265.0,51418.65,-36.57,62.0,X-MC,20.31,55.0,-0.25,1.87,12.24,X40,ATH,APPARELS
5,ANGELONE,-2.96,-4.31,29.78,24.18,86913.0,-13150.0,291850.0,303.00,-85.87,50.0,X-SC,9.74,97.0,-0.15,2.30,12.34,X40N,NTT,FINANCE
1,ABB,-0.73,10.42,31.83,45.57,91953.0,27269.0,288888.0,7934.00,-29.04,49.0,H-MC,13.23,125.0,0.30,2.28,28.29,AR,NTT,ELECTRICAL

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.14
1     25       46.36
2     50       78.29

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.35
MC    29.79
LC    25.84
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.01
X40      25.47
X40N     15.51
AR        9.17
XR        8.27
XY25      7.18
OX40N     6.59
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    23.63
X-MC    22.35
H-SC    21.70
X-SC    12.30
M-SC     9.83
H-MC     5.05
M-MC     2.05
H-LC     1.16
M-LC     1.05
L-SC     0.52
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.37        -28.23   73.76
FINANCE             13.13        -29.14   81.77
IT                  12.13        -46.68  121.32
MISC                 7.01        -50.92  116.48
ELECTRICAL           6.40        -19.45   65.19
PAINTS               5.28        -47.52   73.14
INSURANCE            4.59        -16.50   56.37
BANKS                4.45        -36.41  105.65
PHARMA               4.18        -11.15   46.13
AUTO                 3.64        -41.71   97.93
AC                   1.90        -32.41   68.31
HEALTHCARE           1.90        -48.28   86.97
APPARELS             1.87        -13.11   51.70
FOOTWEAR             1.78        -95.36  173.69
TRAVEL               1.77        -98.63  198.08
DURABLES             1.76        -73.50  115.70
BREWERIES            1.65        -11.91   35.15
REALTY               1.42        -23.18   43.42
REFINERIES           1.36        -16.40   45.85
CERAMICS             1.36        -77.70  131.69
CEMENT               1.24        -70.79  198.56
CABLES               1.15         -1.74  111.54
ENGINEERING          1.07        -78.23  159.75
CHEMICALS            1.02       -104.55  271.43
JEWELLERY            0.98       -158.06  247.72
ENTERTAINMENT        0.76       -101.91  222.33
TEXTILES             0.46        -58.80  104.08
HOTELS               0.35       -153.71  243.20

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      4173750.0     21
X40       1947274.0     16
XR        1442819.0     12
AR        1411211.0     10
X40N      1334081.0     10
OX40N      957171.0     10
XY25       529908.0      5
SR         319994.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        4042870.0     24
X-MC        1902504.0     15
X-LC        1780565.0     13
M-SC        1672037.0     14
X-SC        1623859.0     10
H-MC         438489.0      3
L-SC         224489.0      2
M-LC         159229.0      1
M-MC         125852.0      2
H-LC          86914.0      1
L-MC          59400.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1396085.0      6
           AR         999101.0      5
X-LC       X40        966694.0      7
M-SC       XY24       961591.0      6
H-SC       XR         919948.0      7
X-SC       XY24       874047.0      4
X-MC       X40        750466.0      7
           X40N       575841.0      4
X-SC       X40N       519698.0      4
M-SC       OX40N      433784.0      5
H-SC       OX40N      407742.0      4
X-LC       XY24       406882.0      2
H-SC       SR         319994.0      2
X-MC       XY25       290814.0      2
           XY24       285383.0      2
H-MC       XY24       249762.0      1
X-LC       X40N       238542.0      2
X-SC       X40        230114.0      2
M-SC       XR         195398.0      2
H-MC       AR         188727.0      2
X-LC       XY25       168447.0      2
M-LC       XR         159229.0      1
L-SC       OX40N      115645.0      1
           XR         108844.0      1
H-LC       AR          86914.0      1
M-SC       AR          81264.0      1
M-MC       XY25        70647.0      1
L-MC       XR          59400.0      1
M-MC       AR          55205.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 34.0 seconds