<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-04-20 14:55:57
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 16
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  1.61 K
Current:  1.44 C
-------------------
Today PnL: -78.34 K (-0.54%)
Current PnL: -33.42 L (-20.57%)
CY Booked + Current PnL: -17.53 L (-10.79%)
-------------------
Total profit:  2.65 L
Total loss:  -36.06 L
-------------------
Total Booked + Current PnL: 9.45 L (6.98%)
Total Booked PnL: 42.87 L (31.64%)
Curr Year Booked PnL: 15.89 L (11.06%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.48 C
Est FTT PnL: 1.04 C (72.49%)
===================
Deployed:  1.36 C
Current:  1.44 C
CAGR/XIRR %: 2.83%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-0.31,31.75,-5.74,24.18,-23065.0,96825.0,401825.0,303.00,-80.83,78.0,X-SC,3.70,97.0,-4.20,2.80,53.73,X40N,NTT,FINANCE
50,MASFIN,-0.43,-3.31,25.73,21.57,24377.0,-3240.0,94740.0,397.04,-16.44,56.0,H-SC,3.55,167.0,-0.13,0.66,22.43,XR,ATH,FINANCE
77,TTKPRESTIG,0.58,-35.26,54.62,0.09,35633.0,-35539.0,65238.0,770.00,51.33,55.0,M-SC,23.10,250.0,-1.00,0.45,16.17,OX40N,NTT,DURABLES
67,SONACOMS,-1.14,1.56,36.96,39.09,37970.0,1575.0,102734.0,804.02,-19.52,67.0,M-MC,10.09,193.0,0.04,0.71,45.33,AR,ATH,AUTO
1,ABB,1.47,30.86,11.24,45.57,38481.0,80741.0,342360.0,7934.00,-15.89,75.0,H-MC,17.68,125.0,2.10,2.38,52.03,AR,NTT,ELECTRICAL

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
83,WHIRLPOOL,3.33,-26.32,146.90,81.92,124255.0,-30213.0,84585.0,2270.0,-56.86,65.0,M-SC,24.67,210.0,-0.24,0.59,18.82,XR,NTT,DURABLES
1,ABB,1.47,30.86,11.24,45.57,38481.0,80741.0,342360.0,7934.0,-15.89,75.0,H-MC,17.68,125.0,2.10,2.38,52.03,AR,NTT,ELECTRICAL
13,BERGEPAINT,1.27,-12.55,43.29,25.32,97580.0,-32338.0,225411.0,680.0,-17.30,67.0,X-MC,16.31,68.0,-0.33,1.57,17.32,XY24,NTT,PAINTS
82,VOLTAS,1.22,14.03,27.33,45.20,59754.0,26898.0,218640.0,1856.0,30.49,61.0,X-MC,6.87,79.0,0.45,1.52,21.78,XY25,NTT,AC
62,SATIN,0.63,-2.14,55.15,51.83,149112.0,-5909.0,270375.0,274.0,-11.96,78.0,H-SC,1.84,159.0,-0.04,1.88,31.71,XY24,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,IEX,-6.05,-13.40,71.63,48.63,124029.0,-26801.0,173153.0,219.0,-42.40,52.0,H-SC,11.31,137.0,-0.22,1.21,11.20,XR,NTT,MISC
31,HATHWAY,-4.31,-38.80,183.14,73.29,121861.0,-42180.0,66540.0,31.4,671.74,58.0,H-SC,20.88,171.0,-0.35,0.46,25.03,XR,NTT,ENTERTAINMENT
46,JIOFIN,-2.76,-21.30,63.19,28.43,148351.0,-63558.0,234769.0,387.0,-22.55,47.0,X-LC,18.78,34.0,-0.43,1.63,5.82,XY24,BTT,FINANCE
19,COFFEEDAY,-2.43,-53.91,193.47,35.27,101260.0,-61210.0,52339.0,80.0,-63.78,55.0,L-SC,31.49,266.0,-0.60,0.36,29.07,XR,NTT,HOTELS
56,RAJOOENG,-2.35,-35.60,116.79,39.61,77093.0,-36490.0,66010.0,143.1,-56.41,62.0,H-SC,29.49,136.0,-0.47,0.46,41.41,AR,ATH,MISC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
85,ZYDUSLIFE,-0.19,-0.64,36.51,35.63,76023.0,-1348.0,208226.0,1286.17,-13.51,64.0,H-MC,5.15,120.0,-0.02,1.45,12.73,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
26,FINCABLES,0.26,19.44,74.08,107.91,130633.0,28697.0,176341.0,1641.55,7.56,67.0,M-SC,2.96,220.0,0.22,1.23,32.67,OX40N,ATH,CABLES
66,SIS,-1.38,-26.75,65.54,21.26,53305.0,-29700.0,81332.0,528.00,1915.54,65.0,H-SC,11.39,168.0,-0.56,0.57,20.93,OX40N,NTT,MISC
18,CERA,-0.35,-30.62,78.56,23.89,95879.0,-53858.0,122045.0,9475.00,-33.17,67.0,H-SC,13.89,153.0,-0.56,0.85,17.28,OX40N,NTT,CERAMICS
48,KANSAINER,-1.13,-32.98,69.32,13.47,125275.0,-88947.0,180720.0,340.00,-42.48,62.0,H-SC,21.21,162.0,-0.71,1.26,26.23,XY24,NTT,PAINTS
72,TATAELXSI,-1.98,-35.13,103.51,32.03,88529.0,-46308.0,85527.0,9161.00,-18.85,54.0,H-SC,18.87,158.0,-0.52,0.60,13.20,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.47,30.86,11.24,45.57,38481.0,80741.0,342360.0,7934.0,-15.89,75.0,H-MC,17.68,125.0,2.1,2.38,52.03,AR,NTT,ELECTRICAL
5,ANGELONE,-0.31,31.75,-5.74,24.18,-23065.0,96825.0,401825.0,303.0,-80.83,78.0,X-SC,3.70,97.0,-4.2,2.80,53.73,X40N,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,RECLTD,0.39,1.45,19.01,20.74,39182.0,2942.0,206112.0,446.00,11.33,68.0,M-MC,5.21,191.0,0.08,1.43,22.83,XY25,NTT,FINANCE
26,FINCABLES,0.26,19.44,74.08,107.91,130633.0,28697.0,176341.0,1641.55,7.56,67.0,M-SC,2.96,220.0,0.22,1.23,32.67,OX40N,ATH,CABLES
1,ABB,1.47,30.86,11.24,45.57,38481.0,80741.0,342360.0,7934.00,-15.89,75.0,H-MC,17.68,125.0,2.10,2.38,52.03,AR,NTT,ELECTRICAL
67,SONACOMS,-1.14,1.56,36.96,39.09,37970.0,1575.0,102734.0,804.02,-19.52,67.0,M-MC,10.09,193.0,0.04,0.71,45.33,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.47,30.86,11.24,45.57,38481.0,80741.0,342360.0,7934.00,-15.89,75.0,H-MC,17.68,125.0,2.10,2.38,52.03,AR,NTT,ELECTRICAL
26,FINCABLES,0.26,19.44,74.08,107.91,130633.0,28697.0,176341.0,1641.55,7.56,67.0,M-SC,2.96,220.0,0.22,1.23,32.67,OX40N,ATH,CABLES
67,SONACOMS,-1.14,1.56,36.96,39.09,37970.0,1575.0,102734.0,804.02,-19.52,67.0,M-MC,10.09,193.0,0.04,0.71,45.33,AR,ATH,AUTO
85,ZYDUSLIFE,-0.19,-0.64,36.51,35.63,76023.0,-1348.0,208226.0,1286.17,-13.51,64.0,H-MC,5.15,120.0,-0.02,1.45,12.73,AR,ATH,PHARMA
40,INDIAMART,0.54,-6.21,120.41,106.72,139288.0,-7658.0,115678.0,4810.62,-57.62,63.0,H-SC,12.18,140.0,-0.05,0.81,11.14,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.45,-13.89,37.11,18.07,57157.0,-24835.0,154020.0,35195.00,-26.70,42.0,X-MC,11.77,58.0,-0.43,1.07,0.73,X40,ATH,PHARMA
53,PGHH,-0.73,-25.58,77.38,32.01,122960.0,-54616.0,158904.0,17616.87,-49.68,46.0,X-MC,21.52,57.0,-0.44,1.11,8.68,X40,ATH,FMCG
34,HDFCBANK,-0.54,-4.82,34.87,28.37,77957.0,-11321.0,223564.0,1073.00,-19.05,47.0,X-LC,17.42,26.0,-0.15,1.56,8.76,X40,BTT,BANKS
46,JIOFIN,-2.76,-21.30,63.19,28.43,148351.0,-63558.0,234769.0,387.00,-22.55,47.0,X-LC,18.78,34.0,-0.43,1.63,5.82,XY24,BTT,FINANCE
38,ICICIPRULI,-1.40,-8.30,42.56,30.73,76886.0,-16352.0,180653.0,790.00,-32.95,47.0,X-MC,12.81,78.0,-0.21,1.26,10.08,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
65,SIEMENS,0.49,0.12,25.37,25.51,47267.0,215.0,186310.0,4671.50,56.49,72.0,H-LC,2.11,51.0,0.00,1.30,31.81,AR,ATH,ELECTRICAL
5,ANGELONE,-0.31,31.75,-5.74,24.18,-23065.0,96825.0,401825.0,303.00,-80.83,78.0,X-SC,3.70,97.0,-4.20,2.80,53.73,X40N,NTT,FINANCE
24,DMART,-0.44,10.77,17.00,29.60,47003.0,26886.0,276486.0,5391.45,-6.58,70.0,X-LC,4.65,14.0,0.57,1.92,26.38,X40N,ATH,FMCG
59,RELIANCE,-0.31,-12.65,43.45,25.30,76273.0,-25420.0,175543.0,1952.00,-15.03,49.0,X-LC,5.50,21.0,-0.33,1.22,5.81,XY25,BTT,REFINERIES
78,UNITDSPR,-0.35,-4.63,26.63,20.77,59467.0,-10836.0,223308.0,1644.00,-15.41,52.0,X-MC,6.33,64.0,-0.18,1.55,6.52,X40N,NTT,BREWERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
2,ABBOTINDIA,-0.45,-13.89,37.11,18.07,57157.0,-24835.0,154020.0,35195.0,-26.70,42.0,X-MC,11.77,58.0,-0.43,1.07,0.73,X40,ATH,PHARMA
59,RELIANCE,-0.31,-12.65,43.45,25.30,76273.0,-25420.0,175543.0,1952.0,-15.03,49.0,X-LC,5.50,21.0,-0.33,1.22,5.81,XY25,BTT,REFINERIES
46,JIOFIN,-2.76,-21.30,63.19,28.43,148351.0,-63558.0,234769.0,387.0,-22.55,47.0,X-LC,18.78,34.0,-0.43,1.63,5.82,XY24,BTT,FINANCE
45,ITC,-0.11,-19.28,47.50,19.06,130425.0,-65587.0,274579.0,452.0,-55.52,54.0,X-LC,19.15,1.0,-0.50,1.91,6.52,X40,NTT,FMCG
78,UNITDSPR,-0.35,-4.63,26.63,20.77,59467.0,-10836.0,223308.0,1644.0,-15.41,52.0,X-MC,6.33,64.0,-0.18,1.55,6.52,X40N,NTT,BREWERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,-0.34,-60.11,281.83,52.31,163185.0,-87258.0,57902.0,1176.00,-57.51,58.0,X-SC,32.07,92.0,-0.53,0.40,29.46,X40N,NTT,FOOTWEAR
12,BATAINDIA,-1.35,-51.80,180.53,35.20,111952.0,-66657.0,62013.0,2096.00,-18.70,59.0,X-SC,32.19,91.0,-0.60,0.43,22.99,X40,NTT,FOOTWEAR
54,QUESS,-1.47,-20.25,118.05,73.90,100542.0,-21624.0,85169.0,424.00,-57.02,58.0,X-SC,19.62,80.0,-0.22,0.59,14.57,XY24,NTT,MISC
2,ABBOTINDIA,-0.45,-13.89,37.11,18.07,57157.0,-24835.0,154020.0,35195.00,-26.70,42.0,X-MC,11.77,58.0,-0.43,1.07,0.73,X40,ATH,PHARMA
53,PGHH,-0.73,-25.58,77.38,32.01,122960.0,-54616.0,158904.0,17616.87,-49.68,46.0,X-MC,21.52,57.0,-0.44,1.11,8.68,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,-0.11,-19.28,47.50,19.06,130425.0,-65587.0,274579.0,452.00,-55.52,54.0,X-LC,19.15,1.0,-0.50,1.91,6.52,X40,NTT,FMCG
73,TCS,-0.21,-24.38,67.38,26.57,236056.0,-112937.0,350336.0,4311.59,-36.09,55.0,X-LC,16.52,2.0,-0.48,2.44,9.34,X40,ATH,IT
43,INFY,-0.49,-10.66,50.27,34.24,140515.0,-33368.0,279520.0,1972.00,-29.61,51.0,X-LC,13.06,3.0,-0.24,1.95,7.50,X40,NTT,IT
75,TMPV,-1.01,-18.86,68.33,36.58,197285.0,-67117.0,288724.0,600.00,-83.62,61.0,X-LC,10.09,4.0,-0.34,2.01,20.34,XY24,NTT,AUTO
33,HCLTECH,-0.85,-7.20,33.44,23.83,75076.0,-17414.0,224510.0,1908.19,-2.40,53.0,X-LC,7.70,8.0,-0.23,1.56,9.01,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,SONACOMS,-1.14,1.56,36.96,39.09,37970.0,1575.0,102734.0,804.02,-19.52,67.0,M-MC,10.09,193.0,0.04,0.71,45.33,AR,ATH,AUTO
69,SURYODAY,-1.06,-18.82,51.56,23.03,74953.0,-33701.0,145370.0,216.00,57.89,62.0,H-SC,3.86,166.0,-0.45,1.01,23.97,XR,NTT,BANKS
26,FINCABLES,0.26,19.44,74.08,107.91,130633.0,28697.0,176341.0,1641.55,7.56,67.0,M-SC,2.96,220.0,0.22,1.23,32.67,OX40N,ATH,CABLES
65,SIEMENS,0.49,0.12,25.37,25.51,47267.0,215.0,186310.0,4671.50,56.49,72.0,H-LC,2.11,51.0,0.00,1.30,31.81,AR,ATH,ELECTRICAL
57,RECLTD,0.39,1.45,19.01,20.74,39182.0,2942.0,206112.0,446.00,11.33,68.0,M-MC,5.21,191.0,0.08,1.43,22.83,XY25,NTT,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ANGELONE,-0.31,31.75,-5.74,24.18,-23065.0,96825.0,401825.0,303.00,-80.83,78.0,X-SC,3.70,97.0,-4.20,2.80,53.73,X40N,NTT,FINANCE
55,RAJESHEXPO,-2.22,-76.14,319.43,0.07,104543.0,-104449.0,32728.0,518.00,1099.49,60.0,L-SC,41.88,268.0,-1.00,0.23,53.65,OX40N,NTT,JEWELLERY
24,DMART,-0.44,10.77,17.00,29.60,47003.0,26886.0,276486.0,5391.45,-6.58,70.0,X-LC,4.65,14.0,0.57,1.92,26.38,X40N,ATH,FMCG
62,SATIN,0.63,-2.14,55.15,51.83,149112.0,-5909.0,270375.0,274.00,-11.96,78.0,H-SC,1.84,159.0,-0.04,1.88,31.71,XY24,NTT,FINANCE
48,KANSAINER,-1.13,-32.98,69.32,13.47,125275.0,-88947.0,180720.0,340.00,-42.48,62.0,H-SC,21.21,162.0,-0.71,1.26,26.23,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       21.32
1     25       46.03
2     50       77.97

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    45.32
MC    29.56
LC    25.11
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.07
X40      24.42
X40N     16.05
AR        9.37
XR        8.26
XY25      7.20
OX40N     6.84
SR        0.78
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    22.83
H-SC    22.05
X-MC    21.99
X-SC    12.61
M-SC    10.07
H-MC     5.09
M-MC     2.14
H-LC     1.30
M-LC     0.98
L-SC     0.59
L-MC     0.34
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.77        -17.65   59.40
FINANCE             13.80         -8.32   52.47
IT                  11.51        -36.29  105.64
MISC                 7.03        -32.82   90.52
ELECTRICAL           6.74         -0.16   38.51
PAINTS               5.30        -29.46   51.94
BANKS                4.55        -18.02   77.93
INSURANCE            4.54         -3.98   39.57
PHARMA               3.88         -5.48   38.68
AUTO                 3.82        -19.10   66.36
AC                   2.05         -8.53   37.95
HEALTHCARE           1.90        -30.91   65.07
APPARELS             1.84         -1.70   36.39
FOOTWEAR             1.80        -69.99  138.15
TRAVEL               1.79        -73.86  160.91
DURABLES             1.78        -50.90   87.61
BREWERIES            1.55         -4.85   26.63
REALTY               1.43         -7.95   25.68
CERAMICS             1.34        -59.12  107.46
CABLES               1.23         16.27   74.08
REFINERIES           1.22        -14.48   43.45
CEMENT               1.19        -56.54  173.64
ENGINEERING          1.17        -43.65  109.36
JEWELLERY            1.10       -103.45  174.13
CHEMICALS            1.08        -69.56  207.90
ENTERTAINMENT        0.78        -71.17  173.26
TEXTILES             0.44        -44.71   85.97
HOTELS               0.36       -116.95  193.47

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3706178.0     21
X40       1668016.0     16
XR        1303657.0     12
AR        1224414.0     10
X40N       992201.0     10
OX40N      811343.0     10
XY25       404131.0      5
SR         307162.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3626068.0     24
X-MC        1575461.0     15
X-LC        1493784.0     13
M-SC        1469676.0     14
X-SC        1369938.0     10
H-MC         346821.0      3
L-SC         205803.0      2
M-LC         150813.0      1
M-MC          77152.0      2
L-MC          54319.0      1
H-LC          47267.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1197507.0      6
           AR         950992.0      5
M-SC       XY24       862337.0      6
X-LC       X40        829906.0      7
X-SC       XY24       827901.0      4
H-SC       XR         818203.0      7
X-MC       X40        633442.0      7
           X40N       480674.0      4
M-SC       OX40N      354596.0      5
H-SC       OX40N      352204.0      4
X-LC       XY24       345636.0      2
X-SC       X40N       337369.0      4
H-SC       SR         307162.0      2
X-MC       XY24       240480.0      2
H-MC       XY24       232317.0      1
X-MC       XY25       220865.0      2
X-SC       X40        204668.0      2
M-SC       XR         179062.0      2
X-LC       X40N       174158.0      2
M-LC       XR         150813.0      1
X-LC       XY25       144084.0      2
H-MC       AR         114504.0      2
L-SC       OX40N      104543.0      1
           XR         101260.0      1
M-SC       AR          73681.0      1
L-MC       XR          54319.0      1
H-LC       AR          47267.0      1
M-MC       XY25        39182.0      1
           AR          37970.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds