<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-06 11:58:42
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 11.16 K (0.07%)
Current PnL: -29.69 L (-16.28%)
CY Booked + Current PnL: -27.61 L (-15.14%)
-------------------
Total profit:  4.80 L
Total loss:  -34.49 L
-------------------
Total Booked + Current PnL: 15.26 L (10.94%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.13%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.38%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,0.75,14.10,3.74,18.37,6021.0,19890.0,161000.0,1670.26,-20.04,70.0,X-LC,7.33,5.0,3.30,1.05,26.41,X40,ATH,CHEMICALS
49,JSWINFRA,0.38,11.43,4.49,16.43,11095.0,25338.0,247112.0,342.00,-4.38,66.0,X-MC,11.11,61.0,2.28,1.61,40.11,X40N,NTT,REALTY
83,TTKPRESTIG,0.55,-18.40,22.67,0.09,18641.0,-18548.0,82229.0,770.00,90.82,70.0,M-SC,5.67,250.0,-1.00,0.54,46.42,OX40N,NTT,DURABLES
56,MEDANTA,0.41,16.01,9.57,27.12,19598.0,28269.0,204786.0,1486.00,12.40,75.0,X-SC,7.44,87.0,1.44,1.33,41.11,XY24,NTT,HEALTHCARE
55,MASFIN,-0.57,-1.96,24.00,21.57,23054.0,-1920.0,96060.0,397.04,-15.54,58.0,H-SC,1.89,167.0,-0.08,0.63,14.50,XR,ATH,FINANCE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABBOTINDIA,4.07,-9.59,30.59,18.07,49464.0,-17155.0,161700.0,35195.00,-23.01,63.0,X-MC,6.27,58.0,-0.35,1.05,7.03,X40,ATH,PHARMA
22,DIXON,4.03,-5.60,46.10,37.92,113499.0,-14596.0,246202.0,18931.72,-59.87,68.0,X-MC,8.38,54.0,-0.13,1.60,33.96,X40N,ATH,IT
34,HDFCBANK,3.18,-1.12,29.82,28.37,69256.0,-2639.0,232246.0,1073.00,-16.09,74.0,X-LC,12.83,26.0,-0.04,1.51,14.85,X40,BTT,BANKS
9,BANDHANBNK,2.97,-0.64,93.66,92.42,259229.0,-1782.0,276777.0,400.00,137.07,53.0,H-SC,21.28,174.0,-0.01,1.80,52.47,XY24,NTT,BANKS
5,ATULAUTO,2.86,-13.09,67.49,45.57,115628.0,-25806.0,171326.0,844.00,3716.22,67.0,M-SC,3.71,248.0,-0.22,1.12,31.84,XY24,NTT,AUTO

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-4.20,-0.18,35.62,35.37,112298.0,-574.0,315268.0,670.16,-11.93,38.0,X-LC,9.65,13.0,-0.01,2.05,29.58,X40N,ATH,FMCG
61,RAJESHEXPO,-3.28,-82.25,463.66,0.07,112920.0,-112823.0,24354.0,518.00,792.68,45.0,L-SC,38.60,268.0,-1.00,0.16,20.27,OX40N,NTT,JEWELLERY
51,KOTAKBANK,-3.26,2.55,18.09,21.11,25689.0,3534.0,142006.0,453.24,-12.01,41.0,X-LC,4.27,12.0,0.14,0.93,8.60,X40,ATH,BANKS
80,TITAGARH,-2.24,-19.26,80.50,45.74,157404.0,-46644.0,195533.0,1548.00,7.63,47.0,H-SC,9.59,175.0,-0.30,1.27,49.19,XY24,NTT,ENGINEERING
21,DEN,-2.22,-44.91,157.91,42.07,73472.0,-37936.0,46528.0,75.00,65.80,48.0,M-SC,5.96,235.0,-0.52,0.30,26.54,AR,NTT,ENTERTAINMENT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,2.97,-0.64,93.66,92.42,259229.0,-1782.0,276777.0,400.0,137.07,53.0,H-SC,21.28,174.0,-0.01,1.8,52.47,XY24,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.16,37.71,50.97,107.91,103635.0,55681.0,203325.0,1641.55,23.80,48.0,M-SC,26.84,220.0,0.54,1.32,52.97,OX40N,ATH,CABLES
72,SIS,0.46,-1.77,23.45,21.26,25576.0,-1968.0,109064.0,528.00,2602.59,56.0,H-SC,25.24,168.0,-0.08,0.71,62.16,OX40N,NTT,MISC
16,CERA,0.94,-14.74,45.31,23.89,67952.0,-25931.0,149972.0,9475.00,-17.66,67.0,H-SC,14.11,153.0,-0.38,0.98,44.12,OX40N,NTT,CERAMICS
83,TTKPRESTIG,0.55,-18.40,22.67,0.09,18641.0,-18548.0,82229.0,770.00,90.82,70.0,M-SC,5.67,250.0,-1.00,0.54,46.42,OX40N,NTT,DURABLES
43,INDIGOPNTS,0.69,-23.76,31.18,0.02,41497.0,-41470.0,133089.0,1408.00,103.12,67.0,M-SC,4.89,222.0,-1.00,0.87,51.00,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-1.16,37.71,50.97,107.91,103635.0,55681.0,203325.0,1641.55,23.80,48.0,M-SC,26.84,220.0,0.54,1.32,52.97,OX40N,ATH,CABLES
68,SATIN,0.74,42.24,6.74,51.83,26488.0,116708.0,392992.0,274.00,27.46,66.0,H-SC,40.90,159.0,4.41,2.56,91.45,XY24,NTT,FINANCE
91,ZYDUSLIFE,0.39,20.74,12.33,35.63,31200.0,43471.0,253045.0,1286.17,4.95,68.0,H-MC,14.67,120.0,1.39,1.65,33.05,AR,ATH,PHARMA
60,QUESS,0.65,20.07,44.83,73.90,57483.0,21431.0,128224.0,424.00,-35.54,86.0,X-SC,20.55,80.0,0.37,0.84,74.80,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,1.47,5.28,16.86,23.03,31786.0,9456.0,188527.0,216.00,106.14,69.0,H-SC,20.23,166.0,0.30,1.23,58.73,XR,NTT,BANKS
74,STARHEALTH,0.39,12.73,30.63,47.26,97069.0,35784.0,316907.0,761.00,78.03,67.0,H-SC,15.44,173.0,0.37,2.06,38.05,XY24,NTT,INSURANCE
68,SATIN,0.74,42.24,6.74,51.83,26488.0,116708.0,392992.0,274.00,27.46,66.0,H-SC,40.90,159.0,4.41,2.56,91.45,XY24,NTT,FINANCE
25,FINCABLES,-1.16,37.71,50.97,107.91,103635.0,55681.0,203325.0,1641.55,23.80,48.0,M-SC,26.84,220.0,0.54,1.32,52.97,OX40N,ATH,CABLES
91,ZYDUSLIFE,0.39,20.74,12.33,35.63,31200.0,43471.0,253045.0,1286.17,4.95,68.0,H-MC,14.67,120.0,1.39,1.65,33.05,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,0.39,20.74,12.33,35.63,31200.0,43471.0,253045.0,1286.17,4.95,68.0,H-MC,14.67,120.0,1.39,1.65,33.05,AR,ATH,PHARMA
73,SONACOMS,-0.17,14.00,21.65,38.69,24968.0,14166.0,115325.0,801.69,-9.67,74.0,M-MC,18.97,193.0,0.57,0.75,63.62,AR,ATH,AUTO
25,FINCABLES,-1.16,37.71,50.97,107.91,103635.0,55681.0,203325.0,1641.55,23.80,48.0,M-SC,26.84,220.0,0.54,1.32,52.97,OX40N,ATH,CABLES
75,SURYODAY,1.47,5.28,16.86,23.03,31786.0,9456.0,188527.0,216.00,106.14,69.0,H-SC,20.23,166.0,0.30,1.23,58.73,XR,NTT,BANKS
72,SIS,0.46,-1.77,23.45,21.26,25576.0,-1968.0,109064.0,528.00,2602.59,56.0,H-SC,25.24,168.0,-0.08,0.71,62.16,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-4.20,-0.18,35.62,35.37,112298.0,-574.0,315268.0,670.16,-11.93,38.0,X-LC,9.65,13.0,-0.01,2.05,29.58,X40N,ATH,FMCG
23,DMART,1.62,-2.42,32.82,29.60,79936.0,-6042.0,243558.0,5391.45,-17.73,40.0,X-LC,3.62,14.0,-0.08,1.59,11.33,X40N,ATH,FMCG
58,PGHH,-0.11,-33.37,98.12,32.01,139597.0,-71248.0,142272.0,17616.87,-54.91,40.0,X-MC,21.03,57.0,-0.51,0.93,0.90,X40,ATH,FMCG
51,KOTAKBANK,-3.26,2.55,18.09,21.11,25689.0,3534.0,142006.0,453.24,-12.01,41.0,X-LC,4.27,12.0,0.14,0.93,8.60,X40,ATH,BANKS
79,TCS,-1.54,-39.49,106.37,24.88,298194.0,-182936.0,280337.0,4253.91,-48.87,41.0,X-LC,21.66,2.0,-0.61,1.83,3.97,X40,ATH,IT

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,-0.01,18.04,13.04,33.43,23575.0,27631.0,180792.0,1648.14,-8.67,68.0,X-LC,2.17,18.0,1.17,1.18,23.42,X40N,ATH,PHARMA
84,UNITDSPR,2.50,4.91,15.12,20.77,37140.0,11489.0,245633.0,1644.00,-6.93,70.0,X-MC,3.16,64.0,0.31,1.60,17.17,X40N,NTT,BREWERIES
19,COLPAL,1.20,-21.34,77.81,39.86,161183.0,-56215.0,207150.0,3683.41,-4.73,57.0,X-MC,3.19,62.0,-0.35,1.35,17.18,XY25,ATH,FMCG
11,BERGEPAINT,-0.58,-4.82,31.67,25.32,77691.0,-12435.0,245314.0,680.00,-10.05,50.0,X-MC,3.46,68.0,-0.16,1.60,27.68,XY24,NTT,PAINTS
23,DMART,1.62,-2.42,32.82,29.60,79936.0,-6042.0,243558.0,5391.45,-17.73,40.0,X-LC,3.62,14.0,-0.08,1.59,11.33,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.11,-33.37,98.12,32.01,139597.0,-71248.0,142272.0,17616.87,-54.91,40.0,X-MC,21.03,57.0,-0.51,0.93,0.90,X40,ATH,FMCG
79,TCS,-1.54,-39.49,106.37,24.88,298194.0,-182936.0,280337.0,4253.91,-48.87,41.0,X-LC,21.66,2.0,-0.61,1.83,3.97,X40,ATH,IT
47,ITC,-0.43,-23.96,56.56,19.06,146307.0,-81491.0,258675.0,452.00,-58.35,48.0,X-LC,13.05,1.0,-0.56,1.69,4.22,X40,NTT,FMCG
32,HAVELLS,0.05,-24.34,73.70,31.42,182892.0,-79834.0,248157.0,2052.62,-28.80,50.0,X-MC,12.66,63.0,-0.44,1.62,4.67,X40,ATH,ELECTRICAL
35,HDFCLIFE,0.30,-6.87,42.50,32.71,59289.0,-10297.0,139503.0,811.41,-27.32,42.0,X-LC,15.86,31.0,-0.17,0.91,4.80,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.63,-55.35,202.80,35.20,116515.0,-71217.0,57453.0,2096.00,-24.62,48.0,X-SC,19.93,91.0,-0.61,0.37,13.94,X40,NTT,FOOTWEAR
64,RELAXO,-0.11,-48.62,196.45,52.31,146512.0,-70580.0,74580.0,1176.00,-45.31,64.0,X-SC,11.17,92.0,-0.48,0.49,66.75,X40N,NTT,FOOTWEAR
60,QUESS,0.65,20.07,44.83,73.90,57483.0,21431.0,128224.0,424.00,-35.54,86.0,X-SC,20.55,80.0,0.37,0.84,74.80,XY24,NTT,MISC
35,HDFCLIFE,0.30,-6.87,42.50,32.71,59289.0,-10297.0,139503.0,811.41,-27.32,42.0,X-LC,15.86,31.0,-0.17,0.91,4.80,X40,ATH,INSURANCE
51,KOTAKBANK,-3.26,2.55,18.09,21.11,25689.0,3534.0,142006.0,453.24,-12.01,41.0,X-LC,4.27,12.0,0.14,0.93,8.60,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.43,-23.96,56.56,19.06,146307.0,-81491.0,258675.0,452.00,-58.35,48.0,X-LC,13.05,1.0,-0.56,1.69,4.22,X40,NTT,FMCG
79,TCS,-1.54,-39.49,106.37,24.88,298194.0,-182936.0,280337.0,4253.91,-48.87,41.0,X-LC,21.66,2.0,-0.61,1.83,3.97,X40,ATH,IT
45,INFY,-0.99,-29.42,90.20,34.24,199196.0,-92050.0,220838.0,1972.00,-44.48,41.0,X-LC,20.74,3.0,-0.46,1.44,5.23,X40,NTT,IT
81,TMPV,1.13,-20.78,72.41,36.58,204109.0,-73961.0,281880.0,600.00,-83.62,42.0,X-LC,7.18,4.0,-0.36,1.84,18.46,XY24,NTT,AUTO
59,PIDILITIND,0.75,14.10,3.74,18.37,6021.0,19890.0,161000.0,1670.26,-20.04,70.0,X-LC,7.33,5.0,3.30,1.05,26.41,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.66,-26.87,81.73,32.89,46143.0,-20748.0,56458.0,1800.00,-366.11,69.0,L-MC,7.77,258.0,-0.45,0.37,39.19,XR,NTT,BANKS
64,RELAXO,-0.11,-48.62,196.45,52.31,146512.0,-70580.0,74580.0,1176.00,-45.31,64.0,X-SC,11.17,92.0,-0.48,0.49,66.75,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.96,-22.94,149.85,92.54,116589.0,-23159.0,77804.0,4520.85,-17.40,55.0,H-SC,9.00,142.0,-0.20,0.51,47.74,SR,ATH,CHEMICALS
83,TTKPRESTIG,0.55,-18.40,22.67,0.09,18641.0,-18548.0,82229.0,770.00,90.82,70.0,M-SC,5.67,250.0,-1.00,0.54,46.42,OX40N,NTT,DURABLES
72,SIS,0.46,-1.77,23.45,21.26,25576.0,-1968.0,109064.0,528.00,2602.59,56.0,H-SC,25.24,168.0,-0.08,0.71,62.16,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,-0.03,-26.21,53.01,12.90,85463.0,-57275.0,161221.0,593.0,137.98,80.0,H-SC,4.06,170.0,-0.67,1.05,55.58,OX40N,NTT,FINANCE
64,RELAXO,-0.11,-48.62,196.45,52.31,146512.0,-70580.0,74580.0,1176.0,-45.31,64.0,X-SC,11.17,92.0,-0.48,0.49,66.75,X40N,NTT,FOOTWEAR
60,QUESS,0.65,20.07,44.83,73.90,57483.0,21431.0,128224.0,424.0,-35.54,86.0,X-SC,20.55,80.0,0.37,0.84,74.80,XY24,NTT,MISC
49,JSWINFRA,0.38,11.43,4.49,16.43,11095.0,25338.0,247112.0,342.0,-4.38,66.0,X-MC,11.11,61.0,2.28,1.61,40.11,X40N,NTT,REALTY
83,TTKPRESTIG,0.55,-18.40,22.67,0.09,18641.0,-18548.0,82229.0,770.0,90.82,70.0,M-SC,5.67,250.0,-1.00,0.54,46.42,OX40N,NTT,DURABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.33
1     25       42.69
2     50       72.79

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.78
LC    30.22
MC    26.05
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     28.00
X40      24.48
X40N     17.49
XR        8.86
OX40N     7.17
AR        6.73
XY25      6.45
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.28
H-SC    22.95
X-MC    20.89
X-SC    10.15
M-SC    10.11
H-MC     2.73
M-MC     2.06
H-LC     1.15
M-LC     0.79
L-SC     0.57
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.43        -19.60   61.55
FINANCE             11.47         -4.89   50.34
IT                   9.52        -54.09  131.13
MISC                 7.23        -21.16   73.15
AUTO                 6.74         -5.87   45.34
BANKS                5.84         -1.36   48.23
PAINTS               5.52        -16.27   36.11
INSURANCE            5.23         -3.09   37.86
PHARMA               5.13          5.83   23.32
ELECTRICAL           4.06        -13.73   53.87
CHEMICALS            2.18        -21.61   93.76
HEALTHCARE           2.10        -10.59   39.45
APPARELS             1.94          9.66   20.68
AC                   1.74        -19.63   52.07
FOOTWEAR             1.73        -66.26  132.93
DURABLES             1.62        -55.77   93.67
REALTY               1.61         10.25    4.49
BREWERIES            1.60          4.68   15.12
TRAVEL               1.53        -90.64  186.09
CERAMICS             1.44        -39.24   81.54
CABLES               1.32         27.39   50.97
ENGINEERING          1.27        -23.85   80.50
REFINERIES           1.11        -17.89   47.72
CEMENT               1.09        -59.67  179.12
JEWELLERY            1.03       -103.02  173.55
ENTERTAINMENT        0.74        -69.95  171.32
TEXTILES             0.42        -42.23   82.79
HOTELS               0.41        -81.47  145.47

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3299864.0     21
X40       1921879.0     19
XR        1324907.0     13
AR        1144012.0      9
X40N      1036729.0     13
OX40N      691585.0     10
XY25       446127.0      5
SR         285203.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3257268.0     24
X-LC        1939191.0     21
X-MC        1513655.0     15
M-SC        1366078.0     14
X-SC        1246893.0      9
H-MC         278741.0      2
L-SC         203945.0      2
M-LC         170936.0      1
M-MC          69794.0      2
H-LC          57662.0      1
L-MC          46143.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1046669.0     10
H-SC       AR         956710.0      5
           XY24       935505.0      6
M-SC       XY24       808599.0      6
H-SC       XR         796414.0      7
X-SC       XY24       738513.0      4
X-MC       X40        660335.0      7
           X40N       385710.0      4
X-LC       X40N       357514.0      6
           XY24       349716.0      2
M-SC       OX40N      295229.0      5
X-SC       X40N       293505.0      3
H-SC       SR         285203.0      2
           OX40N      283436.0      4
X-MC       XY25       247620.0      2
H-MC       XY24       247541.0      1
X-MC       XY24       219990.0      2
X-SC       X40        214875.0      2
M-SC       XR         188778.0      2
M-LC       XR         170936.0      1
X-LC       XY25       153681.0      2
L-SC       OX40N      112920.0      1
           XR          91025.0      1
M-SC       AR          73472.0      1
H-LC       AR          57662.0      1
L-MC       XR          46143.0      1
M-MC       XY25        44826.0      1
X-LC       XR          31611.0      1
H-MC       AR          31200.0      1
M-MC       AR          24968.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 49.0 seconds