<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-06-30 11:41:19
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: 22.21 K (0.15%)
Current PnL: -32.22 L (-17.67%)
CY Booked + Current PnL: -30.14 L (-16.53%)
-------------------
Total profit:  4.07 L
Total loss:  -36.29 L
-------------------
Total Booked + Current PnL: 12.73 L (9.12%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.93%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.64%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
59,PIDILITIND,-0.69,12.57,5.15,18.37,8181.0,17740.0,158850.0,1670.26,-21.16,69.0,X-LC,5.61,5.0,2.17,1.05,24.73,X40,ATH,CHEMICALS
49,JSWINFRA,-0.14,9.16,6.66,16.43,16123.0,20317.0,242091.0,342.00,-6.40,65.0,X-MC,7.44,61.0,1.26,1.60,37.26,X40N,NTT,REALTY
83,TTKPRESTIG,3.06,-20.19,25.41,0.09,20438.0,-20343.0,80434.0,770.00,86.77,74.0,M-SC,7.66,250.0,-1.00,0.53,43.22,OX40N,NTT,DURABLES
51,KOTAKBANK,-0.58,5.06,15.27,21.11,22215.0,7012.0,145484.0,453.24,-9.84,48.0,X-LC,4.69,12.0,0.32,0.96,11.26,X40,ATH,BANKS
17,CIPLA,0.98,18.88,12.24,33.43,22287.0,28921.0,182082.0,1648.14,-7.97,72.0,X-LC,2.64,18.0,1.30,1.21,24.30,X40N,ATH,PHARMA

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
54,MARUTI,4.77,4.57,23.06,28.68,35644.0,6755.0,154572.0,17292.00,-14.00,63.0,X-LC,10.19,33.0,0.19,1.02,15.11,XR,ATH,AUTO
83,TTKPRESTIG,3.06,-20.19,25.41,0.09,20438.0,-20343.0,80434.0,770.00,86.77,74.0,M-SC,7.66,250.0,-1.00,0.53,43.22,OX40N,NTT,DURABLES
70,SHALBY,2.98,-32.40,85.05,25.10,104152.0,-58683.0,122460.0,327.00,801.12,62.0,M-SC,11.34,236.0,-0.56,0.81,39.36,XY24,NTT,HEALTHCARE
3,ALKYLAMINE,2.89,-26.50,161.96,92.54,120189.0,-26754.0,74209.0,4520.85,-21.23,48.0,H-SC,8.56,142.0,-0.22,0.49,40.92,SR,ATH,CHEMICALS
60,QUESS,2.19,3.92,67.34,73.90,74734.0,4187.0,110980.0,424.00,-44.35,72.0,X-SC,14.13,80.0,0.06,0.74,51.29,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
13,BSOFT,-4.13,-48.01,190.04,50.79,138959.0,-67532.0,73121.0,831.70,-33.13,27.0,H-SC,16.09,172.0,-0.49,0.48,0.00,XR,ATH,IT
72,SIS,-3.45,-3.36,25.48,21.26,27341.0,-3728.0,107304.0,528.00,2559.07,53.0,H-SC,25.27,168.0,-0.14,0.71,59.55,OX40N,NTT,MISC
18,COFFEEDAY,-2.62,-45.98,150.39,35.27,92255.0,-52205.0,61344.0,80.00,-57.75,46.0,L-SC,15.48,266.0,-0.57,0.41,51.28,XR,NTT,HOTELS
45,INFY,-2.44,-31.15,94.98,34.24,204614.0,-97460.0,215428.0,1972.00,-45.94,32.0,X-LC,19.04,3.0,-0.48,1.43,0.00,X40,NTT,IT
79,TCS,-2.42,-39.90,107.79,24.88,300108.0,-184854.0,278419.0,4253.91,-49.20,34.0,X-LC,21.03,2.0,-0.62,1.84,0.00,X40,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
63,RECLTD,0.44,-0.77,21.68,20.74,43707.0,-1568.0,201602.0,446.0,9.37,62.0,M-MC,0.55,191.0,-0.04,1.34,20.14,XY25,NTT,FINANCE
75,SURYODAY,1.05,-0.10,23.16,23.03,41430.0,-183.0,178888.0,216.0,95.18,60.0,H-SC,19.35,166.0,-0.00,1.19,50.62,XR,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.48,48.63,39.88,107.91,87514.0,71800.0,219444.0,1641.55,33.94,61.0,M-SC,25.09,220.0,0.82,1.45,65.10,OX40N,ATH,CABLES
72,SIS,-3.45,-3.36,25.48,21.26,27341.0,-3728.0,107304.0,528.00,2559.07,53.0,H-SC,25.27,168.0,-0.14,0.71,59.55,OX40N,NTT,MISC
16,CERA,-1.13,-16.44,48.27,23.89,70948.0,-28921.0,146982.0,9475.00,-19.33,62.0,H-SC,10.01,153.0,-0.41,0.97,41.25,OX40N,NTT,CERAMICS
83,TTKPRESTIG,3.06,-20.19,25.41,0.09,20438.0,-20343.0,80434.0,770.00,86.77,74.0,M-SC,7.66,250.0,-1.00,0.53,43.22,OX40N,NTT,DURABLES
69,SFL,-0.90,-27.58,74.86,26.63,142150.0,-72330.0,189888.0,1287.00,43.89,68.0,M-SC,15.81,242.0,-0.51,1.26,58.26,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.48,48.63,39.88,107.91,87514.0,71800.0,219444.0,1641.55,33.94,61.0,M-SC,25.09,220.0,0.82,1.45,65.1,OX40N,ATH,CABLES
68,SATIN,1.40,32.55,14.55,51.83,53284.0,89931.0,366215.0,274.00,18.27,59.0,H-SC,41.24,159.0,1.69,2.43,78.4,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.56,13.78,29.42,47.26,94106.0,38749.0,319872.0,761.00,79.65,75.0,H-SC,13.70,173.0,0.41,2.12,40.37,XY24,NTT,INSURANCE
25,FINCABLES,-0.48,48.63,39.88,107.91,87514.0,71800.0,219444.0,1641.55,33.94,61.0,M-SC,25.09,220.0,0.82,1.45,65.10,OX40N,ATH,CABLES
68,SATIN,1.40,32.55,14.55,51.83,53284.0,89931.0,366215.0,274.00,18.27,59.0,H-SC,41.24,159.0,1.69,2.43,78.40,XY24,NTT,FINANCE
91,ZYDUSLIFE,-0.70,17.42,15.51,35.63,38168.0,36510.0,246084.0,1286.17,2.25,63.0,H-MC,14.09,120.0,0.96,1.63,29.39,AR,ATH,PHARMA
73,SONACOMS,-0.44,6.91,29.72,38.69,32142.0,6991.0,108150.0,801.69,-15.34,60.0,M-MC,17.94,193.0,0.22,0.72,53.44,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-0.70,17.42,15.51,35.63,38168.0,36510.0,246084.0,1286.17,2.25,63.0,H-MC,14.09,120.0,0.96,1.63,29.39,AR,ATH,PHARMA
25,FINCABLES,-0.48,48.63,39.88,107.91,87514.0,71800.0,219444.0,1641.55,33.94,61.0,M-SC,25.09,220.0,0.82,1.45,65.10,OX40N,ATH,CABLES
73,SONACOMS,-0.44,6.91,29.72,38.69,32142.0,6991.0,108150.0,801.69,-15.34,60.0,M-MC,17.94,193.0,0.22,0.72,53.44,AR,ATH,AUTO
75,SURYODAY,1.05,-0.10,23.16,23.03,41430.0,-183.0,178888.0,216.00,95.18,60.0,H-SC,19.35,166.0,-0.00,1.19,50.62,XR,NTT,BANKS
72,SIS,-3.45,-3.36,25.48,21.26,27341.0,-3728.0,107304.0,528.00,2559.07,53.0,H-SC,25.27,168.0,-0.14,0.71,59.55,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-2.44,-31.15,94.98,34.24,204614.0,-97460.0,215428.0,1972.00,-45.94,32.0,X-LC,19.04,3.0,-0.48,1.43,0.00,X40,NTT,IT
33,HCLTECH,-1.81,-29.76,72.98,21.51,124020.0,-71987.0,169937.0,1872.35,-26.39,33.0,X-LC,19.69,8.0,-0.58,1.13,0.00,X40,ATH,IT
79,TCS,-2.42,-39.90,107.79,24.88,300108.0,-184854.0,278419.0,4253.91,-49.20,34.0,X-LC,21.03,2.0,-0.62,1.84,0.00,X40,ATH,IT
1,ABBOTINDIA,0.12,-15.04,38.97,18.07,59215.0,-26905.0,151950.0,35195.00,-27.72,35.0,X-MC,6.62,58.0,-0.45,1.01,0.58,X40,ATH,PHARMA
26,GILLETTE,0.30,-10.39,44.76,29.72,101838.0,-26376.0,227520.0,10978.86,-31.19,38.0,X-SC,6.55,83.0,-0.26,1.51,4.56,X40,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
17,CIPLA,0.98,18.88,12.24,33.43,22287.0,28921.0,182082.0,1648.14,-7.97,72.0,X-LC,2.64,18.0,1.30,1.21,24.30,X40N,ATH,PHARMA
11,BERGEPAINT,1.50,-3.06,29.27,25.32,73138.0,-7875.0,249874.0,680.00,-8.32,54.0,X-MC,2.66,68.0,-0.11,1.66,30.05,XY24,NTT,PAINTS
84,UNITDSPR,0.38,-1.08,22.09,20.77,51164.0,-2529.0,231615.0,1644.00,-12.33,58.0,X-MC,3.55,64.0,-0.05,1.53,10.49,X40N,NTT,BREWERIES
19,COLPAL,-0.20,-24.24,84.60,39.86,168802.0,-63835.0,199530.0,3683.41,-8.32,44.0,X-MC,3.96,62.0,-0.38,1.32,12.87,XY25,ATH,FMCG
23,DMART,0.42,5.18,23.22,29.60,60959.0,12930.0,262530.0,5391.45,-11.31,61.0,X-LC,4.09,14.0,0.21,1.74,20.00,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-2.44,-31.15,94.98,34.24,204614.0,-97460.0,215428.0,1972.00,-45.94,32.0,X-LC,19.04,3.0,-0.48,1.43,0.00,X40,NTT,IT
33,HCLTECH,-1.81,-29.76,72.98,21.51,124020.0,-71987.0,169937.0,1872.35,-26.39,33.0,X-LC,19.69,8.0,-0.58,1.13,0.00,X40,ATH,IT
79,TCS,-2.42,-39.90,107.79,24.88,300108.0,-184854.0,278419.0,4253.91,-49.20,34.0,X-LC,21.03,2.0,-0.62,1.84,0.00,X40,ATH,IT
1,ABBOTINDIA,0.12,-15.04,38.97,18.07,59215.0,-26905.0,151950.0,35195.00,-27.72,35.0,X-MC,6.62,58.0,-0.45,1.01,0.58,X40,ATH,PHARMA
58,PGHH,1.54,-32.94,96.87,32.01,138695.0,-70344.0,143176.0,17616.87,-54.64,39.0,X-MC,20.94,57.0,-0.51,0.95,1.54,X40,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.50,-55.76,205.61,35.20,117046.0,-71744.0,56926.0,2096.00,-25.34,46.0,X-SC,21.35,91.0,-0.61,0.38,12.90,X40,NTT,FOOTWEAR
64,RELAXO,-1.66,-46.78,186.20,52.31,143838.0,-67911.0,77249.0,1176.00,-43.37,74.0,X-SC,12.31,92.0,-0.47,0.51,72.72,X40N,NTT,FOOTWEAR
60,QUESS,2.19,3.92,67.34,73.90,74734.0,4187.0,110980.0,424.00,-44.35,72.0,X-SC,14.13,80.0,0.06,0.74,51.29,XY24,NTT,MISC
28,GODREJCP,-0.38,-8.90,44.31,31.47,59993.0,-13220.0,135394.0,1469.04,-4.16,48.0,X-LC,8.91,32.0,-0.22,0.90,3.88,X40N,ATH,FMCG
35,HDFCLIFE,-1.26,-5.81,40.89,32.71,57694.0,-8704.0,141096.0,811.41,-26.43,44.0,X-LC,16.34,31.0,-0.15,0.93,6.00,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.69,-23.96,56.56,19.06,146307.0,-81491.0,258675.0,452.00,-58.35,48.0,X-LC,14.17,1.0,-0.56,1.71,4.22,X40,NTT,FMCG
79,TCS,-2.42,-39.90,107.79,24.88,300108.0,-184854.0,278419.0,4253.91,-49.20,34.0,X-LC,21.03,2.0,-0.62,1.84,0.00,X40,ATH,IT
45,INFY,-2.44,-31.15,94.98,34.24,204614.0,-97460.0,215428.0,1972.00,-45.94,32.0,X-LC,19.04,3.0,-0.48,1.43,0.00,X40,NTT,IT
81,TMPV,2.07,-19.83,70.36,36.58,200724.0,-70559.0,285282.0,600.00,-83.62,42.0,X-LC,8.60,4.0,-0.35,1.89,19.89,XY24,NTT,AUTO
59,PIDILITIND,-0.69,12.57,5.15,18.37,8181.0,17740.0,158850.0,1670.26,-21.16,69.0,X-LC,5.61,5.0,2.17,1.05,24.73,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.66,-31.30,93.42,32.89,49554.0,-24162.0,53044.0,1800.00,-350.00,55.0,L-MC,7.04,258.0,-0.49,0.35,30.78,XR,NTT,BANKS
64,RELAXO,-1.66,-46.78,186.20,52.31,143838.0,-67911.0,77249.0,1176.00,-43.37,74.0,X-SC,12.31,92.0,-0.47,0.51,72.72,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,3.06,-20.19,25.41,0.09,20438.0,-20343.0,80434.0,770.00,86.77,74.0,M-SC,7.66,250.0,-1.00,0.53,43.22,OX40N,NTT,DURABLES
72,SIS,-3.45,-3.36,25.48,21.26,27341.0,-3728.0,107304.0,528.00,2559.07,53.0,H-SC,25.27,168.0,-0.14,0.71,59.55,OX40N,NTT,MISC
73,SONACOMS,-0.44,6.91,29.72,38.69,32142.0,6991.0,108150.0,801.69,-15.34,60.0,M-MC,17.94,193.0,0.22,0.72,53.44,AR,ATH,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-1.66,-46.78,186.20,52.31,143838.0,-67911.0,77249.0,1176.00,-43.37,74.0,X-SC,12.31,92.0,-0.47,0.51,72.72,X40N,NTT,FOOTWEAR
60,QUESS,2.19,3.92,67.34,73.90,74734.0,4187.0,110980.0,424.00,-44.35,72.0,X-SC,14.13,80.0,0.06,0.74,51.29,XY24,NTT,MISC
69,SFL,-0.90,-27.58,74.86,26.63,142150.0,-72330.0,189888.0,1287.00,43.89,68.0,M-SC,15.81,242.0,-0.51,1.26,58.26,XY24,NTT,MISC
25,FINCABLES,-0.48,48.63,39.88,107.91,87514.0,71800.0,219444.0,1641.55,33.94,61.0,M-SC,25.09,220.0,0.82,1.45,65.10,OX40N,ATH,CABLES
49,JSWINFRA,-0.14,9.16,6.66,16.43,16123.0,20317.0,242091.0,342.00,-6.40,65.0,X-MC,7.44,61.0,1.26,1.60,37.26,X40N,NTT,REALTY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.38
1     25       42.65
2     50       72.87

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.77
LC    30.45
MC    25.78
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.90
X40      24.40
X40N     17.54
XR        8.84
OX40N     7.23
AR        6.79
XY25      6.46
SR        0.84
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.46
H-SC    22.89
X-MC    20.65
M-SC    10.28
X-SC    10.03
H-MC     2.72
M-MC     2.06
H-LC     1.20
M-LC     0.79
L-SC     0.57
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.51        -20.85   63.25
FINANCE             11.22         -8.90   56.09
IT                   9.45        -57.99  136.98
MISC                 7.21        -23.24   76.11
AUTO                 6.69         -8.42   49.03
BANKS                5.80         -3.70   51.66
PAINTS               5.52        -18.45   38.65
INSURANCE            5.33         -2.72   37.37
PHARMA               5.12          3.96   25.77
ELECTRICAL           4.12        -13.79   53.95
CHEMICALS            2.17        -23.59   96.91
HEALTHCARE           2.13        -11.05   40.03
APPARELS             1.88          5.33   26.46
AC                   1.79        -18.35   50.45
FOOTWEAR             1.77        -65.04  131.22
DURABLES             1.62        -57.96   96.39
REALTY               1.60          8.39    6.66
TRAVEL               1.55        -91.49  187.37
BREWERIES            1.53         -1.09   22.09
CABLES               1.45         32.72   39.88
CERAMICS             1.43        -41.42   84.38
ENGINEERING          1.33        -20.46   75.56
REFINERIES           1.11        -20.08   50.47
CEMENT               1.06        -68.00  193.68
JEWELLERY            1.02       -108.44  180.85
ENTERTAINMENT        0.75        -70.44  172.09
TEXTILES             0.43        -43.38   84.26
HOTELS               0.41        -85.10  150.39

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3386185.0     21
X40       1992359.0     19
XR        1346774.0     13
AR        1152260.0      9
X40N      1075139.0     13
OX40N      699633.0     10
XY25       461864.0      5
SR         291568.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3321545.0     24
X-LC        1984103.0     21
X-MC        1600913.0     15
M-SC        1366087.0     14
X-SC        1289883.0      9
H-MC         287344.0      2
L-SC         205144.0      2
M-LC         172516.0      1
M-MC          75849.0      2
H-LC          52844.0      1
L-MC          49554.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1083397.0     10
H-SC       XY24       968180.0      6
           AR         955490.0      5
M-SC       XY24       815229.0      6
H-SC       XR         808292.0      7
X-SC       XY24       781381.0      4
X-MC       X40        690078.0      7
           X40N       432881.0      4
X-LC       X40N       352640.0      6
           XY24       348268.0      2
H-SC       OX40N      298015.0      4
           SR         291568.0      2
X-SC       X40N       289618.0      3
M-SC       OX40N      288729.0      5
X-MC       XY25       254003.0      2
H-MC       XY24       249176.0      1
X-MC       XY24       223951.0      2
X-SC       X40        218884.0      2
M-SC       XR         188513.0      2
M-LC       XR         172516.0      1
X-LC       XY25       164154.0      2
L-SC       OX40N      112889.0      1
           XR          92255.0      1
M-SC       AR          73616.0      1
H-LC       AR          52844.0      1
L-MC       XR          49554.0      1
M-MC       XY25        43707.0      1
H-MC       AR          38168.0      1
X-LC       XR          35644.0      1
M-MC       AR          32142.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds